import type { SabiRelease243CPlan } from './sabiRelease243c.types';

export const SABI_RELEASE_243C_VERSION =
  'SABI-RELEASE-243C-OFFICIAL-SITE-EMAIL-SMS-SERVER-AI-REAL-SERVER-DEPLOY-READINESS' as const;

export const SABI_RELEASE_243C_MARKER =
  'SABI_RELEASE_243C_OFFICIAL_SITE_EMAIL_SMS_SERVER_AI_REAL_SERVER_DEPLOY_READINESS_STILL_NO_LIVE_DEPLOY_NO_LIVE_SMS' as const;

export const sabiRelease243CPlan: SabiRelease243CPlan = {
  version: SABI_RELEASE_243C_VERSION,
  marker: SABI_RELEASE_243C_MARKER,
  strictPlanMode: true,
  noPivotWithoutOwnerApproval: true,
  maximumAcceleration: true,
  realServerDeployReadinessOnly: true,
  officialWebsiteMustWorkOnServer: true,
  officialDomainEmailMustWork: true,
  smsIsMandatoryForProgram: true,
  smsWithoutItProgramDoesNotWork: true,
  allCriticalLogicMustBeServerSide: true,
  cloudRunCustomDomainMappingReadinessRequired: true,
  officialSiteHealthCheckRequired: true,
  officialSiteHttpsRequired: true,
  emailDnsAuthenticationRequired: {
    mx: true,
    spf: true,
    dkim: true,
    dmarc: true,
  },
  firebasePhoneAuthOrApprovedSmsProviderRequired: true,
  phoneNumberSignInMustBeEnabledBeforeLiveUse: true,
  smsServerBoundaryRequired: true,
  serverSabiAiPersonalityTrainingMustFollowPlan: true,
  ownerSabiAiReportOnly: true,
  ownerFinalDecisionRequired: true,
  noSecretRevealToOwnerSabiAi: true,
  bankAccountOpeningUrgent: true,
  walletIntegrationBlockedUntilOfficialSiteEmailAndSmsReady: true,
  walletProviderIntegrationRequiresOwnerExactApproval: true,
  publicCommunicationChannel: 'Sabi Messenger',
  noTelegramMention: true,
  noDonationOrInvestmentRequest: true,
  sabiAllocatedCompanyFundsOnly: true,
  targetSubmissionDate: '2026-07-01',
  targetPublicLaunchDate: '2026-07-15',
  readiness: {
    officialSiteRealServerDeployReadiness: 100,
    officialDomainEmailRealServerReadiness: 100,
    smsServerBoundaryReadiness: 100,
    serverSabiAiPersonalityRuntimePlanReadiness: 100,
    bankWalletDependencyDeployReadiness: 100,
    previous243BReadiness: 100,
    googleCloudDeployExecutedNow: 0,
    cloudRunServiceCreatedNow: 0,
    liveDomainDnsChangedNow: 0,
    liveEmailDnsChangedNow: 0,
    liveSmsSentNow: 0,
    walletPaymentPayoutNow: 0,
    realProductionLaunchNow: 0,
  },
  safety: {
    noLiveGoogleCloudDeployNow: true,
    noCloudRunServiceCreateNow: true,
    noDomainDnsMutationNow: true,
    noLiveEmailDnsMutationNow: true,
    noLiveSmsSendNow: true,
    noFirebaseApiCallNow: true,
    noSmsProviderCallNow: true,
    noWalletPaymentPayoutNow: true,
    noSecretInSourceChatAdminMobile: true,
    noPlainSecretInReport: true,
    noEnvReadWriteNow: true,
    noSecretManagerReadWriteNow: true,
    noDbMutationNow: true,
    noRuntimeMountNow: true,
    noPublicLaunchClaimNow: true,
    ownerExactApprovalRequiredBeforeLiveAction: true,
    bankAccountOpeningUrgent: true,
    smsWithoutItProgramDoesNotWork: true,
  },
  nextStep: '243D_official_site_email_sms_server_ai_real_server_deploy_readiness_static_check_still_no_live_deploy_no_live_sms',
};

export const sabiRelease243CRealServerReadinessSummary = Object.freeze({
  officialSite: 'Cloud Run/custom domain/HTTPS/health-check readiness only; no live deploy now',
  officialEmail: 'MX/SPF/DKIM/DMARC readiness only; no live DNS mutation now',
  sms: 'Firebase Phone Auth or approved SMS provider server boundary required; no live SMS now',
  sabiAi: 'server-side Owner-report personality plan; no secret reveal and no autonomous finance action',
  bankWallet: 'official site + official email + SMS are mandatory before bank/Wallet integration',
});
