import type { TaxiRouteDescriptor } from '../foundation';
import type { TaxiKernelBoundaryReason } from '../kernel';
import type {
  TaxiAiAdminDecisionActionContract,
  TaxiAiAdminDecisionEvidenceContract,
  TaxiAiAdminDecisionSlaContract,
  TaxiAiAdminDecisionStageContract,
  TaxiAiAdminDecisionVersion,
  TaxiDailyReportCompletenessContract,
} from './taxiAiAdminDecision.types';

export const TAXI_AI_ADMIN_DECISION_VERSION: TaxiAiAdminDecisionVersion = 'TAXI-BACKEND-FOUNDATION-001F';

export const TAXI_AI_ADMIN_DECISION_STAGES: readonly TaxiAiAdminDecisionStageContract[] = [
  {
    stageId: 'daily_report_created',
    order: 1,
    title: 'Daily report shell created',
    description: 'Admin-visible daily country report shell exists before any decision is shown as final.',
    requiredForEveryDailyCountryReport: true,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'all_complaints_collected',
    order: 2,
    title: 'All complaints collected',
    description: 'Every driver and rider complaint for the country day must be included in the review queue.',
    requiredForEveryDailyCountryReport: true,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'sabi_ai_precheck_completed',
    order: 3,
    title: 'Sabi AI precheck completed',
    description: 'Sabi AI classifies evidence signals, false complaint signals and leaderboard abuse candidates.',
    requiredForEveryDailyCountryReport: true,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'evidence_bundle_normalized',
    order: 4,
    title: 'Evidence bundle normalized',
    description: 'Trip state, complaint context, chat/call safety, cancellation and country/account signals are normalized.',
    requiredForEveryDailyCountryReport: true,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'admin_review_started',
    order: 5,
    title: 'Admin review started',
    description: 'Admin reviews the Sabi AI signal and evidence bundle before any heavy action.',
    requiredForEveryDailyCountryReport: false,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'admin_decision_drafted',
    order: 6,
    title: 'Admin decision drafted',
    description: 'Admin decision is prepared as a locked candidate, not a real sanction or reward release.',
    requiredForEveryDailyCountryReport: false,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'appeal_window_opened',
    order: 7,
    title: 'Appeal window opened',
    description: 'Driver or rider can explain before a hard block, long restriction or reward disqualification.',
    requiredForEveryDailyCountryReport: false,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'final_admin_decision_waiting_exact_approval',
    order: 8,
    title: 'Final decision waits exact approval',
    description: 'Execution remains locked until explicit runtime/DB/provider/payment approval exists.',
    requiredForEveryDailyCountryReport: false,
    requiredBeforeHeavyAction: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'client_boundary_summary_published',
    order: 9,
    title: 'Kernel-safe mobile summary published',
    description: 'Mobile receives only safe status summaries through kernel facade/events/state, never raw evidence.',
    requiredForEveryDailyCountryReport: false,
    requiredBeforeHeavyAction: false,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    fakeDecisionBlocked: true,
  },
] as const;

export const TAXI_AI_ADMIN_DECISION_ACTIONS: readonly TaxiAiAdminDecisionActionContract[] = [
  {
    actionId: 'no_action_clear',
    label: 'No action / clear',
    mapsEscalation: 'no_verified_complaints_today',
    targetTrustStatus: 'clear',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'warning_candidate',
    label: 'Warning candidate',
    mapsEscalation: 'one_verified_complaint_points_penalty',
    targetTrustStatus: 'warning',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'points_penalty_candidate',
    label: 'Points penalty candidate',
    mapsEscalation: 'one_verified_complaint_points_penalty',
    targetTrustStatus: 'warning',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'one_hour_cooldown_candidate',
    label: 'One hour cooldown candidate',
    mapsEscalation: 'two_verified_complaints_points_penalty_one_hour_cooldown',
    targetTrustStatus: 'cooldown',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'three_hour_cooldown_candidate',
    label: 'Three hour cooldown candidate',
    mapsEscalation: 'three_verified_complaints_points_penalty_three_hour_cooldown',
    targetTrustStatus: 'cooldown',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'block_pending_explanation_candidate',
    label: 'Block pending explanation candidate',
    mapsEscalation: 'more_than_three_verified_complaints_blocked_pending_review',
    targetTrustStatus: 'blocked_pending_review',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: true,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'false_complaint_penalty_candidate',
    label: 'False complaint penalty candidate',
    targetTrustStatus: 'warning',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'restore_points_candidate',
    label: 'Restore points candidate',
    targetTrustStatus: 'restored',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'freeze_reward_candidate',
    label: 'Freeze reward candidate',
    targetTrustStatus: 'appeal_pending',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: true,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
  {
    actionId: 'release_reward_candidate',
    label: 'Release reward candidate',
    targetTrustStatus: 'restored',
    appliesToRoles: ['driver', 'rider'],
    requiresDailyAiReport: true,
    requiresEvidenceBundle: true,
    requiresAdminDecision: true,
    requiresAppealWindowForHeavyAction: false,
    executionAllowedNow: false,
    fakePenaltyOrRewardBlocked: true,
  },
] as const;

export const TAXI_AI_ADMIN_DECISION_EVIDENCE: readonly TaxiAiAdminDecisionEvidenceContract[] = [
  {
    evidenceId: 'verified_trip_state',
    label: 'Verified trip state',
    description: 'Backend trip state must prove that the ride exists and reached the relevant lifecycle state.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: true,
    requiredForFinalDecision: true,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'complaint_text_and_metadata',
    label: 'Complaint text and metadata',
    description: 'Complaint content, timestamps and participant role are reviewed by Sabi AI and Admin.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: false,
    mayContainPrivateData: true,
    requiredForFinalDecision: true,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'chat_call_safety_context',
    label: 'Chat/call safety context',
    description: 'Safety context is admin-only and never exposed raw to client app.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: false,
    mayContainPrivateData: true,
    requiredForFinalDecision: false,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'route_cancel_after_cancel_context',
    label: 'Cancellation and after-cancel route context',
    description: 'Detects contractual cancellation and ride after cancellation abuse candidates.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: true,
    requiredForFinalDecision: true,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'star_rating_conflict_context',
    label: 'Star rating conflict context',
    description: 'Compares stars, complaint timing and repeated patterns to reduce revenge abuse.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: false,
    requiredForFinalDecision: false,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'device_account_country_context',
    label: 'Device/account/country context',
    description: 'Country league and suspicious account/device patterns remain Admin-visible only.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: false,
    mayContainPrivateData: true,
    requiredForFinalDecision: false,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'driver_balance_dispatch_context',
    label: 'Driver balance dispatch context',
    description: 'Driver online eligibility and balance gate context for dispatch fairness.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: false,
    requiredForFinalDecision: false,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'league_points_and_reward_context',
    label: 'League points and reward context',
    description: 'Reward freeze/release decisions need leaderboard and prize eligibility evidence.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: false,
    requiredForFinalDecision: true,
    dbRuntimeAllowedNow: false,
  },
  {
    evidenceId: 'appeal_explanation_context',
    label: 'Appeal explanation context',
    description: 'Participant explanation is required before hard block or disqualification decisions.',
    adminRawAccessOnly: true,
    mobileSummaryAllowed: true,
    mayContainPrivateData: true,
    requiredForFinalDecision: false,
    dbRuntimeAllowedNow: false,
  },
] as const;

export const TAXI_AI_ADMIN_DECISION_SLAS: readonly TaxiAiAdminDecisionSlaContract[] = [
  {
    slaId: 'daily_report_same_country_day',
    label: 'Same country-day report',
    description: 'The report shell must exist for every supported country and local calendar day.',
    countryScoped: true,
    dailyScoped: true,
    adminVisible: true,
    runtimeSchedulerMountedNow: false,
    exactApprovalRequiredForAutomation: true,
  },
  {
    slaId: 'complaint_precheck_daily',
    label: 'Daily complaint precheck',
    description: 'Every complaint must enter Sabi AI precheck on the same daily report lifecycle.',
    countryScoped: true,
    dailyScoped: true,
    adminVisible: true,
    runtimeSchedulerMountedNow: false,
    exactApprovalRequiredForAutomation: true,
  },
  {
    slaId: 'critical_block_review_priority',
    label: 'Critical block priority',
    description: 'More than three verified daily complaints must be prioritized for Admin review and explanation.',
    countryScoped: true,
    dailyScoped: true,
    adminVisible: true,
    runtimeSchedulerMountedNow: false,
    exactApprovalRequiredForAutomation: true,
  },
  {
    slaId: 'appeal_explanation_required_before_hard_action',
    label: 'Appeal before hard action',
    description: 'Hard block or prize disqualification cannot be final without appeal/explanation window.',
    countryScoped: true,
    dailyScoped: true,
    adminVisible: true,
    runtimeSchedulerMountedNow: false,
    exactApprovalRequiredForAutomation: true,
  },
  {
    slaId: 'reward_release_after_clean_admin_decision_only',
    label: 'Reward release only after clean decision',
    description: 'Top-3 prizes remain frozen until report, evidence, appeal and Admin/legal/payment review are clean.',
    countryScoped: true,
    dailyScoped: true,
    adminVisible: true,
    runtimeSchedulerMountedNow: false,
    exactApprovalRequiredForAutomation: true,
  },
] as const;

export const TAXI_DAILY_REPORT_COMPLETENESS_FIELDS: readonly TaxiDailyReportCompletenessContract[] = [
  { fieldId: 'country_day_window', label: 'Country/day window', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'all_driver_complaints', label: 'All driver complaints', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: false, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'all_rider_complaints', label: 'All rider complaints', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: false, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'false_complaint_candidates', label: 'False complaint candidates', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'contractual_cancellation_candidates', label: 'Contractual cancellation candidates', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'trip_after_cancellation_candidates', label: 'Trip after cancellation candidates', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'star_quality_conflicts', label: 'Star quality conflicts', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'cooldown_block_candidates', label: 'Cooldown/block candidates', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'appeal_explanation_queue', label: 'Appeal/explanation queue', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'reward_freeze_release_queue', label: 'Reward freeze/release queue', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
  { fieldId: 'client_boundary_summary_status', label: 'Client kernel boundary summary status', requiredEveryDay: true, countryScoped: true, dailyScoped: true, checksDrivers: true, checksRiders: true, adminVisible: true, mobileRawAccessAllowed: false },
] as const;

export const TAXI_AI_ADMIN_DECISION_BOUNDARY_REASONS: readonly TaxiKernelBoundaryReason[] = [
  'mobile_ui_must_use_kernel_facade',
  'direct_provider_call_blocked',
  'direct_payment_or_payout_blocked',
  'direct_wallet_mutation_blocked',
  'backend_runtime_not_mounted',
  'exact_approval_required',
] as const;

export const taxiAiAdminDecisionRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/taxi/ai-admin-decision/snapshot',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Safe-disabled Admin/Sabi AI decision lifecycle snapshot. Route descriptor only; not mounted.',
  },
  {
    method: 'POST',
    path: '/api/taxi/ai-admin-decision/preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview Admin/Sabi AI decision lifecycle. No DB, no penalty, no reward release.',
  },
  {
    method: 'POST',
    path: '/api/taxi/ai-admin-decision/report-completeness/preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview daily report completeness requirements. No scheduler or DB runtime mounted.',
  },
] as const;
