import { getTaxiAdminIntegrationSnapshot, taxiAdminIntegrationRouteDescriptors } from '../../taxi/admin-integration';
import { getTaxiAiAdminDecisionSnapshot, taxiAiAdminDecisionRouteDescriptors } from '../../taxi/ai-admin-decision';
import { getTaxiAiDailyReportSnapshot, TAXI_AI_DAILY_REVIEW_ROUTE_DESCRIPTORS } from '../../taxi/ai-daily-review';
import { getTaxiAiDailyExportSnapshot, taxiAiDailyExportRouteDescriptors } from '../../taxi/ai-daily-export';
import { getTaxiAdminDashboardReadinessSnapshot, taxiAdminDashboardRouteDescriptors } from '../../taxi/admin-dashboard';
import { getTaxiAdminNotificationReadinessSnapshot, taxiAdminNotificationRouteDescriptors } from '../../taxi/admin-notifications';
import { getTaxiAdminApprovalGatesSnapshot, taxiAdminApprovalGateRouteDescriptors } from '../../taxi/admin-approval-gates';
import { getTaxiAdminExecutionReadinessSnapshot, taxiAdminExecutionReadinessRouteDescriptors } from '../../taxi/admin-execution-readiness';
import { getTaxiFinalControlSnapshot, taxiFinalControlRouteDescriptors } from '../../taxi/final-control';
import { getTaxiNextPhaseHandoffSnapshot, taxiNextPhaseHandoffRouteDescriptors } from '../../taxi/next-phase-handoff';
import { getTaxiDbSchemaApprovalSnapshot, taxiDbSchemaApprovalRouteDescriptors } from '../../taxi/db-schema-approval';
import { getTaxiPrismaSchemaCandidateSnapshot, taxiPrismaSchemaCandidateRouteDescriptors } from '../../taxi/prisma-schema-candidate';
import { getTaxiSchemaCandidateMaterializationSnapshot, taxiSchemaCandidateMaterializationRouteDescriptors } from '../../taxi/schema-candidate-materialization';
import { getTaxiAdminFoundationCompletionSnapshot, taxiAdminFoundationCompletionRouteDescriptors } from '../../taxi/admin-foundation-completion';
import { getTaxiAdminUiCockpitSnapshot, taxiAdminUiCockpitRouteDescriptors } from '../../taxi/admin-ui-cockpit';
import { getTaxiFoundationSnapshot, taxiFoundationRouteDescriptors } from '../../taxi/foundation';
import { getTaxiKernelBridgeSnapshot, taxiKernelRouteDescriptors } from '../../taxi/kernel';
import { getTaxiClientBoundarySnapshot, taxiClientBoundaryRouteDescriptors } from '../../taxi/client-boundary';
import type {
  TaxiAdminCompatibilitySnapshot,
  TaxiAdminReadinessDecision,
  TaxiAdminReadinessDecisionInput,
  TaxiAdminSectionContract,
} from './taxiAdminTaxiReadiness.types';

export const TAXI_ADMIN_SECTION_CONTRACTS: readonly TaxiAdminSectionContract[] = [

{
  sectionId: 'taxi_admin_ui_cockpit',
  title: 'Taxi Admin UI cockpit',
  description: 'Admin UI cockpit renders Taxi foundation contracts only; no DB, runtime, provider, Wallet, payment or payout execution.',
  permission: 'taxi:admin-ui-cockpit:read',
  status: 'visible_contract_ready',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_tariff_config_panel',
  title: 'Admin tariff configuration panel',
  description: 'Tariff catalog is Admin-configured and review-only until DB/runtime approval.',
  permission: 'taxi:admin-ui-cockpit:review',
  status: 'review_only',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_commission_config_panel',
  title: 'Admin commission configuration panel',
  description: 'Commission percent is Admin-configured; foundation and client UI must not hardcode a fixed percent.',
  permission: 'taxi:admin-ui-cockpit:review',
  status: 'review_only',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_application_review_panel',
  title: 'Driver and park application review panel',
  description: 'Driver, vehicle and taxi park application review is Admin-owned and cannot be faked by client UI.',
  permission: 'taxi:admin-ui-cockpit:review',
  status: 'review_only',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_provider_wallet_runtime_lock_panel',
  title: 'Provider, Wallet and runtime lock panel',
  description: 'Provider dispatch, Wallet, payment, payout, route mount, DB and scheduler remain locked until exact approval.',
  permission: 'taxi:admin-ui-cockpit:review',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},

  {
    sectionId: 'taxi_foundation_overview',
    title: 'Taxi foundation overview',
    description: 'Safe-disabled foundation state, no runtime mounted, no fake success.',
    permission: 'taxi:read',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_client_boundary_bridge',
    title: 'Client kernel boundary bridge',
    description: 'Client app must use Taxi kernel facade/events/state only.',
    permission: 'taxi:read',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_driver_balance_gate',
    title: 'Driver balance gate',
    description: 'No balance means no dispatch pool, no order offer and no accept action.',
    permission: 'taxi:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_configured_commission',
    title: 'Admin-configured commission control',
    description: 'Commission is preview-only until real backend trip completion and exact approval.',
    permission: 'taxi:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_country_leagues',
    title: 'Country leagues',
    description: 'Driver and rider leaderboards are separated by country and season.',
    permission: 'taxi:league:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_daily_ai_reports',
    title: 'Daily Sabi AI reports',
    description: 'Full daily report per country checks all complaints, stars, violations and reward freezes.',
    permission: 'taxi:ai-report:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_complaint_review',
    title: 'Complaint review',
    description: 'Daily complaint tiers: 1/2/3/>3 verified complaints per country day for drivers and riders.',
    permission: 'taxi:complaint:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_reward_freeze',
    title: 'Reward freeze review',
    description: 'Top-3 prizes are frozen until reports, appeals and Admin review are clean.',
    permission: 'taxi:reward:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_ai_pipeline_control',
    title: 'Sabi AI daily pipeline control',
    description: 'Daily per-country Sabi AI report pipeline contract and review stages are Admin-visible from foundation.',
    permission: 'taxi:ai-report:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_daily_country_audit',
    title: 'Daily country audit',
    description: 'Admin audit fields for country/day/role complaint, cancellation, reward freeze and appeal reporting.',
    permission: 'taxi:audit:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_complaint_review_queue',
    title: 'Complaint review queue',
    description: 'Driver/rider complaint queue for Sabi AI review and Admin decision before any penalty is real.',
    permission: 'taxi:complaint:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_client_boundary_compatibility',
    title: 'Client kernel boundary compatibility',
    description: 'Mobile Taxi UI stays compatible by using kernel summaries only; raw evidence remains Admin/foundation side.',
    permission: 'taxi:client-boundary:read',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_ai_decision_lifecycle',
    title: 'AI/Admin decision lifecycle',
    description: 'Daily Sabi AI report, evidence bundle, Admin decision and exact approval lifecycle before sanctions or rewards.',
    permission: 'taxi:decision:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_appeal_sla',
    title: 'Appeal and explanation SLA',
    description: 'Hard blocks and prize disqualification require explanation/appeal window before final action.',
    permission: 'taxi:appeal:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_daily_report_completeness',
    title: 'Daily report completeness',
    description: 'Every country/day report must include all complaint, false complaint, cancellation, appeal and reward freeze fields.',
    permission: 'taxi:ai-report:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_daily_report_export',
    title: 'Daily report export and retention',
    description: 'Admin export/retention contracts for country/day AI reports, evidence bundles, decisions and reward freeze audits.',
    permission: 'taxi:report:export',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_evidence_redaction',
    title: 'Evidence redaction and mobile privacy',
    description: 'Raw complaint/chat/call/route evidence remains Admin/foundation only; mobile receives kernel-safe status summaries only.',
    permission: 'taxi:evidence:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_escalation_matrix',
    title: 'Daily complaint escalation matrix',
    description: 'Country/day 0/1/2/3/>3 complaint escalation rules are symmetric for drivers and riders and never execute from UI.',
    permission: 'taxi:decision:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },


  {
    sectionId: 'taxi_admin_daily_dashboard',
    title: 'Admin daily Sabi AI dashboard',
    description: 'Admin dashboard contract for daily country/day AI reports with driver/rider symmetry and review states.',
    permission: 'taxi:dashboard:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_complaint_filters',
    title: 'Admin complaint filters',
    description: 'Country, day, role, complaint tier, AI confidence, review status, appeal and reward freeze filters.',
    permission: 'taxi:dashboard:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_action_state_board',
    title: 'Admin action-state board',
    description: 'Separates AI review, Admin review, explanation, cooldown candidate, hard block candidate, reward freeze and restore candidate.',
    permission: 'taxi:action-state:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_country_day_role_filters',
    title: 'Country/day/role compatibility filters',
    description: 'Admin and client kernel boundary summaries use the same country/day/role framing without leaking raw evidence to mobile.',
    permission: 'taxi:dashboard:read',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_admin_notification_center',
    title: 'Admin Taxi notification center',
    description: 'Admin notification contracts for daily Sabi AI report status, escalation badges and review alerts.',
    permission: 'taxi:notification:read',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_action_inbox',
    title: 'Admin Taxi action inbox',
    description: 'Review queue for complaints, false complaints, cancellation abuse, cooldown candidates, hard blocks, restore and reward freeze candidates.',
    permission: 'taxi:action-inbox:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_daily_report_status',
    title: 'Daily report status lifecycle',
    description: 'Tracks Sabi AI review required/completed, Admin review, participant explanation, appeal SLA and clean-day close states.',
    permission: 'taxi:ai-report:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_appeal_sla_notifications',
    title: 'Appeal SLA notifications',
    description: 'Admin-visible timers for explanation and appeal windows before hard block or prize disqualification.',
    permission: 'taxi:notification:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_reward_freeze_alerts',
    title: 'Reward freeze alerts',
    description: 'Alerts for top-3 reward freeze/release candidates while disputes, reports or appeals remain open.',
    permission: 'taxi:reward:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_admin_approval_gates',
    title: 'Admin approval gates',
    description: 'Approval gates for daily report close, penalties, hard block, reward freeze/release, restore and client kernel boundary summary publish.',
    permission: 'taxi:approval-gate:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_daily_report_close_gate',
    title: 'Daily report close gate',
    description: 'Country/day report cannot be closed until every complaint is checked and Sabi AI evidence bundle is complete.',
    permission: 'taxi:report:close',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_reward_release_approval_gate',
    title: 'Reward release approval gate',
    description: 'Top-3 reward release requires clean daily report, Admin review and legal or finance approval; no payout runtime now.',
    permission: 'taxi:reward:approve',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_client_boundary_publish_gate',
    title: 'Client kernel boundary summary publish gate',
    description: 'Mobile receives only kernel-safe status after Admin locked decision; raw evidence remains Admin/foundation only.',
    permission: 'taxi:mobile-summary:publish',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_provider_payment_locks',
    title: 'Provider/payment locks',
    description: 'Provider, payment, payout and Wallet mutation remain disabled until exact approval.',
    permission: 'taxi:provider:configure',
    status: 'safe_disabled',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_admin_execution_readiness',
    title: 'Admin execution readiness control',
    description: 'Exact-approval readiness plan for future Taxi runtime/API/DB/provider/payment activation while foundation stays safe-disabled.',
    permission: 'taxi:execution-readiness:review',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_runtime_route_mount_gate',
    title: 'Runtime route mount gate',
    description: 'Taxi API routes remain unmounted until exact owner approval, security review, smoke plan and rollback plan are ready.',
    permission: 'taxi:runtime-route:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_scheduler_activation_gate',
    title: 'Scheduler activation gate',
    description: 'Daily Sabi AI report scheduler is contract-only now and cannot run until exact runtime approval.',
    permission: 'taxi:scheduler:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_db_schema_migration_gate',
    title: 'DB schema and migration gate',
    description: 'DB schema, migrations, Prisma generate, reads and writes require separate exact approval before real execution.',
    permission: 'taxi:db-schema:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_wallet_payment_payout_execution_gate',
    title: 'Wallet/payment/payout execution gate',
    description: 'Driver balance top-up, Admin-configured commission debit, ride charge, tips, rewards and payouts remain locked until exact approval.',
    permission: 'taxi:wallet-payment-payout:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_provider_dispatch_execution_gate',
    title: 'Provider dispatch execution gate',
    description: 'Dispatch, map, route, traffic, radar, quote and matching providers remain disabled until reference labels and exact approval are ready.',
    permission: 'taxi:provider-dispatch:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_final_foundation_control',
    title: 'Final Taxi foundation control',
    description: 'Final control layer for readiness score, handoff matrix, anti-runtime guards and kernel compatibility assertions.',
    permission: 'taxi:execution-readiness:review',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_final_readiness_score',
    title: 'Final readiness score',
    description: '100% contract-only readiness score while runtime, DB, Wallet, provider, payment and payout remain disabled.',
    permission: 'taxi:execution-readiness:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_final_admin_handoff_matrix',
    title: 'Admin handoff matrix',
    description: 'Owner-by-owner handoff for foundation, Admin UI, client kernel boundary, Sabi AI, DB, runtime, providers and Wallet/payment/payout.',
    permission: 'taxi:execution-readiness:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_anti_accidental_runtime_guard',
    title: 'Anti-accidental runtime guard',
    description: 'Blocks accidental route mount, scheduler start, DB access, provider call, Wallet mutation, payment, payout and fake success fallback.',
    permission: 'taxi:runtime:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_client_boundary_compatibility_assertions',
    title: 'Client kernel boundary compatibility assertions',
    description: 'Client app must use kernel facade/events/state and receive only redacted status after Admin locked decision.',
    permission: 'taxi:client-boundary:read',
    status: 'visible_contract_ready',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },

  {
    sectionId: 'taxi_next_phase_handoff',
    title: 'Next phase Admin/DB handoff',
    description: 'Admin UI, DB schema, route plan and scheduler plan are aligned with foundation but remain safe-disabled until exact approval.',
    permission: 'taxi:next-phase:review',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_admin_ui_review_only_plan',
    title: 'Admin UI review-only plan',
    description: 'Future Admin UI panels can render contracts without DB reads, runtime execution or fake success.',
    permission: 'taxi:admin-ui:plan',
    status: 'review_only',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_db_schema_plan',
    title: 'Taxi DB schema plan',
    description: 'Schema model plan for rides, complaints, AI reports, evidence, decisions, appeals, leagues and reward freeze audits.',
    permission: 'taxi:db-schema:plan',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_route_contract_plan',
    title: 'Taxi route contract plan',
    description: 'Admin and client-boundary route contracts are planned but no routes are mounted and no runtime is enabled.',
    permission: 'taxi:route-plan:review',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_schema_runtime_separation',
    title: 'Schema/runtime separation',
    description: 'DB schema, Prisma generate, migrations, DB reads/writes and route runtime are separate exact-approval steps.',
    permission: 'taxi:db-schema:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
  {
    sectionId: 'taxi_future_scheduler_plan',
    title: 'Future daily AI scheduler plan',
    description: 'Daily Sabi AI report scheduler is planned but cannot run until runtime, DB and AI provider approvals are complete.',
    permission: 'taxi:scheduler:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },



{
  sectionId: 'taxi_db_schema_exact_approval_plan',
  title: 'DB schema exact approval plan',
  description: 'Exact approval planning for Taxi Prisma schema models, preflight checks and schema-write scope; no schema write now.',
  permission: 'taxi:db-schema:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_prisma_preflight_plan',
  title: 'Prisma preflight plan',
  description: 'Prisma generate and migration are locked until schema review, rollback plan and exact owner approval.',
  permission: 'taxi:db-schema:plan',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_migration_rollback_plan',
  title: 'Migration rollback plan',
  description: 'Migration execution requires backup, dry-run, rollback plan and explicit owner approval.',
  permission: 'taxi:db-schema:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_db_runtime_zero_access_guard',
  title: 'DB zero-access guard',
  description: 'DB read/write remains disabled in this planning stage; Admin panels render contracts only.',
  permission: 'taxi:db-schema:plan',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},


{
  sectionId: 'taxi_prisma_schema_candidate_package',
  title: 'Prisma schema candidate package',
  description: 'Candidate package readiness for Taxi Prisma model shapes; no candidate file, schema write, generate, migration or DB access now.',
  permission: 'taxi:schema-candidate:review',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_owner_approval',
  title: 'Schema candidate owner approval',
  description: 'Owner approval template for a future schema candidate write step only; all runtime, Prisma generate, migration and DB access stay locked.',
  permission: 'taxi:schema-candidate:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_diff_gate',
  title: 'Schema candidate diff gate',
  description: 'Future schema diff review must pass before touching prisma/schema.prisma or running Prisma generate.',
  permission: 'taxi:db-schema:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_zero_access_guard',
  title: 'Schema candidate zero-access guard',
  description: 'Schema candidate planning cannot read DB, write DB, mount routes, start scheduler, mutate Wallet, charge payment, payout or call provider.',
  permission: 'taxi:schema-candidate:review',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},


{
  sectionId: 'taxi_schema_candidate_materialization_plan',
  title: 'Schema candidate materialization plan',
  description: 'Future candidate artifact write plan is visible for Admin review only; no candidate file, Prisma schema, generate, migrate or DB access now.',
  permission: 'taxi:schema-materialization:review',
  status: 'review_only',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_materialization_approval_gate',
  title: 'Schema materialization approval gate',
  description: 'Candidate materialization requires separate exact owner approval and cannot silently mutate schema or DB.',
  permission: 'taxi:schema-materialization:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_diff_preview_gate',
  title: 'Schema candidate diff preview gate',
  description: 'Diff preview and rollback plan must exist before any Prisma schema write, generate or migration.',
  permission: 'taxi:db-schema:approve',
  status: 'exact_approval_required',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_schema_candidate_materialization_zero_access_guard',
  title: 'Schema materialization zero-access guard',
  description: 'Materialization planning keeps DB, Wallet, provider, payment, payout, scheduler and runtime routes disabled.',
  permission: 'taxi:schema-materialization:review',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},


{
  sectionId: 'taxi_admin_foundation_completion_100_percent',
  title: 'Taxi foundation and Admin 100% contract readiness',
  description: 'Foundation and Admin preparation are complete at contract/readiness level before returning to client app/UX; no runtime is enabled.',
  permission: 'taxi:foundation-completion:read',
  status: 'visible_contract_ready',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_mobile_ui_return_gate',
  title: 'Client UI return blocked until real foundation/Admin 100%',
  description: 'Do not continue client UI/UX until real foundation/Admin runtime, DB, Admin UI and approval gates are prepared; clients receive only safe summaries.',
  permission: 'taxi:mobile-ui-return:review',
  status: 'visible_contract_ready',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_runtime_schema_scheduler_lock',
  title: 'Runtime/schema/scheduler lock',
  description: 'Routes, scheduler, Prisma schema write, generate, migrate, DB, Wallet, payment, payout and provider remain locked until exact approval.',
  permission: 'taxi:runtime-lock:review',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},
{
  sectionId: 'taxi_admin_no_fake_success_completion_guard',
  title: 'No fake success completion guard',
  description: 'Completion cannot fake AI report, complaint review, reward release, penalty, driver balance, payment, payout, provider or mobile publish success.',
  permission: 'taxi:foundation-completion:read',
  status: 'safe_disabled',
  sourceBackedByFoundation: true,
  mountedRuntimeNow: false,
  fakeSuccessBlocked: true,
},

  {
    sectionId: 'taxi_exact_approval_control',
    title: 'Exact approval control',
    description: 'Runtime activation, payment, payout, DB writes and provider calls require exact approval.',
    permission: 'taxi:runtime:approve',
    status: 'exact_approval_required',
    sourceBackedByFoundation: true,
    mountedRuntimeNow: false,
    fakeSuccessBlocked: true,
  },
];

export function getTaxiAdminCompatibilitySnapshot(): TaxiAdminCompatibilitySnapshot {
  return {
    version: 'TAXI-BACKEND-FOUNDATION-001S',
    module: 'taxi',
    status: 'admin_compatible_foundation_safe_disabled_ready',
    adminAddedWithFoundation: true,
    maximumCompatibilityMode: true,
    clientAppMustUseKernel: true,
    adminUiMayUseContractsOnlyNow: true,
    foundation: getTaxiFoundationSnapshot(),
    kernel: getTaxiKernelBridgeSnapshot(),
    clientBoundary: getTaxiClientBoundarySnapshot(),
    aiDailyReview: getTaxiAiDailyReportSnapshot(),
    aiDailyExport: getTaxiAiDailyExportSnapshot(),
    adminDashboard: getTaxiAdminDashboardReadinessSnapshot(),
    adminNotifications: getTaxiAdminNotificationReadinessSnapshot(),
    adminApprovalGates: getTaxiAdminApprovalGatesSnapshot(),
    adminExecutionReadiness: getTaxiAdminExecutionReadinessSnapshot(),
    finalControl: getTaxiFinalControlSnapshot(),
    nextPhaseHandoff: getTaxiNextPhaseHandoffSnapshot(),
    dbSchemaApproval: getTaxiDbSchemaApprovalSnapshot(),
    prismaSchemaCandidate: getTaxiPrismaSchemaCandidateSnapshot(),
    schemaCandidateMaterialization: getTaxiSchemaCandidateMaterializationSnapshot(),
    adminFoundationCompletion: getTaxiAdminFoundationCompletionSnapshot(),
    adminUiCockpit: getTaxiAdminUiCockpitSnapshot(),
    adminIntegration: getTaxiAdminIntegrationSnapshot(),
    aiAdminDecision: getTaxiAiAdminDecisionSnapshot(),
    adminSections: TAXI_ADMIN_SECTION_CONTRACTS,
    routeDescriptors: [
      ...taxiFoundationRouteDescriptors,
      ...taxiKernelRouteDescriptors,
      ...taxiClientBoundaryRouteDescriptors,
      ...TAXI_AI_DAILY_REVIEW_ROUTE_DESCRIPTORS,
      ...taxiAdminIntegrationRouteDescriptors,
      ...taxiAiAdminDecisionRouteDescriptors,
      ...taxiAiDailyExportRouteDescriptors,
      ...taxiAdminDashboardRouteDescriptors,
      ...taxiAdminNotificationRouteDescriptors,
      ...taxiAdminApprovalGateRouteDescriptors,
      ...taxiAdminExecutionReadinessRouteDescriptors,
      ...taxiFinalControlRouteDescriptors,
      ...taxiNextPhaseHandoffRouteDescriptors,
      ...taxiDbSchemaApprovalRouteDescriptors,
      ...taxiPrismaSchemaCandidateRouteDescriptors,
      ...taxiSchemaCandidateMaterializationRouteDescriptors,
      ...taxiAdminFoundationCompletionRouteDescriptors,
      ...taxiAdminUiCockpitRouteDescriptors,
    ],
    runtimeRoutesMountedNow: false,
    dbReadEnabled: false,
    dbWriteEnabled: false,
    walletMutationEnabled: false,
    paymentEnabled: false,
    payoutEnabled: false,
    providerEnabled: false,
    exactApprovalRequiredForRuntime: true,
    fakeSuccessBlocked: true,
  };
}

export function evaluateTaxiAdminReadinessRequest(input: TaxiAdminReadinessDecisionInput): TaxiAdminReadinessDecision {
  const blockedReasons: string[] = [];

  if (!input.hasAdminPermission) {
    blockedReasons.push('admin_permission_required');
  }
  if (input.wantsRuntimeExecution) {
    blockedReasons.push('runtime_execution_safe_disabled');
  }
  if (input.wantsDbReadOrWrite) {
    blockedReasons.push('db_runtime_not_enabled');
  }
  if (input.wantsProviderPaymentOrPayout) {
    blockedReasons.push('provider_payment_payout_locked');
  }
  if (!input.hasExactApproval) {
    blockedReasons.push('exact_approval_required');
  }

  return {
    requestedSection: input.requestedSection,
    canRenderAdminSection: input.hasAdminPermission,
    canExecuteRuntime: false,
    blockedReasons: Array.from(new Set(blockedReasons)),
    requiresExactApprovalForRuntime: true,
    fakeSuccessBlocked: true,
  };
}
