import type {
  StreamFoundationKernelDiagnosticsAdminRouteDefinition,
  StreamFoundationKernelDiagnosticsAdminRouteId,
  StreamFoundationKernelDiagnosticsAdminRouteSafety,
} from "./streamFoundationKernelDiagnosticsAdminRouteContracts";

export const STREAM_FOUNDATION_KERNEL_DIAGNOSTICS_ADMIN_ROUTE_SAFETY: StreamFoundationKernelDiagnosticsAdminRouteSafety = {
  streamIndexPatchIncluded: false,
  adminUiFilesChangedNow: false,
  adminRouteMountedNow: false,
  expressRouterCreatedNow: false,
  appServerTouchedNow: false,
  routeMountAllowedNow: false,
  databaseReadAllowedNow: false,
  databaseWriteAllowedNow: false,
  providerCallAllowedNow: false,
  walletMutationAllowedNow: false,
  paymentAuthorizationAllowedNow: false,
  recipientEarningCreditAllowedNow: false,
  monthlyPayoutAllowedNow: false,
  realtimeBroadcastAllowedNow: false,
  moneyMovementAllowedNow: false,
  rawSecretsReturned: false,
  mobileProviderKeysAllowed: false,
  fakeSuccessAllowed: false,
};

export const STREAM_FOUNDATION_KERNEL_DIAGNOSTICS_ADMIN_ROUTE_DEFINITIONS: readonly StreamFoundationKernelDiagnosticsAdminRouteDefinition[] = [
  {
    routeId: "stream_kernel_diagnostics_snapshot",
    method: "GET",
    path: "/api/admin/stream/kernel/diagnostics/snapshot",
    descriptionKey: "stream.admin.kernelDiagnostics.routes.snapshot.description",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
    responseShape: "redacted_admin_handoff_snapshot",
    mountedNow: false,
    appServerPatchRequiredLater: true,
    adminPermissionRequired: true,
    returnsRawSecrets: false,
    performsProviderCall: false,
    performsDatabaseRead: false,
    performsDatabaseWrite: false,
    performsMoneyMovement: false,
  },
  {
    routeId: "stream_kernel_diagnostics_blocked_findings",
    method: "GET",
    path: "/api/admin/stream/kernel/diagnostics/blocked-findings",
    descriptionKey: "stream.admin.kernelDiagnostics.routes.blockedFindings.description",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
    responseShape: "redacted_findings_only",
    mountedNow: false,
    appServerPatchRequiredLater: true,
    adminPermissionRequired: true,
    returnsRawSecrets: false,
    performsProviderCall: false,
    performsDatabaseRead: false,
    performsDatabaseWrite: false,
    performsMoneyMovement: false,
  },
  {
    routeId: "stream_kernel_diagnostics_readiness",
    method: "GET",
    path: "/api/admin/stream/kernel/diagnostics/readiness",
    descriptionKey: "stream.admin.kernelDiagnostics.routes.readiness.description",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
    responseShape: "readiness_status",
    mountedNow: false,
    appServerPatchRequiredLater: true,
    adminPermissionRequired: true,
    returnsRawSecrets: false,
    performsProviderCall: false,
    performsDatabaseRead: false,
    performsDatabaseWrite: false,
    performsMoneyMovement: false,
  },
  {
    routeId: "stream_kernel_diagnostics_safe_summary",
    method: "GET",
    path: "/api/admin/stream/kernel/diagnostics/safe-summary",
    descriptionKey: "stream.admin.kernelDiagnostics.routes.safeSummary.description",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read", "admin:stream:monetization:read"],
    responseShape: "safe_summary",
    mountedNow: false,
    appServerPatchRequiredLater: true,
    adminPermissionRequired: true,
    returnsRawSecrets: false,
    performsProviderCall: false,
    performsDatabaseRead: false,
    performsDatabaseWrite: false,
    performsMoneyMovement: false,
  },
] as const;

export function getStreamFoundationKernelDiagnosticsAdminRouteDefinition(routeId: StreamFoundationKernelDiagnosticsAdminRouteId): StreamFoundationKernelDiagnosticsAdminRouteDefinition | undefined {
  return STREAM_FOUNDATION_KERNEL_DIAGNOSTICS_ADMIN_ROUTE_DEFINITIONS.find((route) => route.routeId === routeId);
}
