import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAiDailyEscalationMatrixRule,
  TaxiAiDailyEvidenceRedactionRule,
  TaxiAiDailyExportContract,
  TaxiAiDailyExportRetentionClass,
  TaxiAiDailyKernelSummaryContract,
  TaxiAiDailyRetentionContract,
  TaxiAiDailyExportVersion,
} from './taxiAiDailyExport.types';

export const TAXI_AI_DAILY_EXPORT_VERSION: TaxiAiDailyExportVersion = 'TAXI-BACKEND-FOUNDATION-001G';

export const TAXI_AI_DAILY_EXPORT_CONTRACTS: readonly TaxiAiDailyExportContract[] = [
  {
    exportId: 'admin_country_day_full_json',
    title: 'Admin country/day full JSON report',
    format: 'admin_json',
    includesEveryCountryDay: true,
    includesDriversAndRiders: true,
    includesAllComplaints: true,
    includesFalseComplaintSignals: true,
    includesCancellationAbuseSignals: true,
    includesTripAfterCancelSignals: true,
    includesStarsComplaintConflict: true,
    includesRewardFreezeQueue: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeExportEnabledNow: false,
    fakeReportBlocked: true,
  },
  {
    exportId: 'admin_country_day_csv_summary',
    title: 'Admin country/day CSV summary',
    format: 'admin_csv_summary',
    includesEveryCountryDay: true,
    includesDriversAndRiders: true,
    includesAllComplaints: true,
    includesFalseComplaintSignals: true,
    includesCancellationAbuseSignals: true,
    includesTripAfterCancelSignals: true,
    includesStarsComplaintConflict: true,
    includesRewardFreezeQueue: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeExportEnabledNow: false,
    fakeReportBlocked: true,
  },
  {
    exportId: 'client_boundary_redacted_status_summary',
    title: 'Client kernel boundary redacted status summary',
    format: 'redacted_client_boundary_summary',
    includesEveryCountryDay: true,
    includesDriversAndRiders: true,
    includesAllComplaints: true,
    includesFalseComplaintSignals: true,
    includesCancellationAbuseSignals: true,
    includesTripAfterCancelSignals: true,
    includesStarsComplaintConflict: true,
    includesRewardFreezeQueue: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeExportEnabledNow: false,
    fakeReportBlocked: true,
  },
] as const;

export const TAXI_AI_DAILY_RETENTION_CLASSES: readonly TaxiAiDailyExportRetentionClass[] = [
  'country_day_report',
  'complaint_evidence_bundle',
  'admin_decision_audit',
  'appeal_explanation',
  'reward_freeze_release_audit',
  'client_boundary_summary',
] as const;

export const TAXI_AI_DAILY_RETENTION_CONTRACTS: readonly TaxiAiDailyRetentionContract[] = [
  {
    retentionClass: 'country_day_report',
    title: 'Country/day report retention',
    adminPurpose: 'Keep the daily report auditable by country and calendar day.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
  {
    retentionClass: 'complaint_evidence_bundle',
    title: 'Complaint evidence bundle retention',
    adminPurpose: 'Keep Sabi AI and Admin review evidence together before any penalty candidate.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
  {
    retentionClass: 'admin_decision_audit',
    title: 'Admin decision audit retention',
    adminPurpose: 'Explain why points, cooldown, block, restore or reward freeze/release was recommended.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
  {
    retentionClass: 'appeal_explanation',
    title: 'Appeal and explanation retention',
    adminPurpose: 'Store participant explanation window outcome before hard action.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
  {
    retentionClass: 'reward_freeze_release_audit',
    title: 'Reward freeze/release audit retention',
    adminPurpose: 'Keep top-3 prize decisions auditable before payment or payout provider flow exists.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
  {
    retentionClass: 'client_boundary_summary',
    title: 'Client kernel boundary summary retention',
    adminPurpose: 'Track what safe summary was visible to mobile without leaking raw evidence.',
    redactBeforeMobile: true,
    rawEvidenceLeavesFoundation: false,
    requiresAdminPermission: true,
    requiresExactApprovalForRuntimeAccess: true,
    runtimeStorageEnabledNow: false,
  },
] as const;

export const TAXI_AI_DAILY_REDACTION_RULES: readonly TaxiAiDailyEvidenceRedactionRule[] = [
  {
    ruleId: 'raw_chat_call_route_admin_only',
    title: 'Raw chat/call/route evidence stays Admin/foundation only',
    rawEvidenceScope: 'admin_full_evidence_only',
    mobileAllowed: false,
    adminAllowed: true,
    protectsDriversAndRiders: true,
    preventsPublicShaming: true,
    fakeEvidenceBlocked: true,
  },
  {
    ruleId: 'complaint_identity_blocked_from_mobile',
    title: 'Complaint identities and private details are blocked from mobile',
    rawEvidenceScope: 'blocked_from_mobile',
    mobileAllowed: false,
    adminAllowed: true,
    protectsDriversAndRiders: true,
    preventsPublicShaming: true,
    fakeEvidenceBlocked: true,
  },
  {
    ruleId: 'mobile_sees_safe_status_only',
    title: 'Mobile sees safe status only through kernel',
    rawEvidenceScope: 'client_boundary_safe_summary',
    mobileAllowed: 'safe_status_only',
    adminAllowed: true,
    protectsDriversAndRiders: true,
    preventsPublicShaming: true,
    fakeEvidenceBlocked: true,
  },
] as const;

export const TAXI_AI_DAILY_ESCALATION_MATRIX: readonly TaxiAiDailyEscalationMatrixRule[] = [
  {
    ruleId: 'zero_verified_complaints_clean_day',
    countryDayComplaintCount: 0,
    severity: 'none',
    driverActionCandidate: 'clean_day_no_action',
    riderActionCandidate: 'clean_day_no_action',
    requiresSabiAiReview: true,
    requiresAdminDecision: false,
    requiresAppealBeforeHardAction: false,
    executionEnabledNow: false,
    fakePenaltyBlocked: true,
  },
  {
    ruleId: 'one_verified_complaint_points_review',
    countryDayComplaintCount: 1,
    severity: 'low',
    driverActionCandidate: 'points_penalty_candidate_after_review',
    riderActionCandidate: 'points_penalty_candidate_after_review',
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    requiresAppealBeforeHardAction: false,
    executionEnabledNow: false,
    fakePenaltyBlocked: true,
  },
  {
    ruleId: 'two_verified_complaints_one_hour_cooldown_review',
    countryDayComplaintCount: 2,
    severity: 'medium',
    driverActionCandidate: 'points_penalty_plus_one_hour_no_orders_candidate',
    riderActionCandidate: 'points_penalty_plus_one_hour_no_orders_candidate',
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    requiresAppealBeforeHardAction: false,
    executionEnabledNow: false,
    fakePenaltyBlocked: true,
  },
  {
    ruleId: 'three_verified_complaints_three_hour_cooldown_review',
    countryDayComplaintCount: 3,
    severity: 'high',
    driverActionCandidate: 'points_penalty_plus_three_hour_no_orders_candidate',
    riderActionCandidate: 'points_penalty_plus_three_hour_no_orders_candidate',
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    requiresAppealBeforeHardAction: false,
    executionEnabledNow: false,
    fakePenaltyBlocked: true,
  },
  {
    ruleId: 'more_than_three_verified_complaints_hard_block_review',
    countryDayComplaintCount: 4,
    severity: 'hard_block_candidate',
    driverActionCandidate: 'blocked_until_explanation_and_admin_review_candidate',
    riderActionCandidate: 'blocked_until_explanation_and_admin_review_candidate',
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    requiresAppealBeforeHardAction: true,
    executionEnabledNow: false,
    fakePenaltyBlocked: true,
  },
] as const;

export const TAXI_AI_DAILY_KERNEL_SUMMARIES: readonly TaxiAiDailyKernelSummaryContract[] = [
  {
    summaryId: 'participant_daily_trust_status',
    title: 'Participant daily trust status',
    clientAppMustUseKernel: true,
    containsRawEvidence: false,
    containsPersonalComplaintDetails: false,
    showsDailyStatusOnly: true,
    showsAppealStatusOnly: true,
    showsRewardFreezeStatusOnly: true,
    runtimePushEnabledNow: false,
  },
  {
    summaryId: 'league_reward_freeze_status',
    title: 'League reward freeze status',
    clientAppMustUseKernel: true,
    containsRawEvidence: false,
    containsPersonalComplaintDetails: false,
    showsDailyStatusOnly: true,
    showsAppealStatusOnly: true,
    showsRewardFreezeStatusOnly: true,
    runtimePushEnabledNow: false,
  },
] as const;

export const taxiAiDailyExportRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/admin/taxi/ai-daily-export/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin-compatible daily report export/retention readiness; no runtime export is mounted now.',
  },
  {
    method: 'POST',
    path: '/admin/taxi/ai-daily-export/preview-redaction',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview-only redaction contract for client kernel boundary summaries; no raw evidence leaves foundation.',
  },
  {
    method: 'POST',
    path: '/admin/taxi/ai-daily-export/preview-escalation',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview-only escalation matrix by country/day complaints; no penalty is executed.',
  },
] as const;
