export const SABI_CORE_MONETIZATION_102F_ENTITLEMENT_EARNINGS_LEDGER_DB_SCHEMA_PLANNING = {
  version: "SABI-CORE-MONETIZATION-102F",
  mode: "entitlement_earnings_ledger_db_schema_planning_only",
  planningOnly: true,
  prismaSchemaWriteAllowedNow: false,
  prismaMigrateOrGenerateAllowedNow: false,
  databaseWriteAllowedNow: false,
  runtimeEnabledNow: false,
  providerActivationAllowedNow: false,
  providerCallAllowedNow: false,
  walletMutationAllowedNow: false,
  moneyMovementAllowedNow: false,
  creatorPayoutExecutionAllowedNow: false,
  googleBillingRuntimeAllowedNow: false,
  airwallexRuntimeAllowedNow: false,
  adminUiWriteAllowedNow: false,
  mobileUiWriteAllowedNow: false,
  schemaPlanning: {
    purpose: "Plan DB schema boundaries for Google Billing entitlements, creator earnings, refund/revocation evidence, payout locks, and audit hashes without writing Prisma schema or DB.",
    futureModelsPlannedOnly: [
      "SabiDigitalEntitlementLedger",
      "SabiGoogleBillingPurchaseEvidence",
      "SabiCreatorEarningsLedger",
      "SabiCreatorPayoutLock",
      "SabiCreatorRefundReserve",
      "SabiMonetizationIdempotencyKey",
      "SabiMonetizationAuditHash",
    ],
    forbiddenNow: [
      "prisma.schema.write",
      "prisma.migrate",
      "prisma.generate",
      "database.write",
      "provider.call",
      "wallet.mutation",
      "money.movement",
      "creator.payout.execution",
      "stake.gambling.runtime",
      "raw.purchase.token.storage",
      "raw.secret.storage.in_source",
    ],
  },
  entitlementLedgerPlanning: {
    ledgerPurpose: "Record verified Android digital goods entitlements after future Google Billing server verification, using idempotent, auditable, reversible records.",
    allowedSources: [
      "google_billing_verified_purchase_future",
      "admin_readonly_review_evidence_future",
    ],
    digitalGoodsScope: [
      "coin_pack",
      "premium_subscription",
      "premium_effect",
      "digital_gift",
      "creator_support_digital",
      "android_digital_game_item",
    ],
    requiredFieldsPlannedOnly: [
      "id",
      "userId",
      "sourceProvider",
      "productId",
      "entitlementType",
      "status",
      "quantityOrAmountMinor",
      "currencyOrUnit",
      "verifiedAt",
      "revokedAt",
      "idempotencyKeyHash",
      "purchaseTokenHash",
      "auditHash",
      "createdAt",
      "updatedAt",
    ],
    rawPurchaseTokenStorageAllowed: false,
    rawPurchaseTokenLogAllowed: false,
    tokenHashOnlyAllowed: true,
  },
  googleBillingPurchaseEvidencePlanning: {
    evidencePurpose: "Store redacted purchase verification evidence and audit hash after future provider connector approval.",
    allowedEvidence: [
      "providerName",
      "packageName",
      "productId",
      "purchaseState",
      "acknowledgementState",
      "consumptionState",
      "orderIdHashOrRedactedSuffix",
      "purchaseTokenHash",
      "verificationAuditHash",
    ],
    blockedEvidence: [
      "rawPurchaseToken",
      "rawProviderSecret",
      "fullOrderIdIfPolicyRequiresRedaction",
      "rawUserPrivateData",
    ],
    providerCallAllowedNow: false,
    runtimeVerificationAllowedNow: false,
  },
  creatorEarningsLedgerPlanning: {
    ledgerPurpose: "Plan creator earnings buckets from future digital gifts, creator support, subscriptions/revenue share, and safe monetization sources without payout execution.",
    earningBuckets: [
      "pending",
      "compliance_hold",
      "refund_reserve",
      "payable",
      "reversed",
      "payout_locked",
    ],
    requiredFieldsPlannedOnly: [
      "id",
      "creatorId",
      "sourceEntitlementId",
      "earningType",
      "grossAmountMinor",
      "platformFeeMinor",
      "taxReserveMinor",
      "refundReserveMinor",
      "netPayableMinor",
      "currency",
      "status",
      "holdReason",
      "countryRiskCode",
      "kycAmlStatus",
      "auditHash",
      "createdAt",
      "updatedAt",
    ],
    payoutExecutionAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
  },
  payoutLockPlanning: {
    lockPurpose: "Keep creator payout and money release impossible until provider, compliance, tax, AML/risk, owner approval, and ledger checks are complete.",
    requiredFutureGates: [
      "creator_identity_kyc_ready",
      "creator_tax_profile_ready",
      "aml_risk_review_ready",
      "provider_payout_config_ready",
      "ledger_balance_reconciled",
      "refund_reserve_window_satisfied",
      "owner_or_compliance_approval_recorded",
    ],
    payoutApproveControlAllowedNow: false,
    moneyReleaseControlAllowedNow: false,
    providerPayoutCallAllowedNow: false,
  },
  refundRevocationPlanning: {
    purpose: "Plan reversible entitlement and earnings states for refund, chargeback, cancellation, abuse, and Play Billing revocation events.",
    futureEvents: [
      "refund",
      "chargeback",
      "subscription_cancelled",
      "subscription_expired",
      "purchase_revoked",
      "abuse_hold",
      "manual_compliance_hold",
    ],
    dbWriteAllowedNow: false,
    providerWebhookRuntimeAllowedNow: false,
  },
  providerBoundaries: {
    googleBilling: {
      androidDigitalGoodsOwner: true,
      runtimeEnabledNow: false,
      providerCallAllowedNow: false,
      rawPurchaseTokenAllowedNow: false,
    },
    airwallex: {
      physicalMerchantBusinessCommerceOnly: true,
      androidDigitalGoodsAllowed: false,
      runtimeEnabledNow: false,
      providerCallAllowedNow: false,
      settlementAllowedNow: false,
    },
    wallet: {
      digitalGoodsBypassAllowed: false,
      walletMutationAllowedNow: false,
      moneyMovementAllowedNow: false,
    },
    paidGamesStake: {
      stakeRuntimeAllowedNow: false,
      gamblingRuntimeAllowedNow: false,
      payoutRuntimeAllowedNow: false,
      requiresFutureLegalLicenseCountryAgeKycAml: true,
    },
  },
  safety: {
    sourceOnlyDesign: true,
    prismaSchemaWritePerformed: false,
    prismaMigrateOrGeneratePerformed: false,
    runtimeDbWritePerformed: false,
    providerActivationPerformed: false,
    providerCallPerformed: false,
    walletMutationPerformed: false,
    moneyMovementPerformed: false,
    creatorPayoutExecutionPerformed: false,
    stakeRuntimeEnabled: false,
    gamblingRuntimeEnabled: false,
    googleBillingRuntimeEnabled: false,
    airwallexRuntimeEnabled: false,
    adminUiTouched: false,
    mobileTouched: false,
    rawSecretsPrinted: false,
    rawPurchaseTokensPrinted: false,
    rawCardDataPrinted: false,
    rawPromptDataPrinted: false,
    rawUserPrivateDataPrinted: false,
  },
} as const;

export type SabiCoreMonetization102FEntitlementEarningsLedgerDbSchemaPlanning =
  typeof SABI_CORE_MONETIZATION_102F_ENTITLEMENT_EARNINGS_LEDGER_DB_SCHEMA_PLANNING;
