import type {
  TaxiTripLifecycleControlVersion001T,
  TaxiTripLifecycleGate001T,
  TaxiTripQuotePolicy001T,
  TaxiTripSettlementPolicy001T,
} from './types';

export const TAXI_TRIP_LIFECYCLE_CONTROL_VERSION_001T: TaxiTripLifecycleControlVersion001T = 'TAXI-BACKEND-FOUNDATION-001T';

export const TAXI_TRIP_QUOTE_POLICY_001T: TaxiTripQuotePolicy001T = {
  adminConfiguredTariffRequired: true,
  adminConfiguredCommissionRequired: true,
  providerRouteRequiredForRuntime: true,
  trafficCameraRadarProviderRequired: true,
  distanceDurationProviderRequired: true,
  upfrontQuotePreviewAllowed: true,
  finalFareRequiresBackendTripCompletion: true,
  paymentAuthorizationBeforeDispatchRequired: true,
  cashModeRequiresDriverAndRiderRegionPolicy: true,
  fakeFareSuccessBlocked: true,
  fakeSurgeSuccessBlocked: true,
  uiMayCreateTrip: false,
};

export const TAXI_TRIP_SETTLEMENT_POLICY_001T: TaxiTripSettlementPolicy001T = {
  commissionDebitTiming: 'after_backend_trip_completed_only',
  driverCreditTiming: 'after_payment_or_cash_reconciliation',
  riderReceiptTiming: 'after_backend_fare_finalization',
  tipsRequireSeparateProviderLedger: true,
  refundsRequireAdminOrPolicyReview: true,
  promoLiabilityRequiresAdminConfig: true,
  walletMutationExecutedNow: false,
  paymentCapturedNow: false,
  payoutExecutedNow: false,
};

export const TAXI_TRIP_LIFECYCLE_GATES_001T: readonly TaxiTripLifecycleGate001T[] = [
  {
    stage: 'rider_request_draft',
    status: 'admin_config_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Rider request remains a foundation preview until Admin tariff, commission and regional policy are configured.',
  },
  {
    stage: 'quote_preview_locked',
    status: 'provider_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Quote preview may be shown only as locked readiness; real distance, ETA, traffic, cameras and radars require provider routing.',
  },
  {
    stage: 'provider_route_required',
    status: 'provider_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Route and navigation signals cannot be produced by UI or static backend constants.',
  },
  {
    stage: 'dispatch_offer_locked',
    status: 'safe_disabled_locked',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Runtime driver offers are locked until dispatch provider, payment authorization and driver eligibility gates are connected.',
  },
  {
    stage: 'driver_acceptance_locked',
    status: 'backend_evidence_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Driver acceptance must be backed by real driver session, balance reserve, document approval and provider timestamp.',
  },
  {
    stage: 'pickup_navigation_locked',
    status: 'provider_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Pickup navigation requires live provider location and active trip session; no fake moving car success.',
  },
  {
    stage: 'active_trip_locked',
    status: 'backend_evidence_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Trip start and active ride state require backend evidence and cannot be toggled by mobile UI.',
  },
  {
    stage: 'backend_completion_required',
    status: 'backend_evidence_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Trip completion, final fare and receipt require backend/provider completion evidence.',
  },
  {
    stage: 'post_trip_settlement_locked',
    status: 'wallet_provider_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Commission debit, driver credit, tips, refunds and receipts require Wallet/payment/provider ledgers.',
  },
  {
    stage: 'support_or_dispute_review',
    status: 'exact_owner_approval_required',
    adminVisible: true,
    exactApprovalRequired: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
    reason: 'Dispute, refund, reward freeze and heavy account action require Admin/Sabi AI evidence review.',
  },
];
