import {
  STREAM_FOUNDATION_141S_EVENT_AUDIT_GATE_VERSION,
  type StreamFoundation141SAuditEventContract,
  type StreamFoundation141SEventAuditGateSnapshot,
} from "./streamFoundationEventAuditGateContractPlanningContracts";

const AUDIT_EVENTS: readonly StreamFoundation141SAuditEventContract[] = [
  {
    id: "stream_live_session_start_requested",
    status: "contract_planned_not_bound",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when a live start command is received; not appended now.",
  },
  {
    id: "stream_live_session_start_source_only_blocked",
    status: "append_blocked_now",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when live start remains blocked by source-only/runtime approval gate.",
  },
  {
    id: "stream_live_session_stop_requested",
    status: "contract_planned_not_bound",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when a live stop command is received; not appended now.",
  },
  {
    id: "stream_live_session_stop_source_only_blocked",
    status: "append_blocked_now",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when live stop remains blocked by source-only/runtime approval gate.",
  },
  {
    id: "stream_live_heartbeat_received",
    status: "contract_planned_not_bound",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when heartbeat arrives; not appended now.",
  },
  {
    id: "stream_live_heartbeat_source_only_blocked",
    status: "append_blocked_now",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when heartbeat remains blocked by source-only/runtime approval gate.",
  },
  {
    id: "stream_runtime_mount_prerequisite_failed",
    status: "schema_review_required",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event for failed runtime prerequisite checks without exposing raw PII or secrets.",
  },
  {
    id: "stream_owner_runtime_mount_approval_required",
    status: "owner_approval_required",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event when runtime mount cannot proceed without owner approval.",
  },
  {
    id: "stream_moderation_policy_gate_required",
    status: "schema_review_required",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event for moderation gate failures or review-required states.",
  },
  {
    id: "stream_provider_readiness_gate_required",
    status: "schema_review_required",
    requiredBeforeRuntimeMount: true,
    appendAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    piiAllowedInAuditNow: false,
    rawSecretAllowedInAuditNow: false,
    description: "Future append event for provider_not_configured/readiness gate states without provider payload leak.",
  },
];

export function getStreamFoundationEventAuditGateContractPlanningSnapshot(): StreamFoundation141SEventAuditGateSnapshot {
  return {
    version: STREAM_FOUNDATION_141S_EVENT_AUDIT_GATE_VERSION,
    stage: "event_audit_gate_source_only_contract_planning",
    status: "event_audit_contract_planned_routes_remain_blocked",
    previousStage: "BACKEND-STREAM-FOUNDATION-141R",
    auditEvents: AUDIT_EVENTS,
    auditPolicy: {
      eventAuditRequiredBeforeRuntimeMount: true,
      immutableAppendRequiredBeforeRuntimeSuccess: true,
      actorUserIdReferenceAllowedLater: true,
      rawPiiAllowedNow: false,
      rawSecretAllowedNow: false,
      rawProviderPayloadAllowedNow: false,
      auditAppendAllowedNow: false,
      routesStayBlockedNow: true,
      expectedCurrentStatusCode: 423,
    },
    totals: {
      auditEvents: 10,
      readyForRuntimeMountNow: 0,
      auditAppendAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      providerCallAllowedNow: 0,
      walletMutationAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowedNow: 0,
    },
    safety: {
      sourceOnly141S: true,
      appTsChangeBy141S: false,
      serverTsChangeBy141S: false,
      streamIndexChangeBy141S: false,
      schemaMigrationBy141S: false,
      backendRestartBy141S: false,
      runtimeHttpBy141S: false,
      runtimePostBy141S: false,
      databaseReadBy141S: false,
      databaseWriteBy141S: false,
      providerCallBy141S: false,
      providerSecretReadBy141S: false,
      walletMutationBy141S: false,
      paymentAuthorizationBy141S: false,
      monthlyPayoutBy141S: false,
      moneyMovementBy141S: false,
      fakeSuccessBy141S: false,
    },
  };
}
