import type {
  SabiHomeProgramCode,
  SabiProgramFoundation,
  SabiProgramFoundationStatus,
  SabiProgramProviderStatus,
  SabiProgramRuntimeStatus,
} from "./programFoundation.types";

export const SABI_HOME_PROGRAM_CODES: SabiHomeProgramCode[] = [
  "home",
  "messenger",
  "wallet",
  "qr",
  "ai",
  "gallery",
  "network_game_center",
  "marketplace",
  "hotels",
  "taxi",
  "supermarket",
  "food_delivery",
  "wholesale_market",
  "stream",
  "delivery",
  "business",
  "merchant",
  "notifications",
  "events",
  "documents",
  "wifi_cast",
];

type LocalProgramSeed = {
  title: string;
  mobileRoute: string;
  apiBasePath: string;
  runtimeStatus: SabiProgramRuntimeStatus;
  providerStatus: SabiProgramProviderStatus;
  paymentsRouteThroughWallet: boolean;
  qrEnabled: boolean;
  notificationsEnabled: boolean;
  aiHooksEnabled: boolean;
  adminReviewRequired: boolean;
  requiredProviders: string[];
  safetyHooks: string[];
  historyStreams: string[];
};

const commerceProviders = ["wallet_payment_provider", "catalog_backend", "admin_compliance"];
const commerceHooks = ["unified_user_id_required", "no_simulated_success", "provider_unavailable_state", "wallet_payment_routing"];

const LOCAL_PROGRAMS: Record<SabiHomeProgramCode, LocalProgramSeed> = {
  home: {
    title: "Home",
    mobileRoute: "/",
    apiBasePath: "/api/v2/programs/home",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: [],
    safetyHooks: ["widget_registry", "notification_digest", "home_top_swipe_notification_drawer_only", "no_persistent_home_banner", "no_external_overlay", "ai_voice_entry"],
    historyStreams: ["home_widget_opened", "home_notification_seen"],
  },
  messenger: {
    title: "Messenger",
    mobileRoute: "/tabs/chats",
    apiBasePath: "/api/v2/messenger",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["auth_session", "messenger_realtime"],
    safetyHooks: ["presence", "message_report", "call_safety", "no_simulated_messages"],
    historyStreams: ["message", "call", "gift", "payment_request"],
  },
  wallet: {
    title: "Sabi Wallet",
    mobileRoute: "/wallet/home",
    apiBasePath: "/api/wallet",
    runtimeStatus: "provider_required",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["bank_or_payment_provider_sdk", "tokenized_card_provider", "ledger"],
    safetyHooks: ["pci_dss_token_only", "aml_kyc_hold", "wallet_risk_check"],
    historyStreams: ["wallet_balance", "wallet_transaction", "wallet_security_alert"],
  },
  qr: {
    title: "QR Center",
    mobileRoute: "/qr",
    apiBasePath: "/api/v2/qr",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["module_executor_mapping", "wallet_provider_for_money_movement"],
    safetyHooks: ["strict_payload_validation", "verified_session_user_id", "honest_result_status"],
    historyStreams: ["qr_scan", "qr_confirm", "qr_execute", "qr_admin_review"],
  },
  ai: {
    title: "Sabi AI",
    mobileRoute: "/ai",
    apiBasePath: "/api/ai",
    runtimeStatus: "provider_required",
    providerStatus: "api_key_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["llm_provider", "stt_provider", "tts_provider", "translation_provider"],
    safetyHooks: ["ai_safety_admin", "provider_not_configured_state", "no_simulated_ai_result"],
    historyStreams: ["ai_chat", "ai_voice", "ai_translation", "ai_alert"],
  },
  gallery: {
    title: "Gallery",
    mobileRoute: "/gallery",
    apiBasePath: "/api/v2/gallery",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["media_storage_before_cloud_sync"],
    safetyHooks: ["private_by_default", "explicit_public_mark_required", "media_report"],
    historyStreams: ["gallery_upload", "gallery_public_toggle", "gallery_share"],
  },
  network_game_center: {
    title: "Game Center",
    mobileRoute: "/network-game-center",
    apiBasePath: "/api/v2/network-game-center",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: false,
    adminReviewRequired: true,
    requiredProviders: ["game_realtime_backend", "coin_wallet_for_rewards"],
    safetyHooks: ["reward_not_income_until_rules", "anti_abuse", "no_simulated_leaderboard"],
    historyStreams: ["game_session", "game_reward", "leaderboard"],
  },
  marketplace: {
    title: "SilkRoad",
    mobileRoute: "/marketplace",
    apiBasePath: "/api/v2/marketplace",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: commerceProviders,
    safetyHooks: commerceHooks,
    historyStreams: ["marketplace_order", "seller_review", "refund"],
  },
  hotels: {
    title: "Hotels",
    mobileRoute: "/hotels",
    apiBasePath: "/api/v2/hotels",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["hotel_catalog_provider", "booking_provider", "wallet_payment_provider"],
    safetyHooks: ["booking_contract_required", "qr_check_in", "refund_review"],
    historyStreams: ["hotel_search", "hotel_booking", "hotel_payment", "hotel_check_in"],
  },
  taxi: {
    title: "Taxi",
    mobileRoute: "/taxi",
    apiBasePath: "/api/v2/taxi",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["maps_geocoding", "driver_runtime", "wallet_payment_provider"],
    safetyHooks: ["complaint_escalation", "serious_violation_hold", "passenger_driver_safety"],
    historyStreams: ["taxi_request", "taxi_trip", "taxi_complaint"],
  },
  supermarket: {
    title: "Supermarket",
    mobileRoute: "/supermarket",
    apiBasePath: "/api/v2/supermarket",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["store_catalog", "delivery_fleet", "wallet_payment_provider"],
    safetyHooks: commerceHooks,
    historyStreams: ["supermarket_order", "delivery_status", "refund"],
  },
  food_delivery: {
    title: "Food Delivery",
    mobileRoute: "/food-delivery",
    apiBasePath: "/api/v2/food-delivery",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["restaurant_catalog", "courier_runtime", "wallet_payment_provider"],
    safetyHooks: ["restaurant_kyb", "courier_safety", "complaint_escalation"],
    historyStreams: ["food_order", "restaurant_status", "delivery_status"],
  },
  wholesale_market: {
    title: "Wholesale Market",
    mobileRoute: "/wholesale-market",
    apiBasePath: "/api/v2/wholesale-market",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["b2b_catalog", "seller_kyb", "logistics_provider", "wallet_payment_provider"],
    safetyHooks: ["b2b_seller_review", "bulk_order_dispute", "kyb_required"],
    historyStreams: ["b2b_offer", "bulk_order", "invoice", "logistics"],
  },
  stream: {
    title: "Stream",
    mobileRoute: "/stream",
    apiBasePath: "/api/v2/stream",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["live_streaming_provider", "moderation_provider", "coin_wallet"],
    safetyHooks: ["stream_18_plus_escalation", "gift_income_monthly_release", "moderation_review"],
    historyStreams: ["stream_session", "gift", "moderation_event"],
  },
  delivery: {
    title: "Delivery",
    mobileRoute: "/delivery",
    apiBasePath: "/api/v2/delivery",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["courier_runtime", "maps_geocoding", "wallet_payment_provider"],
    safetyHooks: ["delivery_complaint_escalation", "serious_violation_hold"],
    historyStreams: ["delivery_request", "delivery_tracking", "complaint"],
  },
  business: {
    title: "Business",
    mobileRoute: "/business",
    apiBasePath: "/api/v2/business",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["premium_gate", "business_kyb", "business_wallet_later"],
    safetyHooks: ["premium_required", "business_routing_layer"],
    historyStreams: ["business_access", "business_invoice", "bot_income_route"],
  },
  merchant: {
    title: "Merchant",
    mobileRoute: "/merchant",
    apiBasePath: "/api/v2/merchant",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["merchant_kyb", "wallet_payment_provider", "business_wallet_later"],
    safetyHooks: ["merchant_payment_review", "business_routing_layer"],
    historyStreams: ["merchant_order", "merchant_qr_payment", "settlement"],
  },
  notifications: {
    title: "Alerts",
    mobileRoute: "/notifications",
    apiBasePath: "/api/v2/notifications",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: ["firebase_push_or_native_push_before_release"],
    safetyHooks: ["missed_calls", "messages", "events", "ai_alerts", "wallet_security", "qr_security"],
    historyStreams: ["notification", "alert", "missed_call", "ai_alert"],
  },
  events: {
    title: "Events",
    mobileRoute: "/events",
    apiBasePath: "/api/v2/events",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: ["calendar_runtime_later"],
    safetyHooks: ["event_reminders", "school_work_attendance_hooks"],
    historyStreams: ["event", "event_reminder"],
  },
  documents: {
    title: "Documents",
    mobileRoute: "/documents",
    apiBasePath: "/api/v2/documents",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["secure_file_storage"],
    safetyHooks: ["file_report", "document_scan_provider_required"],
    historyStreams: ["document_upload", "document_share"],
  },
  wifi_cast: {
    title: "Wi‑Fi Cast",
    mobileRoute: "/wifi-cast",
    apiBasePath: "/api/v2/wifi-cast",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: false,
    aiHooksEnabled: false,
    adminReviewRequired: false,
    requiredProviders: ["native_cast_runtime"],
    safetyHooks: ["local_network_permission_required"],
    historyStreams: ["cast_session"],
  },
};

export function getLocalSabiProgramFoundation(code: SabiHomeProgramCode): SabiProgramFoundation {
  const seed = LOCAL_PROGRAMS[code];

  return {
    code,
    title: seed.title,
    mobileRoute: seed.mobileRoute,
    apiBasePath: seed.apiBasePath,
    runtimeStatus: seed.runtimeStatus,
    providerStatus: seed.providerStatus,
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: seed.paymentsRouteThroughWallet,
    qrEnabled: seed.qrEnabled,
    notificationsEnabled: seed.notificationsEnabled,
    aiHooksEnabled: seed.aiHooksEnabled,
    adminReviewRequired: seed.adminReviewRequired,
    requiredProviders: seed.requiredProviders,
    safetyHooks: seed.safetyHooks,
    historyStreams: seed.historyStreams,
    capabilities: [
      {
        id: `${code}_entry`,
        title: `${seed.title} foundation entry`,
        status: seed.runtimeStatus,
        providerStatus: seed.providerStatus,
        route: seed.mobileRoute,
        apiPath: seed.apiBasePath,
      },
    ],
  };
}

export function buildLocalSabiProgramStatus(code: SabiHomeProgramCode): SabiProgramFoundationStatus {
  return {
    ok: true,
    version: "HOME-100.17-local-foundation",
    generatedAt: new Date().toISOString(),
    program: getLocalSabiProgramFoundation(code),
  };
}

export function isSabiHomeProgramCode(value: string): value is SabiHomeProgramCode {
  return SABI_HOME_PROGRAM_CODES.includes(value as SabiHomeProgramCode);
}

export function resolveSabiProgramCodeFromRoute(route: string): SabiHomeProgramCode | null {
  const normalized = route.trim();
  return (
    SABI_HOME_PROGRAM_CODES.find((code) => getLocalSabiProgramFoundation(code).mobileRoute === normalized) ??
    null
  );
}
