import {
  STREAM_FOUNDATION_141P_MODERATION_POLICY_GATE_VERSION,
  type StreamFoundation141PModerationPolicyGateSnapshot,
  type StreamFoundation141PModerationRule,
} from "./streamFoundationModerationPolicyGateContractPlanningContracts";

const MODERATION_RULES: readonly StreamFoundation141PModerationRule[] = [
  {
    id: "minimum_age_gate",
    status: "admin_review_required",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: false,
    heartbeatGate: false,
    adminReviewRequiredBeforeRuntime: true,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Live start must later check account age policy and streamer eligibility before runtime success.",
  },
  {
    id: "adult_content_gate",
    status: "admin_review_required",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: false,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: true,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "18+ and adult-content classification must be policy-gated before live start or continued live status.",
  },
  {
    id: "profanity_abuse_gate",
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: false,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Profanity, abuse, and repeated harmful-language controls must be bound before runtime live success.",
  },
  {
    id: "hate_harassment_gate",
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: false,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Harassment, hate, and targeted abuse policy checks must exist before runtime live success.",
  },
  {
    id: "report_evidence_gate",
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    liveStartGate: false,
    liveStopGate: true,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Report evidence capture contract must exist before accepting runtime moderation-affecting transitions.",
  },
  {
    id: "streamer_status_gate",
    status: "admin_review_required",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: false,
    heartbeatGate: false,
    adminReviewRequiredBeforeRuntime: true,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Official streamer / allowed-live status must be checked before enabling live runtime success.",
  },
  {
    id: "admin_review_gate",
    status: "admin_review_required",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: true,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: true,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Admin review/hold/disable control must exist before turning blocked live routes into runtime routes.",
  },
  {
    id: "safe_locale_message_gate",
    status: "owner_approval_required",
    requiredBeforeRuntimeMount: true,
    liveStartGate: true,
    liveStopGate: true,
    heartbeatGate: true,
    adminReviewRequiredBeforeRuntime: true,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Runtime errors and policy messages must use safe i18n keys, not mixed hardcoded garbage text.",
  },
];

export function getStreamFoundationModerationPolicyGateContractPlanningSnapshot(): StreamFoundation141PModerationPolicyGateSnapshot {
  return {
    version: STREAM_FOUNDATION_141P_MODERATION_POLICY_GATE_VERSION,
    stage: "moderation_policy_gate_source_only_contract_planning",
    status: "moderation_policy_contract_planned_routes_remain_blocked",
    previousStage: "BACKEND-STREAM-FOUNDATION-141O",
    moderationRules: MODERATION_RULES,
    policySummary: {
      ageGateRequiredBeforeRuntime: true,
      adultContentPolicyRequiredBeforeRuntime: true,
      profanityAndAbuseControlRequiredBeforeRuntime: true,
      reportEvidenceRequiredBeforeRuntime: true,
      adminReviewRequiredBeforeRuntime: true,
      safeI18nMessageKeyRequiredBeforeRuntime: true,
      noDecorativeStarPolicyPreserved: true,
      routesStayBlockedNow: true,
      expectedCurrentStatusCode: 423,
    },
    totals: {
      moderationRules: 8,
      readyForRuntimeMountNow: 0,
      adminReviewRequiredRules: 5,
      runtimeSuccessAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      providerCallAllowedNow: 0,
      walletMutationAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowedNow: 0,
    },
    safety: {
      sourceOnly141P: true,
      appTsChangeBy141P: false,
      serverTsChangeBy141P: false,
      streamIndexChangeBy141P: false,
      backendRestartBy141P: false,
      runtimeHttpBy141P: false,
      runtimePostBy141P: false,
      databaseWriteBy141P: false,
      providerCallBy141P: false,
      walletMutationBy141P: false,
      paymentAuthorizationBy141P: false,
      monthlyPayoutBy141P: false,
      moneyMovementBy141P: false,
      fakeSuccessBy141P: false,
    },
  };
}
