export const sabiAi255BPreparationPackage = {
  version: 'SABI-AI-LEARNING-255B-LOCAL-DRY-RUN-EXECUTION-PREPARATION-PACKAGE-NO-PROVIDER-CALLS',
  readiness: 100,
  mode: 'package_only_no_execution_no_runtime_no_provider_calls',
  localDryRunPreparationPackagePreparedNow: true,
  ownerPreparationApprovalRecordedNow: true,
  ownerControlledPreparationAllowedNow: true,
  ownerExecutionApprovalGrantedNow: false,
  dryRunExecutionPackageReadyNow: false,
  dryRunExecutionPreparedNow: false,
  dryRunExecutionStartedNow: false,
  dryRunExecutionCompletedNow: false,
  runtimeDryRunExecutedNow: false,
  runtimeMountedNow: false,
  runtimeMountAttemptedNow: false,
  noRuntimeMountNow: true,
} as const;

export const sabiAi255BPreparationSafety = {
  rawSecretReadNow: false,
  googleApiCallNow: false,
  googleProviderCallNow: false,
  googleVerifiedDataCallNow: false,
  bigQueryQueryNow: false,
  internetLookupNow: false,
  dbReadNow: false,
  dbWriteNow: false,
  noTrainingIngestionNow: true,
  noPaymentActionNow: true,
  noPayoutActionNow: true,
  noAccountActionNow: true,
  noLegalActionNow: true,
  noProductionLaunchNow: true,
} as const;
