import type {
  TaxiKernelBoundaryReason,
  TaxiKernelBridgeVersion,
  TaxiKernelOperationDescriptor,
} from './taxiKernel.types';

export const TAXI_KERNEL_BRIDGE_VERSION: TaxiKernelBridgeVersion = 'TAXI-BACKEND-FOUNDATION-001B';
export const TAXI_KERNEL_MOBILE_UI_SOURCE_STAGE = 'TAXI-MOBILE-UI-001X' as const;

export const TAXI_KERNEL_BOUNDARY_REASONS: readonly TaxiKernelBoundaryReason[] = [
  'mobile_ui_must_use_kernel_facade',
  'direct_provider_call_blocked',
  'direct_payment_or_payout_blocked',
  'direct_location_runtime_blocked',
  'direct_dispatch_runtime_blocked',
  'direct_wallet_mutation_blocked',
  'backend_runtime_not_mounted',
  'exact_approval_required',
];

export const TAXI_KERNEL_OPERATION_DESCRIPTORS: readonly TaxiKernelOperationDescriptor[] = [
  {
    operation: 'open_taxi_session',
    consumer: 'mobile_ui',
    contractStatus: 'ui_only',
    mapsToCapability: 'kernel_lifecycle',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: false,
    description: 'Opening Taxi in client app may create only local UI state through the kernel facade; no location, socket, dispatch, payment or provider runtime starts.',
  },
  {
    operation: 'close_taxi_session',
    consumer: 'mobile_ui',
    contractStatus: 'ui_only',
    mapsToCapability: 'kernel_lifecycle',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: false,
    description: 'Closing Taxi must release UI subscriptions and must not keep hidden dispatch, geo, payment or provider work alive.',
  },
  {
    operation: 'quote_preview',
    consumer: 'mobile_ui',
    contractStatus: 'safe_disabled',
    mapsToCapability: 'payment_provider',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Mobile can show a fare/quote preview through the kernel contract, but cannot hold, charge, tip, refund or mark payment successful.',
  },
  {
    operation: 'route_preview',
    consumer: 'mobile_ui',
    contractStatus: 'provider_required',
    mapsToCapability: 'route_provider',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Route preview, traffic, radar, speed and ETA must be provider-backed later; UI cannot fake real navigation success.',
  },
  {
    operation: 'traffic_speed_radar_preview',
    consumer: 'mobile_ui',
    contractStatus: 'provider_required',
    mapsToCapability: 'route_provider',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Traffic layers, cameras, radars and speed controls are only preview contracts until provider runtime is approved.',
  },
  {
    operation: 'driver_dispatch_access_preview',
    consumer: 'mobile_ui',
    contractStatus: 'safe_disabled',
    mapsToCapability: 'dispatch_provider',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Driver balance gate can be previewed, but real dispatch offers require backend/provider runtime and exact approval.',
  },
  {
    operation: 'driver_balance_top_up_request',
    consumer: 'mobile_ui',
    contractStatus: 'exact_approval_required',
    mapsToCapability: 'driver_balance_wallet',
    clientPreviewAllowed: false,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Driver balance top-up is locked; client app must not fake top-up or mutate Wallet directly.',
  },
  {
    operation: 'commission_preview',
    consumer: 'mobile_ui',
    contractStatus: 'safe_disabled',
    mapsToCapability: 'commission_debit',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin-configured commission may be previewed, but real debit happens only after verified backend trip completion.',
  },
  {
    operation: 'country_league_snapshot',
    consumer: 'mobile_ui',
    contractStatus: 'admin_review_required',
    mapsToCapability: 'country_league',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Country leagues, top-3 prizes, stars and scores are verified-ledger views only; UI cannot create fake rank or reward.',
  },
  {
    operation: 'daily_complaint_policy_preview',
    consumer: 'mobile_ui',
    contractStatus: 'admin_review_required',
    mapsToCapability: 'sabi_ai_fairness',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Daily complaint penalties are shown as policy preview only; real points/cooldown/block require backend evidence and Admin/Sabi AI review.',
  },
  {
    operation: 'rider_driver_star_review_preview',
    consumer: 'mobile_ui',
    contractStatus: 'safe_disabled',
    mapsToCapability: 'contest_points_ledger',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Driver-to-rider and rider-to-driver stars require verified trip state; UI cannot create fake stars.',
  },
  {
    operation: 'sabi_ai_fairness_signal_preview',
    consumer: 'mobile_ui',
    contractStatus: 'admin_review_required',
    mapsToCapability: 'sabi_ai_fairness',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Sabi AI fairness signals are advisory in UI until backend/Admin review is connected.',
  },
  {
    operation: 'reward_freeze_preview',
    consumer: 'mobile_ui',
    contractStatus: 'admin_review_required',
    mapsToCapability: 'reward_payout',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Prize freeze is a preview state until verified backend evidence, Sabi AI and Admin/legal/payment decision exist.',
  },
  {
    operation: 'appeal_status_preview',
    consumer: 'mobile_ui',
    contractStatus: 'admin_review_required',
    mapsToCapability: 'fairness_appeal',
    clientPreviewAllowed: true,
    clientAppMustUseKernel: true,
    clientMayCallProviderDirectly: false,
    clientMayMutateWalletDirectly: false,
    clientMayExecutePaymentDirectly: false,
    backendRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
    exactApprovalRequiredForRuntime: true,
    description: 'Appeal/explanation state is displayed only; UI cannot clear, block or restore accounts without backend/Admin state.',
  },
];
