export const PLAY_READY_32_CONTROLLED_ADMIN_ROUTE_MOUNT_PLANNING_STAGING_MANIFEST = {
  version: "PLAY-READY-32",
  mode: "controlled_admin_route_mount_planning_source_only",
  sourceOnly: true,
  runtimeRouteMounted: false,
  routeMountedInApp: false,
  actualExpressRouterMounted: false,
  requiresAdminAuth: true,
  methods: ["GET"],
  readOnly: true,
  changedFiles: [
    "src/modules/play-ready/foundation/play-ready-32-controlled-admin-route-mount-planning/index.ts",
    "src/modules/play-ready/foundation/play-ready-32-controlled-admin-route-mount-planning/playReady32ControlledAdminRouteMountPlanning.ts",
    "src/modules/play-ready/foundation/playReady32ControlledAdminRouteMountPlanningStagingManifest.ts",
  ],
  forbiddenNow: [
    "backend restart",
    "runtime route mount",
    "src/app.ts edit",
    "DB write",
    "provider call",
    "Wallet state change",
    "money movement",
    "fake success",
    "Admin UI build",
    "APK/AAB build",
    "Play upload",
  ],
  nextRecommendedStage: "PLAY-READY-33 controlled Admin route mount source patch, still no backend restart until explicit approval",
} as const;
