import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiSchemaCandidateMaterializationApprovalTemplate,
  TaxiSchemaCandidateMaterializationItem,
  TaxiSchemaCandidateMaterializationStage,
  TaxiSchemaCandidateMaterializationVersion,
} from './taxiSchemaCandidateMaterialization.types';

export const TAXI_SCHEMA_CANDIDATE_MATERIALIZATION_VERSION: TaxiSchemaCandidateMaterializationVersion =
  'TAXI-BACKEND-FOUNDATION-001P';

export const TAXI_SCHEMA_CANDIDATE_MATERIALIZATION_STAGES: readonly TaxiSchemaCandidateMaterializationStage[] = [
  'materialization_scope_inventory',
  'candidate_file_shape_review',
  'candidate_write_exact_approval_gate',
  'schema_diff_preview_gate',
  'prisma_schema_write_blocked',
  'prisma_generate_blocked',
  'migration_blocked',
  'db_access_blocked',
  'admin_review_only_ready',
  'client_boundary_contract_unchanged',
];

export const TAXI_SCHEMA_CANDIDATE_MATERIALIZATION_ITEMS: readonly TaxiSchemaCandidateMaterializationItem[] = [
  {
    id: 'taxi-schema-candidate-json',
    title: 'Taxi schema candidate JSON file plan',
    artifactType: 'candidate_json_file',
    targetPath: '.data/taxi/schema/taxi-prisma-schema-candidate.manual.json',
    modelIds: [
      'TaxiRide',
      'TaxiRideRouteSnapshot',
      'TaxiDriverBalanceLedger',
      'TaxiCommissionLedger',
      'TaxiDailyAiReport',
      'TaxiComplaintCase',
      'TaxiEvidenceBundle',
      'TaxiAdminDecision',
      'TaxiAppealExplanation',
      'TaxiCountryLeagueSeason',
      'TaxiLeagueScoreEvent',
      'TaxiRewardFreezeAudit',
    ],
    writeEnabledNow: false,
    exactApprovalRequiredBeforeWrite: true,
    dbAccessEnabledNow: false,
    prismaGenerateEnabledNow: false,
    migrationEnabledNow: false,
    routeRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-prisma-schema-patch-preview',
    title: 'Taxi Prisma schema patch preview plan',
    artifactType: 'prisma_schema_patch_preview',
    targetPath: '.data/taxi/schema/taxi-prisma-schema.patch.preview.prisma',
    modelIds: [
      'TaxiRide',
      'TaxiDriverBalanceLedger',
      'TaxiCommissionLedger',
      'TaxiDailyAiReport',
      'TaxiComplaintCase',
      'TaxiEvidenceBundle',
      'TaxiAdminDecision',
      'TaxiAppealExplanation',
      'TaxiCountryLeagueSeason',
      'TaxiLeagueScoreEvent',
      'TaxiRewardFreezeAudit',
    ],
    writeEnabledNow: false,
    exactApprovalRequiredBeforeWrite: true,
    dbAccessEnabledNow: false,
    prismaGenerateEnabledNow: false,
    migrationEnabledNow: false,
    routeRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-schema-diff-report',
    title: 'Taxi schema diff report plan',
    artifactType: 'schema_diff_report',
    targetPath: '.data/taxi/schema/taxi-prisma-schema-diff-review.json',
    modelIds: ['TaxiRide', 'TaxiDailyAiReport', 'TaxiComplaintCase', 'TaxiEvidenceBundle', 'TaxiAdminDecision'],
    writeEnabledNow: false,
    exactApprovalRequiredBeforeWrite: true,
    dbAccessEnabledNow: false,
    prismaGenerateEnabledNow: false,
    migrationEnabledNow: false,
    routeRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-migration-rollback-plan',
    title: 'Taxi migration rollback plan',
    artifactType: 'migration_rollback_plan',
    targetPath: '.data/taxi/schema/taxi-migration-rollback-plan.md',
    modelIds: ['TaxiRide', 'TaxiDailyAiReport', 'TaxiComplaintCase', 'TaxiAdminDecision'],
    writeEnabledNow: false,
    exactApprovalRequiredBeforeWrite: true,
    dbAccessEnabledNow: false,
    prismaGenerateEnabledNow: false,
    migrationEnabledNow: false,
    routeRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-client-boundary-summary-contract',
    title: 'Taxi client kernel boundary summary contract',
    artifactType: 'client_boundary_summary_contract',
    targetPath: 'src/modules/taxi/client-boundary',
    modelIds: ['TaxiRide', 'TaxiComplaintCase', 'TaxiAdminDecision', 'TaxiCountryLeagueSeason'],
    writeEnabledNow: false,
    exactApprovalRequiredBeforeWrite: true,
    dbAccessEnabledNow: false,
    prismaGenerateEnabledNow: false,
    migrationEnabledNow: false,
    routeRuntimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_SCHEMA_CANDIDATE_MATERIALIZATION_APPROVAL_TEMPLATE: TaxiSchemaCandidateMaterializationApprovalTemplate = {
  approvalId: 'taxi_schema_candidate_materialization_exact_approval',
  ownerMustApprove: true,
  allowsCandidateFileWriteNow: false,
  allowsPrismaSchemaWriteNow: false,
  allowsPrismaGenerateNow: false,
  allowsMigrationNow: false,
  allowsDbReadNow: false,
  allowsDbWriteNow: false,
  requiredOwnerStatement:
    'I approve TAXI-BACKEND-FOUNDATION schema candidate materialization only for the explicitly listed candidate artifacts; no Prisma schema write, no generate, no migrate, no DB read/write, no runtime route mount, no Wallet/payment/payout/provider activation.',
  forbiddenWithoutApproval: [
    'candidate_file_write',
    'prisma_schema_write',
    'prisma_generate',
    'prisma_migration',
    'db_read',
    'db_write',
    'runtime_route_mount',
    'scheduler_start',
    'wallet_mutation',
    'payment_charge',
    'payout_release',
    'provider_dispatch_call',
  ],
};

export const taxiSchemaCandidateMaterializationRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/admin/taxi/schema-candidate-materialization/snapshot',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future Admin read route for Taxi schema candidate materialization plan; not mounted and no DB access now.',
  },
  {
    method: 'POST',
    path: '/api/admin/taxi/schema-candidate-materialization/approve-candidate-write',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future exact owner approval route for candidate artifact write; safe-disabled in this foundation patch.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/schema-candidate-materialization/diff-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future schema diff preview route; no Prisma schema write, generate, migrate or DB access now.',
  },
];
