export const STREAM_109Z_SHORT_VIDEO_COVER_CAPTIONS_REVIEW_PLAN = {
  stage: "109Z",
  title: "Short video cover/captions/review depth",
  scope: "stream_mobile_only",
  touchedAreas: ["Stream", "Short video", "Cover", "Captions", "Review evidence"],
  forbiddenAreas: ["Wallet", "Messenger", "Calls", "server", "foundation", "backend finance", "payments", "gifts", "monetization"],
  addedRuntime: "streamShortVideoCoverCaptionReviewRuntime",
  localActions: [
    "select review item",
    "prepare selected review item",
    "review selected item locally",
    "review cover frame locally",
    "review caption track locally",
    "review caption language locally",
    "review content policy locally",
    "review media locally",
    "review publish handoff locally",
    "queue local review event",
    "request provider handoff blocked",
  ],
  providerBlockers: [
    "media_storage_provider_required",
    "cdn_provider_required",
    "backend_shorts_review_contract_required",
    "admin_shorts_review_required",
  ],
  fakeBlocked: {
    fakeCoverGeneratedAllowed: false,
    fakeCaptionGeneratedAllowed: false,
    fakeReviewPassAllowed: false,
    fakePublishAllowed: false,
    fakePaymentAllowed: false,
    fakeGiftAllowed: false,
  },
  nextStep: "110A short video publish-readiness local gate, still without payments/gifts/Wallet/server",
} as const;
