export const stream111eShortsInAppCameraPremiumUiPlan = {
  version: "111E",
  title: "Shorts Sabi in-app camera premium UI polish",
  scope: "mobile_stream_shorts_only",
  changedFiles: [
    "src/modules/stream/mobile/StreamShortVideoDraftPanel.tsx",
    "src/modules/stream/admin/stream111eShortsInAppCameraPremiumUiPlan.ts",
    "src/modules/stream/index.ts",
  ],
  guarantees: {
    systemCameraLaunchRemoved: true,
    sabiInAppCameraKept: true,
    premiumCameraOverlayAdded: true,
    gridToggleLocal: true,
    torchToggleLocal: true,
    zoomControlsLocal: true,
    clipDurationSelectorLocal: [15, 30, 60],
    recordingTimerLocal: true,
    recordingProgressLocal: true,
    savedRecordingStillBoundToShortsSourceFlow: true,
    fakeUpload: false,
    fakePublish: false,
    fakeProviderSuccess: false,
    backendTouched: false,
    walletTouched: false,
    messengerTouched: false,
    callsTouched: false,
  },
} as const;
