export const stream110yShortVideoSettingsActionsPolishPlan = {
  stage: "110Y",
  title: "Shorts Settings actions polish",
  scope: "mobile_stream_shorts_only",
  status: "ready",
  mainScreen: {
    cleanViewer: true,
    rightRail: ["Settings", "Like", "Comments", "Share", "Save"],
    editorToolsOutsideSettings: false,
    trashCardsRemoved: true,
  },
  settingsActions: {
    productionLabels: true,
    devLikeLabelsRemovedFromDefaultFlow: true,
    advancedToolsCollapsedByDefault: true,
    orderedFlow: ["Video", "Edit", "Text", "Overlays", "Effects", "MP3", "Review"],
    clearPrimaryActions: {
      video: ["record_video", "upload_from_gallery", "choose_video_file"],
      edit: ["save_to_timeline", "set_cover_review", "check_edit"],
      text: ["add_title_caption", "save_text", "review_text"],
      overlays: ["add_useful_mark", "save_overlay", "review_overlay"],
      effects: ["apply_effect", "sync_stack", "render_locked"],
      mp3: ["choose_mp3", "check_mix", "mute_original"],
      review: ["check_draft", "check_timeline", "publish_locked"],
    },
  },
  safety: {
    fakeRenderSuccess: false,
    fakeUploadSuccess: false,
    fakePublishSuccess: false,
    fakeProviderSuccess: false,
    walletTouched: false,
    messengerTouched: false,
    callsTouched: false,
    backendTouched: false,
    paymentsTouched: false,
    giftsTouched: false,
    monetizationTouched: false,
  },
} as const;
