export const STREAM_110P_SHORT_VIDEO_TRIM_CROP_COVER_FRAME_PLAN = {
  id: "STREAM-110P",
  title: "Shorts trim/crop/cover-frame local binding",
  scope: "mobile_stream_shorts_only",
  status: "local_editor_binding_ready",
  changedRuntime: [
    "streamShortVideoTrimCropCoverFrameRuntime",
    "StreamShortVideoDraftPanel trim/crop/cover controls",
    "timeline trim + cover binding",
    "cover review binding",
  ],
  localActions: [
    "bind selected record/upload source to editor metadata",
    "nudge trim start/end locally",
    "cycle crop preset locally",
    "nudge crop focal point locally",
    "cycle crop zoom locally",
    "nudge cover frame locally",
    "bind trim/crop/cover to timeline state",
    "bind cover frame to review state",
    "queue local editor event",
  ],
  blockedUntilProviderIntegration: [
    "real render/export pipeline",
    "media storage provider",
    "CDN/playback manifest provider",
    "backend editor contract",
    "Admin media review approval",
    "publish handoff",
  ],
  safety: {
    walletTouched: false,
    messengerTouched: false,
    callsTouched: false,
    backendTouched: false,
    paymentsTouched: false,
    giftsTouched: false,
    monetizationTouched: false,
    fakeTrimAllowed: false,
    fakeCropAllowed: false,
    fakeCoverGeneratedAllowed: false,
    fakeRenderAllowed: false,
    fakeUploadAllowed: false,
    fakePublishAllowed: false,
  },
} as const;
