import type {
  SabiAiStreamSafetyLocks252G,
  SabiAiStreamTrainingQueue252G,
  SabiAiStreamTrainingSeed252G,
} from './sabiAiStreamTrainingSeeds252G.types';

export const sabiAiStreamTrainingSeeds252G: readonly SabiAiStreamTrainingSeed252G[] = [
  {
    seedId: '252g-ru-love-nature-values-001',
    languageCode: 'ru',
    cultureContext: 'respectful_ru_speaking_general_audience',
    theme: 'love_nature_human_values',
    titleIdea: 'Тихий свет природы',
    messageGoal: 'love_respect_nature_and_kindness',
    songMoodPlan: 'calm_warm_inspiring',
    clipVisualPlan: 'original dawn, river, family-safe nature scenes, soft educational text',
    scriptStructurePlan: 'intro_nature_middle_values_climax_kindness_outro_reflection',
    youthSafetyNotes: 'encourage real friendship, respect, family-safe communication',
    originalityDeclaration: 'original_seed_only_no_copy',
    ownerReviewStatus: 'pending',
    futureUseAllowedNow: false,
  },
  {
    seedId: '252g-en-learning-respect-002',
    languageCode: 'en',
    cultureContext: 'global_youth_safe_respectful_tone',
    theme: 'learning_respect_real_human_communication',
    titleIdea: 'Talk to the World Kindly',
    messageGoal: 'learning_respect_and_real_conversation',
    songMoodPlan: 'positive_light_educational',
    clipVisualPlan: 'original animated notebooks, city lights, friendly dialogue scenes',
    scriptStructurePlan: 'intro_question_middle_learning_climax_respect_outro_real_world',
    youthSafetyNotes: 'discourage isolation, encourage safe respectful real communication',
    originalityDeclaration: 'original_seed_only_no_copy',
    ownerReviewStatus: 'pending',
    futureUseAllowedNow: false,
  },
  {
    seedId: '252g-uz-homeland-kindness-003',
    languageCode: 'uz',
    cultureContext: 'uzbek_respect_family_kindness_culture',
    theme: 'homeland_kindness_family_values',
    titleIdea: 'Mehr va Vatan nuri',
    messageGoal: 'respect_homeland_family_and_kindness',
    songMoodPlan: 'warm_respectful_inspiring',
    clipVisualPlan: 'original peaceful streets, nature, family-safe celebration, respectful culture symbols',
    scriptStructurePlan: 'intro_homeland_middle_kindness_climax_unity_outro_learning',
    youthSafetyNotes: 'respect elders, study, real friendship, no manipulation',
    originalityDeclaration: 'original_seed_only_no_copy',
    ownerReviewStatus: 'pending',
    futureUseAllowedNow: false,
  },
] as const;

export const sabiAiStreamTrainingQueue252G: SabiAiStreamTrainingQueue252G = {
  queueStates: [
    'seed_created',
    'language_culture_check_pending',
    'theme_safety_check_pending',
    'owner_review_pending',
    'approved_for_future_draft_expansion',
    'needs_revision',
    'rejected',
    'red_priority_hold',
  ],
} as const;

export const sabiAiStreamSafetyLocks252G: SabiAiStreamSafetyLocks252G = {
  localCodeArtifactOnly: true,
  noLiveBroadcastNow: true,
  noRuntimeMountNow: true,
  noAdminRouteConnectionNow: true,
  noRuntimeGenerationNow: true,
  noRuntimePostNow: true,
  noProviderCallNow: true,
  noProtectedConfigReadWriteNow: true,
  noDbMutationNow: true,
  noPaymentNow: true,
  noRestrictedLiveActionNow: true,
  finalActionsExecutedNow: false,
  ownerApprovalRequiredForFutureDraftExpansion: true,
  ownerApprovalRequiredForPublicPost: true,
  ownerApprovalRequiredForLiveBroadcast: true,
} as const;
