import type { SabiRelease251AReport } from './sabiRelease251A.types';

export const sabiRelease251AReport: SabiRelease251AReport = {
  "version": "SABI-RELEASE-251A-SERVER-OWNER-SABI-AI-FOUNDATION-PREFLIGHT",
  "status": "passed",
  "createdAt": "2026-06-23T17:28:17.231Z",
  "company": {
    "name": "SABI AI TECHNOLOGIES LIMITED",
    "officialDomain": "sabiai.app"
  },
  "projects": {
    "officialSiteProjectId": "sabi-official-prod",
    "firebaseProjectId": "sabi-official-prod-37629"
  },
  "sourceReports": {
    "bankProof249C": ".data/release/249c/249c-report.json",
    "emailProof249B": ".data/release/249b/249b-report.json",
    "emailDnsRecheck9": ".data/release/249a-fix4-recheck9/249a-fix4-recheck9-report.json"
  },
  "prerequisites": {
    "bankProofReady": true,
    "officialSiteReady": true,
    "officialEmailReady": true,
    "infoPublicContactPaused": true,
    "infoPublicContactReason": "info@sabiai.app is not yet a valid mailbox/alias/group; do not publish it on site yet."
  },
  "expectedPaths": {
    "srcExists": true,
    "packageJsonExists": true,
    "tsconfigExists": true,
    "prismaDirExists": true,
    "modulesDirExists": true,
    "releaseDirExists": true
  },
  "scans": {
    "srcModules": {
      "exists": true,
      "files": [
        "src/modules/index.ts",
        "src/modules/taxi/README-HANDOFF.md",
        "src/modules/taxi/foundation/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-approval-request-040j/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-approval-request-040j/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-approval-request-040j/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-approval-request-040j/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-approval-request-040j/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-approval-request-040k/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-approval-request-040k/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-approval-request-040k/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-approval-request-040k/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-approval-request-040k/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-locked-gate-040m/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-locked-gate-040m/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-locked-gate-040m/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-locked-gate-040m/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-evidence-locked-gate-040m/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-closeout-040r/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-closeout-040r/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-closeout-040r/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-closeout-040r/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-closeout-040r/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-locked-gate-040o/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-locked-gate-040o/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-locked-gate-040o/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-locked-gate-040o/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-locked-gate-040o/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-owner-approval-locked-040q/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-owner-approval-locked-040q/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-owner-approval-locked-040q/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-owner-approval-locked-040q/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-evidence-owner-approval-locked-040q/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-locked-gate-040n/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-locked-gate-040n/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-locked-gate-040n/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-locked-gate-040n/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-locked-gate-040n/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-owner-approval-locked-040p/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-owner-approval-locked-040p/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-owner-approval-locked-040p/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-owner-approval-locked-040p/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-final-owner-approval-locked-040p/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-locked-gate-040l/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-locked-gate-040l/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-locked-gate-040l/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-locked-gate-040l/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-execution-locked-gate-040l/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-evidence-locked-gate-040i/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-evidence-locked-gate-040i/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-evidence-locked-gate-040i/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-evidence-locked-gate-040i/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-evidence-locked-gate-040i/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-locked-gate-040h/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-locked-gate-040h/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-locked-gate-040h/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-locked-gate-040h/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-final-locked-gate-040h/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-locked-gate-040g/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-locked-gate-040g/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-locked-gate-040g/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-locked-gate-040g/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-locked-gate-040g/types.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-owner-filled-reference-intake-040s/constants.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-owner-filled-reference-intake-040s/index.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-owner-filled-reference-intake-040s/routes.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-owner-filled-reference-intake-040s/service.ts",
        "src/modules/taxi/foundation/provider-secret-value-access-owner-filled-reference-intake-040s/types.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-approval-planning-003c/constants.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-approval-planning-003c/index.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-approval-planning-003c/service.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-approval-planning-003c/types.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-finalization-admin-readiness-handoff-003f/constants.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-finalization-admin-readiness-handoff-003f/index.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-finalization-admin-readiness-handoff-003f/service.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-finalization-admin-readiness-handoff-003f/types.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-patch-003d/constants.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-patch-003d/index.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-patch-003d/routes.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-patch-003d/service.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-patch-003d/types.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-smoke-003e/constants.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-smoke-003e/index.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-smoke-003e/service.ts",
        "src/modules/taxi/foundation/provider-wallet-boundary-route-smoke-003e/types.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-002t/constants.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-002t/index.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-002t/routes.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-002t/service.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-002t/types.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-smoke-002u/constants.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-smoke-002u/index.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-smoke-002u/service.ts",
        "src/modules/taxi/foundation/read-only-db-runtime-dry-run-smoke-002u/types.ts",
        "src/modules/taxi/foundation/real-money-movement-approval-request-039n/constants.ts",
        "src/modules/taxi/foundation/real-money-movement-approval-request-039n/index.ts",
        "src/modules/taxi/foundation/real-money-movement-approval-request-039n/routes.ts",
        "src/modules/taxi/foundation/real-money-movement-approval-request-039n/service.ts",
        "src/modules/taxi/foundation/real-money-movement-approval-request-039n/types.ts",
        "src/modules/taxi/foundation/real-money-movement-execution-approval-evidence-039o/constants.ts",
        "src/modules/taxi/foundation/real-money-movement-execution-approval-evidence-039o/index.ts",
        "src/modules/taxi/foundation/real-money-movement-execution-approval-evidence-039o/routes.ts",
        "src/modules/taxi/foundation/real-money-movement-execution-approval-evidence-039o/service.ts",
        "src/modules/taxi/foundation/real-money-movement-execution-approval-evidence-039o/types.ts",
        "src/modules/taxi/foundation/real-wallet-execution-locked-gate-039m/constants.ts",
        "src/modules/taxi/foundation/real-wallet-execution-locked-gate-039m/index.ts",
        "src/modules/taxi/foundation/real-wallet-execution-locked-gate-039m/routes.ts",
        "src/modules/taxi/foundation/real-wallet-execution-locked-gate-039m/service.ts",
        "src/modules/taxi/foundation/real-wallet-execution-locked-gate-039m/types.ts",
        "src/modules/taxi/foundation/real-wallet-execution-preflight-039l/constants.ts",
        "src/modules/taxi/foundation/real-wallet-execution-preflight-039l/index.ts",
        "src/modules/taxi/foundation/real-wallet-execution-preflight-039l/routes.ts",
        "src/modules/taxi/foundation/real-wallet-execution-preflight-039l/service.ts",
        "src/modules/taxi/foundation/real-wallet-execution-preflight-039l/types.ts",
        "src/modules/taxi/foundation/repository-service-contracts-002j/constants.ts",
        "src/modules/taxi/foundation/repository-service-contracts-002j/index.ts",
        "src/modules/taxi/foundation/repository-service-contracts-002j/service.ts",
        "src/modules/taxi/foundation/repository-service-contracts-002j/types.ts",
        "src/modules/taxi/foundation/route-controller-implementation-002l/constants.ts",
        "src/modules/taxi/foundation/route-controller-implementation-002l/index.ts",
        "src/modules/taxi/foundation/route-controller-implementation-002l/service.ts",
        "src/modules/taxi/foundation/route-controller-implementation-002l/types.ts",
        "src/modules/taxi/foundation/route-mount-approval-002m/constants.ts",
        "src/modules/taxi/foundation/route-mount-approval-002m/index.ts",
        "src/modules/taxi/foundation/route-mount-approval-002m/service.ts",
        "src/modules/taxi/foundation/route-mount-approval-002m/types.ts",
        "src/modules/taxi/foundation/route-mount-runtime-002n.routes.tmp",
        "src/modules/taxi/foundation/route-mount-runtime-002n/constants.ts",
        "src/modules/taxi/foundation/route-mount-runtime-002n/index.ts",
        "src/modules/taxi/foundation/route-mount-runtime-002n/routes.ts",
        "src/modules/taxi/foundation/route-mount-runtime-002n/service.ts",
        "src/modules/taxi/foundation/route-mount-runtime-002n/types.ts",
        "src/modules/taxi/foundation/runtime-api-contracts-001v/constants.ts",
        "src/modules/taxi/foundation/runtime-api-contracts-001v/index.ts",
        "src/modules/taxi/foundation/runtime-api-contracts-001v/service.ts",
        "src/modules/taxi/foundation/runtime-api-contracts-001v/types.ts",
        "src/modules/taxi/foundation/runtime-hardening-protected-routes-002p/constants.ts",
        "src/modules/taxi/foundation/runtime-hardening-protected-routes-002p/index.ts",
        "src/modules/taxi/foundation/runtime-hardening-protected-routes-002p/service.ts",
        "src/modules/taxi/foundation/runtime-hardening-protected-routes-002p/types.ts",
        "src/modules/taxi/foundation/runtime-route-drafts-001y/constants.ts",
        "src/modules/taxi/foundation/runtime-route-drafts-001y/index.ts",
        "src/modules/taxi/foundation/runtime-route-drafts-001y/service.ts",
        "src/modules/taxi/foundation/runtime-route-drafts-001y/types.ts",
        "src/modules/taxi/foundation/runtime-service-implementation-002k/constants.ts",
        "src/modules/taxi/foundation/runtime-service-implementation-002k/index.ts",
        "src/modules/taxi/foundation/runtime-service-implementation-002k/service.ts",
        "src/modules/taxi/foundation/runtime-service-implementation-002k/types.ts",
        "src/modules/taxi/foundation/schema-append-approval-002a/constants.ts",
        "src/modules/taxi/foundation/schema-append-approval-002a/index.ts",
        "src/modules/taxi/foundation/schema-append-approval-002a/service.ts",
        "src/modules/taxi/foundation/schema-append-approval-002a/types.ts",
        "src/modules/taxi/foundation/schema-apply-candidate-001z/constants.ts",
        "src/modules/taxi/foundation/schema-apply-candidate-001z/index.ts",
        "src/modules/taxi/foundation/schema-apply-candidate-001z/service.ts",
        "src/modules/taxi/foundation/schema-apply-candidate-001z/types.ts",
        "src/modules/taxi/foundation/schema-planning-001w/constants.ts",
        "src/modules/taxi/foundation/schema-planning-001w/index.ts",
        "src/modules/taxi/foundation/schema-planning-001w/service.ts",
        "src/modules/taxi/foundation/schema-planning-001w/types.ts",
        "src/modules/taxi/foundation/schema-real-append-002b/constants.ts",
        "src/modules/taxi/foundation/schema-real-append-002b/index.ts",
        "src/modules/taxi/foundation/schema-real-append-002b/service.ts",
        "src/modules/taxi/foundation/schema-real-append-002b/types.ts",
        "src/modules/taxi/foundation/service-activation-approval-002r/constants.ts",
        "src/modules/taxi/foundation/service-activation-approval-002r/index.ts",
        "src/modules/taxi/foundation/service-activation-approval-002r/service.ts",
        "src/modules/taxi/foundation/service-activation-approval-002r/types.ts",
        "src/modules/taxi/foundation/taxiFoundation.constants.ts",
        "src/modules/taxi/foundation/taxiFoundation.routes.ts",
        "src/modules/taxi/foundation/taxiFoundation.service.ts",
        "src/modules/taxi/foundation/taxiFoundation.types.ts",
        "src/modules/taxi/foundation/trip-lifecycle-control-001t/constants.ts",
        "src/modules/taxi/foundation/trip-lifecycle-control-001t/index.ts",
        "src/modules/taxi/foundation/trip-lifecycle-control-001t/service.ts",
        "src/modules/taxi/foundation/trip-lifecycle-control-001t/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-execution-preflight-035l/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-execution-preflight-035l/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-execution-preflight-035l/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-execution-preflight-035l/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-execution-preflight-035l/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-final-handoff-035d/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-final-handoff-035d/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-final-handoff-035d/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-final-handoff-035d/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-final-handoff-035d/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-planning-035a/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-planning-035a/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-planning-035a/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-planning-035a/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-chain-planning-035a/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-decision-gate-035j/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-decision-gate-035j/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-decision-gate-035j/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-decision-gate-035j/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-decision-gate-035j/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-execution-runtime-gate-035t/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-execution-runtime-gate-035t/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-execution-runtime-gate-035t/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-execution-runtime-gate-035t/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-execution-runtime-gate-035t/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-final-lock-selection-035v/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-final-lock-selection-035v/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-final-lock-selection-035v/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-final-lock-selection-035v/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-final-lock-selection-035v/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-mega-handoff-035q-035s/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-mega-handoff-035q-035s/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-mega-handoff-035q-035s/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-mega-handoff-035q-035s/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-approval-mega-handoff-035q-035s/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-intake-035p/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-intake-035p/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-intake-035p/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-intake-035p/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-intake-035p/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-package-035g/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-package-035g/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-package-035g/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-package-035g/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-exact-approval-package-035g/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-execution-layer-split-035n/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-execution-layer-split-035n/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-execution-layer-split-035n/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-execution-layer-split-035n/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-owner-execution-layer-split-035n/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-global-scale-safe-read-contract-036g/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-global-scale-safe-read-contract-036g/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-global-scale-safe-read-contract-036g/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-global-scale-safe-read-contract-036g/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-global-scale-safe-read-contract-036g/types.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-sabi-ai-persona-runtime-report-036i/constants.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-sabi-ai-persona-runtime-report-036i/index.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-sabi-ai-persona-runtime-report-036i/routes.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-sabi-ai-persona-runtime-report-036i/service.ts",
        "src/modules/taxi/foundation/wallet-payment-payout-trip-sabi-ai-persona-runtime-report-036i/types.ts",
        "src/modules/taxi/index.ts",
        "src/modules/taxi/kernel/index.ts",
        "src/modules/taxi/kernel/taxiKernel.constants.ts",
        "src/modules/taxi/kernel/taxiKernel.routes.ts",
        "src/modules/taxi/kernel/taxiKernel.service.ts",
        "src/modules/taxi/kernel/taxiKernel.types.ts",
        "src/modules/taxi/next-phase-handoff/index.ts",
        "src/modules/taxi/next-phase-handoff/taxiNextPhaseHandoff.constants.ts",
        "src/modules/taxi/next-phase-handoff/taxiNextPhaseHandoff.routes.ts",
        "src/modules/taxi/next-phase-handoff/taxiNextPhaseHandoff.service.ts",
        "src/modules/taxi/next-phase-handoff/taxiNextPhaseHandoff.types.ts",
        "src/modules/taxi/prisma-schema-candidate/index.ts",
        "src/modules/taxi/prisma-schema-candidate/taxiPrismaSchemaCandidate.constants.ts",
        "src/modules/taxi/prisma-schema-candidate/taxiPrismaSchemaCandidate.routes.ts",
        "src/modules/taxi/prisma-schema-candidate/taxiPrismaSchemaCandidate.service.ts",
        "src/modules/taxi/prisma-schema-candidate/taxiPrismaSchemaCandidate.types.ts",
        "src/modules/taxi/schema-candidate-materialization/index.ts",
        "src/modules/taxi/schema-candidate-materialization/taxiSchemaCandidateMaterialization.constants.ts",
        "src/modules/taxi/schema-candidate-materialization/taxiSchemaCandidateMaterialization.routes.ts",
        "src/modules/taxi/schema-candidate-materialization/taxiSchemaCandidateMaterialization.service.ts",
        "src/modules/taxi/schema-candidate-materialization/taxiSchemaCandidateMaterialization.types.ts",
        "src/modules/transaction/a",
        "src/modules/transaction/application/a",
        "src/modules/transaction/application/services/transaction-engine.ts",
        "src/modules/transaction/application/use-cases/marketplace-payment.usecase.ts",
        "src/modules/transaction/application/use-cases/p2p-transfer.usecase.ts",
        "src/modules/transaction/application/use-cases/qr-payment.usecase.ts",
        "src/modules/transaction/application/use-cases/subscription-payment.usecase.ts",
        "src/modules/transaction/domain/a",
        "src/modules/transaction/domain/entities/transaction.ts",
        "src/modules/transaction/domain/enums/transaction-type.ts",
        "src/modules/transaction/domain/value-objects/money.ts",
        "src/modules/transaction/infrastructure/transaction.repository.ts",
        "src/modules/transaction/presentation/transaction.controller.ts",
        "src/modules/user/application/create-user.usecase.ts",
        "src/modules/user/application/get-user.usecase.ts",
        "src/modules/user/application/public-profile-surface.service.ts",
        "src/modules/user/application/update-user-profile.usecase.ts",
        "src/modules/user/application/user.service.ts",
        "src/modules/user/domain/user.entity.ts",
        "src/modules/user/domain/user.repository.ts",
        "src/modules/user/index.ts",
        "src/modules/user/infrastructure/contracts/user-profile.provision.adapter.ts",
        "src/modules/user/infrastructure/persistence/prisma-user.repository.ts",
        "src/modules/user/presentation/user.controller.ts",
        "src/modules/user/presentation/user.routes.ts",
        "src/modules/user/user.module.ts",
        "src/modules/user/user.schema.ts",
        "src/modules/wallet/README.md",
        "src/modules/wallet/application/balance/balance.service.ts",
        "src/modules/wallet/application/dto/create-wallet.dto.ts",
        "src/modules/wallet/application/dto/deposit.dto.ts",
        "src/modules/wallet/application/dto/get-transactions.dto.ts",
        "src/modules/wallet/application/dto/transfer.dto.ts",
        "src/modules/wallet/application/dto/withdraw.dto.ts",
        "src/modules/wallet/application/escrow/escrow.service.ts",
        "src/modules/wallet/application/factories/create-wallet-core-module.ts",
        "src/modules/wallet/application/factories/create-wallet-runtime.service.ts",
        "src/modules/wallet/application/factories/wallet-module.singleton.ts",
        "src/modules/wallet/application/factories/wallet-runtime.singleton.ts",
        "src/modules/wallet/application/fraud/fraud-detection.service.ts",
        "src/modules/wallet/application/handlers/money-deposited.handler.ts",
        "src/modules/wallet/application/handlers/wallet-event.handler.ts",
        "src/modules/wallet/application/history/transaction-history.service.ts",
        "src/modules/wallet/application/idempotency/idempotency.service.ts",
        "src/modules/wallet/application/ledger.service.ts",
        "src/modules/wallet/application/ledger/ledger.service.ts",
        "src/modules/wallet/application/merchant/merchant.service.ts",
        "src/modules/wallet/application/payment/payment.orchestrator.ts",
        "src/modules/wallet/application/ports/event-bus.port.ts",
        "src/modules/wallet/application/ports/logger.port.ts",
        "src/modules/wallet/application/provider/adapters/alipay-plus-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/aml-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/business-payout-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/card-tokenization-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/coin-wallet-ledger-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/crypto-custody-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/crypto-market-data-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/kyc-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/local-bank-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/merchant-acquiring-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/virtual-card-issuer-execution.adapter.ts",
        "src/modules/wallet/application/provider/adapters/wallet-provider-adapter.registry.ts",
        "src/modules/wallet/application/provider/adapters/wallet-provider-adapter.types.ts",
        "src/modules/wallet/application/provider/compliance/kyc-aml-provider-binding.contract.ts",
        "src/modules/wallet/application/provider/wallet-final-launch-audit.service.ts",
        "src/modules/wallet/application/provider/wallet-provider-config.service.ts",
        "src/modules/wallet/application/provider/wallet-provider-execution.guard.ts",
        "src/modules/wallet/application/provider/wallet-provider-launch-checklist.service.ts",
        "src/modules/wallet/application/qr-payment.service.ts",
        "src/modules/wallet/application/qr.service.ts",
        "src/modules/wallet/application/qr/qr-payment.service.ts",
        "src/modules/wallet/application/rate-limit/rate-limiter.service.ts",
        "src/modules/wallet/application/refund/refund.service.ts",
        "src/modules/wallet/application/security/anti-double-spend.service.ts",
        "src/modules/wallet/application/security/atomic-transaction.service.ts",
        "src/modules/wallet/application/security/balance-verification.service.ts",
        "src/modules/wallet/application/security/ledger.service.ts",
        "src/modules/wallet/application/security/nonce.service.ts",
        "src/modules/wallet/application/security/transfer-limiter.service.ts",
        "src/modules/wallet/application/security/wallet-ai-risk-guard.service.ts",
        "src/modules/wallet/application/security/wallet-lock.service.ts",
        "src/modules/wallet/application/security/wallet-provider-domain.policy.ts",
        "src/modules/wallet/application/security/wallet-provider-persistence.policy.ts",
        "src/modules/wallet/application/security/wallet-security-compliance.service.ts",
        "src/modules/wallet/application/security/wallet-security-runtime-guard.service.ts",
        "src/modules/wallet/application/services/financial-item-details.service.ts",
        "src/modules/wallet/application/services/financial-overview.service.ts",
        "src/modules/wallet/application/services/fraud.service.ts",
        "src/modules/wallet/application/services/ledger.service.ts",
        "src/modules/wallet/application/services/qr-generator.service.ts",
        "src/modules/wallet/application/services/qr-payment.service.ts",
        "src/modules/wallet/application/services/transaction-engine.service.ts",
        "src/modules/wallet/application/services/transaction-router.service.ts",
        "src/modules/wallet/application/services/unified-transaction-history.service.ts",
        "src/modules/wallet/application/services/wallet-core-facade.service.ts",
        "src/modules/wallet/application/services/wallet-query.service.ts",
        "src/modules/wallet/application/services/wallet-runtime.service.ts",
        "src/modules/wallet/application/services/wallet-transfer.service.ts",
        "src/modules/wallet/application/transaction/transaction-engine.ts",
        "src/modules/wallet/application/use-cases/accrue-coin-deposit-interest.use-case.ts",
        "src/modules/wallet/application/use-cases/calculate-business-transfer-preview.use-case.ts",
        "src/modules/wallet/application/use-cases/calculate-merchant-payment-preview.use-case.ts",
        "src/modules/wallet/application/use-cases/calculate-merchant-settlement-preview.use-case.ts",
        "src/modules/wallet/application/use-cases/calculate-service-fee.use-case.ts",
        "src/modules/wallet/application/use-cases/create-business-wallet.use-case.ts",
        "src/modules/wallet/application/use-cases/create-merchant-wallet.use-case.ts",
        "src/modules/wallet/application/use-cases/create-qr.use-case.ts",
        "src/modules/wallet/application/use-cases/create-wallet.use-case.ts",
        "src/modules/wallet/application/use-cases/deposit.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-business-transfer-and-save.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-business-transfer.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-merchant-payment-and-save.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-merchant-payment.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-merchant-settlement-and-save.use-case.ts",
        "src/modules/wallet/application/use-cases/execute-merchant-settlement.use-case.ts",
        "src/modules/wallet/application/use-cases/get-balance.use-case.ts",
        "src/modules/wallet/application/use-cases/get-coin-wallet.use-case.ts",
        "src/modules/wallet/application/use-cases/get-crypto-wallet.use-case.ts",
        "src/modules/wallet/application/use-cases/get-wallet-hub.use-case.ts",
        "src/modules/wallet/application/use-cases/index.ts",
        "src/modules/wallet/application/use-cases/list-card-accounts.use-case.ts",
        "src/modules/wallet/application/use-cases/open-coin-deposit.use-case.ts",
        "src/modules/wallet/application/use-cases/pay-qr.use-case.ts",
        "src/modules/wallet/application/use-cases/request-coin-credit.use-case.ts",
        "src/modules/wallet/application/use-cases/transfer.use-case.ts",
        "src/modules/wallet/application/use-cases/withdraw.use-case.ts",
        "src/modules/wallet/application/wallet.service.ts",
        "src/modules/wallet/cards/virtual-card-issuing.policy.ts",
        "src/modules/wallet/domain/aggregates/wallet.aggregate.ts",
        "src/modules/wallet/domain/aggregates/wallet.ts",
        "src/modules/wallet/domain/anti-double-spend.service.ts",
        "src/modules/wallet/domain/constants/business-wallet-status.ts",
        "src/modules/wallet/domain/constants/card-category.ts",
        "src/modules/wallet/domain/constants/coin-credit-status.ts",
        "src/modules/wallet/domain/constants/coin-deposit-status.ts",
        "src/modules/wallet/domain/constants/coin-product-rates.ts",
        "src/modules/wallet/domain/constants/fee-direction.ts",
        "src/modules/wallet/domain/constants/fee-type.ts",
        "src/modules/wallet/domain/constants/merchant-wallet-status.ts",
        "src/modules/wallet/domain/constants/wallet-account-kind.ts",
        "src/modules/wallet/domain/constants/wallet-account-status.ts",
        "src/modules/wallet/domain/constants/wallet-operation-kind.ts",
        "src/modules/wallet/domain/constants/wallet-owner-type.ts",
        "src/modules/wallet/domain/constants/wallet-product-type.ts",
        "src/modules/wallet/domain/constants/wallet-transaction-type.ts",
        "src/modules/wallet/domain/domain-event.ts",
        "src/modules/wallet/domain/entities/business-wallet.entity.ts",
        "src/modules/wallet/domain/entities/card-account.entity.ts",
        "src/modules/wallet/domain/entities/coin-credit.entity.ts",
        "src/modules/wallet/domain/entities/coin-deposit.entity.ts",
        "src/modules/wallet/domain/entities/coin-wallet.entity.ts",
        "src/modules/wallet/domain/entities/crypto-wallet.entity.ts",
        "src/modules/wallet/domain/entities/fee-policy.entity.ts",
        "src/modules/wallet/domain/entities/ledger-entry.entity.ts",
        "src/modules/wallet/domain/entities/merchant-wallet.entity.ts",
        "src/modules/wallet/domain/entities/qr-payment.entity.ts",
        "src/modules/wallet/domain/entities/qr.entity.ts",
        "src/modules/wallet/domain/entities/transaction.entity.ts",
        "src/modules/wallet/domain/entities/transaction.ts",
        "src/modules/wallet/domain/entities/wallet-account.entity.ts",
        "src/modules/wallet/domain/entities/wallet-operation.entity.ts",
        "src/modules/wallet/domain/entities/wallet.entity.ts",
        "src/modules/wallet/domain/events/money-deposited.event.ts",
        "src/modules/wallet/domain/repositories/business-wallet.repository.ts",
        "src/modules/wallet/domain/repositories/card-account.repository.ts",
        "src/modules/wallet/domain/repositories/coin-credit.repository.ts",
        "src/modules/wallet/domain/repositories/coin-deposit.repository.ts",
        "src/modules/wallet/domain/repositories/coin-wallet.repository.ts",
        "src/modules/wallet/domain/repositories/crypto-wallet.repository.ts",
        "src/modules/wallet/domain/repositories/fee-policy.repository.ts",
        "src/modules/wallet/domain/repositories/ledger.repository.ts",
        "src/modules/wallet/domain/repositories/merchant-wallet.repository.ts",
        "src/modules/wallet/domain/repositories/transaction.repository.ts",
        "src/modules/wallet/domain/repositories/wallet-operation.repository.ts",
        "src/modules/wallet/domain/repositories/wallet.repository.ts",
        "src/modules/wallet/domain/services/wallet-balance.service.ts",
        "src/modules/wallet/domain/services/wallet-domain.service.ts",
        "src/modules/wallet/domain/services/wallet-ledger.service.ts",
        "src/modules/wallet/domain/services/wallet-transfer.service.ts",
        "src/modules/wallet/domain/transaction.entity.ts",
        "src/modules/wallet/domain/value-objects/currency.vo.ts",
        "src/modules/wallet/domain/value-objects/money.vo.ts",
        "src/modules/wallet/domain/value-objects/wallet-balance.vo.ts",
        "src/modules/wallet/domain/value-objects/wallet-id.vo.ts",
        "src/modules/wallet/domain/wallet.entity.ts",
        "src/modules/wallet/engine/wallet-balance.engine.ts",
        "src/modules/wallet/events/wallet-credited.event.ts",
        "src/modules/wallet/foundation/airwallex-readiness/index.ts",
        "src/modules/wallet/foundation/airwallex-readiness/walletAirwallexReadinessControls.ts",
        "src/modules/wallet/index.ts",
        "src/modules/wallet/infrastructure/adapters/prisma-wallet-execution.adapter.ts",
        "src/modules/wallet/infrastructure/di/wallet.container.ts",
        "src/modules/wallet/infrastructure/ledger.repository.ts",
        "src/modules/wallet/infrastructure/mappers/ledger.mapper.ts",
        "src/modules/wallet/infrastructure/mappers/transaction.mapper.ts",
        "src/modules/wallet/infrastructure/mappers/wallet.mapper.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-financial-item-details.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-financial-overview.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-ledger.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-qr.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-transaction.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-unified-transaction-history.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-wallet-compliance.repository.ts",
        "src/modules/wallet/infrastructure/persistence/prisma-wallet.repository.ts",
        "src/modules/wallet/infrastructure/qr.repository.ts",
        "src/modules/wallet/infrastructure/repositories/in-memory-business-wallet.repository.ts",
        "src/modules/wallet/infrastructure/repositories/in-memory-merchant-wallet.repository.ts",
        "src/modules/wallet/infrastructure/repositories/in-memory-wallet-operation.repository.ts",
        "src/modules/wallet/infrastructure/routes/financial-dashboard.routes.ts",
        "src/modules/wallet/infrastructure/routes/financial-item-details.routes.ts",
        "src/modules/wallet/infrastructure/routes/financial-overview.routes.ts",
        "src/modules/wallet/infrastructure/routes/payment.routes.ts",
        "src/modules/wallet/infrastructure/routes/qr.routes.ts",
        "src/modules/wallet/infrastructure/routes/transaction.routes.ts",
        "src/modules/wallet/infrastructure/routes/unified-transaction-history.routes.ts",
        "src/modules/wallet/infrastructure/routes/wallet-core.routes.ts",
        "src/modules/wallet/infrastructure/routes/wallet-provider-config.routes.ts",
        "src/modules/wallet/infrastructure/routes/wallet.routes.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-create.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-guard.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-idempotency.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-query.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-sync.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-core-prisma-wallet-resolver.service.ts",
        "src/modules/wallet/infrastructure/services/wallet-route-fee-policy.service.ts",
        "src/modules/wallet/infrastructure/transaction.repository.ts",
        "src/modules/wallet/infrastructure/wallet.repository.ts",
        "src/modules/wallet/presentation/coin-products.controller.ts",
        "src/modules/wallet/presentation/contracts/wallet-core.contract.ts",
        "src/modules/wallet/presentation/contracts/wallet-core.examples.ts",
        "src/modules/wallet/presentation/controllers/wallet-core.controller.ts",
        "src/modules/wallet/presentation/index.ts",
        "src/modules/wallet/presentation/payment.controller.ts",
        "src/modules/wallet/presentation/qr.controller.ts",
        "src/modules/wallet/presentation/routes/coin-products.routes.ts",
        "src/modules/wallet/presentation/routes/wallet-hub.routes.ts",
        "src/modules/wallet/presentation/transaction.controller.ts",
        "src/modules/wallet/presentation/wallet-hub.controller.ts",
        "src/modules/wallet/presentation/wallet.controller.ts",
        "src/modules/wallet/security/wallet-lock.service.ts",
        "src/modules/wallet/services/anti-double-spend.service.ts",
        "src/modules/wallet/services/atomic-transaction.service.ts",
        "src/modules/wallet/services/idempotency.service.ts"
      ]
    },
    "releaseData": {
      "exists": true,
      "files": [
        ".data/release/243m/243m-handoff.md",
        ".data/release/243m/243m-report.json",
        ".data/release/243n/243n-handoff.md",
        ".data/release/243n/243n-report.json",
        ".data/release/243o/243o-handoff.md",
        ".data/release/243o/243o-report.json",
        ".data/release/243p/243p-handoff.md",
        ".data/release/243p/243p-report.json",
        ".data/release/243q/243q-handoff.md",
        ".data/release/243q/243q-report.json",
        ".data/release/243r/243r-handoff.md",
        ".data/release/243r/243r-report.json",
        ".data/release/243s/243s-handoff.md",
        ".data/release/243s/243s-report.json",
        ".data/release/243t/243t-handoff.md",
        ".data/release/243t/243t-report.json",
        ".data/release/243u/243u-handoff.md",
        ".data/release/243u/243u-report.json",
        ".data/release/243v/243v-handoff.md",
        ".data/release/243v/243v-report.json",
        ".data/release/243w-fix1/243w-fix1-handoff.md",
        ".data/release/243w-fix1/243w-fix1-report.json",
        ".data/release/243w/243w-handoff.md",
        ".data/release/243w/243w-report.json",
        ".data/release/243x/243x-handoff.md",
        ".data/release/243x/243x-report.json",
        ".data/release/243y/243y-handoff.md",
        ".data/release/243y/243y-report.json",
        ".data/release/243z/243z-handoff.md",
        ".data/release/243z/243z-report.json",
        ".data/release/244a/244a-handoff.md",
        ".data/release/244a/244a-report.json",
        ".data/release/244b/244b-handoff.md",
        ".data/release/244b/244b-report.json",
        ".data/release/244c/244c-handoff.md",
        ".data/release/244c/244c-report.json",
        ".data/release/244d/244d-handoff.md",
        ".data/release/244d/244d-report.json",
        ".data/release/244e/244e-handoff.md",
        ".data/release/244e/244e-report.json",
        ".data/release/244f/244f-handoff.md",
        ".data/release/244f/244f-report.json",
        ".data/release/244g/244g-handoff.md",
        ".data/release/244g/244g-report.json",
        ".data/release/244h/244h-handoff.md",
        ".data/release/244h/244h-report.json",
        ".data/release/244i-fix1/244i-fix1-handoff.md",
        ".data/release/244i-fix1/244i-fix1-report.json",
        ".data/release/244i/244i-check-last-output.json",
        ".data/release/244i/244i-handoff.md",
        ".data/release/244i/244i-report.json",
        ".data/release/244j-fix1/244j-fix1-handoff.md",
        ".data/release/244j-fix1/244j-fix1-report.json",
        ".data/release/244j/244j-handoff.md",
        ".data/release/244j/244j-report.json",
        ".data/release/244k/244k-check-output.json",
        ".data/release/244k/244k-handoff.md",
        ".data/release/244k/244k-report.json",
        ".data/release/244l/244l-check-output.json",
        ".data/release/244l/244l-handoff.md",
        ".data/release/244l/244l-report.json",
        ".data/release/244m/244m-check-output.json",
        ".data/release/244m/244m-handoff.md",
        ".data/release/244m/244m-report.json",
        ".data/release/244n/244n-check-output.json",
        ".data/release/244n/244n-handoff.md",
        ".data/release/244n/244n-report.json",
        ".data/release/244o/244o-handoff.md",
        ".data/release/244o/244o-report.json",
        ".data/release/244p/244p-handoff.md",
        ".data/release/244p/244p-report.json",
        ".data/release/244q/244q-handoff.md",
        ".data/release/244q/244q-report.json",
        ".data/release/244r/244r-handoff.md",
        ".data/release/244r/244r-report.json",
        ".data/release/244s/244s-handoff.md",
        ".data/release/244s/244s-report.json",
        ".data/release/244t/244t-handoff.md",
        ".data/release/244t/244t-report.json",
        ".data/release/244u/244u-handoff.md",
        ".data/release/244u/244u-report.json",
        ".data/release/244v/244v-handoff.md",
        ".data/release/244v/244v-report.json",
        ".data/release/244w/244w-handoff.md",
        ".data/release/244w/244w-report.json",
        ".data/release/244x/244x-handoff.md",
        ".data/release/244x/244x-report.json",
        ".data/release/244y/244y-handoff.md",
        ".data/release/244y/244y-report.json",
        ".data/release/244z/244z-handoff.md",
        ".data/release/244z/244z-report.json",
        ".data/release/245a/245a-handoff.md",
        ".data/release/245a/245a-report.json",
        ".data/release/245b/245b-handoff.md",
        ".data/release/245b/245b-report.json",
        ".data/release/245c/245c-handoff.md",
        ".data/release/245c/245c-report.json",
        ".data/release/245d-fix1/245d-fix1-handoff.md",
        ".data/release/245d-fix1/245d-fix1-report.json",
        ".data/release/245d/245d-handoff.md",
        ".data/release/245d/245d-report.json",
        ".data/release/245e/245e-handoff.md",
        ".data/release/245e/245e-report.json",
        ".data/release/245f/245f-handoff.md",
        ".data/release/245f/245f-report.json",
        ".data/release/245g/245g-handoff.md",
        ".data/release/245g/245g-report.json",
        ".data/release/245h/245h-handoff.md",
        ".data/release/245h/245h-report.json",
        ".data/release/245i/245i-handoff.md",
        ".data/release/245i/245i-report.json",
        ".data/release/245j/245j-handoff.md",
        ".data/release/245j/245j-report.json",
        ".data/release/245k/245k-handoff.md",
        ".data/release/245k/245k-report.json",
        ".data/release/245l/245l-handoff.md",
        ".data/release/245l/245l-report.json",
        ".data/release/245m/245m-handoff.md",
        ".data/release/245m/245m-report.json",
        ".data/release/245n/245n-handoff.md",
        ".data/release/245n/245n-report.json",
        ".data/release/245o/245o-handoff.md",
        ".data/release/245o/245o-inventory-report.json",
        ".data/release/245p-fix1/245p-fix1-handoff.md",
        ".data/release/245p-fix1/245p-fix1-report.json",
        ".data/release/245p-fix2/245p-fix2-handoff.md",
        ".data/release/245p-fix2/245p-fix2-report.json",
        ".data/release/245p/245p-handoff.md",
        ".data/release/245p/245p-pre-execution-report.json",
        ".data/release/245q/245q-handoff.md",
        ".data/release/245q/245q-report.json",
        ".data/release/245r-fix1/245r-fix1-handoff.md",
        ".data/release/245r-fix1/245r-fix1-report.json",
        ".data/release/245r-fix2/245r-fix2-handoff.md",
        ".data/release/245r-fix2/245r-fix2-report.json",
        ".data/release/245r-fix3/245r-fix3-handoff.md",
        ".data/release/245r-fix3/245r-fix3-report.json",
        ".data/release/245r-fix4/245r-fix4-handoff.md",
        ".data/release/245r-fix4/245r-fix4-report.json",
        ".data/release/245r-fix5/245r-fix5-handoff.md",
        ".data/release/245r-fix5/245r-fix5-report.json",
        ".data/release/245r-fix6/245r-fix6-handoff.md",
        ".data/release/245r-fix6/245r-fix6-report.json",
        ".data/release/245r-fix7/245r-fix7-handoff.md",
        ".data/release/245r-fix7/245r-fix7-report.json",
        ".data/release/245r-fix7a/245r-fix7a-handoff.md",
        ".data/release/245r-fix7a/245r-fix7a-report.json",
        ".data/release/245r/245r-handoff.md",
        ".data/release/245r/245r-report.json",
        ".data/release/245r/deploy-context/Dockerfile",
        ".data/release/245r/deploy-context/nginx.conf",
        ".data/release/245r/deploy-context/public/app-en.js",
        ".data/release/245r/deploy-context/public/app.js",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-ai-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-camera-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-gallery-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-games-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-hotels-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-marketplace-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-messenger-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-qr-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-stream-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-superapp-main-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-supermarket-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-taxi-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-translation-presentation-approved.png",
        ".data/release/245r/deploy-context/public/assets/approved/237k/sabi-wallet-approved.png",
        ".data/release/245r/deploy-context/public/index-en-fix75.html",
        ".data/release/245r/deploy-context/public/index-en.html",
        ".data/release/245r/deploy-context/public/index.html",
        ".data/release/245r/deploy-context/public/manifest-en.webmanifest",
        ".data/release/245r/deploy-context/public/manifest.webmanifest",
        ".data/release/245r/deploy-context/public/robots.txt",
        ".data/release/245r/deploy-context/public/sitemap.xml",
        ".data/release/245r/deploy-context/public/styles.css",
        ".data/release/245s/245s-handoff.md",
        ".data/release/245s/245s-report.json",
        ".data/release/245t-fix1/245t-fix1-handoff.md",
        ".data/release/245t-fix1/245t-fix1-report.json",
        ".data/release/245t/245t-handoff.md",
        ".data/release/245t/245t-report.json",
        ".data/release/245u-fix1/245u-fix1-handoff.md",
        ".data/release/245u-fix1/245u-fix1-report.json",
        ".data/release/245u/245u-handoff.md",
        ".data/release/245u/245u-report.json",
        ".data/release/246a/246a-handoff.md",
        ".data/release/246a/246a-report.json",
        ".data/release/246b/246b-handoff.md",
        ".data/release/246b/246b-report.json",
        ".data/release/246c/246c-handoff.md",
        ".data/release/246c/246c-report.json",
        ".data/release/246d/246d-handoff.md",
        ".data/release/246d/246d-report.json",
        ".data/release/246e/246e-handoff.md",
        ".data/release/246e/246e-report.json",
        ".data/release/246f-fix1/246f-fix1-handoff.md",
        ".data/release/246f-fix1/246f-fix1-report.json",
        ".data/release/246f-fix2/246f-fix2-handoff.md",
        ".data/release/246f-fix2/246f-fix2-report.json",
        ".data/release/246f/246f-handoff.md",
        ".data/release/246f/246f-report.json",
        ".data/release/246g-fix1/246g-fix1-handoff.md",
        ".data/release/246g-fix1/246g-fix1-report.json",
        ".data/release/246g-fix2/246g-fix2-handoff.md",
        ".data/release/246g-fix2/246g-fix2-report.json",
        ".data/release/246g-fix3/246g-fix3-handoff.md",
        ".data/release/246g-fix3/246g-fix3-report.json",
        ".data/release/246g-fix4/246g-fix4-addfirebase-debug.raw.log",
        ".data/release/246g-fix4/246g-fix4-addfirebase-debug.sanitized.log",
        ".data/release/246g-fix4/246g-fix4-handoff.md",
        ".data/release/246g-fix4/246g-fix4-report.json",
        ".data/release/246g-fix5/246g-fix5-handoff.md",
        ".data/release/246g-fix5/246g-fix5-report.json",
        ".data/release/246g-fix6/246g-fix6-handoff.md",
        ".data/release/246g-fix6/246g-fix6-report.json",
        ".data/release/246g/246g-handoff.md",
        ".data/release/246g/246g-report.json",
        ".data/release/246h/246h-handoff.md",
        ".data/release/246h/246h-report.json",
        ".data/release/246i-fix1/246i-fix1-handoff.md",
        ".data/release/246i-fix1/246i-fix1-report.json",
        ".data/release/246i/246i-handoff.md",
        ".data/release/246i/246i-report.json",
        ".data/release/246i/configs/GoogleService-Info.official.sabi.plist",
        ".data/release/246i/configs/GoogleService-Info.official.sabi.plist.stderr.txt",
        ".data/release/246i/configs/firebase-web-config.official.sabi.js",
        ".data/release/246i/configs/firebase-web-config.official.sabi.js.stderr.txt",
        ".data/release/246i/configs/google-services.official.sabi.json",
        ".data/release/246j/246j-handoff.md",
        ".data/release/246j/246j-report.json",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/build.gradle",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/google-services.json",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/AndroidManifest.xml",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/MainActivity.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/MainApplication.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallActionReceiver.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallActionReporter.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallAppVisibility.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallForegroundService.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallNativeModule.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallNotificationService.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallPackage.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiCallPayload.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/calls/SabiFirebaseMessagingService.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/presentation/SabiPresentationNativeModule.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/android/app/src/main/java/com/anonymous/superappmobile/presentation/SabiPresentationPackage.kt",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/app.json",
        ".data/release/246j/backup/2026-06-23T04-57-05-162Z/superapp-mobile/google-services.json",
        ".data/release/246k-fix1/246k-fix1-handoff.md",
        ".data/release/246k-fix1/246k-fix1-report.json",
        ".data/release/246k-fix2/246k-fix2-handoff.md",
        ".data/release/246k-fix2/246k-fix2-report.json",
        ".data/release/246k-fix3/246k-fix3-handoff.md",
        ".data/release/246k-fix3/246k-fix3-report.json",
        ".data/release/246k/246k-handoff.md",
        ".data/release/246k/246k-report.json",
        ".data/release/246l-fix1/246l-fix1-handoff.md",
        ".data/release/246l-fix1/246l-fix1-report.json",
        ".data/release/246l/246l-handoff.md",
        ".data/release/246l/246l-report.json",
        ".data/release/246m-fix1/246m-fix1-handoff.md",
        ".data/release/246m-fix1/246m-fix1-report.json",
        ".data/release/246m-fix2/246m-fix2-handoff.md",
        ".data/release/246m-fix2/246m-fix2-report.json",
        ".data/release/246m-fix2/246m-fix2-web-recaptcha-test.html",
        ".data/release/246m-fix3/246m-fix3-handoff.md",
        ".data/release/246m-fix3/246m-fix3-report.json",
        ".data/release/246m-fix3/246m-fix3-strict-recaptcha-test.html",
        ".data/release/246m-fix3a/246m-fix3a-handoff.md",
        ".data/release/246m-fix3a/246m-fix3a-report.json",
        ".data/release/246m-fix3a/246m-fix3a-strict-recaptcha-test.html",
        ".data/release/246m-fix4-closeout/246m-fix4-closeout-handoff.md",
        ".data/release/246m-fix4-closeout/246m-fix4-closeout-report.json",
        ".data/release/246m-fix4/.firebase/hosting.cHVibGlj.cache",
        ".data/release/246m-fix4/firebase.json",
        ".data/release/246m-fix4/public/index.html",
        ".data/release/246m/246m-handoff.md",
        ".data/release/246m/246m-report.json",
        ".data/release/246n/246n-browser-console-snippet.txt",
        ".data/release/246n/246n-handoff.md",
        ".data/release/246n/246n-report.json",
        ".data/release/246o/.firebase/hosting.cHVibGlj.cache",
        ".data/release/246o/246o-handoff.md",
        ".data/release/246o/246o-report.json",
        ".data/release/246o/firebase.json",
        ".data/release/246o/public/404.html",
        ".data/release/246o/public/index.html",
        ".data/release/246p/246p-handoff.md",
        ".data/release/246p/246p-report.json",
        ".data/release/247a/247a-crypto-scan-report.json",
        ".data/release/247b/247b-handoff.md",
        ".data/release/247b/247b-report.json",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/.data/237n-fix66/fix66-report.json",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/app-en.js",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/app.js",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/assets/approved/237k/sabi-wallet-approved.png",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/index-en-fix75.html",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/index-en.html",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/index.html",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/legal/sabi-crypto-wallet-external-provider-policy-en.pdf",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/legal/sabi-crypto-wallet-external-provider-policy-ru.pdf",
        ".data/release/247b/backup-site-ui-2026-06-23T01-31-00-351Z/styles.css",
        ".data/release/247c-fix1/247c-fix1-handoff.md",
        ".data/release/247c-fix1/247c-fix1-report.json",
        ".data/release/247c-fix1/deploy-context/Dockerfile",
        ".data/release/247c-fix1/deploy-context/package.json",
        ".data/release/247c-fix1/deploy-context/public/app-en.js",
        ".data/release/247c-fix1/deploy-context/public/app.js",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-ai-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-camera-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-finance-center-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-gallery-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-games-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-hotels-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-marketplace-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-messenger-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-qr-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-stream-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-superapp-main-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-supermarket-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-taxi-approved.png",
        ".data/release/247c-fix1/deploy-context/public/assets/approved/237k/sabi-translation-presentation-approved.png",
        ".data/release/247c-fix1/deploy-context/public/index-en-fix75.html",
        ".data/release/247c-fix1/deploy-context/public/index-en.html",
        ".data/release/247c-fix1/deploy-context/public/index.html",
        ".data/release/247c-fix1/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-en.pdf",
        ".data/release/247c-fix1/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-ru.pdf",
        ".data/release/247c-fix1/deploy-context/public/legal/sabi-terms-of-service-en.pdf",
        ".data/release/247c-fix1/deploy-context/public/legal/sabi-terms-of-service-ru.pdf",
        ".data/release/247c-fix1/deploy-context/public/robots.txt",
        ".data/release/247c-fix1/deploy-context/public/sitemap.xml",
        ".data/release/247c-fix1/deploy-context/public/styles.css",
        ".data/release/247c-fix1/deploy-context/server.js",
        ".data/release/247c-fix2/247c-fix2-handoff.md",
        ".data/release/247c-fix2/247c-fix2-report.json",
        ".data/release/247c-fix2/deploy-context/Dockerfile",
        ".data/release/247c-fix2/deploy-context/package.json",
        ".data/release/247c-fix2/deploy-context/public/app-en.js",
        ".data/release/247c-fix2/deploy-context/public/app.js",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-ai-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-camera-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-finance-center-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-gallery-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-games-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-hotels-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-marketplace-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-messenger-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-qr-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-stream-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-superapp-main-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-supermarket-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-taxi-approved.png",
        ".data/release/247c-fix2/deploy-context/public/assets/approved/237k/sabi-translation-presentation-approved.png",
        ".data/release/247c-fix2/deploy-context/public/index-en-fix75.html",
        ".data/release/247c-fix2/deploy-context/public/index-en.html",
        ".data/release/247c-fix2/deploy-context/public/index.html",
        ".data/release/247c-fix2/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-en.pdf",
        ".data/release/247c-fix2/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-ru.pdf",
        ".data/release/247c-fix2/deploy-context/public/legal/sabi-terms-of-service-en.pdf",
        ".data/release/247c-fix2/deploy-context/public/legal/sabi-terms-of-service-ru.pdf",
        ".data/release/247c-fix2/deploy-context/public/robots.txt",
        ".data/release/247c-fix2/deploy-context/public/sitemap.xml",
        ".data/release/247c-fix2/deploy-context/public/styles.css",
        ".data/release/247c-fix2/deploy-context/server.js",
        ".data/release/247c/247c-handoff.md",
        ".data/release/247c/247c-report.json",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/index-en-fix75.html",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/index-en.html",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/index.html",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/legal/sabi-finance-finance-center-external-provider-policy-en.pdf",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/legal/sabi-finance-finance-center-external-provider-policy-ru.pdf",
        ".data/release/247c/backup-before-deploy-2026-06-23T01-41-28-927Z/styles.css",
        ".data/release/247c/quarantined-bank-risk-docs/legal/sabi-finance-finance-center-external-provider-policy-en.pdf",
        ".data/release/247c/quarantined-bank-risk-docs/legal/sabi-finance-finance-center-external-provider-policy-ru.pdf",
        ".data/release/248a-fix1/248a-fix1-handoff.md",
        ".data/release/248a-fix1/248a-fix1-report.json",
        ".data/release/248a/248a-handoff.md",
        ".data/release/248a/248a-report.json",
        ".data/release/248a/backup-before-kyc-aml-2026-06-23T02-22-08-145Z/index-en-fix75.html",
        ".data/release/248a/backup-before-kyc-aml-2026-06-23T02-22-08-145Z/index-en.html",
        ".data/release/248a/backup-before-kyc-aml-2026-06-23T02-22-08-145Z/index.html",
        ".data/release/248a/backup-before-kyc-aml-2026-06-23T02-22-08-145Z/styles.css",
        ".data/release/248b-fix1/248b-fix1-handoff.md",
        ".data/release/248b-fix1/248b-fix1-report.json",
        ".data/release/248b-fix1/backup-before-fix1-2026-06-23T02-47-15-827Z/index-en-fix75.html",
        ".data/release/248b-fix1/backup-before-fix1-2026-06-23T02-47-15-827Z/index-en.html",
        ".data/release/248b-fix1/backup-before-fix1-2026-06-23T02-47-15-827Z/index.html",
        ".data/release/248b-fix1/backup-before-fix1-2026-06-23T02-47-15-827Z/sitemap.xml",
        ".data/release/248b-fix1/deploy-context/Dockerfile",
        ".data/release/248b-fix1/deploy-context/package.json",
        ".data/release/248b-fix1/deploy-context/public/app-en.js",
        ".data/release/248b-fix1/deploy-context/public/app.js",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-ai-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-camera-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-finance-center-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-gallery-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-games-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-hotels-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-marketplace-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-messenger-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-qr-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-stream-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-superapp-main-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-supermarket-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-taxi-approved.png",
        ".data/release/248b-fix1/deploy-context/public/assets/approved/237k/sabi-translation-presentation-approved.png",
        ".data/release/248b-fix1/deploy-context/public/index-en-fix75.html",
        ".data/release/248b-fix1/deploy-context/public/index-en.html",
        ".data/release/248b-fix1/deploy-context/public/index.html",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-kyc-aml-policy-en.pdf",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-kyc-aml-policy-ru.pdf",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-en.pdf",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-ru.pdf",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-terms-of-service-en.pdf",
        ".data/release/248b-fix1/deploy-context/public/legal/sabi-terms-of-service-ru.pdf",
        ".data/release/248b-fix1/deploy-context/public/robots.txt",
        ".data/release/248b-fix1/deploy-context/public/sitemap.xml",
        ".data/release/248b-fix1/deploy-context/public/styles.css",
        ".data/release/248b-fix1/deploy-context/server.js",
        ".data/release/248b/248b-handoff.md",
        ".data/release/248b/248b-report.json",
        ".data/release/248b/deploy-context/Dockerfile",
        ".data/release/248b/deploy-context/package.json",
        ".data/release/248b/deploy-context/public/app-en.js",
        ".data/release/248b/deploy-context/public/app.js",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-ai-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-camera-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-finance-center-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-gallery-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-games-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-hotels-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-marketplace-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-messenger-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-qr-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-stream-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-superapp-main-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-supermarket-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-taxi-approved.png",
        ".data/release/248b/deploy-context/public/assets/approved/237k/sabi-translation-presentation-approved.png",
        ".data/release/248b/deploy-context/public/index-en-fix75.html",
        ".data/release/248b/deploy-context/public/index-en.html",
        ".data/release/248b/deploy-context/public/index.html",
        ".data/release/248b/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-en.pdf",
        ".data/release/248b/deploy-context/public/legal/sabi-privacy-policy-uk-gdpr-ru.pdf",
        ".data/release/248b/deploy-context/public/legal/sabi-terms-of-service-en.pdf",
        ".data/release/248b/deploy-context/public/legal/sabi-terms-of-service-ru.pdf",
        ".data/release/248b/deploy-context/public/robots.txt",
        ".data/release/248b/deploy-context/public/sitemap.xml",
        ".data/release/248b/deploy-context/public/styles.css",
        ".data/release/248b/deploy-context/server.js",
        ".data/release/249a-fix1/249a-fix1-dns-mailbox-fix-plan.json",
        ".data/release/249a-fix1/249a-fix1-dns-mailbox-fix-plan.md",
        ".data/release/249a-fix1/249a-fix1-handoff.md",
        ".data/release/249a-fix1/249a-fix1-report.json",
        ".data/release/249a-fix2/249a-fix2-handoff.md",
        ".data/release/249a-fix2/249a-fix2-manual-dns-records-if-not-cloud-dns.md",
        ".data/release/249a-fix2/249a-fix2-report.json",
        ".data/release/249a-fix3-retry/249a-fix3-retry-handoff.md",
        ".data/release/249a-fix3-retry/249a-fix3-retry-report.json",
        ".data/release/249a-fix3/249a-fix3-handoff.md",
        ".data/release/249a-fix3/249a-fix3-report.json",
        ".data/release/249a-fix4-recheck/249a-fix4-recheck-handoff.md",
        ".data/release/249a-fix4-recheck/249a-fix4-recheck-report.json",
        ".data/release/249a-fix4-recheck2/249a-fix4-recheck2-handoff.md",
        ".data/release/249a-fix4-recheck2/249a-fix4-recheck2-report.json",
        ".data/release/249a-fix4-recheck3/249a-fix4-recheck3-handoff.md",
        ".data/release/249a-fix4-recheck3/249a-fix4-recheck3-report.json",
        ".data/release/249a-fix4-recheck4/249a-fix4-recheck4-handoff.md",
        ".data/release/249a-fix4-recheck4/249a-fix4-recheck4-report.json",
        ".data/release/249a-fix4-recheck5/249a-fix4-recheck5-handoff.md",
        ".data/release/249a-fix4-recheck5/249a-fix4-recheck5-report.json",
        ".data/release/249a-fix4-recheck6/249a-fix4-recheck6-handoff.md",
        ".data/release/249a-fix4-recheck6/249a-fix4-recheck6-report.json",
        ".data/release/249a-fix4-recheck7/249a-fix4-recheck7-handoff.md",
        ".data/release/249a-fix4-recheck7/249a-fix4-recheck7-report.json",
        ".data/release/249a-fix4-recheck8/249a-fix4-recheck8-handoff.md",
        ".data/release/249a-fix4-recheck8/249a-fix4-recheck8-report.json",
        ".data/release/249a-fix4-recheck9/249a-fix4-recheck9-handoff.md",
        ".data/release/249a-fix4-recheck9/249a-fix4-recheck9-report.json",
        ".data/release/249a-fix4/249a-fix4-authoritative-dns-correction-plan.md",
        ".data/release/249a-fix4/249a-fix4-handoff.md",
        ".data/release/249a-fix4/249a-fix4-report.json",
        ".data/release/249a/249a-handoff.md",
        ".data/release/249a/249a-report.json",
        ".data/release/249b/249b-handoff.md",
        ".data/release/249b/249b-manual-send-receive-instructions.md",
        ".data/release/249b/249b-owner-recorded-proof.json",
        ".data/release/249b/249b-proof-template.json",
        ".data/release/249b/249b-report.json",
        ".data/release/249b/249b-test-email-body.txt",
        ".data/release/249b/249b-test-package.json",
        ".data/release/249c/249c-bank-ready-site-email-proof-summary.md",
        ".data/release/249c/249c-handoff.md",
        ".data/release/249c/249c-report.json",
        ".data/release/250a/250a-handoff.md",
        ".data/release/250a/250a-info-manual-send-receive-instructions.md",
        ".data/release/250a/250a-info-proof-template.json",
        ".data/release/250a/250a-info-test-email-body.txt",
        ".data/release/250a/250a-info-test-package.json",
        ".data/release/250a/250a-report.json"
      ]
    }
  },
  "ownerSabiAiFoundation": {
    "role": "Owner Sabi AI is the company controller/business assistant directly below Owner.",
    "authority": "Owner has final authority. Owner Sabi AI prepares analysis, warnings, reports, evidence, and recommendations but does not execute final irreversible actions independently.",
    "dailyReports": true,
    "urgentReports": true,
    "antiFraudAmlAntiCorruptionMonitoring": true,
    "evidencePreservation": true,
    "noAutonomousMoneyMovement": true,
    "noAutonomousWalletPaymentPayout": true,
    "noAutonomousProviderMutation": true,
    "languages": [
      "RU",
      "EN",
      "ZH",
      "UZ"
    ],
    "publicRestrictions": [
      "No Telegram wording on public site",
      "No donations",
      "No investments",
      "No public crypto/wallet/blockchain wording",
      "Sabi Messenger only for public communication wording"
    ]
  },
  "serverFoundationTarget": {
    "phase": "server_base_and_owner_sabi_ai_foundation",
    "root": "C:\\Users\\User\\Desktop\\superapp",
    "officialDomain": "sabiai.app",
    "officialSiteProjectId": "sabi-official-prod",
    "firebaseProjectId": "sabi-official-prod-37629",
    "requiredNoMutationPreflight": true,
    "nextAfterPreflight": [
      "251B create safe Owner Sabi AI policy/training kernel files",
      "251C prepare server module boundaries and read-only health endpoints",
      "251D prepare admin-visible Owner Sabi AI daily report shell",
      "251E prepare production deployment checklist without secrets",
      "252A begin real server runtime bridge only after exact Owner approval"
    ]
  },
  "readiness": {
    "officialWebsiteReadiness": 100,
    "officialDomainEmailReadiness": 100,
    "bankReadySiteEmailProofReadiness": 100,
    "infoPublicContactReadiness": 0,
    "serverFoundationPreflightReadiness": 100,
    "ownerSabiAiFoundationPolicyReadiness": 100,
    "release251AReadiness": 100,
    "dnsMutationNow": 0,
    "cloudRunMutationNow": 0,
    "firebaseUserDeletionNow": 0,
    "googlePayBillingNow": 0,
    "walletPaymentPayoutNow": 0,
    "dbMutationNow": 0,
    "secretManagerReadWriteNow": 0,
    "envReadWriteNow": 0,
    "liveEmailSentNow": 0
  },
  "safety": {
    "readOnlyPreflightOnly": true,
    "noDnsMutationNow": true,
    "noCloudRunMutationNow": true,
    "noFirebaseUserDeletionNow": true,
    "noGooglePayBillingNow": true,
    "noWalletPaymentPayoutNow": true,
    "noDbMutationNow": true,
    "noSecretManagerReadWriteNow": true,
    "noEnvReadWriteNow": true,
    "noLiveEmailSentNow": true
  },
  "checksPassed": 20,
  "checksTotal": 20,
  "checks": [
    {
      "name": "251a_bank_ready_249c_exists",
      "passed": true,
      "details": {
        "path": ".data/release/249c/249c-report.json"
      }
    },
    {
      "name": "251a_bank_ready_249c_passed",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_official_site_ready_100",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_official_email_ready_100",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_src_exists",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_package_json_exists",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_tsconfig_exists",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_modules_dir_exists",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_release_dir_exists",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_owner_sabi_ai_foundation_policy_defined",
      "passed": true,
      "details": {
        "role": "Owner Sabi AI is the company controller/business assistant directly below Owner.",
        "authority": "Owner has final authority. Owner Sabi AI prepares analysis, warnings, reports, evidence, and recommendations but does not execute final irreversible actions independently.",
        "dailyReports": true,
        "urgentReports": true,
        "antiFraudAmlAntiCorruptionMonitoring": true,
        "evidencePreservation": true,
        "noAutonomousMoneyMovement": true,
        "noAutonomousWalletPaymentPayout": true,
        "noAutonomousProviderMutation": true,
        "languages": [
          "RU",
          "EN",
          "ZH",
          "UZ"
        ],
        "publicRestrictions": [
          "No Telegram wording on public site",
          "No donations",
          "No investments",
          "No public crypto/wallet/blockchain wording",
          "Sabi Messenger only for public communication wording"
        ]
      }
    },
    {
      "name": "251a_server_foundation_target_defined",
      "passed": true,
      "details": {
        "phase": "server_base_and_owner_sabi_ai_foundation",
        "root": "C:\\Users\\User\\Desktop\\superapp",
        "officialDomain": "sabiai.app",
        "officialSiteProjectId": "sabi-official-prod",
        "firebaseProjectId": "sabi-official-prod-37629",
        "requiredNoMutationPreflight": true,
        "nextAfterPreflight": [
          "251B create safe Owner Sabi AI policy/training kernel files",
          "251C prepare server module boundaries and read-only health endpoints",
          "251D prepare admin-visible Owner Sabi AI daily report shell",
          "251E prepare production deployment checklist without secrets",
          "252A begin real server runtime bridge only after exact Owner approval"
        ]
      }
    },
    {
      "name": "251a_no_dns_mutation_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_cloud_run_mutation_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_firebase_user_deletion_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_google_pay_billing_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_wallet_payment_payout_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_db_mutation_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_secret_manager_read_write_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_env_read_write_now",
      "passed": true,
      "details": {}
    },
    {
      "name": "251a_no_live_email_sent_now",
      "passed": true,
      "details": {}
    }
  ],
  "blockers": [],
  "warnings": [
    "info@sabiai.app is paused and must not be published until an alias/group/mailbox proof passes.",
    "251A does not create runtime endpoints, DB tables, secrets, provider config, or production mutations.",
    "Next stages must keep Owner approval gates for any real runtime, DB, provider, Wallet/payment/payout, or secret actions."
  ],
  "nextStep": "251B_owner_sabi_ai_policy_training_kernel_safe_files",
  "exactApprovalForNext": "I approve RELEASE-251B Owner Sabi AI policy and training kernel safe files, local code/artifact only, no DNS mutation, no Cloud Run mutation, no Firebase user deletion, no Secret Manager/env read-write, no DB mutation, no Google Pay Billing, no wallet, no payment, no payout",
  "artifacts": {}
} as unknown as SabiRelease251AReport;
