import {
  STREAM_FOUNDATION_140T_ROUTE_INVENTORY_CONTRACT_MATRIX_VERSION,
  type StreamFoundation140TRouteInventoryItem,
  type StreamFoundation140TRouteInventoryMatrixSnapshot,
} from "./streamFoundationRouteInventoryContractMatrixContracts";

const BLOCKED_RUNTIME_ACTIONS = [
  "backend_restart",
  "database_write",
  "provider_call",
  "wallet_mutation",
  "payment_authorization",
  "monthly_payout",
  "money_movement",
  "fake_success",
] as const;

const ROUTE_INVENTORY: readonly StreamFoundation140TRouteInventoryItem[] = [
  {
    id: "admin_stream_foundation_diagnostics_readiness",
    routeId: "stream_kernel_diagnostics_readiness",
    title: "Admin Stream foundation diagnostics readiness",
    audience: "admin",
    method: "GET",
    path: "/api/admin/stream/foundation/diagnostics/readiness",
    safetyClass: "read_only_diagnostics",
    runtimeStatus: "authenticated_get_passed",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
    allowedNow: true,
    mountedNow: true,
    sourceOnly: false,
    nextStage: "keep_as_read_only_diagnostics",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "admin_stream_foundation_diagnostics_preview",
    routeId: "stream_kernel_diagnostics_snapshot",
    title: "Admin Stream foundation diagnostics preview",
    audience: "admin",
    method: "GET",
    path: "/api/admin/stream/foundation/diagnostics/preview",
    safetyClass: "read_only_diagnostics",
    runtimeStatus: "authenticated_get_passed",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
    allowedNow: true,
    mountedNow: true,
    sourceOnly: false,
    nextStage: "keep_as_read_only_diagnostics",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "admin_stream_foundation_preview_source_route",
    routeId: "stream_foundation_preview",
    title: "Admin Stream foundation read-only preview route contract",
    audience: "admin",
    method: "GET",
    path: "/api/admin/stream/foundation/preview",
    safetyClass: "read_only_foundation_preview",
    runtimeStatus: "source_only_ready_unmounted",
    requiredScopes: ["admin:stream:read"],
    allowedNow: false,
    mountedNow: false,
    sourceOnly: true,
    nextStage: "BACKEND-STREAM-FOUNDATION-140U read-only handler envelope batch",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "mobile_stream_live_start_source_route",
    routeId: "stream_live_start",
    title: "Mobile Stream live start write route contract",
    audience: "mobile",
    method: "POST",
    path: "/api/stream/live/start",
    safetyClass: "live_write_requires_gate",
    runtimeStatus: "approval_required_before_mount",
    requiredScopes: ["stream:live:write"],
    allowedNow: false,
    mountedNow: false,
    sourceOnly: true,
    nextStage: "BACKEND-STREAM-FOUNDATION-140W live write route approval gate",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "mobile_stream_short_publish_source_route",
    routeId: "stream_short_publish",
    title: "Mobile Stream shorts publish write route contract",
    audience: "mobile",
    method: "POST",
    path: "/api/stream/shorts/publish",
    safetyClass: "shorts_write_requires_gate",
    runtimeStatus: "approval_required_before_mount",
    requiredScopes: ["stream:shorts:write"],
    allowedNow: false,
    mountedNow: false,
    sourceOnly: true,
    nextStage: "BACKEND-STREAM-FOUNDATION-140W live/write route approval gate",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "mobile_stream_gift_purchase_gate_source_route",
    routeId: "stream_gift_purchase_gate",
    title: "Stream gift purchase Wallet boundary route contract",
    audience: "mobile",
    method: "POST",
    path: "/api/stream/gifts/purchase",
    safetyClass: "gift_wallet_boundary_requires_gate",
    runtimeStatus: "blocked_until_provider_wallet_ledger_ready",
    requiredScopes: ["stream:write", "wallet:gift:boundary"],
    allowedNow: false,
    mountedNow: false,
    sourceOnly: true,
    nextStage: "Wallet ledger/provider/payment approval required before runtime",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
  {
    id: "admin_stream_live_moderation_gate_source_route",
    routeId: "stream_admin_moderation_gate",
    title: "Admin Stream moderation gate route contract",
    audience: "admin",
    method: "POST",
    path: "/api/admin/stream/moderation/gate",
    safetyClass: "admin_write_requires_gate",
    runtimeStatus: "approval_required_before_mount",
    requiredScopes: ["admin:stream:write", "admin:stream:moderation"],
    allowedNow: false,
    mountedNow: false,
    sourceOnly: true,
    nextStage: "Admin moderation approval gate source-only first",
    blockedActions: BLOCKED_RUNTIME_ACTIONS,
  },
];

function countByStatus(status: StreamFoundation140TRouteInventoryItem["runtimeStatus"]): number {
  return ROUTE_INVENTORY.filter((route) => route.runtimeStatus === status).length;
}

export function getStreamFoundationRouteInventoryContractMatrixSnapshot(): StreamFoundation140TRouteInventoryMatrixSnapshot {
  return {
    version: STREAM_FOUNDATION_140T_ROUTE_INVENTORY_CONTRACT_MATRIX_VERSION,
    stage: "route_inventory_contract_matrix_source_only",
    status: "route_inventory_matrix_ready",
    previousPassedStage: "BACKEND-STREAM-FOUNDATION-140R",
    postSmokeHandoffStage: "BACKEND-STREAM-FOUNDATION-140S",
    authenticatedDiagnosticsReady: true,
    routeInventory: ROUTE_INVENTORY,
    totals: {
      total: ROUTE_INVENTORY.length,
      authenticatedGetPassed: countByStatus("authenticated_get_passed"),
      sourceOnlyReadyUnmounted: countByStatus("source_only_ready_unmounted"),
      approvalRequiredBeforeMount: countByStatus("approval_required_before_mount"),
      providerWalletBlocked: countByStatus("blocked_until_provider_wallet_ledger_ready"),
    },
    safety: {
      sourceOnly: true,
      appTsChange: false,
      serverTsChange: false,
      streamIndexChange: false,
      backendRestart: false,
      runtimeHttpBy140T: false,
      databaseWrite: false,
      providerCall: false,
      walletMutation: false,
      paymentAuthorization: false,
      monthlyPayout: false,
      moneyMovement: false,
      fakeSuccess: false,
    },
  };
}
