export const TAXI_039X_STAGE = 'TAXI_039X_PROVIDER_BINDING_FINAL_GATE_NO_SECRET_VALUE_NO_PROVIDER_CALL';
export const TAXI_039X_PROVIDER_BINDING_FINAL_GATE_STATE = 'locked';
export const TAXI_039X_TAXI_COMMISSION_BPS = 0;
export const TAXI_039X_VISA_CASHBACK_BPS = 200;
