import {
  STREAM_FOUNDATION_140U_READ_ONLY_ROUTE_HANDLER_ENVELOPE_BATCH_VERSION,
  type StreamFoundation140UReadOnlyEnvelopeBatchSnapshot,
  type StreamFoundation140UReadOnlyEnvelopeSpec,
} from "./streamFoundationReadOnlyRouteHandlerEnvelopeBatchContracts";

const READ_ONLY_ENVELOPES: readonly StreamFoundation140UReadOnlyEnvelopeSpec[] = [
  {
    envelopeId: "admin_diagnostics_readiness_live",
    routeId: "stream_kernel_diagnostics_readiness",
    title: "Admin diagnostics readiness live envelope",
    audience: "admin",
    method: "GET",
    plannedPath: "/api/admin/stream/foundation/diagnostics/readiness",
    runtimeStatus: "authenticated_diagnostics_live",
    dataStatus: "diagnostics_live_ready",
    mountedNow: true,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: true,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_diagnostics_readiness_authenticated_ready",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
  },
  {
    envelopeId: "admin_diagnostics_preview_live",
    routeId: "stream_kernel_diagnostics_snapshot",
    title: "Admin diagnostics preview live envelope",
    audience: "admin",
    method: "GET",
    plannedPath: "/api/admin/stream/foundation/diagnostics/preview",
    runtimeStatus: "authenticated_diagnostics_live",
    dataStatus: "diagnostics_live_ready",
    mountedNow: true,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: true,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_diagnostics_preview_authenticated_ready",
    requiredScopes: ["admin:stream:read", "admin:stream:diagnostics:read"],
  },
  {
    envelopeId: "admin_foundation_preview_source_only",
    routeId: "stream_foundation_preview",
    title: "Admin foundation preview source-only envelope",
    audience: "admin",
    method: "GET",
    plannedPath: "/api/admin/stream/foundation/preview",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_foundation_preview_source_ready_unmounted",
    requiredScopes: ["admin:stream:read"],
  },
  {
    envelopeId: "mobile_live_list_read_model_source_only",
    routeId: "stream_live_list_read_model",
    title: "Mobile live list read-model source-only envelope",
    audience: "mobile",
    method: "GET",
    plannedPath: "/api/stream/live",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_live_list_read_model_source_ready_empty_not_fake",
    requiredScopes: ["stream:read"],
  },
  {
    envelopeId: "mobile_live_room_snapshot_source_only",
    routeId: "stream_live_room_snapshot_read_model",
    title: "Mobile live room snapshot source-only envelope",
    audience: "mobile",
    method: "GET",
    plannedPath: "/api/stream/live/:roomId",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_live_room_snapshot_source_ready_empty_not_fake",
    requiredScopes: ["stream:read"],
  },
  {
    envelopeId: "mobile_shorts_feed_source_only",
    routeId: "stream_shorts_feed_read_model",
    title: "Mobile shorts feed source-only envelope",
    audience: "mobile",
    method: "GET",
    plannedPath: "/api/stream/shorts/feed",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_shorts_feed_source_ready_empty_not_fake",
    requiredScopes: ["stream:read"],
  },
  {
    envelopeId: "mobile_creator_profile_source_only",
    routeId: "stream_creator_profile_read_model",
    title: "Mobile creator profile source-only envelope",
    audience: "mobile",
    method: "GET",
    plannedPath: "/api/stream/creators/:creatorId",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_creator_profile_source_ready_empty_not_fake",
    requiredScopes: ["stream:read"],
  },
  {
    envelopeId: "mobile_business_catalog_source_only",
    routeId: "stream_business_catalog_read_model",
    title: "Mobile Business Stream catalog source-only envelope",
    audience: "mobile",
    method: "GET",
    plannedPath: "/api/stream/business/catalog",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_business_catalog_source_ready_empty_not_fake",
    requiredScopes: ["stream:read"],
  },
  {
    envelopeId: "admin_moderation_queue_source_only",
    routeId: "stream_moderation_queue_read_model",
    title: "Admin moderation queue source-only envelope",
    audience: "admin",
    method: "GET",
    plannedPath: "/api/admin/stream/moderation/queue",
    runtimeStatus: "source_only_unmounted",
    dataStatus: "contract_ready_no_data_store",
    mountedNow: false,
    returnsFakeData: false,
    requiresDatabaseReadNow: false,
    requiresProviderCallNow: false,
    requiresWalletReadNow: false,
    allowedBeforeMount: false,
    statusCodeIfMountedWithoutData: 200,
    safeCode: "stream_moderation_queue_source_ready_empty_not_fake",
    requiredScopes: ["admin:stream:read", "admin:stream:moderation"],
  },
];

function countByRuntime(status: StreamFoundation140UReadOnlyEnvelopeSpec["runtimeStatus"]): number {
  return READ_ONLY_ENVELOPES.filter((envelope) => envelope.runtimeStatus === status).length;
}

export function getStreamFoundationReadOnlyRouteHandlerEnvelopeBatchSnapshot(): StreamFoundation140UReadOnlyEnvelopeBatchSnapshot {
  return {
    version: STREAM_FOUNDATION_140U_READ_ONLY_ROUTE_HANDLER_ENVELOPE_BATCH_VERSION,
    stage: "read_only_route_handler_envelope_batch_source_only",
    status: "read_only_envelope_batch_ready_unmounted",
    previousStage: "BACKEND-STREAM-FOUNDATION-140T",
    diagnosticsRoutesAlreadyLive: ["readiness", "preview"],
    envelopes: READ_ONLY_ENVELOPES,
    totals: {
      total: READ_ONLY_ENVELOPES.length,
      diagnosticsLive: countByRuntime("authenticated_diagnostics_live"),
      sourceOnlyUnmounted: countByRuntime("source_only_unmounted"),
      fakeDataRoutes: 0,
      routesRequiringDatabaseNow: 0,
      routesRequiringProviderNow: 0,
      routesRequiringWalletNow: 0,
    },
    safety: {
      sourceOnly: true,
      appTsChange: false,
      serverTsChange: false,
      streamIndexChange: false,
      routeMountNow: false,
      backendRestart: false,
      runtimeHttpBy140U: false,
      databaseWrite: false,
      providerCall: false,
      walletMutation: false,
      paymentAuthorization: false,
      monthlyPayout: false,
      moneyMovement: false,
      fakeSuccess: false,
    },
  };
}
