import {
  STREAM_FOUNDATION_140W_WRITE_ROUTE_APPROVAL_GATE_VERSION,
  type StreamFoundation140WWriteRouteApprovalGateSnapshot,
  type StreamFoundation140WWriteRouteApprovalItem,
} from "./streamFoundationWriteRouteApprovalGateContracts";

const BLOCKED_ACTIONS = [
  "route_mount",
  "backend_restart",
  "database_write",
  "provider_call",
  "wallet_mutation",
  "payment_authorization",
  "monthly_payout",
  "money_movement",
  "fake_success",
] as const;

const WRITE_ROUTES: readonly StreamFoundation140WWriteRouteApprovalItem[] = [
  {
    id: "live_session_start_gate",
    routeId: "stream_live_start",
    title: "Start Stream live session write route",
    kind: "live_session_write",
    method: "POST",
    plannedPath: "/api/stream/live/start",
    approvalStatus: "blocked_requires_owner_approval",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "identity_session_gate",
      "stream_live_kernel_gate",
      "moderation_policy_gate",
      "realtime_provider_readiness_gate",
      "owner_runtime_mount_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Owner approval for source-only live write handler plan; runtime mount remains blocked.",
  },
  {
    id: "live_session_stop_gate",
    routeId: "stream_live_stop",
    title: "Stop Stream live session write route",
    kind: "live_session_write",
    method: "POST",
    plannedPath: "/api/stream/live/stop",
    approvalStatus: "blocked_requires_owner_approval",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "identity_session_gate",
      "stream_live_kernel_gate",
      "event_audit_gate",
      "owner_runtime_mount_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Owner approval for source-only live stop handler plan; runtime mount remains blocked.",
  },
  {
    id: "live_heartbeat_gate",
    routeId: "stream_live_heartbeat",
    title: "Stream live heartbeat write route",
    kind: "live_session_write",
    method: "POST",
    plannedPath: "/api/stream/live/heartbeat",
    approvalStatus: "blocked_requires_owner_approval",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "identity_session_gate",
      "presence_repository_gate",
      "rate_limit_gate",
      "owner_runtime_mount_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Owner approval for source-only heartbeat handler plan; runtime mount remains blocked.",
  },
  {
    id: "shorts_publish_gate",
    routeId: "stream_short_publish",
    title: "Publish Stream short video write route",
    kind: "shorts_publish_write",
    method: "POST",
    plannedPath: "/api/stream/shorts/publish",
    approvalStatus: "blocked_requires_owner_approval",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "identity_session_gate",
      "media_asset_gate",
      "moderation_policy_gate",
      "storage_provider_readiness_gate",
      "owner_runtime_mount_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Owner approval for source-only shorts publish handler plan; runtime mount remains blocked.",
  },
  {
    id: "moderation_action_gate",
    routeId: "stream_admin_moderation_gate",
    title: "Admin Stream moderation write route",
    kind: "moderation_write",
    method: "POST",
    plannedPath: "/api/admin/stream/moderation/action",
    approvalStatus: "blocked_until_moderation_policy_ready",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "admin_permission_gate",
      "moderation_policy_gate",
      "audit_log_gate",
      "owner_runtime_mount_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Moderation policy/Admin approval before any runtime write mount.",
  },
  {
    id: "gift_purchase_wallet_boundary_gate",
    routeId: "stream_gift_purchase_gate",
    title: "Stream gift purchase Wallet boundary write route",
    kind: "gift_wallet_boundary_write",
    method: "POST",
    plannedPath: "/api/stream/gifts/purchase",
    approvalStatus: "blocked_until_provider_wallet_ledger_ready",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "wallet_ledger_gate",
      "payment_provider_key_gate",
      "merchant_settlement_gate",
      "provider_not_configured_safe_disabled_gate",
      "owner_money_movement_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Wallet/provider/ledger approval required; no money movement before separate stage.",
  },
  {
    id: "monthly_payout_wallet_boundary_gate",
    routeId: "stream_monthly_payout_gate",
    title: "Stream creator monthly payout boundary write route",
    kind: "monthly_payout_boundary_write",
    method: "POST",
    plannedPath: "/api/admin/stream/payouts/monthly/run",
    approvalStatus: "blocked_until_provider_wallet_ledger_ready",
    mountedNow: false,
    runtimeWriteAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredBeforeRuntimeMount: [
      "wallet_ledger_gate",
      "payout_provider_gate",
      "kyc_kyb_tax_gate",
      "admin_finance_approval_gate",
      "owner_money_movement_approval",
    ],
    blockedActions: BLOCKED_ACTIONS,
    nextRequiredApproval: "Monthly payout remains blocked until Wallet/provider/compliance approval.",
  },
];

export function getStreamFoundationWriteRouteApprovalGateSnapshot(): StreamFoundation140WWriteRouteApprovalGateSnapshot {
  return {
    version: STREAM_FOUNDATION_140W_WRITE_ROUTE_APPROVAL_GATE_VERSION,
    stage: "write_route_approval_gate_source_only",
    status: "write_routes_blocked_until_separate_exact_approval",
    previousStage: "BACKEND-STREAM-FOUNDATION-140V",
    readOnlyRoutesVerified: true,
    writeRoutes: WRITE_ROUTES,
    totals: {
      totalWriteRoutes: WRITE_ROUTES.length,
      mountedNow: 0,
      runtimeWriteAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      providerCallAllowedNow: 0,
      walletMutationAllowedNow: 0,
      paymentAuthorizationAllowedNow: 0,
      monthlyPayoutAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowed: 0,
    },
    safety: {
      sourceOnly: true,
      appTsChange: false,
      serverTsChange: false,
      streamIndexChange: false,
      routeMountNow: false,
      backendRestart: false,
      runtimeHttpBy140W: false,
      postPutPatchDeleteBy140W: false,
      databaseWrite: false,
      providerCall: false,
      walletMutation: false,
      paymentAuthorization: false,
      monthlyPayout: false,
      moneyMovement: false,
      fakeSuccess: false,
    },
  };
}
