// BACKEND-STREAM-GIFTS-LEDGER-198L
// Canonical unified Stream + Messenger gift catalog seed source.
// Source-only catalog data: no DB write happens from importing this file.

import { STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, type StreamGiftCatalogSeedItem198L } from "./streamGiftLedgerCatalogSeed198L.types";

export const STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS = ["STREAM_LIVE", "MESSENGER", "SHORTS", "CREATOR_PROFILE"] as const;

export const streamGiftLedgerCanonicalCatalog198L = [
  {
    id: "sakura-heart-burst",
    giftKey: "sakura-heart-burst",
    title: "Sakura Heart Burst",
    titleRu: "Сакура Сердце",
    diamondPrice: 18,
    assetId: "sakura-heart-burst",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/sakura-heart-burst.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/sakura-heart-burst.mp4",
    premiumTier: "starter",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "anime",
    rarityLabel: "Common Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Сакура Сердце", rarityLabel: "Common Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "koi-luck-splash",
    giftKey: "koi-luck-splash",
    title: "Koi Luck Splash",
    titleRu: "Карп Удачи",
    diamondPrice: 28,
    assetId: "koi-luck-splash",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/koi-luck-splash.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/koi-luck-splash.mp4",
    premiumTier: "rare",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "anime",
    rarityLabel: "Rare Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Карп Удачи", rarityLabel: "Rare Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "neon-fox-tail",
    giftKey: "neon-fox-tail",
    title: "Neon Fox Tail",
    titleRu: "Неоновый Лис",
    diamondPrice: 55,
    assetId: "neon-fox-tail",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/neon-fox-tail.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/neon-fox-tail.mp4",
    premiumTier: "rare",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "anime",
    rarityLabel: "Epic Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Неоновый Лис", rarityLabel: "Epic Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "moon-cat-guard",
    giftKey: "moon-cat-guard",
    title: "Moon Cat Guard",
    titleRu: "Лунный Кот",
    diamondPrice: 75,
    assetId: "moon-cat-guard",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/moon-cat-guard.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/moon-cat-guard.mp4",
    premiumTier: "rare",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "anime",
    rarityLabel: "Epic Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Лунный Кот", rarityLabel: "Epic Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "dj-star-drop",
    giftKey: "dj-star-drop",
    title: "DJ Star Drop",
    titleRu: "DJ Звезда",
    diamondPrice: 42,
    assetId: "dj-star-drop",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/dj-star-drop.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/dj-star-drop.mp4",
    premiumTier: "rare",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "sound",
    rarityLabel: "Rare Sound",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "DJ Звезда", rarityLabel: "Rare Sound", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "golden-lion-roar",
    giftKey: "golden-lion-roar",
    title: "Golden Lion Roar",
    titleRu: "Золотой Лев",
    diamondPrice: 120,
    assetId: "golden-lion-roar",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/golden-lion-roar.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/golden-lion-roar.mp4",
    premiumTier: "premium",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "premium",
    rarityLabel: "Legendary",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Золотой Лев", rarityLabel: "Legendary", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-rose-stage",
    giftKey: "royal-rose-stage",
    title: "Royal Rose Stage",
    titleRu: "Королевская Роза",
    diamondPrice: 150,
    assetId: "royal-rose-stage",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/royal-rose-stage.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/royal-rose-stage.mp4",
    premiumTier: "premium",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "premium",
    rarityLabel: "Legendary",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Королевская Роза", rarityLabel: "Legendary", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "cosmic-dragon-gate",
    giftKey: "cosmic-dragon-gate",
    title: "Cosmic Dragon Gate",
    titleRu: "Космический Дракон",
    diamondPrice: 220,
    assetId: "cosmic-dragon-gate",
    assetPosterUrl: "assets/stream/gifts/187a-premium-pack/posters/cosmic-dragon-gate.svg",
    assetAnimationUrl: "assets/stream/gifts/187a-premium-pack/loops/cosmic-dragon-gate.mp4",
    premiumTier: "premium",
    packKey: "pack1",
    packLabel: "Pack 1 · Classic Anime",
    catalogSegment: "premium",
    rarityLabel: "Mythic",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack1", titleRu: "Космический Дракон", rarityLabel: "Mythic", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "phoenix-crown-burst",
    giftKey: "phoenix-crown-burst",
    title: "Phoenix Crown Burst",
    titleRu: "Феникс Корона",
    diamondPrice: 260,
    assetId: "phoenix-crown-burst",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/phoenix-crown-burst.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/phoenix-crown-burst.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "premium",
    rarityLabel: "Mythic+",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Феникс Корона", rarityLabel: "Mythic+", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-whale-wave",
    giftKey: "crystal-whale-wave",
    title: "Crystal Whale Wave",
    titleRu: "Кристальный Кит",
    diamondPrice: 190,
    assetId: "crystal-whale-wave",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/crystal-whale-wave.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/crystal-whale-wave.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "anime",
    rarityLabel: "Legendary Aqua",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Кристальный Кит", rarityLabel: "Legendary Aqua", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "cyber-panda-beat",
    giftKey: "cyber-panda-beat",
    title: "Cyber Panda Beat",
    titleRu: "Кибер Панда",
    diamondPrice: 88,
    assetId: "cyber-panda-beat",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/cyber-panda-beat.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/cyber-panda-beat.mp4",
    premiumTier: "rare",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "sound",
    rarityLabel: "Epic Sound",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Кибер Панда", rarityLabel: "Epic Sound", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "velvet-butterfly-storm",
    giftKey: "velvet-butterfly-storm",
    title: "Velvet Butterfly Storm",
    titleRu: "Бархатные Бабочки",
    diamondPrice: 72,
    assetId: "velvet-butterfly-storm",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/velvet-butterfly-storm.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/velvet-butterfly-storm.mp4",
    premiumTier: "rare",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "anime",
    rarityLabel: "Rare Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Бархатные Бабочки", rarityLabel: "Rare Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "thunder-tiger-flash",
    giftKey: "thunder-tiger-flash",
    title: "Thunder Tiger Flash",
    titleRu: "Громовой Тигр",
    diamondPrice: 180,
    assetId: "thunder-tiger-flash",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/thunder-tiger-flash.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/thunder-tiger-flash.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "premium",
    rarityLabel: "Legendary Impact",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Громовой Тигр", rarityLabel: "Legendary Impact", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "aurora-unicorn-ride",
    giftKey: "aurora-unicorn-ride",
    title: "Aurora Unicorn Ride",
    titleRu: "Аврора Единорог",
    diamondPrice: 240,
    assetId: "aurora-unicorn-ride",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/aurora-unicorn-ride.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/aurora-unicorn-ride.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "anime",
    rarityLabel: "Mythic Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Аврора Единорог", rarityLabel: "Mythic Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-genie-lamp",
    giftKey: "diamond-genie-lamp",
    title: "Diamond Genie Lamp",
    titleRu: "Алмазный Джинн",
    diamondPrice: 300,
    assetId: "diamond-genie-lamp",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/diamond-genie-lamp.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/diamond-genie-lamp.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "premium",
    rarityLabel: "Mythic Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Алмазный Джинн", rarityLabel: "Mythic Premium", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "galaxy-idol-stage",
    giftKey: "galaxy-idol-stage",
    title: "Galaxy Idol Stage",
    titleRu: "Галакси Айдол",
    diamondPrice: 160,
    assetId: "galaxy-idol-stage",
    assetPosterUrl: "assets/stream/gifts/188a-premium-pack/posters/galaxy-idol-stage.svg",
    assetAnimationUrl: "assets/stream/gifts/188a-premium-pack/loops/galaxy-idol-stage.mp4",
    premiumTier: "premium",
    packKey: "pack2",
    packLabel: "Pack 2 · Ultra Stage",
    catalogSegment: "sound",
    rarityLabel: "Legendary Sound",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack2", titleRu: "Галакси Айдол", rarityLabel: "Legendary Sound", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "solar-samurai-dash",
    giftKey: "solar-samurai-dash",
    title: "Solar Samurai Dash",
    titleRu: "Солнечный Самурай",
    diamondPrice: 320,
    assetId: "solar-samurai-dash",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/solar-samurai-dash.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/solar-samurai-dash.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "anime",
    rarityLabel: "Mythic Solar",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Солнечный Самурай", rarityLabel: "Mythic Solar", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "mermaid-pearl-bloom",
    giftKey: "mermaid-pearl-bloom",
    title: "Mermaid Pearl Bloom",
    titleRu: "Русалка Жемчуг",
    diamondPrice: 240,
    assetId: "mermaid-pearl-bloom",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/mermaid-pearl-bloom.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/mermaid-pearl-bloom.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "premium",
    rarityLabel: "Legendary Pearl",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Русалка Жемчуг", rarityLabel: "Legendary Pearl", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "midnight-wolf-moon",
    giftKey: "midnight-wolf-moon",
    title: "Midnight Wolf Moon",
    titleRu: "Полночный Волк",
    diamondPrice: 180,
    assetId: "midnight-wolf-moon",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/midnight-wolf-moon.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/midnight-wolf-moon.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "anime",
    rarityLabel: "Legendary Moon",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Полночный Волк", rarityLabel: "Legendary Moon", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "candy-planet-pop",
    giftKey: "candy-planet-pop",
    title: "Candy Planet Pop",
    titleRu: "Конфетная Планета",
    diamondPrice: 95,
    assetId: "candy-planet-pop",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/candy-planet-pop.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/candy-planet-pop.mp4",
    premiumTier: "rare",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "sound",
    rarityLabel: "Epic Pop",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Конфетная Планета", rarityLabel: "Epic Pop", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-peacock-fan",
    giftKey: "royal-peacock-fan",
    title: "Royal Peacock Fan",
    titleRu: "Королевский Павлин",
    diamondPrice: 360,
    assetId: "royal-peacock-fan",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/royal-peacock-fan.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/royal-peacock-fan.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "premium",
    rarityLabel: "Mythic Royal",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Королевский Павлин", rarityLabel: "Mythic Royal", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "neon-shark-surge",
    giftKey: "neon-shark-surge",
    title: "Neon Shark Surge",
    titleRu: "Неоновая Акула",
    diamondPrice: 210,
    assetId: "neon-shark-surge",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/neon-shark-surge.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/neon-shark-surge.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "anime",
    rarityLabel: "Legendary Surge",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Неоновая Акула", rarityLabel: "Legendary Surge", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "angel-harp-glow",
    giftKey: "angel-harp-glow",
    title: "Angel Harp Glow",
    titleRu: "Ангельская Арфа",
    diamondPrice: 150,
    assetId: "angel-harp-glow",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/angel-harp-glow.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/angel-harp-glow.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "sound",
    rarityLabel: "Rare Harmony",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Ангельская Арфа", rarityLabel: "Rare Harmony", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "volcano-dragon-flare",
    giftKey: "volcano-dragon-flare",
    title: "Volcano Dragon Flare",
    titleRu: "Вулкан Дракон",
    diamondPrice: 420,
    assetId: "volcano-dragon-flare",
    assetPosterUrl: "assets/stream/gifts/190a-premium-pack/posters/volcano-dragon-flare.svg",
    assetAnimationUrl: "assets/stream/gifts/190a-premium-pack/loops/volcano-dragon-flare.mp4",
    premiumTier: "premium",
    packKey: "pack3",
    packLabel: "Pack 3 · Premium Live",
    catalogSegment: "premium",
    rarityLabel: "Mythic Flare",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack3", titleRu: "Вулкан Дракон", rarityLabel: "Mythic Flare", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "celestial-tiger-crown",
    giftKey: "celestial-tiger-crown",
    title: "Celestial Tiger Crown",
    titleRu: "Небесный Тигр",
    diamondPrice: 95,
    assetId: "celestial-tiger-crown",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/celestial-tiger-crown.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/celestial-tiger-crown.mp4",
    premiumTier: "rare",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "premium",
    rarityLabel: "Legendary Crown",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Небесный Тигр", rarityLabel: "Legendary Crown", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-sakura-palace",
    giftKey: "diamond-sakura-palace",
    title: "Diamond Sakura Palace",
    titleRu: "Алмазная Сакура",
    diamondPrice: 120,
    assetId: "diamond-sakura-palace",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/diamond-sakura-palace.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/diamond-sakura-palace.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "anime",
    rarityLabel: "Legendary Sakura",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Алмазная Сакура", rarityLabel: "Legendary Sakura", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "aurora-phoenix-parade",
    giftKey: "aurora-phoenix-parade",
    title: "Aurora Phoenix Parade",
    titleRu: "Аврора Феникс",
    diamondPrice: 180,
    assetId: "aurora-phoenix-parade",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/aurora-phoenix-parade.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/aurora-phoenix-parade.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "premium",
    rarityLabel: "Mythic Aurora",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Аврора Феникс", rarityLabel: "Mythic Aurora", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-galaxy-yacht",
    giftKey: "royal-galaxy-yacht",
    title: "Royal Galaxy Yacht",
    titleRu: "Галактика Яхта",
    diamondPrice: 210,
    assetId: "royal-galaxy-yacht",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/royal-galaxy-yacht.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/royal-galaxy-yacht.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "premium",
    rarityLabel: "Mythic Royal",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Галактика Яхта", rarityLabel: "Mythic Royal", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-lotus-dragon",
    giftKey: "crystal-lotus-dragon",
    title: "Crystal Lotus Dragon",
    titleRu: "Лотос Дракон",
    diamondPrice: 260,
    assetId: "crystal-lotus-dragon",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/crystal-lotus-dragon.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/crystal-lotus-dragon.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "anime",
    rarityLabel: "Ultra Mythic Lotus",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Лотос Дракон", rarityLabel: "Ultra Mythic Lotus", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "neon-opera-idol",
    giftKey: "neon-opera-idol",
    title: "Neon Opera Idol",
    titleRu: "Неон Опера",
    diamondPrice: 85,
    assetId: "neon-opera-idol",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/neon-opera-idol.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/neon-opera-idol.mp4",
    premiumTier: "rare",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "sound",
    rarityLabel: "Epic Sound",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Неон Опера", rarityLabel: "Epic Sound", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "golden-falcon-crown",
    giftKey: "golden-falcon-crown",
    title: "Golden Falcon Crown",
    titleRu: "Золотой Сокол",
    diamondPrice: 150,
    assetId: "golden-falcon-crown",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/golden-falcon-crown.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/golden-falcon-crown.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "premium",
    rarityLabel: "Legendary Falcon",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Золотой Сокол", rarityLabel: "Legendary Falcon", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "imperial-dragon-meteor",
    giftKey: "imperial-dragon-meteor",
    title: "Imperial Dragon Meteor",
    titleRu: "Имперский Дракон",
    diamondPrice: 340,
    assetId: "imperial-dragon-meteor",
    assetPosterUrl: "assets/stream/gifts/197a-ultra-premium-pack/posters/imperial-dragon-meteor.svg",
    assetAnimationUrl: "assets/stream/gifts/197a-ultra-premium-pack/loops/imperial-dragon-meteor.mp4",
    premiumTier: "premium",
    packKey: "pack4",
    packLabel: "Pack 4 · Ultra Premium",
    catalogSegment: "premium",
    rarityLabel: "Ultra Mythic Dragon",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack4", titleRu: "Имперский Дракон", rarityLabel: "Ultra Mythic Dragon", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-spark-one",
    giftKey: "diamond-spark-one",
    title: "Diamond Spark One",
    titleRu: "Алмазная Искра",
    diamondPrice: 1,
    assetId: "diamond-spark-one",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/diamond-spark-one.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/diamond-spark-one.mp4",
    premiumTier: "starter",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "premium",
    rarityLabel: "Micro Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Алмазная Искра", rarityLabel: "Micro Premium", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "aurora-heart-five",
    giftKey: "aurora-heart-five",
    title: "Aurora Heart Five",
    titleRu: "Аврора Сердце",
    diamondPrice: 5,
    assetId: "aurora-heart-five",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/aurora-heart-five.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/aurora-heart-five.mp4",
    premiumTier: "starter",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "anime",
    rarityLabel: "Starter Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Аврора Сердце", rarityLabel: "Starter Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "silver-rose-ten",
    giftKey: "silver-rose-ten",
    title: "Silver Rose Ten",
    titleRu: "Серебряная Роза",
    diamondPrice: 10,
    assetId: "silver-rose-ten",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/silver-rose-ten.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/silver-rose-ten.mp4",
    premiumTier: "starter",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "premium",
    rarityLabel: "Clean Rare",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Серебряная Роза", rarityLabel: "Clean Rare", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-cat-twenty-five",
    giftKey: "crystal-cat-twenty-five",
    title: "Crystal Cat Twenty Five",
    titleRu: "Кристальный Кот",
    diamondPrice: 25,
    assetId: "crystal-cat-twenty-five",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/crystal-cat-twenty-five.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/crystal-cat-twenty-five.mp4",
    premiumTier: "rare",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "anime",
    rarityLabel: "Rare Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Кристальный Кот", rarityLabel: "Rare Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-pegasus-seventy-five",
    giftKey: "royal-pegasus-seventy-five",
    title: "Royal Pegasus Seventy Five",
    titleRu: "Королевский Пегас",
    diamondPrice: 75,
    assetId: "royal-pegasus-seventy-five",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/royal-pegasus-seventy-five.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/royal-pegasus-seventy-five.mp4",
    premiumTier: "rare",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "anime",
    rarityLabel: "Epic Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Королевский Пегас", rarityLabel: "Epic Premium", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "stellar-train-two-fifty",
    giftKey: "stellar-train-two-fifty",
    title: "Stellar Train Two Fifty",
    titleRu: "Звёздный Поезд",
    diamondPrice: 250,
    assetId: "stellar-train-two-fifty",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/stellar-train-two-fifty.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/stellar-train-two-fifty.mp4",
    premiumTier: "premium",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "premium",
    rarityLabel: "Legendary Motion",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Звёздный Поезд", rarityLabel: "Legendary Motion", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "sky-palace-one-thousand",
    giftKey: "sky-palace-one-thousand",
    title: "Sky Palace One Thousand",
    titleRu: "Небесный Дворец",
    diamondPrice: 1000,
    assetId: "sky-palace-one-thousand",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/sky-palace-one-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/sky-palace-one-thousand.mp4",
    premiumTier: "legendary",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "premium",
    rarityLabel: "Mythic Palace",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Небесный Дворец", rarityLabel: "Mythic Palace", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "imperial-galaxy-ten-thousand",
    giftKey: "imperial-galaxy-ten-thousand",
    title: "Imperial Galaxy Ten Thousand",
    titleRu: "Императорская Галактика",
    diamondPrice: 10000,
    assetId: "imperial-galaxy-ten-thousand",
    assetPosterUrl: "assets/stream/gifts/197c-pack-5-diamond-range/posters/imperial-galaxy-ten-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197c-pack-5-diamond-range/loops/imperial-galaxy-ten-thousand.mp4",
    premiumTier: "ultra_top",
    packKey: "pack5",
    packLabel: "Pack 5 · Diamond Range",
    catalogSegment: "premium",
    rarityLabel: "Ultra Mythic Galaxy",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack5", titleRu: "Императорская Галактика", rarityLabel: "Ultra Mythic Galaxy", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "jade-like-spark",
    giftKey: "jade-like-spark",
    title: "Jade Like Spark",
    titleRu: "Нефритовый Лайк",
    diamondPrice: 2,
    assetId: "jade-like-spark",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/jade-like-spark.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/jade-like-spark.mp4",
    premiumTier: "starter",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "premium",
    rarityLabel: "Micro Clean",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Нефритовый Лайк", rarityLabel: "Micro Clean", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "sakura-melody-shell",
    giftKey: "sakura-melody-shell",
    title: "Sakura Melody Shell",
    titleRu: "Сакура Мелодия",
    diamondPrice: 15,
    assetId: "sakura-melody-shell",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/sakura-melody-shell.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/sakura-melody-shell.mp4",
    premiumTier: "starter",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "sound",
    rarityLabel: "Clean Rare",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Сакура Мелодия", rarityLabel: "Clean Rare", catalogSegment: "sound", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "moon-bunny-crown",
    giftKey: "moon-bunny-crown",
    title: "Moon Bunny Crown",
    titleRu: "Лунный Зайчик",
    diamondPrice: 50,
    assetId: "moon-bunny-crown",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/moon-bunny-crown.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/moon-bunny-crown.mp4",
    premiumTier: "rare",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "anime",
    rarityLabel: "Rare Anime",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Лунный Зайчик", rarityLabel: "Rare Anime", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "amber-phoenix-wing",
    giftKey: "amber-phoenix-wing",
    title: "Amber Phoenix Wing",
    titleRu: "Янтарный Феникс",
    diamondPrice: 150,
    assetId: "amber-phoenix-wing",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/amber-phoenix-wing.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/amber-phoenix-wing.mp4",
    premiumTier: "premium",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "anime",
    rarityLabel: "Epic Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Янтарный Феникс", rarityLabel: "Epic Premium", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "emerald-supercar-glide",
    giftKey: "emerald-supercar-glide",
    title: "Emerald Supercar Glide",
    titleRu: "Изумрудный Автомобиль",
    diamondPrice: 500,
    assetId: "emerald-supercar-glide",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/emerald-supercar-glide.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/emerald-supercar-glide.mp4",
    premiumTier: "premium",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "premium",
    rarityLabel: "Legendary Motion",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Изумрудный Автомобиль", rarityLabel: "Legendary Motion", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "atlantis-crown-wave",
    giftKey: "atlantis-crown-wave",
    title: "Atlantis Crown Wave",
    titleRu: "Корона Атлантиды",
    diamondPrice: 1500,
    assetId: "atlantis-crown-wave",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/atlantis-crown-wave.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/atlantis-crown-wave.mp4",
    premiumTier: "legendary",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "premium",
    rarityLabel: "Mythic Ocean",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Корона Атлантиды", rarityLabel: "Mythic Ocean", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "cosmic-castle-orbit",
    giftKey: "cosmic-castle-orbit",
    title: "Cosmic Castle Orbit",
    titleRu: "Космический Замок",
    diamondPrice: 5000,
    assetId: "cosmic-castle-orbit",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/cosmic-castle-orbit.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/cosmic-castle-orbit.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "premium",
    rarityLabel: "Ultra Mythic",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Космический Замок", rarityLabel: "Ultra Mythic", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "sultan-universe-throne",
    giftKey: "sultan-universe-throne",
    title: "Sultan Universe Throne",
    titleRu: "Султанская Вселенная",
    diamondPrice: 9999,
    assetId: "sultan-universe-throne",
    assetPosterUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/posters/sultan-universe-throne.svg",
    assetAnimationUrl: "assets/stream/gifts/197d-pack-6-royal-mythic/loops/sultan-universe-throne.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack6",
    packLabel: "Pack 6 · Royal Mythic",
    catalogSegment: "premium",
    rarityLabel: "Ultra Top Mythic",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack6", titleRu: "Султанская Вселенная", rarityLabel: "Ultra Top Mythic", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-drop-one",
    giftKey: "diamond-drop-one",
    title: "Diamond Drop One",
    titleRu: "Алмазная Капля",
    diamondPrice: 1,
    assetId: "diamond-drop-one",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/diamond-drop-one.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/diamond-drop-one.mp4",
    premiumTier: "starter",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Micro Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Алмазная Капля", rarityLabel: "Micro Premium", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "neon-jasmine-eight",
    giftKey: "neon-jasmine-eight",
    title: "Neon Jasmine Eight",
    titleRu: "Неоновый Жасмин",
    diamondPrice: 8,
    assetId: "neon-jasmine-eight",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/neon-jasmine-eight.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/neon-jasmine-eight.mp4",
    premiumTier: "starter",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "anime",
    rarityLabel: "Clean Starter",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Неоновый Жасмин", rarityLabel: "Clean Starter", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-butterfly-thirty-five",
    giftKey: "crystal-butterfly-thirty-five",
    title: "Crystal Butterfly Thirty Five",
    titleRu: "Кристальная Бабочка",
    diamondPrice: 35,
    assetId: "crystal-butterfly-thirty-five",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/crystal-butterfly-thirty-five.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/crystal-butterfly-thirty-five.mp4",
    premiumTier: "rare",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "anime",
    rarityLabel: "Rare Crystal",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Кристальная Бабочка", rarityLabel: "Rare Crystal", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-lantern-one-twenty",
    giftKey: "royal-lantern-one-twenty",
    title: "Royal Lantern One Twenty",
    titleRu: "Королевский Фонарь",
    diamondPrice: 120,
    assetId: "royal-lantern-one-twenty",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/royal-lantern-one-twenty.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/royal-lantern-one-twenty.mp4",
    premiumTier: "premium",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Epic Light",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Королевский Фонарь", rarityLabel: "Epic Light", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "dragon-pearl-seven-seven-seven",
    giftKey: "dragon-pearl-seven-seven-seven",
    title: "Dragon Pearl Seven Seven Seven",
    titleRu: "Жемчуг Дракона",
    diamondPrice: 777,
    assetId: "dragon-pearl-seven-seven-seven",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/dragon-pearl-seven-seven-seven.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/dragon-pearl-seven-seven-seven.mp4",
    premiumTier: "premium",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Legendary Pearl",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Жемчуг Дракона", rarityLabel: "Legendary Pearl", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "silk-road-caravan-two-five-zero-zero",
    giftKey: "silk-road-caravan-two-five-zero-zero",
    title: "Silk Road Caravan Two Five Zero Zero",
    titleRu: "Шёлковый Караван",
    diamondPrice: 2500,
    assetId: "silk-road-caravan-two-five-zero-zero",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/silk-road-caravan-two-five-zero-zero.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/silk-road-caravan-two-five-zero-zero.mp4",
    premiumTier: "legendary",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Mythic Caravan",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Шёлковый Караван", rarityLabel: "Mythic Caravan", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "aurora-palace-seven-five-zero-zero",
    giftKey: "aurora-palace-seven-five-zero-zero",
    title: "Aurora Palace Seven Five Zero Zero",
    titleRu: "Дворец Авроры",
    diamondPrice: 7500,
    assetId: "aurora-palace-seven-five-zero-zero",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/aurora-palace-seven-five-zero-zero.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/aurora-palace-seven-five-zero-zero.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Ultra Mythic Palace",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Дворец Авроры", rarityLabel: "Ultra Mythic Palace", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "celestial-emperor-ten-thousand",
    giftKey: "celestial-emperor-ten-thousand",
    title: "Celestial Emperor Ten Thousand",
    titleRu: "Небесный Император",
    diamondPrice: 10000,
    assetId: "celestial-emperor-ten-thousand",
    assetPosterUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/posters/celestial-emperor-ten-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197e-pack-7-celestial-dynasty/loops/celestial-emperor-ten-thousand.mp4",
    premiumTier: "ultra_top",
    packKey: "pack7",
    packLabel: "Pack 7 · Celestial Dynasty",
    catalogSegment: "premium",
    rarityLabel: "Ultra Top Emperor",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack7", titleRu: "Небесный Император", rarityLabel: "Ultra Top Emperor", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "azure-like-three",
    giftKey: "azure-like-three",
    title: "Azure Like Three",
    titleRu: "Лазурный Лайк",
    diamondPrice: 3,
    assetId: "azure-like-three",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/azure-like-three.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/azure-like-three.mp4",
    premiumTier: "starter",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Micro Premium",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Лазурный Лайк", rarityLabel: "Micro Premium", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "ruby-heart-twelve",
    giftKey: "ruby-heart-twelve",
    title: "Ruby Heart Twelve",
    titleRu: "Рубиновое Сердце",
    diamondPrice: 12,
    assetId: "ruby-heart-twelve",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/ruby-heart-twelve.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/ruby-heart-twelve.mp4",
    premiumTier: "starter",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "anime",
    rarityLabel: "Clean Starter",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Рубиновое Сердце", rarityLabel: "Clean Starter", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-unicorn-sixty",
    giftKey: "crystal-unicorn-sixty",
    title: "Crystal Unicorn Sixty",
    titleRu: "Хрустальный Единорог",
    diamondPrice: 60,
    assetId: "crystal-unicorn-sixty",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/crystal-unicorn-sixty.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/crystal-unicorn-sixty.mp4",
    premiumTier: "rare",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "anime",
    rarityLabel: "Rare Crystal",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Хрустальный Единорог", rarityLabel: "Rare Crystal", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "golden-meteor-three-hundred",
    giftKey: "golden-meteor-three-hundred",
    title: "Golden Meteor Three Hundred",
    titleRu: "Золотой Метеор",
    diamondPrice: 300,
    assetId: "golden-meteor-three-hundred",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/golden-meteor-three-hundred.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/golden-meteor-three-hundred.mp4",
    premiumTier: "premium",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Epic Meteor",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Золотой Метеор", rarityLabel: "Epic Meteor", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "imperial-lily-eight-eight-eight",
    giftKey: "imperial-lily-eight-eight-eight",
    title: "Imperial Lily Eight Eight Eight",
    titleRu: "Имперская Лилия",
    diamondPrice: 888,
    assetId: "imperial-lily-eight-eight-eight",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/imperial-lily-eight-eight-eight.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/imperial-lily-eight-eight-eight.mp4",
    premiumTier: "premium",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Legendary Lily",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Имперская Лилия", rarityLabel: "Legendary Lily", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "galactic-lion-three-thousand",
    giftKey: "galactic-lion-three-thousand",
    title: "Galactic Lion Three Thousand",
    titleRu: "Галактический Лев",
    diamondPrice: 3000,
    assetId: "galactic-lion-three-thousand",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/galactic-lion-three-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/galactic-lion-three-thousand.mp4",
    premiumTier: "legendary",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Mythic Lion",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Галактический Лев", rarityLabel: "Mythic Lion", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-jet-eight-eight-zero-zero",
    giftKey: "diamond-jet-eight-eight-zero-zero",
    title: "Diamond Jet Eight Eight Zero Zero",
    titleRu: "Алмазный Самолёт",
    diamondPrice: 8800,
    assetId: "diamond-jet-eight-eight-zero-zero",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/diamond-jet-eight-eight-zero-zero.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/diamond-jet-eight-eight-zero-zero.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Ultra Mythic Jet",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Алмазный Самолёт", rarityLabel: "Ultra Mythic Jet", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "universe-crown-ten-thousand",
    giftKey: "universe-crown-ten-thousand",
    title: "Universe Crown Ten Thousand",
    titleRu: "Корона Вселенной",
    diamondPrice: 10000,
    assetId: "universe-crown-ten-thousand",
    assetPosterUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/posters/universe-crown-ten-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197f-pack-8-imperial-galaxy/loops/universe-crown-ten-thousand.mp4",
    premiumTier: "ultra_top",
    packKey: "pack8",
    packLabel: "Pack 8 · Imperial Galaxy",
    catalogSegment: "premium",
    rarityLabel: "Ultra Top Crown",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack8", titleRu: "Корона Вселенной", rarityLabel: "Ultra Top Crown", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "pearl-like-four",
    giftKey: "pearl-like-four",
    title: "Pearl Like Four",
    titleRu: "Жемчужный Лайк",
    diamondPrice: 4,
    assetId: "pearl-like-four",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/pearl-like-four.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/pearl-like-four.mp4",
    premiumTier: "starter",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "premium",
    rarityLabel: "Micro Pearl",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Жемчужный Лайк", rarityLabel: "Micro Pearl", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "coral-heart-eighteen",
    giftKey: "coral-heart-eighteen",
    title: "Coral Heart Eighteen",
    titleRu: "Коралловое Сердце",
    diamondPrice: 18,
    assetId: "coral-heart-eighteen",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/coral-heart-eighteen.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/coral-heart-eighteen.mp4",
    premiumTier: "starter",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "anime",
    rarityLabel: "Rare Coral",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Коралловое Сердце", rarityLabel: "Rare Coral", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "aqua-dolphin-eighty",
    giftKey: "aqua-dolphin-eighty",
    title: "Aqua Dolphin Eighty",
    titleRu: "Аква Дельфин",
    diamondPrice: 80,
    assetId: "aqua-dolphin-eighty",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/aqua-dolphin-eighty.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/aqua-dolphin-eighty.mp4",
    premiumTier: "rare",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "anime",
    rarityLabel: "Rare Ocean",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Аква Дельфин", rarityLabel: "Rare Ocean", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "golden-anchor-four-fifty",
    giftKey: "golden-anchor-four-fifty",
    title: "Golden Anchor Four Fifty",
    titleRu: "Золотой Якорь",
    diamondPrice: 450,
    assetId: "golden-anchor-four-fifty",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/golden-anchor-four-fifty.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/golden-anchor-four-fifty.mp4",
    premiumTier: "premium",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "premium",
    rarityLabel: "Epic Anchor",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Золотой Якорь", rarityLabel: "Epic Anchor", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "emerald-mermaid-nine-ninety",
    giftKey: "emerald-mermaid-nine-ninety",
    title: "Emerald Mermaid Nine Ninety",
    titleRu: "Изумрудная Русалка",
    diamondPrice: 990,
    assetId: "emerald-mermaid-nine-ninety",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/emerald-mermaid-nine-ninety.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/emerald-mermaid-nine-ninety.mp4",
    premiumTier: "premium",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "anime",
    rarityLabel: "Legendary Mermaid",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Изумрудная Русалка", rarityLabel: "Legendary Mermaid", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-submarine-four-thousand",
    giftKey: "royal-submarine-four-thousand",
    title: "Royal Submarine Four Thousand",
    titleRu: "Королевская Субмарина",
    diamondPrice: 4000,
    assetId: "royal-submarine-four-thousand",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/royal-submarine-four-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/royal-submarine-four-thousand.mp4",
    premiumTier: "legendary",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "premium",
    rarityLabel: "Mythic Submarine",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Королевская Субмарина", rarityLabel: "Mythic Submarine", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "atlantic-palace-nine-thousand",
    giftKey: "atlantic-palace-nine-thousand",
    title: "Atlantic Palace Nine Thousand",
    titleRu: "Атлантический Дворец",
    diamondPrice: 9000,
    assetId: "atlantic-palace-nine-thousand",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/atlantic-palace-nine-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/atlantic-palace-nine-thousand.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "premium",
    rarityLabel: "Ultra Ocean Palace",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Атлантический Дворец", rarityLabel: "Ultra Ocean Palace", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "ocean-emperor-ten-thousand",
    giftKey: "ocean-emperor-ten-thousand",
    title: "Ocean Emperor Ten Thousand",
    titleRu: "Океанский Император",
    diamondPrice: 10000,
    assetId: "ocean-emperor-ten-thousand",
    assetPosterUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/posters/ocean-emperor-ten-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197g-pack-9-royal-ocean-legends/loops/ocean-emperor-ten-thousand.mp4",
    premiumTier: "ultra_top",
    packKey: "pack9",
    packLabel: "Pack 9 · Royal Ocean Legends",
    catalogSegment: "premium",
    rarityLabel: "Ultra Top Emperor",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack9", titleRu: "Океанский Император", rarityLabel: "Ultra Top Emperor", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "emerald-clover-six",
    giftKey: "emerald-clover-six",
    title: "Emerald Clover Six",
    titleRu: "Изумрудный Клевер",
    diamondPrice: 6,
    assetId: "emerald-clover-six",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/emerald-clover-six.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/emerald-clover-six.mp4",
    premiumTier: "starter",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "anime",
    rarityLabel: "Lucky Starter",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Изумрудный Клевер", rarityLabel: "Lucky Starter", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "ruby-fox-twenty-two",
    giftKey: "ruby-fox-twenty-two",
    title: "Ruby Fox Twenty Two",
    titleRu: "Рубиновый Лис",
    diamondPrice: 22,
    assetId: "ruby-fox-twenty-two",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/ruby-fox-twenty-two.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/ruby-fox-twenty-two.mp4",
    premiumTier: "starter",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "anime",
    rarityLabel: "Rare Fox",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Рубиновый Лис", rarityLabel: "Rare Fox", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "silver-koi-ninety",
    giftKey: "silver-koi-ninety",
    title: "Silver Koi Ninety",
    titleRu: "Серебряный Кои",
    diamondPrice: 90,
    assetId: "silver-koi-ninety",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/silver-koi-ninety.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/silver-koi-ninety.mp4",
    premiumTier: "rare",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "anime",
    rarityLabel: "Rare Koi",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Серебряный Кои", rarityLabel: "Rare Koi", catalogSegment: "anime", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "golden-phoenix-six-hundred",
    giftKey: "golden-phoenix-six-hundred",
    title: "Golden Phoenix Six Hundred",
    titleRu: "Золотой Феникс",
    diamondPrice: 600,
    assetId: "golden-phoenix-six-hundred",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/golden-phoenix-six-hundred.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/golden-phoenix-six-hundred.mp4",
    premiumTier: "premium",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "premium",
    rarityLabel: "Epic Phoenix",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Золотой Феникс", rarityLabel: "Epic Phoenix", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "royal-airship-twelve-hundred",
    giftKey: "royal-airship-twelve-hundred",
    title: "Royal Airship Twelve Hundred",
    titleRu: "Королевский Дирижабль",
    diamondPrice: 1200,
    assetId: "royal-airship-twelve-hundred",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/royal-airship-twelve-hundred.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/royal-airship-twelve-hundred.mp4",
    premiumTier: "legendary",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "premium",
    rarityLabel: "Legendary Airship",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Королевский Дирижабль", rarityLabel: "Legendary Airship", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "diamond-tiger-forty-five-hundred",
    giftKey: "diamond-tiger-forty-five-hundred",
    title: "Diamond Tiger Forty Five Hundred",
    titleRu: "Алмазный Тигр",
    diamondPrice: 4500,
    assetId: "diamond-tiger-forty-five-hundred",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/diamond-tiger-forty-five-hundred.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/diamond-tiger-forty-five-hundred.mp4",
    premiumTier: "legendary",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "premium",
    rarityLabel: "Mythic Tiger",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Алмазный Тигр", rarityLabel: "Mythic Tiger", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "crystal-planet-nine-five-hundred",
    giftKey: "crystal-planet-nine-five-hundred",
    title: "Crystal Planet Nine Five Hundred",
    titleRu: "Кристальная Планета",
    diamondPrice: 9500,
    assetId: "crystal-planet-nine-five-hundred",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/crystal-planet-nine-five-hundred.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/crystal-planet-nine-five-hundred.mp4",
    premiumTier: "ultra_mythic",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "premium",
    rarityLabel: "Ultra Planet",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Кристальная Планета", rarityLabel: "Ultra Planet", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
  {
    id: "immortal-dragon-ten-thousand",
    giftKey: "immortal-dragon-ten-thousand",
    title: "Immortal Dragon Ten Thousand",
    titleRu: "Бессмертный Дракон",
    diamondPrice: 10000,
    assetId: "immortal-dragon-ten-thousand",
    assetPosterUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/posters/immortal-dragon-ten-thousand.svg",
    assetAnimationUrl: "assets/stream/gifts/197h-pack-10-legendary-sky-empire/loops/immortal-dragon-ten-thousand.mp4",
    premiumTier: "ultra_top",
    packKey: "pack10",
    packLabel: "Pack 10 · Legendary Sky Empire",
    catalogSegment: "premium",
    rarityLabel: "Ultra Top Dragon",
    active: true,
    runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
    metadata: { sourceVersion: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION, packKey: "pack10", titleRu: "Бессмертный Дракон", rarityLabel: "Ultra Top Dragon", catalogSegment: "premium", pricingPolicy: "1 diamond = $0.01; receiver pending = 70%; platform fee = 30%" },
  },
] as const satisfies readonly StreamGiftCatalogSeedItem198L[];

export const streamGiftLedgerCanonicalCatalogSummary198L = Object.freeze({
  version: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_VERSION,
  totalGiftCount: 80,
  minDiamondPrice: 1,
  maxDiamondPrice: 10000,
  activeGiftCount: 80,
  runtimeContexts: STREAM_GIFT_LEDGER_CATALOG_SEED_198L_RUNTIME_CONTEXTS,
  packs: ["Pack 1 · Classic Anime", "Pack 2 · Ultra Stage", "Pack 3 · Premium Live", "Pack 4 · Ultra Premium", "Pack 5 · Diamond Range", "Pack 6 · Royal Mythic", "Pack 7 · Celestial Dynasty", "Pack 8 · Imperial Galaxy", "Pack 9 · Royal Ocean Legends", "Pack 10 · Legendary Sky Empire"],
});
