import type { TaxiRouteDescriptor } from '../foundation';
import type { TaxiKernelBoundaryReason } from '../kernel';
import type {
  TaxiAdminDailyAuditFieldContract,
  TaxiAiDailyPipelineStageContract,
  TaxiAdminIntegrationVersion,
  TaxiComplaintReviewQueueContract,
  TaxiClientBoundaryAdminCompatibilityRule,
} from './taxiAdminIntegration.types';

export const TAXI_ADMIN_INTEGRATION_VERSION: TaxiAdminIntegrationVersion = 'TAXI-BACKEND-FOUNDATION-001E';

export const TAXI_ADMIN_INTEGRATION_BOUNDARY_REASONS: readonly TaxiKernelBoundaryReason[] = [
  'mobile_ui_must_use_kernel_facade',
  'backend_runtime_not_mounted',
  'exact_approval_required',
  'direct_payment_or_payout_blocked',
  'direct_wallet_mutation_blocked',
  'direct_provider_call_blocked',
];

export const TAXI_AI_DAILY_PIPELINE_STAGES: readonly TaxiAiDailyPipelineStageContract[] = [
  {
    stageId: 'country_day_window_opened',
    order: 10,
    title: 'Country/day window opened',
    description: 'Every report is scoped by country local calendar day; old days do not mix with today.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'complaint_case_collection',
    order: 20,
    title: 'Complaint case collection',
    description: 'All driver and rider complaints for the country day must enter the review queue.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'trip_state_evidence_normalization',
    order: 30,
    title: 'Trip state evidence normalization',
    description: 'Complaints, stars, points and rewards require backend-verified trip state; fake trip completion is rejected.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'sabi_ai_signal_classification',
    order: 40,
    title: 'Sabi AI signal classification',
    description: 'Sabi AI reviews complaint text, route/state signals, stars, cancellation patterns and abuse markers.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'daily_complaint_tier_mapping',
    order: 50,
    title: 'Daily complaint tier mapping',
    description: 'Maps 1/2/3/>3 verified complaints in one country day to points, cooldown or block-pending-review candidates.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'false_complaint_and_abuse_review',
    order: 60,
    title: 'False complaint and abuse review',
    description: 'False complaints, arranged cancellation and ride-after-cancel are checked as violations for both sides.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'leaderboard_reward_freeze_review',
    order: 70,
    title: 'Leaderboard and reward freeze review',
    description: 'Top-3 country prizes stay frozen while complaints, appeals or leaderboard abuse signals remain open.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'appeal_explanation_queue',
    order: 80,
    title: 'Appeal and explanation queue',
    description: 'Drivers and riders can provide an explanation before long blocking or prize decisions are finalized.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'admin_action_queue_build',
    order: 90,
    title: 'Admin action queue build',
    description: 'Admin receives clear actions: review complaint, false complaint, cooldown, block, reward freeze or restore.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'full_daily_report_publish_preview',
    order: 100,
    title: 'Full daily report publish preview',
    description: 'Admin can render a complete daily report shell; real persistence requires DB/runtime approval later.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: false,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
  {
    stageId: 'client_boundary_summary_sync_preview',
    order: 110,
    title: 'Client kernel boundary summary sync preview',
    description: 'Mobile sees only safe summary state through kernel facade/events/state, never raw Admin evidence.',
    requiredEveryCountryDay: true,
    checksDrivers: true,
    checksRiders: true,
    adminVisible: true,
    mobileVisibleThroughKernelSummaryOnly: true,
    runtimeMountedNow: false,
    dbReadOrWriteAllowedNow: false,
    fakeDecisionBlocked: true,
  },
];

export const TAXI_ADMIN_DAILY_AUDIT_FIELDS: readonly TaxiAdminDailyAuditFieldContract[] = [
  ['country_code', 'Country code', 'Country-specific contest/report boundary.'],
  ['local_date', 'Local date', 'Country local calendar date for daily reset.'],
  ['role', 'Participant role', 'Driver, rider or both for symmetric rule checks.'],
  ['participant_id_reference', 'Participant reference', 'Reference-only identifier; no raw private data in mobile.'],
  ['verified_trip_reference_count', 'Verified trip references', 'Counts backend-verified trips only.'],
  ['verified_complaint_count', 'Verified complaints', 'Complaints that passed evidence review.'],
  ['false_complaint_count', 'False complaints', 'False complaint abuse after review.'],
  ['contractual_cancellation_signal_count', 'Arranged cancellation signals', 'Договорная отмена signal count.'],
  ['trip_after_cancellation_signal_count', 'Ride after cancellation signals', 'Trip after cancellation violation candidate count.'],
  ['star_quality_conflict_count', 'Star quality conflicts', 'Stars versus politeness, cleanliness, punctuality and complaint conflicts.'],
  ['cooldown_candidate_count', 'Cooldown candidates', 'One-hour and three-hour cooldown candidates.'],
  ['block_pending_explanation_count', 'Block pending explanation', 'More-than-three complaint cases pending explanation.'],
  ['reward_freeze_candidate_count', 'Reward freeze candidates', 'Top-3 reward candidates held for review.'],
  ['appeal_pending_count', 'Pending appeals', 'Driver/rider explanations waiting for Admin decision.'],
  ['admin_action_required_count', 'Admin actions required', 'Cases requiring Admin decision before real execution.'],
].map(([fieldId, label, description]) => ({
  fieldId: fieldId as TaxiAdminDailyAuditFieldContract['fieldId'],
  label,
  description,
  countryScoped: true,
  dailyScoped: true,
  backendVerifiedOnly: true,
  adminVisible: true,
  mobileRawAccessAllowed: false,
}));

export const TAXI_COMPLAINT_REVIEW_QUEUES: readonly TaxiComplaintReviewQueueContract[] = [
  {
    queueId: 'driver_daily_complaints',
    title: 'Driver daily complaints',
    role: 'driver',
    status: 'sabi_ai_review_required',
    countryScoped: true,
    dailyScoped: true,
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    executionAllowedNow: false,
    fakePenaltyBlocked: true,
  },
  {
    queueId: 'rider_daily_complaints',
    title: 'Rider daily complaints',
    role: 'rider',
    status: 'sabi_ai_review_required',
    countryScoped: true,
    dailyScoped: true,
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    executionAllowedNow: false,
    fakePenaltyBlocked: true,
  },
  {
    queueId: 'false_complaint_abuse',
    title: 'False complaint abuse',
    role: 'both',
    status: 'admin_decision_required',
    countryScoped: true,
    dailyScoped: true,
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    executionAllowedNow: false,
    fakePenaltyBlocked: true,
  },
  {
    queueId: 'reward_freeze_and_appeal',
    title: 'Reward freeze and appeal',
    role: 'both',
    status: 'admin_decision_required',
    countryScoped: true,
    dailyScoped: true,
    requiresSabiAiReview: true,
    requiresAdminDecision: true,
    executionAllowedNow: false,
    fakePenaltyBlocked: true,
  },
];

export const TAXI_CLIENT_BOUNDARY_ADMIN_COMPATIBILITY_RULES: readonly TaxiClientBoundaryAdminCompatibilityRule[] = [
  {
    ruleId: 'client_boundary_only_for_taxi',
    title: 'Mobile Taxi uses kernel only',
    description: 'Taxi client app cannot directly import backend runtime/provider/payment/payout; it uses kernel facade/events/state.',
    mobileUiMayCallDirectBackend: false,
    clientAppMustUseKernelFacade: true,
    adminMayRenderSameContract: true,
    providerRuntimeAllowedNow: false,
    paymentOrPayoutAllowedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    ruleId: 'admin_reads_same_contracts',
    title: 'Admin reads same foundation contracts',
    description: 'Admin sections are built from foundation contracts now to avoid later incompatible redesign.',
    mobileUiMayCallDirectBackend: false,
    clientAppMustUseKernelFacade: true,
    adminMayRenderSameContract: true,
    providerRuntimeAllowedNow: false,
    paymentOrPayoutAllowedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    ruleId: 'raw_evidence_admin_only',
    title: 'Raw evidence is Admin-only',
    description: 'Mobile may display safe status summaries only; complaint evidence and audit detail are Admin/foundation side.',
    mobileUiMayCallDirectBackend: false,
    clientAppMustUseKernelFacade: true,
    adminMayRenderSameContract: true,
    providerRuntimeAllowedNow: false,
    paymentOrPayoutAllowedNow: false,
    fakeSuccessBlocked: true,
  },
];

export const taxiAdminIntegrationRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/admin/taxi/ai-daily-report/pipeline-readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin-ready Taxi daily AI report pipeline contract; no scheduler or DB runtime is mounted.',
  },
  {
    method: 'GET',
    path: '/admin/taxi/complaints/review-queue/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Complaint review queue contract for drivers/riders; no real penalty execution.',
  },
  {
    method: 'GET',
    path: '/admin/taxi/daily-audit/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Daily country audit snapshot contract for Admin reporting visibility.',
  },
  {
    method: 'POST',
    path: '/admin/taxi/ai-daily-report/pipeline-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview-only daily report request decision; blocks scheduler/DB/penalty/reward runtime.',
  },
  {
    method: 'POST',
    path: '/admin/taxi/complaints/review-queue-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Preview-only queue filter decision; mobile raw evidence and penalty execution remain blocked.',
  },
];
