import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAdminActionInboxContract,
  TaxiAdminDailyReportLifecycleContract,
  TaxiAdminNotificationSurfaceContract,
  TaxiAdminNotificationsVersion,
} from './taxiAdminNotifications.types';

export const TAXI_ADMIN_NOTIFICATIONS_VERSION: TaxiAdminNotificationsVersion = 'TAXI-BACKEND-FOUNDATION-001I';

export const TAXI_ADMIN_NOTIFICATION_SURFACES: readonly TaxiAdminNotificationSurfaceContract[] = [
  {
    surfaceId: 'daily_report_status_banner',
    title: 'Daily Sabi AI report status banner',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'admin_action_inbox',
    title: 'Admin action inbox for Taxi complaints and daily reports',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'reviewer_assignment_queue',
    title: 'Reviewer assignment queue for country/day complaint cases',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'appeal_sla_timer',
    title: 'Appeal and explanation SLA timer',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'reward_freeze_alert',
    title: 'Reward freeze and release review alert',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'country_day_escalation_badge',
    title: 'Country/day escalation badge for 1/2/3/>3 complaint tiers',
    adminVisible: true,
    mobileVisible: false,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: false,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    surfaceId: 'kernel_safe_mobile_status',
    title: 'Kernel-safe mobile status summary',
    adminVisible: true,
    mobileVisible: true,
    rawEvidenceVisibleToMobile: false,
    usesFoundationContracts: true,
    usesClientBoundarySafeSummary: true,
    runtimePushEnabledNow: false,
    fakeSuccessBlocked: true,
  },
] as const;

export const TAXI_ADMIN_DAILY_REPORT_LIFECYCLE: readonly TaxiAdminDailyReportLifecycleContract[] = [
  {
    statusId: 'contract_scheduled_not_running',
    title: 'Daily report is defined by contract but scheduler is not running now',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: false,
    requiresSabiAiReview: false,
    requiresAdminReview: false,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'sabi_ai_review_required',
    title: 'Sabi AI must check every complaint for the country/day',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: false,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'sabi_ai_review_completed',
    title: 'Sabi AI evidence bundle completed, awaiting Admin visibility or review state',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: false,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'admin_review_required',
    title: 'Admin review required before any real sanction, restore or reward release',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: true,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'participant_explanation_required',
    title: 'Participant explanation is required before hard block or prize disqualification',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: true,
    requiresParticipantExplanation: true,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'appeal_sla_open',
    title: 'Appeal SLA is open and heavy action remains locked',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: true,
    requiresParticipantExplanation: true,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'final_decision_locked',
    title: 'Final decision contract locked after AI/Admin/evidence/appeal gates',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: true,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    statusId: 'clean_day_closed',
    title: 'Clean country/day closed without complaint action',
    requiresCountryDayScope: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiReview: true,
    requiresAdminReview: false,
    requiresParticipantExplanation: false,
    visibleInAdminActionInbox: true,
    canExecuteRuntimeNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
] as const;

export const TAXI_ADMIN_ACTION_INBOX_ITEMS: readonly TaxiAdminActionInboxContract[] = [
  {
    itemKind: 'review_driver_complaint',
    title: 'Review driver complaint after Sabi AI evidence bundle',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_rider_complaint',
    title: 'Review rider complaint after Sabi AI evidence bundle',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'verify_false_complaint_signal',
    title: 'Verify false complaint signal and protect the innocent participant',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_arranged_cancellation',
    title: 'Review arranged cancellation abuse before league or access action',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_trip_after_cancellation',
    title: 'Review trip-after-cancellation abuse before any action',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_stars_vs_complaint_conflict',
    title: 'Review conflict between high stars and serious complaints',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'request_participant_explanation',
    title: 'Request participant explanation before hard block or prize disqualification',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: true,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_cooldown_candidate',
    title: 'Review cooldown candidate from daily complaint tier 2 or 3',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_hard_block_candidate',
    title: 'Review hard block candidate from more than three verified daily complaints',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: true,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_reward_freeze_candidate',
    title: 'Review top-3 reward freeze candidate while dispute, appeal or complaint remains open',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    itemKind: 'review_restore_candidate',
    title: 'Review restore candidate after false complaint or clean Admin decision',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresDailyCountryReport: true,
    requiresSabiAiEvidenceBundle: true,
    requiresAdminDecisionBeforeRealAction: true,
    requiresAppealBeforeHeavyAction: false,
    actionRuntimeEnabledNow: false,
    fakeSanctionBlocked: true,
    fakeRewardBlocked: true,
  },
] as const;

export const taxiAdminNotificationRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/taxi/admin/notifications/contracts',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin notification contracts for daily Sabi AI report status, action inbox and escalation surfaces.',
  },
  {
    method: 'GET',
    path: '/api/taxi/admin/notifications/action-inbox',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future Admin action inbox read route; blocked until exact runtime approval and DB read approval.',
  },
  {
    method: 'POST',
    path: '/api/taxi/admin/notifications/decision-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future decision preview route; no real penalty, reward release, payout or participant status change now.',
  },
] as const;
