import type { SabiRelease243H } from './sabiRelease243h.types';

export const sabiRelease243H: SabiRelease243H = {
  version: 'SABI-RELEASE-243H-OFFICIAL-SITE-EMAIL-SMS-SERVER-AI-GOOGLE-CLOUD-DEPLOY-EXACT-OWNER-APPROVAL-GATE-REPORT-STATIC-CHECK',
  marker: 'SABI_RELEASE_243H_OFFICIAL_SITE_EMAIL_SMS_SERVER_AI_GOOGLE_CLOUD_DEPLOY_EXACT_OWNER_APPROVAL_GATE_REPORT_STATIC_CHECK_STILL_NO_LIVE_DEPLOY_NO_LIVE_SMS',
  readiness: {
    officialSiteGoogleCloudDeployApprovalGateReportStaticCheckReadiness: 100,
    officialDomainEmailGoogleCloudApprovalGateReportStaticCheckReadiness: 100,
    smsGoogleCloudServerBoundaryApprovalGateReportStaticCheckReadiness: 100,
    serverSabiAiGoogleCloudPersonalityApprovalGateReportStaticCheckReadiness: 100,
    bankWalletGoogleCloudDependencyApprovalGateReportStaticCheckReadiness: 100,
    previous243GReadiness: 100,
    googleCloudDeployExecutedNow: 0,
    cloudRunServiceCreatedNow: 0,
    liveDomainDnsChangedNow: 0,
    liveEmailDnsChangedNow: 0,
    liveSmsSentNow: 0,
    walletPaymentPayoutNow: 0,
    realProductionLaunchNow: 0,
  },
  safety: {
    noLiveGoogleCloudDeployNow: true,
    noCloudRunServiceCreateNow: true,
    noDomainDnsMutationNow: true,
    noLiveEmailDnsMutationNow: true,
    noLiveSmsSendNow: true,
    noFirebaseApiCallNow: true,
    noSmsProviderCallNow: true,
    noWalletPaymentPayoutNow: true,
    noSecretInSourceChatAdminMobile: true,
    noPlainSecretInReport: true,
    noEnvReadWriteNow: true,
    noSecretManagerReadWriteNow: true,
    noDbMutationNow: true,
    noRuntimeMountNow: true,
    noPublicLaunchClaimNow: true,
    ownerExactApprovalRequiredBeforeLiveAction: true,
  },
  nextStep: '243I_official_site_email_sms_server_ai_google_cloud_deploy_final_owner_command_candidate_still_no_live_deploy_no_live_sms',
};

export const sabiRelease243HChecks = [
  'strictPlanMode: true',
  'noPivotWithoutOwnerApproval: true',
  'maximumAcceleration: true',
  'googleCloudDeployExactOwnerApprovalGateReportStaticCheckOnly: true',
  'ownerExactApprovalGateReportStaticCheckReady: true',
  'officialWebsiteMustWorkOnServer: true',
  'officialDomainEmailMustWork: true',
  'smsIsMandatoryForProgram: true',
  'smsWithoutItProgramDoesNotWork: true',
  'allCriticalLogicMustBeServerSide: true',
  'cloudRunCustomDomainMappingOwnerApprovalReportStaticCheckRequired: true',
  'officialSiteHttpsOwnerApprovalReportStaticCheckRequired: true',
  'officialSiteHealthCheckOwnerApprovalReportStaticCheckRequired: true',
  'emailDnsAuthenticationOwnerApprovalReportStaticCheckRequired',
  'mx: true',
  'spf: true',
  'dkim: true',
  'dmarc: true',
  'firebasePhoneAuthOrApprovedSmsProviderRequired: true',
  'phoneNumberSignInMustBeEnabledBeforeLiveUse: true',
  'liveSmsStillLockedUntilExactOwnerApproval: true',
  'smsServerBoundaryRequired: true',
  'serverSabiAiPersonalityTrainingMustFollowPlan: true',
  'ownerSabiAiReportOnly: true',
  'ownerFinalDecisionRequired: true',
  'noSecretRevealToOwnerSabiAi: true',
  'bankAccountOpeningUrgent: true',
  'walletIntegrationBlockedUntilOfficialSiteEmailAndSmsReady: true',
  'walletProviderIntegrationRequiresOwnerExactApproval: true',
  "publicCommunicationChannel: 'Sabi Messenger'",
  'noTelegramMention: true',
  'noDonationOrInvestmentRequest: true',
  'sabiAllocatedCompanyFundsOnly: true',
  'targetSubmissionDate',
  '2026-07-01',
  'targetPublicLaunchDate',
  '2026-07-15',
  'ownerApprovalPhraseReferenceOnly',
  'I approve RELEASE-243H official site email SMS server AI Google Cloud deploy exact Owner approval gate report static check planning only',
  'liveDeployCommandReferenceOnly',
  'gcloud run deploy sabi-official-site --region <REGION> --source <SERVER_BUILD_CONTEXT>',
  'acceptedNow: false',
  'executableNow: false',
  'noExecutionNow: true',
  '243I_official_site_email_sms_server_ai_google_cloud_deploy_final_owner_command_candidate_still_no_live_deploy_no_live_sms',
] as const;

export const sabiRelease243HNoLiveExecution = {
  googleCloudDeployExecutedNow: 0,
  cloudRunServiceCreatedNow: 0,
  liveDomainDnsChangedNow: 0,
  liveEmailDnsChangedNow: 0,
  liveSmsSentNow: 0,
  walletPaymentPayoutNow: 0,
  realProductionLaunchNow: 0,
} as const;
