import { getStreamFoundationKernelDiagnosticsRuntimeRouteSourceOnlyPostWriteVerificationSnapshot } from "../kernel-diagnostics-runtime-route-source-only-post-write-verification";
import {
  STREAM_FOUNDATION_139M_KERNEL_DIAGNOSTICS_CONTROLLED_ROUTE_MOUNT_PLANNING_VERSION,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningCheck,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningDecision,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningSafety,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningSnapshot,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningStatus,
  type StreamFoundationKernelDiagnosticsControlledRouteMountPlanningStep,
} from "./streamFoundationKernelDiagnosticsControlledRouteMountPlanningContracts";

const PLANNING_SAFETY: StreamFoundationKernelDiagnosticsControlledRouteMountPlanningSafety = {
  patchScope: "src/modules/stream/foundation/** only",
  previousPostWriteVerificationRequired: true,
  sourceOnlyRouteVerifiedNow: true,
  planningOnly: true,
  sourcePatchPackageCreatedNow: false,
  routeMountAllowedNow: false,
  routeMountPerformedNow: false,
  protectedRouteRegisteredNow: false,
  expressRouterCreatedNow: false,
  expressRouterImportedNow: false,
  expressRouterBoundNow: false,
  streamIndexPatchIncluded: false,
  streamModuleIndexTouchedNow: false,
  appServerPatchIncluded: false,
  appServerTouchedNow: false,
  runtimeHttpRequestPerformedNow: false,
  databaseReadAllowedNow: false,
  databaseWriteAllowedNow: false,
  providerCallAllowedNow: false,
  walletMutationAllowedNow: false,
  paymentAuthorizationAllowedNow: false,
  monthlyPayoutAllowedNow: false,
  moneyMovementAllowedNow: false,
  rawSecretsReturned: false,
  mobileProviderKeysAllowed: false,
  fakeSuccessAllowed: false,
};

function buildPlanningSteps(): readonly StreamFoundationKernelDiagnosticsControlledRouteMountPlanningStep[] {
  return [
    {
      stepId: "confirm_previous_source_only_route_verified",
      title: "Confirm source-only runtime route verification",
      purpose: "Use 139L as the gate proving contracts, response mapper, and handler factory exist inside foundation only.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "previous_source_only_route_verified_planning_step",
    },
    {
      stepId: "prepare_owner_approval_text",
      title: "Prepare owner approval wording",
      purpose: "Make the next stage explicit before any stream module index or server route mount is touched.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "owner_approval_text_prepared_planning_step",
    },
    {
      stepId: "prepare_mount_target_inventory",
      title: "Prepare mount target inventory",
      purpose: "Define future target route path and backend mount boundary without changing app/server/index files now.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "mount_target_inventory_prepared_planning_step",
    },
    {
      stepId: "prepare_protected_route_registration_plan",
      title: "Prepare protected route registration plan",
      purpose: "Ensure the Admin diagnostics route can only be mounted behind admin authentication and safe response envelopes later.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "protected_route_registration_plan_prepared",
    },
    {
      stepId: "prepare_admin_auth_guard_plan",
      title: "Prepare Admin auth guard plan",
      purpose: "Keep diagnostics unavailable to public/mobile clients and only expose redacted server-side status to Admin later.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "admin_auth_guard_plan_prepared",
    },
    {
      stepId: "prepare_response_envelope_plan",
      title: "Prepare response envelope plan",
      purpose: "Require every future diagnostics response to be redacted, server-side only, and provider-not-configured honest.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "response_envelope_plan_prepared",
    },
    {
      stepId: "prepare_source_patch_boundary",
      title: "Prepare source patch boundary",
      purpose: "Keep this package foundation-only and delay stream index/app/server changes for controlled backend connection stages.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "source_patch_boundary_prepared",
    },
    {
      stepId: "prepare_server_smoke_boundary",
      title: "Prepare server smoke boundary",
      purpose: "List smoke expectations for the later backend mount stage without performing runtime HTTP requests now.",
      requiredBeforeNextStage: true,
      allowedInThisStage: true,
      executedNow: false,
      routeMountPerformedNow: false,
      runtimeHttpRequestPerformedNow: false,
      databaseWritePerformedNow: false,
      providerCallPerformedNow: false,
      walletMutationPerformedNow: false,
      moneyMovementPerformedNow: false,
      safeCode: "server_smoke_boundary_prepared",
    },
  ];
}

function buildChecks(): readonly StreamFoundationKernelDiagnosticsControlledRouteMountPlanningCheck[] {
  const previous = getStreamFoundationKernelDiagnosticsRuntimeRouteSourceOnlyPostWriteVerificationSnapshot();
  return [
    {
      area: "previous_post_write_verification",
      checkId: "139m_previous_139l_verified",
      passed: previous.status === "runtime_route_source_only_post_write_verified" && previous.readyForControlledRouteMountPlanning === true && previous.blockingChecks === 0,
      blocking: previous.status !== "runtime_route_source_only_post_write_verified" || previous.readyForControlledRouteMountPlanning !== true || previous.blockingChecks !== 0,
      expected: "139L post-write verification is ready with zero blockers",
      observed: `${previous.status}:${String(previous.readyForControlledRouteMountPlanning)}:${previous.blockingChecks}`,
      remediation: "Fix 139L verification before controlled route mount planning can continue.",
      safeCode: "previous_post_write_verification_ready",
      safeMessageKey: "stream.foundation.139m.previousPostWriteVerificationReady",
    },
    {
      area: "owner_approval_boundary",
      checkId: "139m_owner_approval_required_before_mount",
      passed: true,
      blocking: false,
      expected: "Owner approval remains required before any route mount or runtime activation",
      observed: "ownerApprovalRequiredBeforeRouteMount:true",
      remediation: "Do not mount routes without explicit owner approval in a later stage.",
      safeCode: "owner_approval_boundary_locked",
      safeMessageKey: "stream.foundation.139m.ownerApprovalBoundaryLocked",
    },
    {
      area: "mount_target_boundary",
      checkId: "139m_no_mount_target_modified_now",
      passed: true,
      blocking: false,
      expected: "No backend mount target file is modified in this planning stage",
      observed: "sourcePackageCreatedNow:false",
      remediation: "Keep mount target changes for a controlled source patch stage.",
      safeCode: "mount_target_boundary_planning_only",
      safeMessageKey: "stream.foundation.139m.mountTargetBoundaryPlanningOnly",
    },
    {
      area: "protected_route_boundary",
      checkId: "139m_protected_route_not_registered_now",
      passed: previous.protectedRouteRegisteredNow === false,
      blocking: previous.protectedRouteRegisteredNow !== false,
      expected: "Protected route registration is still false",
      observed: String(previous.protectedRouteRegisteredNow),
      remediation: "Do not register protected route until controlled mount stage.",
      safeCode: "protected_route_registration_blocked_now",
      safeMessageKey: "stream.foundation.139m.protectedRouteRegistrationBlockedNow",
    },
    {
      area: "admin_auth_boundary",
      checkId: "139m_admin_auth_required_later",
      passed: true,
      blocking: false,
      expected: "Future route must be admin-only and unavailable to public/mobile clients",
      observed: "adminOnlyFutureRoute:true",
      remediation: "Add auth guard in the future backend route mount source package.",
      safeCode: "admin_auth_required_later",
      safeMessageKey: "stream.foundation.139m.adminAuthRequiredLater",
    },
    {
      area: "response_envelope_boundary",
      checkId: "139m_response_envelope_redacted_later",
      passed: previous.rawSecretsReturned === 0 && previous.mobileProviderKeysAllowed === false,
      blocking: previous.rawSecretsReturned !== 0 || previous.mobileProviderKeysAllowed !== false,
      expected: "No raw secrets and no mobile provider keys are exposed",
      observed: `${previous.rawSecretsReturned}:${String(previous.mobileProviderKeysAllowed)}`,
      remediation: "Keep every future diagnostics route response redacted and server-side only.",
      safeCode: "response_envelope_redaction_boundary_ready",
      safeMessageKey: "stream.foundation.139m.responseEnvelopeRedactionBoundaryReady",
    },
    {
      area: "stream_index_guard",
      checkId: "139m_no_stream_index_patch",
      passed: previous.streamIndexPatchIncluded === false && previous.streamModuleIndexTouchedNow === false,
      blocking: previous.streamIndexPatchIncluded || previous.streamModuleIndexTouchedNow,
      expected: "No src/modules/stream/index.ts patch or touch",
      observed: `${String(previous.streamIndexPatchIncluded)}:${String(previous.streamModuleIndexTouchedNow)}`,
      remediation: "Keep stream index changes for explicit controlled backend connection approval.",
      safeCode: "stream_index_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.streamIndexGuardLocked",
    },
    {
      area: "app_server_guard",
      checkId: "139m_no_app_server_patch",
      passed: previous.appServerPatchIncluded === false && previous.appServerTouchedNow === false,
      blocking: previous.appServerPatchIncluded || previous.appServerTouchedNow,
      expected: "No app/server patch or touch",
      observed: `${String(previous.appServerPatchIncluded)}:${String(previous.appServerTouchedNow)}`,
      remediation: "Keep app/server changes for later controlled route connection only.",
      safeCode: "app_server_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.appServerGuardLocked",
    },
    {
      area: "runtime_execution_guard",
      checkId: "139m_no_runtime_execution_now",
      passed: previous.runtimeHttpRequestsPerformed === 0 && previous.diagnosticsRouteRuntimeMountPerformedNow === false,
      blocking: previous.runtimeHttpRequestsPerformed !== 0 || previous.diagnosticsRouteRuntimeMountPerformedNow !== false,
      expected: "No runtime HTTP request and no route mount",
      observed: `${previous.runtimeHttpRequestsPerformed}:${String(previous.diagnosticsRouteRuntimeMountPerformedNow)}`,
      remediation: "Do not execute runtime smoke until route is mounted in a later approved stage.",
      safeCode: "runtime_execution_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.runtimeExecutionGuardLocked",
    },
    {
      area: "database_provider_wallet_guard",
      checkId: "139m_no_db_provider_wallet_money",
      passed: previous.databaseExecutionPerformed === 0 && previous.providerCallsPerformed === 0 && previous.walletMutationPerformed === 0 && previous.moneyMovementPerformed === 0,
      blocking: previous.databaseExecutionPerformed !== 0 || previous.providerCallsPerformed !== 0 || previous.walletMutationPerformed !== 0 || previous.moneyMovementPerformed !== 0,
      expected: "No DB/provider/Wallet/money movement",
      observed: `${previous.databaseExecutionPerformed}:${previous.providerCallsPerformed}:${previous.walletMutationPerformed}:${previous.moneyMovementPerformed}`,
      remediation: "Keep DB/provider/Wallet/money flows disabled until production provider gates are implemented.",
      safeCode: "db_provider_wallet_money_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.dbProviderWalletMoneyGuardLocked",
    },
    {
      area: "secret_guard",
      checkId: "139m_no_secrets_or_mobile_keys",
      passed: previous.rawSecretsReturned === 0 && previous.mobileProviderKeysAllowed === false,
      blocking: previous.rawSecretsReturned !== 0 || previous.mobileProviderKeysAllowed !== false,
      expected: "No raw secrets and no mobile provider keys",
      observed: `${previous.rawSecretsReturned}:${String(previous.mobileProviderKeysAllowed)}`,
      remediation: "Keep provider keys server-side only and redacted from diagnostics.",
      safeCode: "secret_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.secretGuardLocked",
    },
    {
      area: "fake_success_guard",
      checkId: "139m_no_fake_success",
      passed: previous.fakeSuccessAllowed === false,
      blocking: previous.fakeSuccessAllowed !== false,
      expected: "fakeSuccessAllowed remains false",
      observed: String(previous.fakeSuccessAllowed),
      remediation: "Never claim provider/payment/live readiness without real configured providers and smokes.",
      safeCode: "fake_success_guard_locked_139m",
      safeMessageKey: "stream.foundation.139m.fakeSuccessGuardLocked",
    },
  ];
}

function buildDecision(status: StreamFoundationKernelDiagnosticsControlledRouteMountPlanningStatus): StreamFoundationKernelDiagnosticsControlledRouteMountPlanningDecision {
  const ready = status === "controlled_route_mount_planning_ready";
  return {
    decisionCode: ready
      ? "controlled_route_mount_planning_ready_for_source_patch_package"
      : "controlled_route_mount_planning_blocked_by_safety_boundary",
    readyForControlledRouteMountSourcePatchPackage: ready,
    readyForProductionRouteMount: false,
    ownerApprovalRequiredBeforeRouteMount: true,
    routeMountAllowedNow: false,
    routeMountPerformedNow: false,
    runtimeActivationAllowedNow: false,
    safeCode: ready ? "controlled_route_mount_planning_ready" : "controlled_route_mount_planning_blocked",
    safeMessageKey: ready
      ? "stream.foundation.139m.controlledRouteMountPlanningReady"
      : "stream.foundation.139m.controlledRouteMountPlanningBlocked",
  };
}

export function getStreamFoundationKernelDiagnosticsControlledRouteMountPlanningSnapshot(): StreamFoundationKernelDiagnosticsControlledRouteMountPlanningSnapshot {
  const previous = getStreamFoundationKernelDiagnosticsRuntimeRouteSourceOnlyPostWriteVerificationSnapshot();
  const planningSteps = buildPlanningSteps();
  const checks = buildChecks();
  const passedChecks = checks.filter((check) => check.passed).length;
  const blockingChecks = checks.filter((check) => check.blocking).length;
  const status: StreamFoundationKernelDiagnosticsControlledRouteMountPlanningStatus =
    previous.status === "runtime_route_source_only_post_write_verified" && blockingChecks === 0
      ? "controlled_route_mount_planning_ready"
      : "controlled_route_mount_planning_blocked";

  return {
    version: STREAM_FOUNDATION_139M_KERNEL_DIAGNOSTICS_CONTROLLED_ROUTE_MOUNT_PLANNING_VERSION,
    status,
    patchScope: "src/modules/stream/foundation/** only",
    previousPostWriteVerificationStatus: previous.status,
    totalSteps: planningSteps.length,
    executableStepsNow: 0,
    totalChecks: checks.length,
    passedChecks,
    blockingChecks,
    readyForControlledRouteMountSourcePatchPackage: status === "controlled_route_mount_planning_ready",
    readyForProductionRouteMount: false,
    ownerApprovalRequiredBeforeRouteMount: true,
    routeMountAllowedNow: false,
    routeMountPerformedNow: false,
    protectedRouteRegisteredNow: false,
    streamIndexPatchIncluded: false,
    streamModuleIndexTouchedNow: false,
    appServerPatchIncluded: false,
    appServerTouchedNow: false,
    runtimeHttpRequestsPerformed: 0,
    providerCallsPerformed: 0,
    databaseExecutionPerformed: 0,
    walletMutationPerformed: 0,
    paymentAuthorizationPerformed: 0,
    monthlyPayoutPerformed: 0,
    moneyMovementPerformed: 0,
    rawSecretsReturned: 0,
    mobileProviderKeysAllowed: false,
    fakeSuccessAllowed: false,
    planningSteps,
    checks,
    decision: buildDecision(status),
    safety: PLANNING_SAFETY,
  };
}
