import {
  STREAM_FOUNDATION_141O_RATE_LIMIT_GATE_VERSION,
  type StreamFoundation141ORateLimitGateSnapshot,
  type StreamFoundation141ORateLimitRule,
} from "./streamFoundationRateLimitGateContractPlanningContracts";

const RATE_LIMIT_RULES: readonly StreamFoundation141ORateLimitRule[] = [
  {
    id: "start_by_actor_device_window",
    commandId: "stream_start_live_session_command",
    scopes: ["actor_user_id", "device_session_id", "command_id"],
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 60,
    proposedMaxAttempts: 3,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Prevent repeated live start attempts from the same actor/device before runtime success is enabled.",
  },
  {
    id: "start_by_room_window",
    commandId: "stream_start_live_session_command",
    scopes: ["room_id", "command_id"],
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 120,
    proposedMaxAttempts: 2,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Prevent duplicate live start lifecycle transitions for the same room.",
  },
  {
    id: "stop_by_actor_device_window",
    commandId: "stream_stop_live_session_command",
    scopes: ["actor_user_id", "device_session_id", "command_id"],
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 60,
    proposedMaxAttempts: 5,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Throttle repeated stop commands while keeping stop idempotency for future runtime design.",
  },
  {
    id: "stop_by_room_window",
    commandId: "stream_stop_live_session_command",
    scopes: ["room_id", "command_id"],
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 60,
    proposedMaxAttempts: 5,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Protect one live room from repeated stop state transitions.",
  },
  {
    id: "heartbeat_by_actor_device_window",
    commandId: "stream_live_heartbeat_command",
    scopes: ["actor_user_id", "device_session_id", "room_id", "command_id"],
    status: "contract_planned_not_enabled",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 10,
    proposedMaxAttempts: 12,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Allow normal heartbeat cadence while blocking burst spam before runtime success.",
  },
  {
    id: "ip_hash_abuse_window_later",
    commandId: "stream_live_heartbeat_command",
    scopes: ["ip_hash_later", "command_id"],
    status: "owner_approval_required",
    requiredBeforeRuntimeMount: true,
    proposedWindowSeconds: 60,
    proposedMaxAttempts: 120,
    runtimeEnforcementEnabledNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Future abuse-control scope must use derived hash only; raw IP storage is not enabled here.",
  },
];

export function getStreamFoundationRateLimitGateContractPlanningSnapshot(): StreamFoundation141ORateLimitGateSnapshot {
  return {
    version: STREAM_FOUNDATION_141O_RATE_LIMIT_GATE_VERSION,
    stage: "rate_limit_gate_source_only_contract_planning",
    status: "rate_limit_contract_planned_routes_remain_blocked",
    previousStage: "BACKEND-STREAM-FOUNDATION-141N",
    rateLimitRules: RATE_LIMIT_RULES,
    antiAbusePolicy: {
      startStopHeartbeatMustBeThrottledBeforeRuntime: true,
      perUserAndDeviceScopesRequiredBeforeRuntime: true,
      ipHashScopeAllowedLaterWithoutRawIpExposure: true,
      rawIpStorageAllowedNow: false,
      runtimeEnforcementEnabledNow: false,
      routesStayBlockedNow: true,
      expectedCurrentStatusCode: 423,
    },
    totals: {
      rateLimitRules: 6,
      readyForRuntimeMountNow: 0,
      runtimeEnforcementEnabledNow: 0,
      runtimeSuccessAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      providerCallAllowedNow: 0,
      walletMutationAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowedNow: 0,
    },
    safety: {
      sourceOnly141O: true,
      appTsChangeBy141O: false,
      serverTsChangeBy141O: false,
      streamIndexChangeBy141O: false,
      backendRestartBy141O: false,
      runtimeHttpBy141O: false,
      runtimePostBy141O: false,
      databaseWriteBy141O: false,
      providerCallBy141O: false,
      walletMutationBy141O: false,
      paymentAuthorizationBy141O: false,
      monthlyPayoutBy141O: false,
      moneyMovementBy141O: false,
      fakeSuccessBy141O: false,
    },
  };
}
