import {
  STREAM_FOUNDATION_142P_POST_PATCH_RUNTIME_SMOKE_APPROVAL_VERSION,
  type StreamFoundation142PPostPatchRuntimeSmokeApprovalSnapshot,
  type StreamFoundation142PRuntimeSmokeApprovalRoute,
} from "./streamFoundationPostPatchRuntimeSmokeApprovalPackageContracts";

export const STREAM_FOUNDATION_142P_REQUIRED_EXACT_APPROVAL_TEXT_FOR_142Q =
  "I approve BACKEND-STREAM-FOUNDATION-142Q controlled blocked-route runtime POST smoke only, send POST requests only to /api/stream/live/start, /api/stream/live/stop, and /api/stream/live/heartbeat against local backend to verify all three still return 423 blocked after 142N, do not restart backend, no DB write, no provider call, no Wallet mutation, no payment authorization, no monthly payout, no money movement, no fake success.";

const RUNTIME_SMOKE_APPROVAL_ROUTES: readonly StreamFoundation142PRuntimeSmokeApprovalRoute[] = [
  {
    id: "runtime_smoke_stream_live_start",
    method: "POST",
    path: "/api/stream/live/start",
    expectedStatusCode: 423,
    expectedBlockedBehavior: true,
    allowedOnlyAfter142QApproval: true,
    requestBodySafeFieldsOnly: ["actorUserId", "roomId", "clientRequestId", "deviceSessionId", "locale"],
    databaseWriteAllowed: false,
    providerCallAllowed: false,
    walletMutationAllowed: false,
    paymentAuthorizationAllowed: false,
    monthlyPayoutAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  {
    id: "runtime_smoke_stream_live_stop",
    method: "POST",
    path: "/api/stream/live/stop",
    expectedStatusCode: 423,
    expectedBlockedBehavior: true,
    allowedOnlyAfter142QApproval: true,
    requestBodySafeFieldsOnly: ["actorUserId", "roomId", "clientRequestId", "deviceSessionId", "locale"],
    databaseWriteAllowed: false,
    providerCallAllowed: false,
    walletMutationAllowed: false,
    paymentAuthorizationAllowed: false,
    monthlyPayoutAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  {
    id: "runtime_smoke_stream_live_heartbeat",
    method: "POST",
    path: "/api/stream/live/heartbeat",
    expectedStatusCode: 423,
    expectedBlockedBehavior: true,
    allowedOnlyAfter142QApproval: true,
    requestBodySafeFieldsOnly: ["actorUserId", "roomId", "clientRequestId", "deviceSessionId", "locale"],
    databaseWriteAllowed: false,
    providerCallAllowed: false,
    walletMutationAllowed: false,
    paymentAuthorizationAllowed: false,
    monthlyPayoutAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
];

export function getStreamFoundationPostPatchRuntimeSmokeApprovalPackageSnapshot(): StreamFoundation142PPostPatchRuntimeSmokeApprovalSnapshot {
  return {
    version: STREAM_FOUNDATION_142P_POST_PATCH_RUNTIME_SMOKE_APPROVAL_VERSION,
    stage: "post_patch_handoff_and_controlled_blocked_route_runtime_smoke_approval_package",
    status: "post_patch_handoff_ready_next_exact_approval_required",
    previousStage: "BACKEND-STREAM-FOUNDATION-142O-FIX2",
    verification142OFix2: {
      ok: true,
      routeBindingPassed: 3,
      routeBindingFailed: 0,
      runtimeImportOk: true,
      runtimeHandlerReadinessPassed: 3,
      runtimeHandlerReadinessFailed: 0,
      routePatchContextSafetyOk: true,
      tscExitCode: 0,
      runtimeHttpPerformed: 0,
      runtimePostPerformed: 0,
      backendRestartPerformed: 0,
      databaseReadPerformed: 0,
      databaseWritePerformed: 0,
      providerCallPerformed: 0,
      walletMutationPerformed: 0,
      moneyMovementPerformed: 0,
      fakeSuccessAllowed: false,
    },
    runtimeSmokeApprovalRoutes: RUNTIME_SMOKE_APPROVAL_ROUTES,
    requiredExactApprovalTextFor142Q: STREAM_FOUNDATION_142P_REQUIRED_EXACT_APPROVAL_TEXT_FOR_142Q,
    nextApprovalPolicy: {
      exactApprovalRequiredBefore142Q: true,
      nextStageMayRunRuntimePostSmoke: true,
      nextStageMustUseLocalBackendOnly: true,
      nextStageMustExpect423Blocked: true,
      backendRestartAllowedFor142Q: false,
      sourceWriteAllowedFor142Q: false,
      databaseWriteAllowedFor142Q: false,
      providerCallAllowedFor142Q: false,
      walletMutationAllowedFor142Q: false,
      paymentAuthorizationAllowedFor142Q: false,
      monthlyPayoutAllowedFor142Q: false,
      moneyMovementAllowedFor142Q: false,
      fakeSuccessAllowedFor142Q: false,
      expectedStatusCodeForAllRoutes: 423,
    },
    totals: {
      approvalRoutes: 3,
      runtimePostAllowedBy142P: 0,
      runtimePostAllowedFor142QAfterApproval: 3,
      backendRestartAllowedFor142Q: 0,
      databaseWriteAllowedFor142Q: 0,
      providerCallAllowedFor142Q: 0,
      walletMutationAllowedFor142Q: 0,
      moneyMovementAllowedFor142Q: 0,
      fakeSuccessAllowedFor142Q: 0,
    },
    safety: {
      sourceOnly142P: true,
      targetWriteBy142P: false,
      backendRestartBy142P: false,
      runtimeHttpBy142P: false,
      runtimePostBy142P: false,
      databaseReadBy142P: false,
      databaseWriteBy142P: false,
      providerCallBy142P: false,
      providerSecretReadBy142P: false,
      walletMutationBy142P: false,
      paymentAuthorizationBy142P: false,
      monthlyPayoutBy142P: false,
      moneyMovementBy142P: false,
      fakeSuccessBy142P: false,
    },
  };
}
