import type { SabiProgramFoundation, SabiProgramCode } from "./program-foundation.types";

const commonSafetyHooks = [
  "unified_user_id_required",
  "admin_review_signal_supported",
  "no_fake_success",
  "provider_unavailable_state_required",
];

export const SABI_PROGRAM_FOUNDATIONS: Record<SabiProgramCode, SabiProgramFoundation> = {
  home: {
    code: "home",
    title: "Home",
    mobileRoute: "/",
    apiBasePath: "/api/v2/programs/home",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: [],
    safetyHooks: ["home_widget_registry", "notification_digest", "ai_voice_entry"],
    historyStreams: ["home_widget_opened", "home_notification_seen"],
    capabilities: [
      { id: "widget_registry", title: "Home widget registry", status: "foundation_ready", providerStatus: "not_required", apiPath: "/api/v2/programs" },
      { id: "notifications_summary", title: "Missed calls, messages, events and AI alerts", status: "foundation_ready", providerStatus: "not_required", apiPath: "/api/v2/programs/notifications/status" },
    ],
  },
  messenger: {
    code: "messenger",
    title: "Messenger",
    mobileRoute: "/tabs/chats",
    apiBasePath: "/api/v2/messenger",
    launchPhase: "launch_core",
    runtimeStatus: "ready",
    providerStatus: "not_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["socket_io_runtime", "auth_session"],
    safetyHooks: [...commonSafetyHooks, "presence", "message_report", "call_safety"],
    historyStreams: ["message", "call", "gift", "payment_request"],
    capabilities: [
      { id: "chat", title: "Chats", status: "foundation_ready", providerStatus: "not_required", apiPath: "/api/v2/messenger" },
      { id: "calls", title: "Calls", status: "foundation_ready", providerStatus: "not_required", apiPath: "/api/v2/calls" },
      { id: "ai_translation", title: "AI translation hooks", status: "provider_required", providerStatus: "api_key_required", apiPath: "/api/ai/translation" },
    ],
  },
  wallet: {
    code: "wallet",
    title: "Sabi Wallet",
    mobileRoute: "/wallet/home",
    apiBasePath: "/api/wallet",
    launchPhase: "launch_core",
    runtimeStatus: "provider_required",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["bank_or_payment_provider_sdk", "tokenized_card_provider", "ledger"],
    safetyHooks: [...commonSafetyHooks, "pci_dss_token_only", "aml_kyc_hold", "wallet_risk_check"],
    historyStreams: ["wallet_balance", "wallet_transaction", "wallet_security_alert"],
    capabilities: [
      { id: "balance", title: "Real balance", status: "provider_required", providerStatus: "contract_required", apiPath: "/api/wallet/status" },
      { id: "qr_payment", title: "QR payment execution", status: "foundation_ready", providerStatus: "contract_required", apiPath: "/api/v2/qr" },
      { id: "virtual_cards", title: "Virtual card token-only foundation", status: "foundation_ready", providerStatus: "contract_required", apiPath: "/api/v2/qr/virtual-card" },
    ],
  },
  qr: {
    code: "qr",
    title: "QR Center",
    mobileRoute: "/qr",
    apiBasePath: "/api/v2/qr",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["module_executor_mapping", "wallet_provider_for_money_movement"],
    safetyHooks: [...commonSafetyHooks, "strict_payload_validation", "verified_session_user_id"],
    historyStreams: ["qr_scan", "qr_confirm", "qr_execute", "qr_admin_review"],
    capabilities: [
      { id: "scan_confirm_execute", title: "Strict scan → confirm → execute", status: "foundation_ready", providerStatus: "provider_required", apiPath: "/api/v2/qr" },
      { id: "result_status", title: "Honest result/status flow", status: "foundation_ready", providerStatus: "not_required", route: "/qr/result" },
    ],
  },
  ai: {
    code: "ai",
    title: "Sabi AI",
    mobileRoute: "/ai",
    apiBasePath: "/api/ai",
    launchPhase: "launch_core",
    runtimeStatus: "provider_required",
    providerStatus: "api_key_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["llm_provider", "stt_provider", "tts_provider", "translation_provider"],
    safetyHooks: [...commonSafetyHooks, "ai_safety_admin", "provider_not_configured_state"],
    historyStreams: ["ai_chat", "ai_voice", "ai_translation", "ai_alert"],
    capabilities: [
      { id: "basic_text_chat", title: "Basic AI chat", status: "provider_required", providerStatus: "api_key_required", apiPath: "/api/ai" },
      { id: "voice_control", title: "SABI wake-word voice control", status: "foundation_ready", providerStatus: "api_key_required", route: "/ai/voice-control" },
      { id: "call_translation", title: "Realtime call translation", status: "provider_required", providerStatus: "api_key_required", apiPath: "/api/ai/translation/realtime" },
    ],
  },
  gallery: {
    code: "gallery",
    title: "Gallery",
    mobileRoute: "/gallery",
    apiBasePath: "/api/v2/gallery",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["media_upload_storage_before_cloud_sync"],
    safetyHooks: ["public_photo_explicit_mark_required", "private_by_default", "media_report"],
    historyStreams: ["gallery_upload", "gallery_public_toggle", "gallery_share"],
    capabilities: [
      { id: "private_gallery", title: "Private media storage", status: "foundation_ready", providerStatus: "not_required", route: "/gallery" },
      { id: "public_gallery", title: "Explicit public photo subset", status: "foundation_ready", providerStatus: "not_required", route: "/profile/photos" },
      { id: "ai_media", title: "AI media analysis hooks", status: "provider_required", providerStatus: "api_key_required", apiPath: "/api/ai/media" },
    ],
  },
  network_game_center: {
    code: "network_game_center",
    title: "Network Game Center",
    mobileRoute: "/network-game-center",
    apiBasePath: "/api/v2/games",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: false,
    adminReviewRequired: true,
    requiredProviders: ["game_realtime_backend", "coin_wallet_for_rewards"],
    safetyHooks: [...commonSafetyHooks, "reward_not_income_until_rules", "anti_abuse"],
    historyStreams: ["game_session", "game_reward", "leaderboard"],
    capabilities: [
      { id: "network_lobby", title: "Network lobby", status: "foundation_ready", providerStatus: "provider_required", route: "/network-game-center" },
      { id: "coin_rewards", title: "Coin reward hooks", status: "provider_required", providerStatus: "contract_required" },
    ],
  },
  marketplace: {
    code: "marketplace",
    title: "Marketplace",
    mobileRoute: "/marketplace",
    apiBasePath: "/api/v2/marketplace",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["catalog_db", "seller_kyb", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "seller_review", "product_moderation", "order_dispute"],
    historyStreams: ["product", "order", "payment", "dispute"],
    capabilities: [
      { id: "catalog", title: "Product catalog foundation", status: "foundation_ready", providerStatus: "contract_required", route: "/marketplace" },
      { id: "orders", title: "Order lifecycle", status: "provider_required", providerStatus: "contract_required" },
    ],
  },
  hotels: {
    code: "hotels",
    title: "Hotels",
    mobileRoute: "/hotels",
    apiBasePath: "/api/v2/hotels",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["hotel_inventory_provider", "booking_provider_or_partner_contract", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "booking_policy", "refund_policy", "partner_kyb"],
    historyStreams: ["hotel_search", "booking", "qr_checkin", "refund"],
    capabilities: [
      { id: "hotel_search", title: "Hotel search and map foundation", status: "provider_required", providerStatus: "contract_required", route: "/hotels" },
      { id: "booking", title: "Booking confirmation", status: "provider_required", providerStatus: "contract_required" },
      { id: "qr_checkin", title: "QR check-in", status: "foundation_ready", providerStatus: "contract_required", route: "/qr" },
    ],
  },
  taxi: {
    code: "taxi",
    title: "Taxi",
    mobileRoute: "/taxi",
    apiBasePath: "/api/v2/taxi",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["maps_geocoding", "driver_app", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "taxi_delivery_complaint_escalation", "serious_violation_hold"],
    historyStreams: ["ride_request", "ride_status", "driver_rating", "complaint"],
    capabilities: [
      { id: "ride_request", title: "Ride request foundation", status: "provider_required", providerStatus: "contract_required", route: "/taxi" },
      { id: "complaints", title: "Symmetric complaint restrictions", status: "foundation_ready", providerStatus: "not_required" },
    ],
  },
  supermarket: {
    code: "supermarket",
    title: "Supermarket",
    mobileRoute: "/supermarket",
    apiBasePath: "/api/v2/supermarket",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["store_catalog", "delivery_fleet", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "store_kyb", "courier_safety", "refund_review"],
    historyStreams: ["supermarket_order", "delivery_status", "refund"],
    capabilities: [
      { id: "catalog", title: "Supermarket catalog", status: "foundation_ready", providerStatus: "contract_required", route: "/supermarket" },
      { id: "delivery", title: "Delivery routing", status: "provider_required", providerStatus: "contract_required" },
    ],
  },
  food_delivery: {
    code: "food_delivery",
    title: "Food Delivery",
    mobileRoute: "/food-delivery",
    apiBasePath: "/api/v2/food-delivery",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["restaurant_catalog", "courier_runtime", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "restaurant_kyb", "courier_safety", "complaint_escalation"],
    historyStreams: ["food_order", "restaurant_status", "delivery_status"],
    capabilities: [
      { id: "restaurant_catalog", title: "Restaurants and cafes", status: "foundation_ready", providerStatus: "contract_required", route: "/food-delivery" },
      { id: "courier_delivery", title: "Courier delivery", status: "provider_required", providerStatus: "contract_required" },
    ],
  },
  wholesale_market: {
    code: "wholesale_market",
    title: "Wholesale Market",
    mobileRoute: "/wholesale-market",
    apiBasePath: "/api/v2/wholesale-market",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["b2b_catalog", "seller_kyb", "logistics_provider", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "b2b_seller_review", "bulk_order_dispute", "kyb_required"],
    historyStreams: ["b2b_offer", "bulk_order", "invoice", "logistics"],
    capabilities: [
      { id: "b2b_catalog", title: "Domestic B2B wholesale catalog", status: "foundation_ready", providerStatus: "contract_required", route: "/wholesale-market" },
      { id: "bulk_invoice", title: "Bulk invoice and QR payment", status: "foundation_ready", providerStatus: "contract_required", route: "/qr/business" },
    ],
  },
  stream: {
    code: "stream",
    title: "Stream",
    mobileRoute: "/stream",
    apiBasePath: "/api/v2/stream",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["live_streaming_provider", "moderation_provider", "coin_wallet"],
    safetyHooks: [...commonSafetyHooks, "stream_18_plus_escalation", "gift_income_monthly_release"],
    historyStreams: ["stream_session", "gift", "moderation_event"],
    capabilities: [
      { id: "live", title: "Live streaming foundation", status: "provider_required", providerStatus: "provider_required", route: "/stream" },
      { id: "moderation", title: "18+ restriction escalation", status: "foundation_ready", providerStatus: "provider_required" },
    ],
  },
  delivery: {
    code: "delivery",
    title: "Delivery",
    mobileRoute: "/delivery",
    apiBasePath: "/api/v2/delivery",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["courier_runtime", "maps_geocoding", "wallet_payment_provider"],
    safetyHooks: [...commonSafetyHooks, "taxi_delivery_complaint_escalation", "serious_violation_hold"],
    historyStreams: ["delivery_request", "delivery_tracking", "complaint"],
    capabilities: [
      { id: "courier_runtime", title: "Courier runtime", status: "provider_required", providerStatus: "contract_required", route: "/delivery" },
    ],
  },
  business: {
    code: "business",
    title: "Business",
    mobileRoute: "/business",
    apiBasePath: "/api/v2/business",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["premium_gate", "business_kyb", "business_wallet_later"],
    safetyHooks: [...commonSafetyHooks, "premium_required", "business_routing_layer"],
    historyStreams: ["business_access", "business_invoice", "bot_income_route"],
    capabilities: [
      { id: "business_entry", title: "Simple business entry only", status: "foundation_ready", providerStatus: "contract_required", route: "/business" },
    ],
  },
  merchant: {
    code: "merchant",
    title: "Merchant",
    mobileRoute: "/merchant",
    apiBasePath: "/api/v2/merchant",
    launchPhase: "postlaunch_update",
    runtimeStatus: "foundation_ready",
    providerStatus: "contract_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: true,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["merchant_kyb", "wallet_payment_provider", "business_wallet_later"],
    safetyHooks: [...commonSafetyHooks, "merchant_payment_review", "business_routing_layer"],
    historyStreams: ["merchant_order", "merchant_qr_payment", "settlement"],
    capabilities: [
      { id: "merchant_qr", title: "Merchant QR order foundation", status: "foundation_ready", providerStatus: "contract_required", route: "/qr/merchant" },
    ],
  },
  notifications: {
    code: "notifications",
    title: "Notifications",
    mobileRoute: "/notifications",
    apiBasePath: "/api/v2/notifications",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: false,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: ["firebase_push_or_native_push_before_release"],
    safetyHooks: ["missed_calls", "messages", "events", "ai_alerts", "wallet_security", "qr_security"],
    historyStreams: ["notification", "push_delivery", "notification_read"],
    capabilities: [
      { id: "missed_calls", title: "Missed call alerts", status: "foundation_ready", providerStatus: "provider_required" },
      { id: "messages", title: "Message alerts", status: "foundation_ready", providerStatus: "provider_required" },
      { id: "ai_alerts", title: "AI alerts", status: "foundation_ready", providerStatus: "provider_required" },
    ],
  },
  events: {
    code: "events",
    title: "Events",
    mobileRoute: "/events",
    apiBasePath: "/api/v2/events",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "not_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: [],
    safetyHooks: ["event_reminder", "calendar_hook_later"],
    historyStreams: ["event", "reminder", "attendance_qr"],
    capabilities: [
      { id: "event_reminder", title: "Event reminders", status: "foundation_ready", providerStatus: "not_required", route: "/events" },
    ],
  },
  documents: {
    code: "documents",
    title: "Documents",
    mobileRoute: "/documents",
    apiBasePath: "/api/v2/documents",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: true,
    aiHooksEnabled: true,
    adminReviewRequired: true,
    requiredProviders: ["secure_file_storage", "ocr_provider_later"],
    safetyHooks: ["private_by_default", "ai_ocr_provider_not_configured_state"],
    historyStreams: ["document_upload", "document_share", "document_qr"],
    capabilities: [
      { id: "secure_files", title: "Secure file foundation", status: "foundation_ready", providerStatus: "provider_required", route: "/documents" },
    ],
  },
  wifi_cast: {
    code: "wifi_cast",
    title: "Wi‑Fi Cast",
    mobileRoute: "/wifi-cast",
    apiBasePath: "/api/v2/wifi-cast",
    launchPhase: "launch_core",
    runtimeStatus: "foundation_ready",
    providerStatus: "provider_required",
    enabledOnHome: true,
    fakeDataAllowed: false,
    paymentsRouteThroughWallet: false,
    qrEnabled: true,
    notificationsEnabled: false,
    aiHooksEnabled: true,
    adminReviewRequired: false,
    requiredProviders: ["native_cast_module"],
    safetyHooks: ["local_network_permission", "no_background_capture_without_permission"],
    historyStreams: ["cast_session"],
    capabilities: [
      { id: "cast_entry", title: "Local cast entry", status: "provider_required", providerStatus: "provider_required", route: "/wifi-cast" },
    ],
  },
};

export const SABI_PROGRAM_ORDER: SabiProgramCode[] = [
  "home",
  "messenger",
  "wallet",
  "qr",
  "ai",
  "gallery",
  "network_game_center",
  "marketplace",
  "hotels",
  "taxi",
  "supermarket",
  "food_delivery",
  "wholesale_market",
  "stream",
  "delivery",
  "business",
  "merchant",
  "notifications",
  "events",
  "documents",
  "wifi_cast",
];

export function isSabiProgramCode(value: string): value is SabiProgramCode {
  return Object.prototype.hasOwnProperty.call(SABI_PROGRAM_FOUNDATIONS, value);
}
