export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_VERSION = 'TAXI-COMPETITOR-SOURCE-CONFIG-008E';

export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_JSON_ENV = 'SABI_TAXI_COMPETITOR_PRICE_SOURCE_CONFIG_008E';
export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_URLS_ENV = 'SABI_TAXI_COMPETITOR_PRICE_FEED_URLS';
export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_URL_ENV = 'SABI_TAXI_COMPETITOR_PRICE_FEED_URL';

export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_ENDPOINTS = [
  'GET /api/admin/taxi/tariffs/008e/competitor-source-config/readiness',
  'GET /api/admin/taxi/tariffs/008e/competitor-source-config',
] as const;

export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_PROVIDERS = ['yandex', 'uber'] as const;
export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_MAX_SOURCES = 24;

export const TAXI_COMPETITOR_SOURCE_CONFIG_008E_ENV_NAMES = [
  TAXI_COMPETITOR_SOURCE_CONFIG_008E_JSON_ENV,
  TAXI_COMPETITOR_SOURCE_CONFIG_008E_URLS_ENV,
  TAXI_COMPETITOR_SOURCE_CONFIG_008E_URL_ENV,
] as const;
