import type {
  HomeAccountSnapshot,
  HomeDockItem,
  HomeLayoutDefaults,
  HomeQuickAction,
  HomeThemeState,
  HomeWidgetDefinition,
} from "./home.types";

export const DEFAULT_HOME_WIDGETS: readonly HomeWidgetDefinition[] = [
  {
    id: "home-account-snapshot",
    moduleId: "profile",
    title: "Account snapshot",
    description: "Identity, premium, unread counters and balance preview for the home header.",
    kind: "summary",
    size: "wide",
    route: "/profile",
    iconKey: "user",
    defaultVisible: true,
    pinnedByDefault: true,
    priority: 1,
  },
  {
    id: "home-messenger-status",
    moduleId: "messenger",
    title: "Messenger",
    description: "Unread chats, realtime status and fast entry to dialogs.",
    kind: "status",
    size: "medium",
    route: "/messenger",
    iconKey: "message-circle",
    defaultVisible: true,
    pinnedByDefault: true,
    priority: 2,
  },
  {
    id: "home-wallet-balance",
    moduleId: "wallet",
    title: "Wallet",
    description: "Personal, card and coin balance preview on the home screen.",
    kind: "balance",
    size: "large",
    route: "/wallet/home",
    iconKey: "wallet",
    defaultVisible: true,
    pinnedByDefault: true,
    priority: 3,
  },
  {
    id: "home-notification-center",
    moduleId: "notifications",
    title: "Notifications",
    description: "Unified project notifications grouped by module and priority.",
    kind: "feed",
    size: "large",
    route: "/notifications",
    iconKey: "bell",
    defaultVisible: true,
    priority: 4,
  },
  {
    id: "home-qr-shortcut",
    moduleId: "qr",
    title: "Universal QR",
    description: "Wallet, messenger, business, attendance and public-profile QR entry point.",
    kind: "shortcut",
    size: "medium",
    route: "/qr",
    iconKey: "qr-code",
    defaultVisible: true,
    priority: 5,
  },
  {
    id: "home-ai-assistant",
    moduleId: "ai",
    title: "AI assistant",
    description: "Assistant state, premium translation features and quick smart actions.",
    kind: "summary",
    size: "medium",
    route: "/profile/ai",
    iconKey: "sparkles",
    defaultVisible: true,
    premiumRequired: true,
    featureFlagKey: "ai.realtime.translation.premium",
    priority: 6,
  },
  {
    id: "home-marketplace-entry",
    moduleId: "marketplace",
    title: "Marketplace",
    description: "Store and order entry point prepared for future domain connection.",
    kind: "shortcut",
    size: "medium",
    route: "/marketplace",
    iconKey: "shopping-bag",
    defaultVisible: false,
    featureFlagKey: "home.widgets.future-domains",
    priority: 10,
  },
  {
    id: "home-stream-entry",
    moduleId: "stream",
    title: "Stream",
    description: "Live rooms and creator entry point prepared for stream domain wiring.",
    kind: "shortcut",
    size: "medium",
    route: "/stream",
    iconKey: "broadcast",
    defaultVisible: false,
    featureFlagKey: "home.widgets.future-domains",
    priority: 11,
  },
  {
    id: "home-games-entry",
    moduleId: "games",
    title: "Game center",
    description: "Game center entry point and future reward surface.",
    kind: "shortcut",
    size: "medium",
    route: "/games",
    iconKey: "gamepad-2",
    defaultVisible: false,
    featureFlagKey: "home.widgets.future-domains",
    priority: 12,
  },
  {
    id: "home-gallery-entry",
    moduleId: "gallery",
    title: "Gallery",
    description: "Profile/public media index and attachment surface.",
    kind: "shortcut",
    size: "medium",
    route: "/gallery",
    iconKey: "images",
    defaultVisible: false,
    featureFlagKey: "home.widgets.future-domains",
    priority: 13,
  },
];

export function createDefaultDockItems(): HomeDockItem[] {
  return [
    {
      id: "dock-messenger",
      kind: "module",
      label: "Messenger",
      iconKey: "message-circle",
      moduleId: "messenger",
      route: "/messenger",
      order: 1,
    },
    {
      id: "dock-wallet",
      kind: "module",
      label: "Wallet",
      iconKey: "wallet",
      moduleId: "wallet",
      route: "/wallet/home",
      order: 2,
    },
    {
      id: "dock-qr",
      kind: "module",
      label: "QR",
      iconKey: "qr-code",
      moduleId: "qr",
      route: "/qr",
      order: 3,
    },
    {
      id: "dock-ai",
      kind: "module",
      label: "AI",
      iconKey: "sparkles",
      moduleId: "ai",
      route: "/profile/ai",
      premiumRequired: true,
      featureFlagKey: "ai.realtime.translation.premium",
      order: 4,
    },
    {
      id: "dock-profile",
      kind: "module",
      label: "Profile",
      iconKey: "user",
      moduleId: "profile",
      route: "/profile",
      order: 5,
    },
  ];
}

export function createDefaultQuickActions(): HomeQuickAction[] {
  return [
    {
      id: "quick-transfer",
      label: "Transfer",
      iconKey: "arrow-right-left",
      route: "/wallet/transfer",
      moduleId: "wallet",
      order: 1,
    },
    {
      id: "quick-topup",
      label: "Top up",
      iconKey: "plus-circle",
      route: "/wallet/topup",
      moduleId: "wallet",
      order: 2,
    },
    {
      id: "quick-new-chat",
      label: "New chat",
      iconKey: "message-square-plus",
      route: "/messenger/contacts",
      moduleId: "messenger",
      order: 3,
    },
    {
      id: "quick-scan-qr",
      label: "Scan QR",
      iconKey: "scan-line",
      route: "/qr/scan",
      moduleId: "qr",
      order: 4,
    },
    {
      id: "quick-translate",
      label: "Translate",
      iconKey: "languages",
      route: "/profile/ai",
      moduleId: "ai",
      premiumRequired: true,
      featureFlagKey: "ai.realtime.translation.premium",
      order: 5,
    },
  ];
}

export function createDefaultTheme(): HomeThemeState {
  return {
    appearance: "system",
    accentColor: "#7C5CFF",
    backgroundPreset: "sabi-default",
    wallpaperUrl: null,
    glassMode: true,
  };
}

export function createDefaultAccountSnapshot(userId: string): HomeAccountSnapshot {
  return {
    userId,
    displayName: "Sabi User",
    username: null,
    avatarUrl: null,
    verified: false,
    premiumPlan: "FREE",
    unreadCount: 0,
    balances: {
      localBalance: "0.00",
      coinBalance: "0.00",
      cryptoBalance: "0.00",
    },
  };
}

export function createHomeLayoutDefaults(): HomeLayoutDefaults {
  return {
    dockItems: createDefaultDockItems(),
    quickActions: createDefaultQuickActions(),
    theme: createDefaultTheme(),
  };
}
