import type {
  SabiAiDomainBrain254B,
  SabiAiLearningSafetyLocks254B,
  SabiAiUnifiedBrain254B,
} from './sabiAiDomainBrain254B.types';

export const sabiAiDomainBrains254B: readonly SabiAiDomainBrain254B[] = [
  {
    id: 'legal_brain',
    name: 'Legal knowledge brain',
    readiness: 100,
    purpose: 'Legal rules, user rights, company policy, KYC/AML, privacy, evidence, disputes and lawful escalation.',
    helpsPeopleWith: ['explain rules', 'guide lawful requests', 'prepare allowed complaint or appeal flow'],
    controls: ['legal risk', 'policy violation', 'evidence preservation', 'Owner/legal review gate'],
    forbiddenNow: ['no final legal decision', 'no public evidence exposure'],
  },
  {
    id: 'crime_compliance_brain',
    name: 'Crime, fraud and compliance brain',
    readiness: 100,
    purpose: 'Detect fraud, corruption, AML risk, violent/criminal signals, prohibited content and organized abuse patterns.',
    helpsPeopleWith: ['protect victims', 'reduce fraud damage', 'prepare private Owner reports'],
    controls: ['red priority evidence', 'silent suspect handling', 'financial/risky feature safety gate'],
    forbiddenNow: ['no autonomous punishment', 'no suspect disclosure', 'no public accusation'],
  },
  {
    id: 'taxi_brain',
    name: 'Taxi control and help brain',
    readiness: 100,
    purpose: 'Help passengers, drivers, agents and Taxi staff while monitoring safety, fraud, complaints and lost property.',
    helpsPeopleWith: ['ride help', 'driver onboarding', 'agent contact guidance', 'lost property support'],
    controls: ['driver review support', 'complaint analysis', 'fraud ride detection', 'daily Owner report'],
    forbiddenNow: ['no direct approval', 'no balance mutation', 'no payout', 'no separate Taxi wallet'],
  },
  {
    id: 'messenger_brain',
    name: 'Messenger control and help brain',
    readiness: 100,
    purpose: 'Help users communicate safely and monitor abuse, scams, coercion, illegal content and spam.',
    helpsPeopleWith: ['chat help', 'safe communication', 'abuse report guidance', 'translation by request'],
    controls: ['spam risk', 'scam risk', 'coercion signal', 'private evidence pack'],
    forbiddenNow: ['no private message access without gate', 'no public exposure', 'no suspect warning'],
  },
  {
    id: 'profile_account_brain',
    name: 'Profile, account and KYC help brain',
    readiness: 100,
    purpose: 'Help users with profile, account, verification, privacy, security, language and recovery.',
    helpsPeopleWith: ['profile setup', 'verification explanation', 'account security', 'privacy settings'],
    controls: ['duplicate identity risk', 'fake account risk', 'KYC/KYB support', 'account takeover risk'],
    forbiddenNow: ['no fake verification', 'no KYC bypass', 'no sensitive data exposure'],
  },
  {
    id: 'wallet_finance_brain',
    name: 'Wallet and finance brain',
    readiness: 100,
    purpose: 'Help with wallet understanding, statements, OTP/3DS, finance safety and restricted money workflows.',
    helpsPeopleWith: ['statement explanation', 'OTP/3DS explanation', 'finance support request'],
    controls: ['fraud risk', 'AML risk', 'restricted access', 'Owner/finance gate'],
    forbiddenNow: ['no direct money movement', 'no payout release', 'no provider settings', 'no secret access'],
  },
  {
    id: 'stream_brain',
    name: 'Stream creative and safety brain',
    readiness: 100,
    purpose: 'Prepare original safe Stream content and control abuse, copyright risk, minors safety and live gates.',
    helpsPeopleWith: ['creator guidance', 'safe content advice', 'original script planning'],
    controls: ['copyright safety', 'prohibited content risk', 'live broadcast gate', 'Owner review'],
    forbiddenNow: ['no live broadcast', 'no auto-post', 'no copied protected content'],
  },
  {
    id: 'marketplace_business_brain',
    name: 'Marketplace, merchant and business brain',
    readiness: 100,
    purpose: 'Help future merchants/business accounts with limited cabinet, documents, reports, orders and support requests.',
    helpsPeopleWith: ['merchant onboarding', 'own report explanation', 'own order status help'],
    controls: ['merchant KYB risk', 'fake business risk', 'restricted finance access'],
    forbiddenNow: ['no internal Admin access', 'no global finance', 'no payout approval'],
  },
  {
    id: 'public_ecology_transparency_brain',
    name: 'Public, ecology and transparency brain',
    readiness: 100,
    purpose: 'Help with public programs, ecology projects, transparency voting, tenders, evidence and Sabi own-funds rules.',
    helpsPeopleWith: ['project submission guidance', 'voting explanation', 'tender transparency'],
    controls: ['one verified user one vote', 'no donations', 'no investments', 'anti-corruption checks'],
    forbiddenNow: ['no donation wording', 'no investment wording', 'no personal data public exposure'],
  },
  {
    id: 'future_programs_brain',
    name: 'Future programs brain',
    readiness: 100,
    purpose: 'Prepare learning boundaries for hotels, supermarket, games, QR, gallery, camera, translation and presentation.',
    helpsPeopleWith: ['program explanation', 'safe onboarding', 'support routing'],
    controls: ['program fraud signals', 'abuse detection', 'privacy checks'],
    forbiddenNow: ['no provider activation', 'no commercial launch', 'no payment movement'],
  },
] as const;

export const sabiAiUnifiedBrain254B: SabiAiUnifiedBrain254B = {
  oneSabiAiBrainAboveDomains: true,
  domainsRemainSeparatedForAccuracy: true,
  sharedOwnerRulesApplyEverywhere: true,
  sharedCrimeControlAppliesEverywhere: true,
  sharedHelpPeopleMissionAppliesEverywhere: true,
  sharedEvidencePolicyAppliesEverywhere: true,
  sharedFinalActionGatesApplyEverywhere: true,
} as const;

export const sabiAiLearningSafetyLocks254B: SabiAiLearningSafetyLocks254B = {
  localCodeArtifactOnly: true,
  domainLearningMappedNow: true,
  unifiedBrainMappedNow: true,
  noModelProviderTrainingNow: true,
  noAiProviderCallNow: true,
  noNetworkCallNow: true,
  noDbReadNow: true,
  noDbWriteNow: true,
  noRuntimeMountNow: true,
  noDeploymentNow: true,
  noPaymentNow: true,
  noPayoutNow: true,
  noProviderActivationNow: true,
  noSecretReadWriteNow: true,
  noRealUserMonitoringNow: true,
  noLawEnforcementSendNow: true,
  noAccountBlockNow: true,
  ownerApprovalRequiredForProviderTraining: true,
  ownerApprovalRequiredForDbPersistence: true,
  ownerApprovalRequiredForRuntimeLearningService: true,
  ownerApprovalRequiredForLiveMonitoring: true,
  ownerApprovalRequiredForLegalEscalation: true,
} as const;
