import type {
  SabiAiStreamDraftExpansion252H,
  SabiAiStreamDraftExpansionQueue252H,
  SabiAiStreamSafetyLocks252H,
} from './sabiAiStreamDraftExpansion252H.types';

export const sabiAiStreamDraftExpansionSamples252H: readonly SabiAiStreamDraftExpansion252H[] = [
  {
    expansionId: '252h-ru-love-nature-values-expand-001',
    sourceSeedId: '252g-ru-love-nature-values-001',
    languageCode: 'ru',
    cultureContext: 'respectful_ru_speaking_general_audience',
    theme: 'love_nature_human_values',
    titleWorkingDraft: 'Тихий свет природы',
    coreMessage: 'любовь к природе, доброта, уважение и спокойная сила человека',
    songDirectionPlan: 'warm calm cinematic mood, simple original melody direction, no full lyrics',
    lyricDirectionPlan: 'outline only: nature light, kindness, human respect, peaceful conclusion',
    melodyDirectionPlan: 'soft original piano/string direction, no generated audio',
    sceneOutline: 'dawn over river, safe family nature scenes, gentle educational text, peaceful ending',
    editTimelineOutline: 'intro_dawn_middle_values_climax_kindness_outro_reflection',
    thumbnailDirection: 'original sunrise and soft nature symbol',
    subtitleDirection: 'clear safe Russian subtitles after future review',
    youthSafetyNotes: 'encourage kindness, study, real friendship and respectful communication',
    cultureRespectNotes: 'avoid mockery, avoid stereotype abuse, keep warm respectful tone',
    originalityDeclaration: 'original_draft_plan_only_no_copy',
    safetyReviewStatus: 'pending',
    ownerReviewStatus: 'pending',
    futureUseAllowedNow: false,
  },
  {
    expansionId: '252h-en-learning-respect-expand-002',
    sourceSeedId: '252g-en-learning-respect-002',
    languageCode: 'en',
    cultureContext: 'global_youth_safe_respectful_tone',
    theme: 'learning_respect_real_human_communication',
    titleWorkingDraft: 'Talk to the World Kindly',
    coreMessage: 'learning languages, respecting people and returning to real human communication',
    songDirectionPlan: 'light positive educational pop direction, no audio generation',
    lyricDirectionPlan: 'outline only: question, learning, respect, real-world conversation',
    melodyDirectionPlan: 'bright original rhythm direction, no generated voice',
    sceneOutline: 'notebooks, city lights, friendly dialogue, safe community learning',
    editTimelineOutline: 'intro_question_middle_learning_climax_respect_outro_real_world',
    thumbnailDirection: 'original notebook and warm city light symbol',
    subtitleDirection: 'safe English subtitles after future review',
    youthSafetyNotes: 'discourage isolation, encourage real respectful communication',
    cultureRespectNotes: 'global respectful tone, no cultural arrogance',
    originalityDeclaration: 'original_draft_plan_only_no_copy',
    safetyReviewStatus: 'pending',
    ownerReviewStatus: 'pending',
    futureUseAllowedNow: false,
  },
] as const;

export const sabiAiStreamDraftExpansionQueue252H: SabiAiStreamDraftExpansionQueue252H = {
  queueStates: [
    'seed_selected',
    'structured_draft_plan_created',
    'language_culture_review_pending',
    'originality_review_pending',
    'youth_safety_review_pending',
    'owner_review_pending',
    'approved_for_future_draft_gallery',
    'needs_revision',
    'rejected',
    'red_priority_hold',
  ],
} as const;

export const sabiAiStreamSafetyLocks252H: SabiAiStreamSafetyLocks252H = {
  localCodeArtifactOnly: true,
  noLiveBroadcastNow: true,
  noRuntimeMountNow: true,
  noAdminRouteConnectionNow: true,
  noRuntimeGenerationNow: true,
  noRuntimePostNow: true,
  noProviderCallNow: true,
  noProtectedConfigReadWriteNow: true,
  noDbMutationNow: true,
  noPaymentNow: true,
  noRestrictedLiveActionNow: true,
  finalActionsExecutedNow: false,
  ownerApprovalRequiredForFutureDraftExpansion: true,
  ownerApprovalRequiredForPublicPost: true,
  ownerApprovalRequiredForLiveBroadcast: true,
} as const;
