import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAdminPanelPlanItem,
  TaxiDbSchemaPlanItem,
  TaxiNextPhaseHandoffItem,
  TaxiNextPhaseHandoffVersion,
  TaxiRoutePlanItem,
} from './taxiNextPhaseHandoff.types';

export const TAXI_NEXT_PHASE_HANDOFF_VERSION: TaxiNextPhaseHandoffVersion = 'TAXI-BACKEND-FOUNDATION-001M';

export const TAXI_NEXT_PHASE_HANDOFF_ITEMS: readonly TaxiNextPhaseHandoffItem[] = [
  {
    owner: 'foundation',
    stage: 'contract_ready_now',
    title: 'Foundation remains the single source of Taxi truth.',
    deliverable: 'Contracts for AI daily reports, complaint review, approval gates, Admin handoff and kernel summaries stay safe-disabled.',
    dependsOn: ['TAXI-BACKEND-FOUNDATION-001A-001L'],
    canExecuteNow: true,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'admin_ui',
    stage: 'admin_ui_plan_ready_now',
    title: 'Admin UI can be added as review-only panels using the same foundation contracts.',
    deliverable: 'Readiness, daily AI report, complaint queue, action inbox, approval gates and schema-plan panels.',
    dependsOn: ['taxiAdminTaxiReadiness', 'taxiNextPhaseHandoff'],
    canExecuteNow: true,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'db_schema',
    stage: 'schema_plan_only_now',
    title: 'DB schema is plan-only until a separate exact schema/migration approval.',
    deliverable: 'Model plan for rides, complaints, AI reports, evidence, decisions, appeals, leagues and reward freezes.',
    dependsOn: ['db_schema_review', 'migration_review', 'rollback_plan_review'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'api_routes',
    stage: 'route_plan_only_now',
    title: 'Runtime/API routes are planned but not mounted.',
    deliverable: 'Admin read routes, client kernel boundary summary route and future runtime trip routes remain locked.',
    dependsOn: ['owner_exact_approval', 'security_review', 'admin_permission_review', 'runtime_smoke_review'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'scheduler',
    stage: 'blocked_until_exact_approval',
    title: 'Daily Sabi AI scheduler cannot run yet.',
    deliverable: 'Scheduler must later run every country/day complaint report only after DB read/write and AI provider approval.',
    dependsOn: ['owner_exact_approval', 'db_read_gate', 'ai_provider_gate', 'runtime_smoke_review'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'client_boundary',
    stage: 'contract_ready_now',
    title: 'Client app remains kernel-only.',
    deliverable: 'Mobile receives redacted summary after Admin locked decisions; no raw evidence, provider, payment, payout or direct backend runtime.',
    dependsOn: ['client_boundary_facade', 'admin_locked_decision'],
    canExecuteNow: true,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'sabi_ai',
    stage: 'blocked_until_exact_approval',
    title: 'Sabi AI runtime is required later, but not activated now.',
    deliverable: 'AI must check every complaint every day and produce full country/day reports when runtime is approved.',
    dependsOn: ['ai_provider_reference', 'db_read_gate', 'evidence_redaction_gate'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'provider_dispatch',
    stage: 'blocked_until_exact_approval',
    title: 'Dispatch/map/route providers are disabled now.',
    deliverable: 'Provider reference labels, route quote, driver matching and live trip states require exact approval.',
    dependsOn: ['provider_reference_label_gate', 'runtime_route_gate', 'location_privacy_gate'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'wallet_payment_payout',
    stage: 'blocked_until_exact_approval',
    title: 'Wallet, payment, commission debit and payout are disabled now.',
    deliverable: 'Driver balance top-up, Admin-configured commission debit, trip charge, tips, prize release and payouts require ledger/provider approvals.',
    dependsOn: ['wallet_ledger_gate', 'payment_provider_gate', 'payout_provider_gate', 'legal_finance_review'],
    canExecuteNow: false,
    exactApprovalRequiredForRuntime: true,
    adminCompatibleFromFoundation: true,
    clientAppMustUseKernel: true,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_DB_SCHEMA_PLAN: readonly TaxiDbSchemaPlanItem[] = [
  {
    modelId: 'taxi_ride',
    title: 'TaxiRide',
    purpose: 'Stores verified ride lifecycle state after future runtime approval; never creates fake completed trips.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_ride_route_snapshot',
    title: 'TaxiRideRouteSnapshot',
    purpose: 'Stores provider-backed route, ETA, traffic, radar/camera and speed summary after route provider approval.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_driver_balance_ledger',
    title: 'TaxiDriverBalanceLedger',
    purpose: 'Future driver reserve/top-up ledger; no fake top-up and no balance mutation now.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_commission_ledger',
    title: 'TaxiCommissionLedger',
    purpose: 'Future Admin-configured commission debit after verified backend trip completion only.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_daily_ai_report',
    title: 'TaxiDailyAiReport',
    purpose: 'Full country/day Sabi AI report; all complaints must be checked before close.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_complaint_case',
    title: 'TaxiComplaintCase',
    purpose: 'Driver/rider complaint case and daily complaint tier state before any penalty.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_evidence_bundle',
    title: 'TaxiEvidenceBundle',
    purpose: 'Admin/foundation-only evidence bundle for chat, call, route and dispute signals.',
    storesRawEvidence: true,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_admin_decision',
    title: 'TaxiAdminDecision',
    purpose: 'Locked Admin decision after Sabi AI evidence and appeal/explanation windows.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_appeal_explanation',
    title: 'TaxiAppealExplanation',
    purpose: 'Participant explanation and appeal SLA before hard block or prize disqualification.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_country_league_season',
    title: 'TaxiCountryLeagueSeason',
    purpose: 'Country-separated league season configuration owned by Admin.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_league_score_event',
    title: 'TaxiLeagueScoreEvent',
    purpose: 'Verified trip/stars/complaint score events; UI cannot create fake score events.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'taxi_reward_freeze_audit',
    title: 'TaxiRewardFreezeAudit',
    purpose: 'Reward freeze/release audit before any top-3 prize action; payout remains locked.',
    storesRawEvidence: false,
    visibleToMobile: false,
    requiresMigrationApproval: true,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_ROUTE_PLAN: readonly TaxiRoutePlanItem[] = [
  {
    routeId: 'admin_taxi_readiness_snapshot',
    method: 'GET',
    path: '/api/admin/taxi/readiness',
    audience: 'admin',
    title: 'Admin Taxi readiness snapshot route plan.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'admin_taxi_daily_ai_report_list',
    method: 'GET',
    path: '/api/admin/taxi/ai/daily-reports',
    audience: 'admin',
    title: 'Admin daily Sabi AI report list route plan.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'admin_taxi_complaint_review_queue',
    method: 'GET',
    path: '/api/admin/taxi/complaints/review-queue',
    audience: 'admin',
    title: 'Admin complaint review queue route plan.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'admin_taxi_action_inbox',
    method: 'GET',
    path: '/api/admin/taxi/action-inbox',
    audience: 'admin',
    title: 'Admin action inbox route plan.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'admin_taxi_approval_gate_snapshot',
    method: 'GET',
    path: '/api/admin/taxi/approval-gates',
    audience: 'admin',
    title: 'Admin approval gate snapshot route plan.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'mobile_taxi_kernel_summary',
    method: 'GET',
    path: '/api/taxi/kernel/summary',
    audience: 'client_boundary',
    title: 'Client kernel boundary-safe Taxi summary route plan; no raw evidence.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'driver_dispatch_gate_preview',
    method: 'GET',
    path: '/api/taxi/driver/dispatch-gate/preview',
    audience: 'client_boundary',
    title: 'Driver dispatch gate preview route plan through kernel only.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'taxi_runtime_trip_request_future',
    method: 'POST',
    path: '/api/taxi/trips/request',
    audience: 'runtime_future',
    title: 'Future trip request runtime route; cannot mount now.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
  {
    routeId: 'taxi_scheduler_daily_ai_report_future',
    method: 'POST',
    path: '/api/admin/taxi/ai/daily-reports/run',
    audience: 'runtime_future',
    title: 'Future daily AI report scheduler trigger; cannot run now.',
    mountedNow: false,
    runtimeEnabledNow: false,
    dbReadEnabledNow: false,
    dbWriteEnabledNow: false,
    exactApprovalRequiredBeforeMount: true,
    rawEvidenceAllowedToMobile: false,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_ADMIN_PANEL_PLAN: readonly TaxiAdminPanelPlanItem[] = [
  {
    panelId: 'taxi_readiness_overview_panel',
    title: 'Taxi readiness overview panel',
    sourceContract: 'getTaxiAdminCompatibilitySnapshot',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_daily_ai_report_panel',
    title: 'Daily Sabi AI report panel',
    sourceContract: 'getTaxiAiDailyReportSnapshot + getTaxiNextPhaseHandoffSnapshot',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_complaint_review_queue_panel',
    title: 'Complaint review queue panel',
    sourceContract: 'taxiAdminNotification + taxiAdminDashboard contracts',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_action_inbox_panel',
    title: 'Admin action inbox panel',
    sourceContract: 'taxiAdminNotificationRouteDescriptors',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_approval_gate_panel',
    title: 'Approval gates panel',
    sourceContract: 'getTaxiAdminApprovalGatesSnapshot',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_reward_freeze_panel',
    title: 'Reward freeze panel',
    sourceContract: 'daily report + approval gates + legal finance review locks',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_db_schema_plan_panel',
    title: 'DB schema plan panel',
    sourceContract: 'TAXI_DB_SCHEMA_PLAN',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_runtime_gate_panel',
    title: 'Runtime gate panel',
    sourceContract: 'TAXI_ROUTE_PLAN + final control anti-runtime guards',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'taxi_client_boundary_summary_panel',
    title: 'Client kernel boundary summary panel',
    sourceContract: 'client kernel boundary bridge + next phase handoff',
    usesFoundationContracts: true,
    canRenderAsReviewOnly: true,
    canExecuteRuntimeNow: false,
    canReadDbNow: false,
    canWriteDbNow: false,
    rawEvidenceAdminOnly: true,
    fakeSuccessBlocked: true,
  },
];

export const taxiNextPhaseHandoffRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/admin/taxi/next-phase-handoff/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin-compatible next phase handoff readiness contract for DB schema, routes, panels and execution gates.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/next-phase-handoff/db-schema-plan',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future DB schema plan read route; not mounted and no DB read/write now.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/next-phase-handoff/route-plan',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future route plan read route; not mounted and no runtime now.',
  },
];
