import type { SabiRelease245NReport } from './sabiRelease245N.types';

export const sabiRelease245NReport: SabiRelease245NReport = {
  "version": "SABI-RELEASE-245N-OFFICIAL-SITE-EMAIL-SMS-SERVER-AI-GOOGLE-CLOUD-FINAL-PREFLIGHT",
  "status": "passed",
  "approvalFlagRequired": "--i-approve-release-245n-official-site-email-sms-server-ai-google-cloud-final-owner-command-exact-phrase-final-execution-preflight-gate-static-check-report-acceptance-boundary-final-review",
  "approvalFlagProvided": true,
  "scope": "245N_final_static_preflight_only_no_live_execution",
  "createdAt": "2026-06-22T21:06:31.326Z",
  "officialDomain": "sabiai.app",
  "companyName": "SABI AI TECHNOLOGIES LIMITED",
  "registeredAddress": "128 City Road, London, England, EC1V 2NX, United Kingdom",
  "officialWebsiteMustWorkOnServer": true,
  "officialDomainEmailMustWork": true,
  "smsIsMandatoryForProgram": true,
  "smsWithoutItProgramDoesNotWork": true,
  "allCriticalLogicMustBeServerSide": true,
  "cloudRunCustomDomainMappingRequired": true,
  "officialSiteHttpsRequired": true,
  "officialSiteHealthCheckRequired": true,
  "emailDnsAuthenticationRequired": true,
  "mx": true,
  "spf": true,
  "dkim": true,
  "dmarc": true,
  "firebasePhoneAuthOrApprovedSmsProviderRequired": true,
  "phoneNumberSignInMustBeEnabledBeforeLiveUse": true,
  "smsServerBoundaryRequired": true,
  "liveSmsStillLockedUntilExactOwnerApproval": true,
  "serverSabiAiPersonalityTrainingMustFollowPlan": true,
  "ownerSabiAiReportOnly": true,
  "ownerFinalDecisionRequired": true,
  "noSecretRevealToOwnerSabiAi": true,
  "bankAccountOpeningUrgent": true,
  "walletIntegrationBlockedUntilOfficialSiteEmailAndSmsReady": true,
  "walletProviderIntegrationRequiresOwnerExactApproval": true,
  "publicCommunicationChannel": "Sabi Messenger",
  "noTelegramMention": true,
  "noDonationOrInvestmentRequest": true,
  "sabiAllocatedCompanyFundsOnly": true,
  "targetOfficialSiteServerReadyDate": "2026-07-01",
  "targetBankWalletDependencyDate": "2026-07-15",
  "ownerFinalCommandAcceptedNow": false,
  "finalOwnerCommandExecutableNow": false,
  "exactPhraseAcceptedNow": false,
  "exactPhraseExecutableNow": false,
  "acceptedNow": false,
  "executableNow": false,
  "noExecutionNow": true,
  "reviewMatrix": [
    "official_site_build_context_reference_only_without_execution",
    "official_domain_email_dns_auth_reference_only_without_mutation",
    "sms_provider_or_firebase_phone_auth_reference_only_without_call",
    "server_sabi_ai_personality_training_report_only",
    "wallet_payment_payout_still_locked",
    "google_cloud_deploy_still_locked_until_separate_exact_owner_approval"
  ],
  "readiness": {
    "release245NReadiness": 100,
    "previous245MReadiness": 100,
    "release245DFix1TypeClean": 100,
    "publicSiteFix75StaticReadiness": 100,
    "officialWebsiteServerExecutionReadiness": 0,
    "googleCloudDeployExecutedNow": 0,
    "cloudRunServiceCreatedNow": 0,
    "liveDomainDnsChangedNow": 0,
    "officialDomainEmailLiveReadiness": 0,
    "liveEmailDnsChangedNow": 0,
    "smsLiveReadiness": 0,
    "liveSmsSentNow": 0,
    "walletPaymentPayoutNow": 0,
    "realProductionLaunchNow": 0
  },
  "safety": {
    "noLiveGoogleCloudDeployNow": true,
    "noCloudRunServiceCreateNow": true,
    "noDomainDnsMutationNow": true,
    "noLiveEmailDnsMutationNow": true,
    "noLiveSmsSendNow": true,
    "noFirebaseApiCallNow": true,
    "noSmsProviderCallNow": true,
    "noWalletPaymentPayoutNow": true,
    "noSecretInSourceChatAdminMobile": true,
    "noPlainSecretInReport": true,
    "noEnvReadWriteNow": true,
    "noSecretManagerReadWriteNow": true,
    "noDbMutationNow": true,
    "noRuntimeMountNow": true,
    "noPublicLaunchClaimNow": true,
    "ownerExactApprovalRequiredBeforeLiveAction": true,
    "noPivotWithoutOwnerApproval": true
  },
  "nextStep": "245O_official_site_google_cloud_deploy_email_dns_sms_runtime_final_execution_package_requires_separate_exact_owner_approval_still_no_wallet_payment_payout"
} as unknown as SabiRelease245NReport;
