import {
  SUPPORTED_LANGUAGE_CODES,
  type SupportedLanguageCode,
} from "../../../shared/data/languages";

export type ProfileRouteTextParams = Record<string, unknown>;

const PROFILE_EMPTY_TEXT = "";

const PROFILE_CORE_TEXT: Record<SupportedLanguageCode, {
  profile: string;
  completeTitle: string;
  completeSubtitle: string;
  phoneVerified: string;
  firstName: string;
  firstNamePlaceholder: string;
  lastName: string;
  lastNamePlaceholder: string;
  sabiId: string;
  sabiIdPlaceholder: string;
  preview: string;
  unifiedId: string;
  unifiedIdHint: string;
  privacy: string;
  required: string;
  saving: string;
  saveErrorTitle: string;
  saveErrorMessage: string;
  verification: string;
  securityStatus: string;
  notBlocking: string;
  verified: string;
  pending: string;
  unknown: string;
  documents: string;
  security: string;
  checks: string;
  noRestrictions: string;
  logout: string;
  deleteAccount: string;
}> = {
  en: {
    profile: "Profile",
    completeTitle: "Complete your profile",
    completeSubtitle: "Add your name and Sabi ID. The home screen will open immediately after this.",
    phoneVerified: "Phone verified",
    firstName: "First name",
    firstNamePlaceholder: "Enter first name",
    lastName: "Last name",
    lastNamePlaceholder: "Enter last name",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Enter Sabi ID",
    preview: "Preview",
    unifiedId: "Unified ID",
    unifiedIdHint: "This ID connects your Sabi profile with Messenger, Taxi, Stream and other services.",
    privacy: "Only your name, Sabi ID and selected public data are visible.",
    required: "Fill in first name, last name and Sabi ID.",
    saving: "Saving…",
    saveErrorTitle: "Profile not saved",
    saveErrorMessage: "Could not save your profile. Check connection and try again.",
    verification: "Verification",
    securityStatus: "Security status",
    notBlocking: "This screen shows verification status and does not block app access.",
    verified: "Verified",
    pending: "Pending",
    unknown: "Unknown",
    documents: "Documents",
    security: "Security",
    checks: "Checks",
    noRestrictions: "No restrictions.",
    logout: "Sign out",
    deleteAccount: "Delete account data",
  },
  ru: {
    profile: "Профиль",
    completeTitle: "Завершите профиль",
    completeSubtitle: "Укажите имя, фамилию и Sabi ID. После этого главный экран откроется сразу.",
    phoneVerified: "Телефон подтверждён",
    firstName: "Имя",
    firstNamePlaceholder: "Введите имя",
    lastName: "Фамилия",
    lastNamePlaceholder: "Введите фамилию",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Введите Sabi ID",
    preview: "Предпросмотр",
    unifiedId: "Единый ID",
    unifiedIdHint: "Этот ID связывает профиль с Messenger, Taxi, Stream и другими сервисами Sabi.",
    privacy: "Публично показываются только имя, Sabi ID и выбранные вами данные.",
    required: "Заполните имя, фамилию и Sabi ID.",
    saving: "Сохраняем…",
    saveErrorTitle: "Профиль не сохранён",
    saveErrorMessage: "Не удалось сохранить профиль. Проверьте соединение и попробуйте ещё раз.",
    verification: "Проверка",
    securityStatus: "Статус безопасности",
    notBlocking: "Этот экран показывает статус проверок и не блокирует доступ к приложениям.",
    verified: "Подтверждено",
    pending: "Ожидает",
    unknown: "Неизвестно",
    documents: "Документы",
    security: "Безопасность",
    checks: "Проверки",
    noRestrictions: "Ограничений нет.",
    logout: "Выйти",
    deleteAccount: "Удалить данные аккаунта",
  },
  zh: {
    profile: "个人资料",
    completeTitle: "完善个人资料",
    completeSubtitle: "填写姓名和 Sabi ID。完成后主页会立即打开。",
    phoneVerified: "手机号已验证",
    firstName: "名字",
    firstNamePlaceholder: "输入名字",
    lastName: "姓氏",
    lastNamePlaceholder: "输入姓氏",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "输入 Sabi ID",
    preview: "预览",
    unifiedId: "统一 ID",
    unifiedIdHint: "此 ID 连接你的 Sabi 资料、Messenger、Taxi、Stream 和其他服务。",
    privacy: "仅显示姓名、Sabi ID 和你选择公开的数据。",
    required: "请填写名字、姓氏和 Sabi ID。",
    saving: "正在保存…",
    saveErrorTitle: "资料未保存",
    saveErrorMessage: "无法保存资料。请检查网络后重试。",
    verification: "验证",
    securityStatus: "安全状态",
    notBlocking: "此页面显示验证状态，不会阻止应用访问。",
    verified: "已验证",
    pending: "待处理",
    unknown: "未知",
    documents: "文件",
    security: "安全",
    checks: "检查",
    noRestrictions: "没有限制。",
    logout: "退出登录",
    deleteAccount: "删除账号数据",
  },
  ko: {
    profile: "프로필",
    completeTitle: "프로필 완료",
    completeSubtitle: "이름과 Sabi ID를 입력하면 홈 화면이 즉시 열립니다.",
    phoneVerified: "전화번호 확인됨",
    firstName: "이름",
    firstNamePlaceholder: "이름 입력",
    lastName: "성",
    lastNamePlaceholder: "성 입력",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID 입력",
    preview: "미리보기",
    unifiedId: "통합 ID",
    unifiedIdHint: "이 ID는 Sabi 프로필, Messenger, Taxi, Stream 및 다른 서비스와 연결됩니다.",
    privacy: "이름, Sabi ID 및 선택한 공개 데이터만 표시됩니다.",
    required: "이름, 성, Sabi ID를 입력하세요.",
    saving: "저장 중…",
    saveErrorTitle: "프로필이 저장되지 않음",
    saveErrorMessage: "프로필을 저장할 수 없습니다. 연결을 확인하고 다시 시도하세요.",
    verification: "확인",
    securityStatus: "보안 상태",
    notBlocking: "이 화면은 확인 상태를 표시하며 앱 접근을 차단하지 않습니다.",
    verified: "확인됨",
    pending: "대기 중",
    unknown: "알 수 없음",
    documents: "문서",
    security: "보안",
    checks: "검사",
    noRestrictions: "제한 없음.",
    logout: "로그아웃",
    deleteAccount: "계정 데이터 삭제",
  },
  ja: {
    profile: "プロフィール",
    completeTitle: "プロフィールを完了",
    completeSubtitle: "名前と Sabi ID を入力すると、ホーム画面がすぐに開きます。",
    phoneVerified: "電話番号確認済み",
    firstName: "名",
    firstNamePlaceholder: "名を入力",
    lastName: "姓",
    lastNamePlaceholder: "姓を入力",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID を入力",
    preview: "プレビュー",
    unifiedId: "統合 ID",
    unifiedIdHint: "この ID は Sabi プロフィール、Messenger、Taxi、Stream などのサービスに接続されます。",
    privacy: "名前、Sabi ID、選択した公開データのみ表示されます。",
    required: "名、姓、Sabi ID を入力してください。",
    saving: "保存中…",
    saveErrorTitle: "プロフィールが保存されませんでした",
    saveErrorMessage: "プロフィールを保存できません。接続を確認して再試行してください。",
    verification: "確認",
    securityStatus: "セキュリティ状態",
    notBlocking: "この画面は確認状態を表示し、アプリへのアクセスをブロックしません。",
    verified: "確認済み",
    pending: "保留中",
    unknown: "不明",
    documents: "書類",
    security: "セキュリティ",
    checks: "チェック",
    noRestrictions: "制限はありません。",
    logout: "サインアウト",
    deleteAccount: "アカウントデータを削除",
  },
  uz: {
    profile: "Profil",
    completeTitle: "Profilni yakunlang",
    completeSubtitle: "Ism, familiya va Sabi ID kiriting. Shundan keyin asosiy ekran darhol ochiladi.",
    phoneVerified: "Telefon tasdiqlandi",
    firstName: "Ism",
    firstNamePlaceholder: "Ismni kiriting",
    lastName: "Familiya",
    lastNamePlaceholder: "Familiyani kiriting",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID kiriting",
    preview: "Ko‘rinish",
    unifiedId: "Yagona ID",
    unifiedIdHint: "Bu ID profilni Messenger, Taxi, Stream va boshqa Sabi servislar bilan bog‘laydi.",
    privacy: "Faqat ismingiz, Sabi ID va tanlangan ochiq ma’lumotlar ko‘rinadi.",
    required: "Ism, familiya va Sabi ID ni to‘ldiring.",
    saving: "Saqlanmoqda…",
    saveErrorTitle: "Profil saqlanmadi",
    saveErrorMessage: "Profilni saqlab bo‘lmadi. Internetni tekshirib, qayta urinib ko‘ring.",
    verification: "Tekshiruv",
    securityStatus: "Xavfsizlik holati",
    notBlocking: "Bu ekran tekshiruv holatini ko‘rsatadi va ilovalarga kirishni bloklamaydi.",
    verified: "Tasdiqlangan",
    pending: "Kutilmoqda",
    unknown: "Noma’lum",
    documents: "Hujjatlar",
    security: "Xavfsizlik",
    checks: "Tekshiruvlar",
    noRestrictions: "Cheklovlar yo‘q.",
    logout: "Chiqish",
    deleteAccount: "Akkaunt ma’lumotlarini o‘chirish",
  },
  tg: {
    profile: "Профил",
    completeTitle: "Профилро пурра кунед",
    completeSubtitle: "Ном, насаб ва Sabi ID ворид кунед. Пас экрани асосӣ фавран кушода мешавад.",
    phoneVerified: "Телефон тасдиқ шуд",
    firstName: "Ном",
    firstNamePlaceholder: "Номро ворид кунед",
    lastName: "Насаб",
    lastNamePlaceholder: "Насабро ворид кунед",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID ворид кунед",
    preview: "Пешнамоиш",
    unifiedId: "ID ягона",
    unifiedIdHint: "Ин ID профилро бо Messenger, Taxi, Stream ва дигар хизматрасониҳои Sabi пайваст мекунад.",
    privacy: "Танҳо ном, Sabi ID ва маълумоти оммавии интихобшуда намоён мешаванд.",
    required: "Ном, насаб ва Sabi ID-ро пур кунед.",
    saving: "Захира мешавад…",
    saveErrorTitle: "Профил захира нашуд",
    saveErrorMessage: "Профилро захира карда нашуд. Пайвастро санҷед ва боз кӯшиш кунед.",
    verification: "Санҷиш",
    securityStatus: "Ҳолати амният",
    notBlocking: "Ин экран ҳолати санҷишро нишон медиҳад ва дастрасиро ба барномаҳо намебандад.",
    verified: "Тасдиқ шуд",
    pending: "Интизор",
    unknown: "Номаълум",
    documents: "Ҳуҷҷатҳо",
    security: "Амният",
    checks: "Санҷишҳо",
    noRestrictions: "Маҳдудият нест.",
    logout: "Баромадан",
    deleteAccount: "Нест кардани маълумоти аккаунт",
  },
  ky: {
    profile: "Профиль",
    completeTitle: "Профилди аяктаңыз",
    completeSubtitle: "Атыңызды, фамилияңызды жана Sabi ID киргизиңиз. Башкы экран дароо ачылат.",
    phoneVerified: "Телефон ырасталды",
    firstName: "Аты",
    firstNamePlaceholder: "Атыңызды киргизиңиз",
    lastName: "Фамилия",
    lastNamePlaceholder: "Фамилияны киргизиңиз",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID киргизиңиз",
    preview: "Алдын ала көрүү",
    unifiedId: "Бирдиктүү ID",
    unifiedIdHint: "Бул ID профилди Messenger, Taxi, Stream жана башка Sabi кызматтары менен байланыштырат.",
    privacy: "Атыңыз, Sabi ID жана тандаган ачык маалыматтар гана көрүнөт.",
    required: "Аты, фамилия жана Sabi ID толтуруңуз.",
    saving: "Сакталып жатат…",
    saveErrorTitle: "Профиль сакталган жок",
    saveErrorMessage: "Профилди сактоо мүмкүн болгон жок. Байланышты текшерип, кайра аракет кылыңыз.",
    verification: "Текшерүү",
    securityStatus: "Коопсуздук абалы",
    notBlocking: "Бул экран текшерүү абалын көрсөтөт жана колдонмолорду бөгөттөбөйт.",
    verified: "Ырасталды",
    pending: "Күтүүдө",
    unknown: "Белгисиз",
    documents: "Документтер",
    security: "Коопсуздук",
    checks: "Текшерүүлөр",
    noRestrictions: "Чектөөлөр жок.",
    logout: "Чыгуу",
    deleteAccount: "Аккаунт дайындарын өчүрүү",
  },
  kk: {
    profile: "Профиль",
    completeTitle: "Профильді аяқтаңыз",
    completeSubtitle: "Атыңызды, тегіңізді және Sabi ID енгізіңіз. Басты экран бірден ашылады.",
    phoneVerified: "Телефон расталды",
    firstName: "Аты",
    firstNamePlaceholder: "Атын енгізіңіз",
    lastName: "Тегі",
    lastNamePlaceholder: "Тегін енгізіңіз",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID енгізіңіз",
    preview: "Алдын ала көру",
    unifiedId: "Бірыңғай ID",
    unifiedIdHint: "Бұл ID профильді Messenger, Taxi, Stream және басқа Sabi сервистерімен байланыстырады.",
    privacy: "Тек аты, Sabi ID және таңдаған ашық деректер көрінеді.",
    required: "Аты, тегі және Sabi ID толтырыңыз.",
    saving: "Сақталуда…",
    saveErrorTitle: "Профиль сақталмады",
    saveErrorMessage: "Профильді сақтау мүмкін болмады. Байланысты тексеріп, қайталап көріңіз.",
    verification: "Тексеру",
    securityStatus: "Қауіпсіздік күйі",
    notBlocking: "Бұл экран тексеру күйін көрсетеді және қолданбаларды бұғаттамайды.",
    verified: "Расталды",
    pending: "Күтілуде",
    unknown: "Белгісіз",
    documents: "Құжаттар",
    security: "Қауіпсіздік",
    checks: "Тексерулер",
    noRestrictions: "Шектеулер жоқ.",
    logout: "Шығу",
    deleteAccount: "Аккаунт деректерін өшіру",
  },
  "fa-AF": {
    profile: "پروفایل",
    completeTitle: "پروفایل را کامل کنید",
    completeSubtitle: "نام و Sabi ID را وارد کنید. سپس صفحه اصلی فوراً باز می‌شود.",
    phoneVerified: "تلفن تأیید شد",
    firstName: "نام",
    firstNamePlaceholder: "نام را وارد کنید",
    lastName: "نام خانوادگی",
    lastNamePlaceholder: "نام خانوادگی را وارد کنید",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID را وارد کنید",
    preview: "پیش‌نمایش",
    unifiedId: "شناسه یکپارچه",
    unifiedIdHint: "این ID پروفایل را با Messenger، Taxi، Stream و خدمات دیگر Sabi وصل می‌کند.",
    privacy: "فقط نام، Sabi ID و داده‌های عمومی انتخاب‌شده نمایش داده می‌شود.",
    required: "نام، نام خانوادگی و Sabi ID را وارد کنید.",
    saving: "در حال ذخیره…",
    saveErrorTitle: "پروفایل ذخیره نشد",
    saveErrorMessage: "پروفایل ذخیره نشد. اتصال را بررسی کرده و دوباره تلاش کنید.",
    verification: "تأیید",
    securityStatus: "وضعیت امنیت",
    notBlocking: "این صفحه وضعیت تأیید را نشان می‌دهد و دسترسی برنامه‌ها را مسدود نمی‌کند.",
    verified: "تأیید شده",
    pending: "در انتظار",
    unknown: "نامشخص",
    documents: "اسناد",
    security: "امنیت",
    checks: "بررسی‌ها",
    noRestrictions: "بدون محدودیت.",
    logout: "خروج",
    deleteAccount: "حذف داده‌های حساب",
  },
  ps: {
    profile: "پروفایل",
    completeTitle: "پروفایل بشپړ کړئ",
    completeSubtitle: "نوم او Sabi ID ولیکئ. وروسته اصلي پرده ژر خلاصیږي.",
    phoneVerified: "تلیفون تایید شو",
    firstName: "نوم",
    firstNamePlaceholder: "نوم ولیکئ",
    lastName: "تخلص",
    lastNamePlaceholder: "تخلص ولیکئ",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID ولیکئ",
    preview: "مخکتنه",
    unifiedId: "یو واحد ID",
    unifiedIdHint: "دا ID پروفایل له Messenger، Taxi، Stream او نورو Sabi خدمتونو سره نښلوي.",
    privacy: "یوازې نوم، Sabi ID او ټاکل شوي عام معلومات ښکاري.",
    required: "نوم، تخلص او Sabi ID ډک کړئ.",
    saving: "ساتل کېږي…",
    saveErrorTitle: "پروفایل ونه ساتل شو",
    saveErrorMessage: "پروفایل ونه ساتل شو. اړیکه وګورئ او بیا هڅه وکړئ.",
    verification: "تایید",
    securityStatus: "د امنیت حالت",
    notBlocking: "دا پرده د تایید حالت ښيي او اپلیکیشنونه نه بندوي.",
    verified: "تایید شوی",
    pending: "انتظار",
    unknown: "نامعلوم",
    documents: "اسناد",
    security: "امنیت",
    checks: "کتنې",
    noRestrictions: "محدودیت نشته.",
    logout: "وتل",
    deleteAccount: "د حساب معلومات حذف کړئ",
  },
  tk: {
    profile: "Profil",
    completeTitle: "Profili tamamlaň",
    completeSubtitle: "Ady, familiýany we Sabi ID giriziň. Baş ekran derrew açylar.",
    phoneVerified: "Telefon tassyklandy",
    firstName: "Ady",
    firstNamePlaceholder: "Adyňyzy giriziň",
    lastName: "Familiýa",
    lastNamePlaceholder: "Familiýany giriziň",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID giriziň",
    preview: "Öňünden gör",
    unifiedId: "Bitewi ID",
    unifiedIdHint: "Bu ID profili Messenger, Taxi, Stream we beýleki Sabi hyzmatlary bilen baglanyşdyrýar.",
    privacy: "Diňe adyňyz, Sabi ID we saýlanan açyk maglumatlar görünýär.",
    required: "Ady, familiýany we Sabi ID dolduryň.",
    saving: "Saklanylýar…",
    saveErrorTitle: "Profil saklanmady",
    saveErrorMessage: "Profil saklanyp bilinmedi. Baglanyşygy barlap, gaýtadan synanyşyň.",
    verification: "Barlag",
    securityStatus: "Howpsuzlyk ýagdaýy",
    notBlocking: "Bu ekran barlag ýagdaýyny görkezýär we programmalara girişi bloklamaýar.",
    verified: "Tassyklandy",
    pending: "Garaşylýar",
    unknown: "Näbelli",
    documents: "Resminamalar",
    security: "Howpsuzlyk",
    checks: "Barlaglar",
    noRestrictions: "Çäklendirme ýok.",
    logout: "Çykmak",
    deleteAccount: "Hasap maglumatlaryny pozmak",
  },
  az: {
    profile: "Profil",
    completeTitle: "Profili tamamlayın",
    completeSubtitle: "Ad, soyad və Sabi ID daxil edin. Sonra əsas ekran dərhal açılacaq.",
    phoneVerified: "Telefon təsdiqləndi",
    firstName: "Ad",
    firstNamePlaceholder: "Ad daxil edin",
    lastName: "Soyad",
    lastNamePlaceholder: "Soyad daxil edin",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID daxil edin",
    preview: "Ön baxış",
    unifiedId: "Vahid ID",
    unifiedIdHint: "Bu ID profili Messenger, Taxi, Stream və digər Sabi xidmətləri ilə birləşdirir.",
    privacy: "Yalnız ad, Sabi ID və seçilmiş açıq məlumatlar görünür.",
    required: "Ad, soyad və Sabi ID doldurun.",
    saving: "Yadda saxlanılır…",
    saveErrorTitle: "Profil saxlanmadı",
    saveErrorMessage: "Profil saxlanmadı. Bağlantını yoxlayın və yenidən cəhd edin.",
    verification: "Yoxlama",
    securityStatus: "Təhlükəsizlik statusu",
    notBlocking: "Bu ekran yoxlama statusunu göstərir və tətbiqlərə girişi bloklamır.",
    verified: "Təsdiqləndi",
    pending: "Gözləmədə",
    unknown: "Naməlum",
    documents: "Sənədlər",
    security: "Təhlükəsizlik",
    checks: "Yoxlamalar",
    noRestrictions: "Məhdudiyyət yoxdur.",
    logout: "Çıxış",
    deleteAccount: "Hesab məlumatlarını sil",
  },
  tr: {
    profile: "Profil",
    completeTitle: "Profili tamamla",
    completeSubtitle: "Ad, soyad ve Sabi ID girin. Ana ekran hemen açılır.",
    phoneVerified: "Telefon doğrulandı",
    firstName: "Ad",
    firstNamePlaceholder: "Ad girin",
    lastName: "Soyad",
    lastNamePlaceholder: "Soyad girin",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID girin",
    preview: "Önizleme",
    unifiedId: "Birleşik ID",
    unifiedIdHint: "Bu ID profili Messenger, Taxi, Stream ve diğer Sabi hizmetlerine bağlar.",
    privacy: "Yalnızca ad, Sabi ID ve seçilen herkese açık veriler görünür.",
    required: "Ad, soyad ve Sabi ID doldurun.",
    saving: "Kaydediliyor…",
    saveErrorTitle: "Profil kaydedilmedi",
    saveErrorMessage: "Profil kaydedilemedi. Bağlantıyı kontrol edin ve tekrar deneyin.",
    verification: "Doğrulama",
    securityStatus: "Güvenlik durumu",
    notBlocking: "Bu ekran doğrulama durumunu gösterir ve uygulama erişimini engellemez.",
    verified: "Doğrulandı",
    pending: "Beklemede",
    unknown: "Bilinmiyor",
    documents: "Belgeler",
    security: "Güvenlik",
    checks: "Kontroller",
    noRestrictions: "Kısıtlama yok.",
    logout: "Çıkış yap",
    deleteAccount: "Hesap verilerini sil",
  },
  hi: {
    profile: "प्रोफ़ाइल",
    completeTitle: "प्रोफ़ाइल पूरी करें",
    completeSubtitle: "नाम और Sabi ID जोड़ें। इसके बाद होम स्क्रीन तुरंत खुलेगी।",
    phoneVerified: "फ़ोन सत्यापित",
    firstName: "नाम",
    firstNamePlaceholder: "नाम दर्ज करें",
    lastName: "उपनाम",
    lastNamePlaceholder: "उपनाम दर्ज करें",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID दर्ज करें",
    preview: "पूर्वावलोकन",
    unifiedId: "यूनिफाइड ID",
    unifiedIdHint: "यह ID प्रोफ़ाइल को Messenger, Taxi, Stream और अन्य Sabi सेवाओं से जोड़ता है.",
    privacy: "केवल नाम, Sabi ID और चुना गया सार्वजनिक डेटा दिखाई देगा।",
    required: "नाम, उपनाम और Sabi ID भरें।",
    saving: "सहेजा जा रहा है…",
    saveErrorTitle: "प्रोफ़ाइल सहेजी नहीं गई",
    saveErrorMessage: "प्रोफ़ाइल सहेजी नहीं जा सकी। कनेक्शन जाँचें और फिर कोशिश करें।",
    verification: "सत्यापन",
    securityStatus: "सुरक्षा स्थिति",
    notBlocking: "यह स्क्रीन सत्यापन स्थिति दिखाती है और ऐप एक्सेस ब्लॉक नहीं करती।",
    verified: "सत्यापित",
    pending: "लंबित",
    unknown: "अज्ञात",
    documents: "दस्तावेज़",
    security: "सुरक्षा",
    checks: "जाँच",
    noRestrictions: "कोई प्रतिबंध नहीं।",
    logout: "साइन आउट",
    deleteAccount: "खाता डेटा हटाएँ",
  },
  ur: {
    profile: "پروفائل",
    completeTitle: "پروفائل مکمل کریں",
    completeSubtitle: "نام اور Sabi ID درج کریں۔ اس کے بعد ہوم اسکرین فوراً کھلے گی۔",
    phoneVerified: "فون تصدیق شدہ",
    firstName: "نام",
    firstNamePlaceholder: "نام درج کریں",
    lastName: "خاندانی نام",
    lastNamePlaceholder: "خاندانی نام درج کریں",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID درج کریں",
    preview: "پیش نظارہ",
    unifiedId: "متحدہ ID",
    unifiedIdHint: "یہ ID پروفائل کو Messenger، Taxi، Stream اور دیگر Sabi خدمات سے جوڑتا ہے.",
    privacy: "صرف نام، Sabi ID اور منتخب عوامی ڈیٹا دکھائی دے گا۔",
    required: "نام، خاندانی نام اور Sabi ID درج کریں۔",
    saving: "محفوظ ہو رہا ہے…",
    saveErrorTitle: "پروفائل محفوظ نہیں ہوا",
    saveErrorMessage: "پروفائل محفوظ نہیں ہو سکا۔ کنکشن چیک کریں اور دوبارہ کوشش کریں۔",
    verification: "تصدیق",
    securityStatus: "سیکیورٹی حالت",
    notBlocking: "یہ اسکرین تصدیق کی حالت دکھاتی ہے اور ایپ تک رسائی نہیں روکتی۔",
    verified: "تصدیق شدہ",
    pending: "زیر التوا",
    unknown: "نامعلوم",
    documents: "دستاویزات",
    security: "سیکیورٹی",
    checks: "چیکس",
    noRestrictions: "کوئی پابندی نہیں۔",
    logout: "سائن آؤٹ",
    deleteAccount: "اکاؤنٹ ڈیٹا حذف کریں",
  },
  ar: {
    profile: "الملف الشخصي",
    completeTitle: "أكمل ملفك الشخصي",
    completeSubtitle: "أدخل الاسم ومعرّف Sabi. سيتم فتح الشاشة الرئيسية فوراً.",
    phoneVerified: "تم تأكيد الهاتف",
    firstName: "الاسم",
    firstNamePlaceholder: "أدخل الاسم",
    lastName: "اسم العائلة",
    lastNamePlaceholder: "أدخل اسم العائلة",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "أدخل Sabi ID",
    preview: "معاينة",
    unifiedId: "المعرّف الموحد",
    unifiedIdHint: "يربط هذا المعرّف الملف الشخصي مع Messenger و Taxi و Stream وخدمات Sabi الأخرى.",
    privacy: "يظهر فقط الاسم و Sabi ID والبيانات العامة التي تختارها.",
    required: "أدخل الاسم واسم العائلة و Sabi ID.",
    saving: "جارٍ الحفظ…",
    saveErrorTitle: "لم يتم حفظ الملف الشخصي",
    saveErrorMessage: "تعذر حفظ الملف الشخصي. تحقق من الاتصال وحاول مرة أخرى.",
    verification: "التحقق",
    securityStatus: "حالة الأمان",
    notBlocking: "تعرض هذه الشاشة حالة التحقق ولا تمنع الوصول إلى التطبيقات.",
    verified: "تم التحقق",
    pending: "قيد الانتظار",
    unknown: "غير معروف",
    documents: "المستندات",
    security: "الأمان",
    checks: "الفحوصات",
    noRestrictions: "لا توجد قيود.",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف بيانات الحساب",
  },
  be: {
    profile: "Профіль",
    completeTitle: "Завяршыце профіль",
    completeSubtitle: "Укажыце імя, прозвішча і Sabi ID. Пасля гэтага галоўны экран адкрыецца адразу.",
    phoneVerified: "Тэлефон пацверджаны",
    firstName: "Імя",
    firstNamePlaceholder: "Увядзіце імя",
    lastName: "Прозвішча",
    lastNamePlaceholder: "Увядзіце прозвішча",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Увядзіце Sabi ID",
    preview: "Папярэдні прагляд",
    unifiedId: "Адзіны ID",
    unifiedIdHint: "Гэты ID звязвае профіль з Messenger, Taxi, Stream і іншымі сэрвісамі Sabi.",
    privacy: "Бачныя толькі імя, Sabi ID і выбраныя вамі публічныя даныя.",
    required: "Запоўніце імя, прозвішча і Sabi ID.",
    saving: "Захоўваем…",
    saveErrorTitle: "Профіль не захаваны",
    saveErrorMessage: "Не ўдалося захаваць профіль. Праверце злучэнне і паспрабуйце яшчэ раз.",
    verification: "Праверка",
    securityStatus: "Стан бяспекі",
    notBlocking: "Гэты экран паказвае стан праверкі і не блакуе доступ да праграм.",
    verified: "Пацверджана",
    pending: "Чакае",
    unknown: "Невядома",
    documents: "Дакументы",
    security: "Бяспека",
    checks: "Праверкі",
    noRestrictions: "Абмежаванняў няма.",
    logout: "Выйсці",
    deleteAccount: "Выдаліць даныя акаўнта",
  },
  uk: {
    profile: "Профіль",
    completeTitle: "Завершіть профіль",
    completeSubtitle: "Вкажіть ім’я, прізвище та Sabi ID. Після цього головний екран відкриється одразу.",
    phoneVerified: "Телефон підтверджено",
    firstName: "Ім’я",
    firstNamePlaceholder: "Введіть ім’я",
    lastName: "Прізвище",
    lastNamePlaceholder: "Введіть прізвище",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Введіть Sabi ID",
    preview: "Попередній перегляд",
    unifiedId: "Єдиний ID",
    unifiedIdHint: "Цей ID з’єднує профіль із Messenger, Taxi, Stream та іншими сервісами Sabi.",
    privacy: "Публічно видно лише ім’я, Sabi ID і вибрані вами дані.",
    required: "Заповніть ім’я, прізвище та Sabi ID.",
    saving: "Зберігаємо…",
    saveErrorTitle: "Профіль не збережено",
    saveErrorMessage: "Не вдалося зберегти профіль. Перевірте з’єднання і спробуйте ще раз.",
    verification: "Перевірка",
    securityStatus: "Статус безпеки",
    notBlocking: "Цей екран показує статус перевірки і не блокує доступ до застосунків.",
    verified: "Підтверджено",
    pending: "Очікує",
    unknown: "Невідомо",
    documents: "Документи",
    security: "Безпека",
    checks: "Перевірки",
    noRestrictions: "Обмежень немає.",
    logout: "Вийти",
    deleteAccount: "Видалити дані акаунта",
  },
  de: {
    profile: "Profil",
    completeTitle: "Profil abschließen",
    completeSubtitle: "Name und Sabi ID eingeben. Danach öffnet sich der Startbildschirm sofort.",
    phoneVerified: "Telefon bestätigt",
    firstName: "Vorname",
    firstNamePlaceholder: "Vorname eingeben",
    lastName: "Nachname",
    lastNamePlaceholder: "Nachname eingeben",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID eingeben",
    preview: "Vorschau",
    unifiedId: "Einheitliche ID",
    unifiedIdHint: "Diese ID verbindet das Profil mit Messenger, Taxi, Stream und anderen Sabi-Diensten.",
    privacy: "Nur Name, Sabi ID und ausgewählte öffentliche Daten sind sichtbar.",
    required: "Vorname, Nachname und Sabi ID ausfüllen.",
    saving: "Speichern…",
    saveErrorTitle: "Profil nicht gespeichert",
    saveErrorMessage: "Profil konnte nicht gespeichert werden. Verbindung prüfen und erneut versuchen.",
    verification: "Verifizierung",
    securityStatus: "Sicherheitsstatus",
    notBlocking: "Dieser Bildschirm zeigt den Prüfstatus und blockiert keine Apps.",
    verified: "Verifiziert",
    pending: "Ausstehend",
    unknown: "Unbekannt",
    documents: "Dokumente",
    security: "Sicherheit",
    checks: "Prüfungen",
    noRestrictions: "Keine Einschränkungen.",
    logout: "Abmelden",
    deleteAccount: "Kontodaten löschen",
  },
  th: {
    profile: "โปรไฟล์",
    completeTitle: "กรอกโปรไฟล์ให้เสร็จ",
    completeSubtitle: "กรอกชื่อ นามสกุล และ Sabi ID จากนั้นหน้าหลักจะเปิดทันที",
    phoneVerified: "ยืนยันโทรศัพท์แล้ว",
    firstName: "ชื่อ",
    firstNamePlaceholder: "กรอกชื่อ",
    lastName: "นามสกุล",
    lastNamePlaceholder: "กรอกนามสกุล",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "กรอก Sabi ID",
    preview: "ตัวอย่าง",
    unifiedId: "ID รวม",
    unifiedIdHint: "ID นี้เชื่อมโปรไฟล์กับ Messenger, Taxi, Stream และบริการ Sabi อื่น ๆ",
    privacy: "จะแสดงเฉพาะชื่อ Sabi ID และข้อมูลสาธารณะที่คุณเลือก",
    required: "กรอกชื่อ นามสกุล และ Sabi ID",
    saving: "กำลังบันทึก…",
    saveErrorTitle: "ยังไม่ได้บันทึกโปรไฟล์",
    saveErrorMessage: "ไม่สามารถบันทึกโปรไฟล์ได้ ตรวจสอบการเชื่อมต่อแล้วลองอีกครั้ง",
    verification: "การตรวจสอบ",
    securityStatus: "สถานะความปลอดภัย",
    notBlocking: "หน้านี้แสดงสถานะการตรวจสอบและไม่บล็อกการเข้าถึงแอป",
    verified: "ยืนยันแล้ว",
    pending: "รอดำเนินการ",
    unknown: "ไม่ทราบ",
    documents: "เอกสาร",
    security: "ความปลอดภัย",
    checks: "การตรวจสอบ",
    noRestrictions: "ไม่มีข้อจำกัด",
    logout: "ออกจากระบบ",
    deleteAccount: "ลบข้อมูลบัญชี",
  },
  sw: {
    profile: "Wasifu",
    completeTitle: "Kamilisha wasifu",
    completeSubtitle: "Weka jina, ukoo na Sabi ID. Skrini kuu itafunguka mara moja.",
    phoneVerified: "Simu imethibitishwa",
    firstName: "Jina",
    firstNamePlaceholder: "Weka jina",
    lastName: "Ukoo",
    lastNamePlaceholder: "Weka ukoo",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Weka Sabi ID",
    preview: "Muhtasari",
    unifiedId: "ID moja",
    unifiedIdHint: "ID hii inaunganisha wasifu na Messenger, Taxi, Stream na huduma nyingine za Sabi.",
    privacy: "Jina, Sabi ID na data ya umma uliyochagua pekee huonekana.",
    required: "Jaza jina, ukoo na Sabi ID.",
    saving: "Inahifadhi…",
    saveErrorTitle: "Wasifu haujahifadhiwa",
    saveErrorMessage: "Imeshindikana kuhifadhi wasifu. Angalia muunganisho na ujaribu tena.",
    verification: "Uthibitishaji",
    securityStatus: "Hali ya usalama",
    notBlocking: "Skrini hii inaonyesha hali ya uthibitishaji na haizuii ufikiaji wa programu.",
    verified: "Imethibitishwa",
    pending: "Inasubiri",
    unknown: "Haijulikani",
    documents: "Nyaraka",
    security: "Usalama",
    checks: "Ukaguzi",
    noRestrictions: "Hakuna vizuizi.",
    logout: "Ondoka",
    deleteAccount: "Futa data ya akaunti",
  },
  am: {
    profile: "መገለጫ",
    completeTitle: "መገለጫዎን ያጠናቅቁ",
    completeSubtitle: "ስም፣ የአባት ስም እና Sabi ID ያስገቡ። ዋና ገጽ ወዲያውኑ ይከፈታል።",
    phoneVerified: "ስልክ ተረጋግጧል",
    firstName: "ስም",
    firstNamePlaceholder: "ስም ያስገቡ",
    lastName: "የአባት ስም",
    lastNamePlaceholder: "የአባት ስም ያስገቡ",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Sabi ID ያስገቡ",
    preview: "ቅድመ እይታ",
    unifiedId: "የተዋሃደ ID",
    unifiedIdHint: "ይህ ID መገለጫን ከ Messenger, Taxi, Stream እና ሌሎች Sabi አገልግሎቶች ጋር ያገናኛል።",
    privacy: "ስም፣ Sabi ID እና የመረጡት የህዝብ መረጃ ብቻ ይታያል።",
    required: "ስም፣ የአባት ስም እና Sabi ID ይሙሉ።",
    saving: "በማስቀመጥ ላይ…",
    saveErrorTitle: "መገለጫ አልተቀመጠም",
    saveErrorMessage: "መገለጫ ማስቀመጥ አልተቻለም። ግንኙነት ያረጋግጡ እና እንደገና ይሞክሩ።",
    verification: "ማረጋገጫ",
    securityStatus: "የደህንነት ሁኔታ",
    notBlocking: "ይህ ገጽ የማረጋገጫ ሁኔታን ያሳያል እና የመተግበሪያ መዳረሻን አያግድም።",
    verified: "ተረጋግጧል",
    pending: "በመጠባበቅ ላይ",
    unknown: "ያልታወቀ",
    documents: "ሰነዶች",
    security: "ደህንነት",
    checks: "ምርመራዎች",
    noRestrictions: "ገደቦች የሉም።",
    logout: "ውጣ",
    deleteAccount: "የመለያ ውሂብ ሰርዝ",
  },
  af: {
    profile: "Profiel",
    completeTitle: "Voltooi profiel",
    completeSubtitle: "Voer naam, van en Sabi ID in. Die tuisskerm sal dadelik oopmaak.",
    phoneVerified: "Foon bevestig",
    firstName: "Naam",
    firstNamePlaceholder: "Voer naam in",
    lastName: "Van",
    lastNamePlaceholder: "Voer van in",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Voer Sabi ID in",
    preview: "Voorskou",
    unifiedId: "Eenvormige ID",
    unifiedIdHint: "Hierdie ID verbind die profiel met Messenger, Taxi, Stream en ander Sabi-dienste.",
    privacy: "Net naam, Sabi ID en gekose openbare data is sigbaar.",
    required: "Vul naam, van en Sabi ID in.",
    saving: "Stoor…",
    saveErrorTitle: "Profiel nie gestoor nie",
    saveErrorMessage: "Kon nie profiel stoor nie. Gaan verbinding na en probeer weer.",
    verification: "Verifikasie",
    securityStatus: "Sekuriteitstatus",
    notBlocking: "Hierdie skerm wys verifikasiestatus en blokkeer nie toepassingstoegang nie.",
    verified: "Geverifieer",
    pending: "Hangend",
    unknown: "Onbekend",
    documents: "Dokumente",
    security: "Sekuriteit",
    checks: "Kontroles",
    noRestrictions: "Geen beperkings nie.",
    logout: "Meld af",
    deleteAccount: "Vee rekeningdata uit",
  },
  hy: {
    profile: "Պրոֆիլ",
    completeTitle: "Ավարտեք պրոֆիլը",
    completeSubtitle: "Մուտքագրեք անուն, ազգանուն և Sabi ID։ Հիմնական էկրանը կբացվի անմիջապես։",
    phoneVerified: "Հեռախոսը հաստատված է",
    firstName: "Անուն",
    firstNamePlaceholder: "Մուտքագրեք անունը",
    lastName: "Ազգանուն",
    lastNamePlaceholder: "Մուտքագրեք ազգանունը",
    sabiId: "Sabi ID",
    sabiIdPlaceholder: "Մուտքագրեք Sabi ID",
    preview: "Նախադիտում",
    unifiedId: "Միասնական ID",
    unifiedIdHint: "Այս ID-ն կապում է պրոֆիլը Messenger-ի, Taxi-ի, Stream-ի և այլ Sabi ծառայությունների հետ։",
    privacy: "Տեսանելի են միայն անունը, Sabi ID-ն և ընտրված հանրային տվյալները։",
    required: "Լրացրեք անունը, ազգանունը և Sabi ID-ն։",
    saving: "Պահպանվում է…",
    saveErrorTitle: "Պրոֆիլը չի պահպանվել",
    saveErrorMessage: "Չհաջողվեց պահպանել պրոֆիլը։ Ստուգեք կապը և փորձեք կրկին։",
    verification: "Ստուգում",
    securityStatus: "Անվտանգության կարգավիճակ",
    notBlocking: "Այս էկրանը ցույց է տալիս ստուգման կարգավիճակը և չի արգելափակում հավելվածների հասանելիությունը։",
    verified: "Հաստատված է",
    pending: "Սպասման մեջ",
    unknown: "Անհայտ",
    documents: "Փաստաթղթեր",
    security: "Անվտանգություն",
    checks: "Ստուգումներ",
    noRestrictions: "Սահմանափակումներ չկան։",
    logout: "Դուրս գալ",
    deleteAccount: "Ջնջել հաշվի տվյալները",
  },
};

const PROFILE_KEY_MAP: Record<string, keyof typeof PROFILE_CORE_TEXT.en> = {
  "common.continue": "profile",
  "common.cancel": "profile",
  "common.save": "profile",
  "common.back": "profile",

  "profile.completeScreen.badge": "profile",
  "profile.completeScreen.title": "completeTitle",
  "profile.completeScreen.subtitle": "completeSubtitle",
  "profile.completeScreen.phone": "phoneVerified",
  "profile.completeScreen.firstName": "firstName",
  "profile.completeScreen.firstNamePlaceholder": "firstNamePlaceholder",
  "profile.completeScreen.lastName": "lastName",
  "profile.completeScreen.lastNamePlaceholder": "lastNamePlaceholder",
  "profile.completeScreen.username": "sabiId",
  "profile.completeScreen.usernamePlaceholder": "sabiIdPlaceholder",
  "profile.completeScreen.usernamePreview": "preview",
  "profile.completeScreen.usernameHint": "required",
  "profile.completeScreen.unifiedId": "unifiedId",
  "profile.completeScreen.unifiedIdHint": "unifiedIdHint",
  "profile.completeScreen.privacy": "privacy",
  "profile.completeScreen.required": "required",
  "profile.completeScreen.saving": "saving",
  "profile.completeScreen.saveErrorTitle": "saveErrorTitle",
  "profile.completeScreen.saveErrorMessage": "saveErrorMessage",

  "profile.verificationScreen.intro.eyebrow": "verification",
  "profile.verificationScreen.intro.title": "securityStatus",
  "profile.verificationScreen.intro.subtitle": "notBlocking",
  "profile.verificationScreen.metrics.phone": "phoneVerified",
  "profile.verificationScreen.metrics.email": "verification",
  "profile.verificationScreen.metrics.liveness": "verification",
  "profile.verificationScreen.sections.checks": "checks",
  "profile.verificationScreen.sections.documents": "documents",
  "profile.verificationScreen.sections.compliance": "security",
  "profile.verificationScreen.checks.phone": "phoneVerified",
  "profile.verificationScreen.checks.email": "verification",
  "profile.verificationScreen.checks.liveness": "verification",
  "profile.verificationScreen.checks.address": "verification",
  "profile.verificationScreen.common.verified": "verified",
  "profile.verificationScreen.common.pending": "pending",
  "profile.verificationScreen.common.unknown": "unknown",
  "profile.verificationScreen.status.verified": "verified",
  "profile.verificationScreen.status.pending": "pending",
  "profile.verificationScreen.status.review": "pending",
  "profile.verificationScreen.status.limited": "pending",
  "profile.verificationScreen.status.rejected": "unknown",
  "profile.verificationScreen.documentStatus.approved": "verified",
  "profile.verificationScreen.documentStatus.pending": "pending",
  "profile.verificationScreen.documentStatus.review": "pending",
  "profile.verificationScreen.complianceState.noRestrictions": "noRestrictions",

  "profile.accountActions.logout.title": "logout",
  "profile.accountActions.logout.confirm": "logout",
  "profile.accountActions.delete.title": "deleteAccount",
  "profile.accountActions.delete.confirm": "deleteAccount",
};

export function normalizeProfileFallbackLanguage(value: unknown): SupportedLanguageCode {
  const raw = String(value ?? "").trim().toLowerCase().replace(/_/g, "-");
  const exact = SUPPORTED_LANGUAGE_CODES.find((code) => code.toLowerCase() === raw);

  if (exact) return exact;

  const base = raw.split("-")[0];
  const byBase = SUPPORTED_LANGUAGE_CODES.find((code) => code.toLowerCase().split("-")[0] === base);

  return byBase ?? "ru";
}

function applyProfileTextParams(text: string, params?: ProfileRouteTextParams): string {
  if (!params) return text;

  return Object.entries(params).reduce((current, [key, value]) => {
    return current.split(`{${key}}`).join(String(value ?? ""));
  }, text);
}

function humanizeProfileKey(language: SupportedLanguageCode, key: string): string {
  const text = PROFILE_CORE_TEXT[language] ?? PROFILE_CORE_TEXT.ru;
  const last = key.split(".").filter(Boolean).pop();

  if (!last) return text.profile;

  const normalized = last
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .trim();

  if (!normalized || normalized.length > 28) return text.profile;

  if (["zh", "ko", "ja", "ar", "ur", "fa-AF", "ps", "hi", "th", "am", "hy"].includes(language)) {
    return text.profile;
  }

  return normalized.charAt(0).toUpperCase() + normalized.slice(1);
}

export function getProfileRouteTextFallback(
  languageValue: unknown,
  key: string,
  params?: ProfileRouteTextParams,
): string {
  const language = normalizeProfileFallbackLanguage(languageValue);
  const text = PROFILE_CORE_TEXT[language] ?? PROFILE_CORE_TEXT.ru;
  const mapped = PROFILE_KEY_MAP[key];
  const value = mapped ? text[mapped] : PROFILE_EMPTY_TEXT;

  return applyProfileTextParams(value || humanizeProfileKey(language, key), params);
}
