import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiDbSchemaApprovalModelPlan,
  TaxiDbSchemaApprovalStage,
  TaxiDbSchemaApprovalVersion,
  TaxiDbSchemaForbiddenExecutionLock,
  TaxiDbSchemaPreflightCheck,
} from './taxiDbSchemaApproval.types';

export const TAXI_DB_SCHEMA_APPROVAL_VERSION: TaxiDbSchemaApprovalVersion = 'TAXI-BACKEND-FOUNDATION-001N';

export const TAXI_DB_SCHEMA_APPROVAL_STAGES: readonly TaxiDbSchemaApprovalStage[] = [
  'schema_inventory',
  'model_contract_review',
  'prisma_diff_review',
  'migration_plan_review',
  'rollback_plan_review',
  'owner_exact_approval_request',
  'blocked_until_exact_approval',
];

export const TAXI_DB_SCHEMA_MODEL_APPROVAL_PLAN: readonly TaxiDbSchemaApprovalModelPlan[] = [
  {
    modelId: 'TaxiRide',
    purpose: 'Verified ride lifecycle, never fake-completed by client app or foundation preview.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiRideRouteSnapshot',
    purpose: 'Provider-backed route, ETA, traffic, radar/camera and speed summary after future route provider approval.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiDriverBalanceLedger',
    purpose: 'Driver reserve/top-up ledger and dispatch eligibility; no fake balance top-up now.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiCommissionLedger',
    purpose: 'Admin-configured commission debit only after verified backend trip completion and ledger approval.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiDailyAiReport',
    purpose: 'Country/day full Sabi AI report; all complaints checked before close.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiComplaintCase',
    purpose: 'Driver/rider complaint review case, daily complaint tier and appeal state before any penalty.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiEvidenceBundle',
    purpose: 'Admin/foundation-only raw evidence bundle; mobile receives redacted kernel-safe summary only.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiAdminDecision',
    purpose: 'Locked Admin decision after Sabi AI evidence, explanation/appeal SLA and supervisor approval.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiAppealExplanation',
    purpose: 'Participant explanation before hard block, prize disqualification or heavy action.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiCountryLeagueSeason',
    purpose: 'Country-separated league season configuration and top-3 reward lock state.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiLeagueScoreEvent',
    purpose: 'Verified trip/stars/complaint score events; no fake score or fake stars from UI.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiRewardFreezeAudit',
    purpose: 'Reward freeze/release audit before any top-3 prize action; payout remains locked.',
    adminVisible: true,
    mobileVisibleRaw: false,
    requiresPrismaSchemaWrite: true,
    requiresMigration: true,
    exactApprovalRequiredBeforeWrite: true,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_DB_SCHEMA_PREFLIGHT_CHECKS: readonly TaxiDbSchemaPreflightCheck[] = [
  {
    checkId: 'schema_write_scope_locked',
    title: 'Prisma schema write scope must be exact and reviewed.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'No schema source write is allowed in this foundation patch.',
  },
  {
    checkId: 'prisma_generate_locked',
    title: 'Prisma generate is separate from schema planning.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'No Prisma generate can run before exact owner approval and dependency review.',
  },
  {
    checkId: 'migration_locked',
    title: 'Migration execution requires rollback plan.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'No migration can run before exact approval, backup and rollback plan.',
  },
  {
    checkId: 'db_read_locked',
    title: 'DB read remains locked.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'No DB read is needed for schema planning and no DB read runs now.',
  },
  {
    checkId: 'db_write_locked',
    title: 'DB write remains locked.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'No Taxi data mutation runs in foundation planning.',
  },
  {
    checkId: 'raw_evidence_admin_only',
    title: 'Raw evidence must stay Admin/foundation only.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'Client kernel boundary can only receive redacted safe summaries after Admin locked decision.',
  },
  {
    checkId: 'client_boundary_summary_only',
    title: 'Client app must stay kernel-only.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'Client app must not connect directly to backend provider/payment/payout/runtime.',
  },
  {
    checkId: 'all_complaints_daily_report_coverage',
    title: 'Daily AI report must cover all complaints.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'Schema must support all driver/rider complaints by country/day before close.',
  },
  {
    checkId: 'admin_compatibility_coverage',
    title: 'Admin UI must use same foundation contracts.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'Admin panels, filters, action inbox, approval gates and export must match the schema plan.',
  },
  {
    checkId: 'rollback_plan_required',
    title: 'Rollback plan required before migration.',
    requiredBeforeSchemaWrite: true,
    passedNow: false,
    reason: 'Schema execution requires rollback plan, migration dry-run and owner exact approval.',
  },
];

export const TAXI_DB_SCHEMA_FORBIDDEN_EXECUTION_LOCKS: readonly TaxiDbSchemaForbiddenExecutionLock[] = [
  {
    id: 'no_prisma_schema_write_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: '001N is schema exact-approval planning only; it must not modify prisma/schema.prisma.',
  },
  {
    id: 'no_prisma_generate_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'Generated client changes are blocked until separate exact approval.',
  },
  {
    id: 'no_prisma_migration_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'Migration execution is blocked until backup, rollback and owner approval are ready.',
  },
  {
    id: 'no_db_read_write_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'No DB read/write is permitted in this contract-only foundation stage.',
  },
  {
    id: 'no_runtime_route_mount_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'Routes remain descriptors only and must not be mounted in app.ts/server.ts.',
  },
  {
    id: 'no_scheduler_activation_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'Daily AI report scheduler cannot run without DB and AI runtime approvals.',
  },
  {
    id: 'no_wallet_payment_payout_provider_now',
    blockedNow: true,
    exactApprovalRequired: true,
    reason: 'Wallet, payment, payout and provider dispatch are still locked.',
  },
];

export const taxiDbSchemaApprovalRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/admin/taxi/db-schema-approval/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin DB schema exact-approval readiness contract; not mounted and no DB access now.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/db-schema-approval/model-plan',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future model plan read route; not mounted and no schema/DB write now.',
  },
  {
    method: 'POST',
    path: '/api/admin/taxi/db-schema-approval/request',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future exact approval request route for schema/migration; not mounted and cannot execute now.',
  },
];
