import {
  STREAM_FOUNDATION_140X_LIVE_WRITE_HANDLER_SOURCE_PLAN_VERSION,
  type StreamFoundation140XLiveWriteHandlerPlanItem,
  type StreamFoundation140XLiveWriteHandlerSourcePlanSnapshot,
} from "./streamFoundationLiveWriteHandlerSourcePlanContracts";

const COMMON_SAFE_FAILURE_CODES = [
  "STREAM_IDENTITY_SESSION_REQUIRED",
  "STREAM_ROUTE_RUNTIME_BLOCKED",
  "STREAM_PROVIDER_NOT_CONFIGURED",
  "STREAM_REPOSITORY_NOT_CONFIGURED",
  "STREAM_OWNER_RUNTIME_APPROVAL_REQUIRED",
] as const;

const LIVE_WRITE_HANDLERS: readonly StreamFoundation140XLiveWriteHandlerPlanItem[] = [
  {
    id: "live_start_handler_source_plan",
    routeId: "stream_live_start",
    commandId: "stream_start_live_session_command",
    title: "Source-only plan for starting a live stream session",
    plannedMethod: "POST",
    plannedPath: "/api/stream/live/start",
    status: "source_plan_ready_runtime_blocked",
    sourcePlanReady: true,
    runtimeMountedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredInputFields: [
      "actorUserId",
      "streamMode",
      "visibility",
      "locale",
      "deviceSessionId",
      "clientRequestId",
    ],
    requiredGatesBeforeRuntime: [
      "identity_session_gate",
      "rate_limit_gate",
      "moderation_policy_gate",
      "realtime_provider_readiness_gate",
      "live_room_repository_gate",
      "event_audit_gate",
      "owner_runtime_mount_approval",
    ],
    safeFailureCodes: COMMON_SAFE_FAILURE_CODES,
    auditEventPlan: [
      "stream_live_session_start_requested",
      "stream_live_session_start_blocked_if_provider_missing",
      "stream_live_session_start_blocked_if_repository_missing",
      "stream_live_session_start_blocked_if_owner_approval_missing",
    ],
  },
  {
    id: "live_stop_handler_source_plan",
    routeId: "stream_live_stop",
    commandId: "stream_stop_live_session_command",
    title: "Source-only plan for stopping a live stream session",
    plannedMethod: "POST",
    plannedPath: "/api/stream/live/stop",
    status: "source_plan_ready_runtime_blocked",
    sourcePlanReady: true,
    runtimeMountedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredInputFields: [
      "actorUserId",
      "roomId",
      "reason",
      "locale",
      "deviceSessionId",
      "clientRequestId",
    ],
    requiredGatesBeforeRuntime: [
      "identity_session_gate",
      "live_room_repository_gate",
      "event_audit_gate",
      "realtime_provider_readiness_gate",
      "owner_runtime_mount_approval",
    ],
    safeFailureCodes: COMMON_SAFE_FAILURE_CODES,
    auditEventPlan: [
      "stream_live_session_stop_requested",
      "stream_live_session_stop_blocked_if_repository_missing",
      "stream_live_session_stop_blocked_if_owner_approval_missing",
    ],
  },
  {
    id: "live_heartbeat_handler_source_plan",
    routeId: "stream_live_heartbeat",
    commandId: "stream_live_heartbeat_command",
    title: "Source-only plan for live session heartbeat",
    plannedMethod: "POST",
    plannedPath: "/api/stream/live/heartbeat",
    status: "source_plan_ready_runtime_blocked",
    sourcePlanReady: true,
    runtimeMountedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    paymentAuthorizationAllowedNow: false,
    monthlyPayoutAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowed: false,
    requiredInputFields: [
      "actorUserId",
      "roomId",
      "heartbeatAt",
      "deviceSessionId",
      "clientRequestId",
    ],
    requiredGatesBeforeRuntime: [
      "identity_session_gate",
      "presence_repository_gate",
      "rate_limit_gate",
      "event_audit_gate",
      "owner_runtime_mount_approval",
    ],
    safeFailureCodes: COMMON_SAFE_FAILURE_CODES,
    auditEventPlan: [
      "stream_live_heartbeat_received",
      "stream_live_heartbeat_blocked_if_presence_repository_missing",
      "stream_live_heartbeat_blocked_if_owner_approval_missing",
    ],
  },
];

export function getStreamFoundationLiveWriteHandlerSourcePlanSnapshot(): StreamFoundation140XLiveWriteHandlerSourcePlanSnapshot {
  return {
    version: STREAM_FOUNDATION_140X_LIVE_WRITE_HANDLER_SOURCE_PLAN_VERSION,
    stage: "live_write_handler_source_plan_only",
    status: "live_write_handler_plan_ready_runtime_blocked",
    previousStage: "BACKEND-STREAM-FOUNDATION-140W",
    writeRouteApprovalGatePassed: true,
    liveWriteHandlers: LIVE_WRITE_HANDLERS,
    totals: {
      totalLiveWriteHandlers: LIVE_WRITE_HANDLERS.length,
      runtimeMountedNow: 0,
      runtimePostAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      providerCallAllowedNow: 0,
      walletMutationAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowed: 0,
    },
    safety: {
      sourceOnly: true,
      appTsChange: false,
      serverTsChange: false,
      streamIndexChange: false,
      routeMountNow: false,
      runtimePostBy140X: false,
      backendRestart: false,
      databaseWrite: false,
      providerCall: false,
      walletMutation: false,
      paymentAuthorization: false,
      monthlyPayout: false,
      moneyMovement: false,
      fakeSuccess: false,
    },
  };
}
