import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiPrismaSchemaCandidateModelShape,
  TaxiPrismaSchemaCandidateOwnerApprovalTemplate,
  TaxiPrismaSchemaCandidatePackageGuard,
  TaxiPrismaSchemaCandidateStage,
  TaxiPrismaSchemaCandidateVersion,
} from './taxiPrismaSchemaCandidate.types';

export const TAXI_PRISMA_SCHEMA_CANDIDATE_VERSION: TaxiPrismaSchemaCandidateVersion = 'TAXI-BACKEND-FOUNDATION-001O';

export const TAXI_PRISMA_SCHEMA_CANDIDATE_STAGES: readonly TaxiPrismaSchemaCandidateStage[] = [
  'candidate_scope_inventory',
  'model_shape_candidate_review',
  'field_privacy_review',
  'index_unique_constraint_review',
  'relation_integrity_review',
  'admin_ui_compatibility_review',
  'client_boundary_summary_review',
  'owner_exact_approval_template',
  'blocked_until_schema_write_approval',
];

export const TAXI_PRISMA_SCHEMA_CANDIDATE_MODEL_SHAPES: readonly TaxiPrismaSchemaCandidateModelShape[] = [
  {
    modelId: 'TaxiRide',
    purpose: 'Verified trip lifecycle, driver/rider assignment state, no fake completion, no fake active trip resume.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiRideRouteSnapshot',
    purpose: 'Route/ETA/traffic/radar/speed snapshot references for provider-backed map state; mobile receives redacted summaries only.',
    fieldClasses: ['identity', 'country_day_partition', 'redacted_mobile_summary', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiDriverBalanceLedger',
    purpose: 'Driver reserve eligibility, top-up references and dispatch access; no fake top-up and no UI balance mutation.',
    fieldClasses: ['identity', 'money_minor_units', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiCommissionLedger',
    purpose: 'Admin-configured commission candidate ledger after verified backend trip completion only; no debit before completion.',
    fieldClasses: ['identity', 'money_minor_units', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiDailyAiReport',
    purpose: 'Country/day full Sabi AI report completeness, every complaint checked before report close.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: false,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiComplaintCase',
    purpose: 'Driver/rider complaint case, daily tier, false complaint review and appeal/explanation state.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiEvidenceBundle',
    purpose: 'Admin/foundation-only raw evidence references for chat/call/route/device/account/country signals.',
    fieldClasses: ['identity', 'admin_raw_evidence_reference', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: false,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiAdminDecision',
    purpose: 'Locked Admin/supervisor decision after Sabi AI evidence, explanation window and approval gates.',
    fieldClasses: ['identity', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiAppealExplanation',
    purpose: 'Participant explanation before hard block, prize disqualification or restore decision.',
    fieldClasses: ['identity', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiCountryLeagueSeason',
    purpose: 'Country-separated driver/rider league season and top-3 prize lock state.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiLeagueScoreEvent',
    purpose: 'Verified trip/stars/complaint score events with false-star and fake-trip protection.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
  {
    modelId: 'TaxiRewardFreezeAudit',
    purpose: 'Top-3 reward freeze/release audit, legal/finance review references; payout remains locked.',
    fieldClasses: ['identity', 'country_day_partition', 'status_lifecycle', 'approval_lock', 'audit_timestamp'],
    adminUiRequired: true,
    clientBoundarySummaryAllowed: true,
    rawEvidenceMobileBlocked: true,
    requiresExactOwnerApprovalBeforeSchemaWrite: true,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_PRISMA_SCHEMA_CANDIDATE_PACKAGE_GUARDS: readonly TaxiPrismaSchemaCandidatePackageGuard[] = [
  {
    id: 'candidate_file_write_locked_now',
    title: 'Candidate file write requires exact owner approval.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'This patch prepares candidate readiness only; no .prisma candidate or schema source file is written now.',
  },
  {
    id: 'prisma_schema_write_locked_now',
    title: 'Prisma schema write is locked.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'prisma/schema.prisma must not be changed until the owner approves exact schema write scope.',
  },
  {
    id: 'prisma_generate_locked_now',
    title: 'Prisma generate is locked.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'Client generation is separate from schema candidate review and requires exact approval.',
  },
  {
    id: 'migration_locked_now',
    title: 'Migration execution is locked.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'Migration requires diff review, backup, rollback plan, dry-run and owner approval.',
  },
  {
    id: 'db_access_locked_now',
    title: 'DB access remains zero.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'No DB read/write is needed for schema candidate readiness planning.',
  },
  {
    id: 'admin_mobile_raw_evidence_boundary_locked',
    title: 'Raw evidence stays Admin/foundation only.',
    lockedNow: true,
    exactApprovalRequired: true,
    reason: 'Client app must receive only kernel-safe status summaries, never raw evidence payloads.',
  },
];

export const TAXI_PRISMA_SCHEMA_CANDIDATE_OWNER_APPROVAL_TEMPLATE: TaxiPrismaSchemaCandidateOwnerApprovalTemplate = {
  approvalId: 'taxi_prisma_schema_candidate_write_approval',
  ownerMustApprove: true,
  allowsSchemaWriteNow: false,
  allowsPrismaGenerateNow: false,
  allowsMigrationNow: false,
  allowsDbReadNow: false,
  allowsDbWriteNow: false,
  requiredOwnerStatement:
    'I approve TAXI-BACKEND-FOUNDATION next stage to write a Prisma schema candidate file only, with no Prisma generate, no migration, no DB read/write, no route mount, no Wallet/payment/payout/provider runtime.',
  forbiddenWithoutApproval: [
    'write_prisma_schema_or_candidate_file',
    'run_prisma_generate',
    'run_prisma_migrate',
    'read_or_write_database',
    'mount_runtime_routes',
    'start_scheduler_or_cron',
    'mutate_wallet_or_payment_or_payout',
    'call_dispatch_or_map_provider',
  ],
};

export const taxiPrismaSchemaCandidateRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/admin/taxi/prisma-schema-candidate/readiness',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future Admin readiness route for Taxi Prisma schema candidate package; not mounted now.',
  },
  {
    method: 'POST',
    path: '/api/admin/taxi/prisma-schema-candidate/request-owner-approval',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future owner approval request route for schema candidate write; no execution in this patch.',
  },
];
