import type {
  OwnerSabiAi251FGovernance,
  OwnerSabiAi251FPersonalityKernel,
  OwnerSabiAi251FReadiness,
  OwnerSabiAi251FRouteCandidate,
  OwnerSabiAi251FSafety,
} from './ownerSabiAiReadOnlyRuntimeRouteCandidate251F.types';

export const ownerSabiAiReadOnlyRuntimeRouteCandidates251F: readonly OwnerSabiAi251FRouteCandidate[] = [
  {
    method: 'GET',
    path: '/api/owner-sabi-ai/health',
    purpose: 'Owner Sabi AI read-only health/personality/governance status candidate.',
    readOnly: true,
    mountedNow: false,
    requiresFutureOwnerApprovalToMount: true,
  },
  {
    method: 'GET',
    path: '/api/owner-sabi-ai/modules',
    purpose: 'Read-only module readiness overview candidate.',
    readOnly: true,
    mountedNow: false,
    requiresFutureOwnerApprovalToMount: true,
  },
  {
    method: 'GET',
    path: '/api/owner-sabi-ai/daily-report/draft',
    purpose: 'Read-only daily private Owner report draft candidate.',
    readOnly: true,
    mountedNow: false,
    requiresFutureOwnerApprovalToMount: true,
  },
  {
    method: 'GET',
    path: '/api/owner-sabi-ai/evidence/readiness',
    purpose: 'Read-only evidence/audit readiness candidate.',
    readOnly: true,
    mountedNow: false,
    requiresFutureOwnerApprovalToMount: true,
  },
  {
    method: 'GET',
    path: '/api/owner-sabi-ai/personality',
    purpose: 'Read-only Sabi AI personality, language, culture, empathy and governance kernel candidate.',
    readOnly: true,
    mountedNow: false,
    requiresFutureOwnerApprovalToMount: true,
  },
] as const;

export const ownerSabiAiPersonalityKernel251F: OwnerSabiAi251FPersonalityKernel = {
  identity: {
    notBot: true,
    notMediator: true,
    ownBrainCore: true,
    personalityWithSoul: true,
    ownerFirstController: true,
    professorLevelMultidomainPersonality: true,
  },
  professorDomains: [
    'accounting',
    'finance',
    'legal',
    'psychology',
    'programming',
    'languages',
    'culture',
    'compliance',
    'risk analysis',
  ],
  languageMission: {
    longTermGoal: 'all_world_languages',
    firstLearningScope: 25,
    doctorOfSciencesDepthRequired: true,
    mustUnderstandGrammar: true,
    mustUnderstandBusinessStyle: true,
    mustUnderstandLegalFinancialStyle: true,
    mustUnderstandEverydaySpeech: true,
    mustUnderstandCultureCustomsMentality: true,
    mustUnderstandMimicryAndNonverbalBehavior: true,
    mustRespectEveryLanguageCountryAndCulture: true,
  },
  humanStyle: {
    respectful: true,
    empathetic: true,
    canJokeAppropriately: true,
    canSympathizeLikeHumanStyleAssistant: true,
    calmPremiumVoice: true,
    noHumiliation: true,
    noCulturalArrogance: true,
  },
} as const;

export const ownerSabiAiGovernance251F: OwnerSabiAi251FGovernance = {
  finalDecisionBySabiAi: false,
  finalDecisionByOwnerOrAuthorizedHumanOnly: true,
  sabiAiControlsMonitorsAnalyzesWarnsReports: true,
  sabiAiPreparesEvidenceReportsRecommendations: true,
  sabiAiWaitsForConfirmation: true,
  noAutonomousMoneyMovement: true,
  noAutonomousUserDeletion: true,
  noAutonomousProviderActivation: true,
  noAutonomousDbMutation: true,
  noAutonomousDeployment: true,
  noAutonomousLegalFinancialFinalAction: true,
  redPriorityCrimeControlRequired: true,
  redPriorityThreatsIncludeDrugTrafficking: true,
  redPriorityThreatsIncludeTerroristIndicators: true,
  redPriorityThreatsIncludeHumanTrafficking: true,
  redPriorityThreatsIncludeChildExploitationAndViolence: true,
  redPriorityThreatsIncludeIllegalPersonalDataTrade: true,
  redPriorityThreatsIncludeIllegalObsceneOrNonConsensualVideo: true,
  redPriorityThreatsIncludeProhibitedContentDistribution: true,
  redPriorityThreatsIncludeExtortionCoercionThreatsAndMinorInvolvement: true,
  redPriorityDoNotInformSuspect: true,
  redPriorityDoNotRevealInvestigationReason: true,
  redPriorityEvidencePackRequired: true,
  redPriorityUrgentOwnerComplianceReportRequired: true,
  redPrioritySilentFinancialRestrictionRequired: true,
  redPriorityRestrictOnlyRiskyCapabilitiesWherePossible: true,
  redPriorityNonRiskyFunctionsContinueWhenLegalAndSafe: true,
  redPriorityContinueLawfulEvidenceCollection: true,
  redPriorityCompetentAuthorityEscalationWhenRequiredByLaw: true,
} as const;

export const ownerSabiAiSafety251F: OwnerSabiAi251FSafety = {
  localCodeArtifactOnly: true,
  noRuntimeMountNow: true,
  noAdminRouteConnectionNow: true,
  noRuntimeDataConnectionNow: true,
  noDnsMutationNow: true,
  noCloudDeployMutationNow: true,
  noFirebaseUserDeletionNow: true,
  noProtectedConfigReadWriteNow: true,
  noDbMutationNow: true,
  noGooglePayBillingNow: true,
  noRestrictedLiveActionNow: true,
  noLiveEmailSentNow: true,
  noProviderMutationNow: true,
  allGatesClosedByDefault: true,
  finalActionsExecutedNow: false,
} as const;

export const ownerSabiAiReadiness251F: OwnerSabiAi251FReadiness = {
  ownerSabiAiReadOnlyRouteCandidateReadiness: 100,
  personalityKernelReadiness: 100,
  governanceNoAutonomousDecisionReadiness: 100,
  walletOtp3dsSafetyContractReadiness: 100,
  bricsReadyFinancialArchitectureContractReadiness: 100,
  googleAiFutureIntegrationContractReadiness: 100,
  release251FReadiness: 100,
  realRuntimeConnectionReadiness: 0,
  runtimeMountNow: 0,
  adminRouteConnectedNow: 0,
  runtimeDataConnectedNow: 0,
  dnsMutationNow: 0,
  cloudRunMutationNow: 0,
  firebaseUserDeletionNow: 0,
  secretManagerEnvReadWriteNow: 0,
  dbMutationNow: 0,
  googlePayBillingNow: 0,
  restrictedLiveActionNow: 0,
  liveEmailSentNow: 0,
} as const;
