import {
  STREAM_FOUNDATION_141R_REALTIME_PROVIDER_READINESS_VERSION,
  type StreamFoundation141RProviderReadinessContract,
  type StreamFoundation141RRealtimeProviderReadinessSnapshot,
} from "./streamFoundationRealtimeProviderReadinessGateContractPlanningContracts";

const PROVIDER_CONTRACTS: readonly StreamFoundation141RProviderReadinessContract[] = [
  {
    id: "realtime_room_provider_manifest",
    status: "contract_planned_not_configured",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Future realtime room provider manifest for room join/leave/signal lifecycle; not configured or called now.",
  },
  {
    id: "media_session_provider_manifest",
    status: "contract_planned_not_configured",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Future media session provider manifest for live stream media lifecycle; no provider success now.",
  },
  {
    id: "provider_secret_server_side_gate",
    status: "server_side_secret_required",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Provider keys must stay on backend/server environment only; no mobile secrets and no returned raw secrets.",
  },
  {
    id: "provider_health_readiness_gate",
    status: "provider_not_configured",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Health/readiness probe must exist before provider-backed live runtime can be enabled.",
  },
  {
    id: "provider_region_policy_gate",
    status: "contract_planned_not_configured",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Region and latency policy must be reviewed before realtime/media session allocation.",
  },
  {
    id: "provider_fallback_disabled_gate",
    status: "runtime_mount_blocked",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Fake/fallback provider success remains disabled; missing provider must stay provider_not_configured.",
  },
  {
    id: "provider_runtime_owner_approval",
    status: "owner_approval_required",
    requiredBeforeRuntimeMount: true,
    serverSideOnly: true,
    mobileSecretAllowed: false,
    providerCallAllowedNow: false,
    providerLiveAllowedNow: false,
    fakeProviderSuccessAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    databaseWriteAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    description: "Separate owner approval is required before any provider-backed live runtime behavior.",
  },
];

export function getStreamFoundationRealtimeProviderReadinessGateContractPlanningSnapshot(): StreamFoundation141RRealtimeProviderReadinessSnapshot {
  return {
    version: STREAM_FOUNDATION_141R_REALTIME_PROVIDER_READINESS_VERSION,
    stage: "realtime_provider_readiness_gate_source_only_contract_planning",
    status: "realtime_provider_contract_planned_routes_remain_blocked",
    previousStage: "BACKEND-STREAM-FOUNDATION-141Q",
    providerContracts: PROVIDER_CONTRACTS,
    providerPolicy: {
      realtimeProviderRequiredBeforeRuntimeMount: true,
      mediaSessionProviderRequiredBeforeRuntimeMount: true,
      providerSecretsServerSideOnly: true,
      mobileProviderSecretsAllowed: false,
      fakeProviderFallbackAllowed: false,
      providerLiveAllowedNow: false,
      providerCallAllowedNow: false,
      routesStayBlockedNow: true,
      expectedCurrentStatusCode: 423,
    },
    totals: {
      providerContracts: 7,
      readyForRuntimeMountNow: 0,
      providerConfiguredNow: 0,
      providerCallAllowedNow: 0,
      providerLiveAllowedNow: 0,
      fakeProviderSuccessAllowedNow: 0,
      runtimeSuccessAllowedNow: 0,
      databaseWriteAllowedNow: 0,
      walletMutationAllowedNow: 0,
      moneyMovementAllowedNow: 0,
      fakeSuccessAllowedNow: 0,
    },
    safety: {
      sourceOnly141R: true,
      appTsChangeBy141R: false,
      serverTsChangeBy141R: false,
      streamIndexChangeBy141R: false,
      backendRestartBy141R: false,
      runtimeHttpBy141R: false,
      runtimePostBy141R: false,
      databaseWriteBy141R: false,
      providerCallBy141R: false,
      providerSecretReadBy141R: false,
      walletMutationBy141R: false,
      paymentAuthorizationBy141R: false,
      monthlyPayoutBy141R: false,
      moneyMovementBy141R: false,
      fakeSuccessBy141R: false,
    },
  };
}
