import { getStreamFoundationProviderRealtimeModerationGateContractsScaffoldReadiness } from "./provider-realtime-moderation-gate-contracts";

export const STREAM_143F_PROVIDER_REALTIME_MODERATION_GATE_CONTRACTS_SCAFFOLD_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-143F",
  stage: "controlled_provider_realtime_moderation_gate_contracts_scaffold_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/provider-realtime-moderation-gate-contracts/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-143E",
  contractGates: [
    "provider_readiness_gate",
    "realtime_handoff_gate",
    "moderation_gate",
    "runtime_mount_prerequisite_gate",
    "admin_review_gate",
    "safe_disabled_response_gate",
  ],
  blockedNow: {
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    fakeSuccessAllowed: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-143G",
    exactApprovalRequiredBefore143G: true,
    opsOnlyCompileAndSafetyVerification: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy143F: false,
    appTsChangeBy143F: false,
    serverTsChangeBy143F: false,
    streamIndexChangeBy143F: false,
    prismaSchemaChangeBy143F: false,
    migrationCreatedBy143F: false,
    routeBehaviorChangeBy143F: false,
    backendRestartBy143F: false,
    runtimeHttpBy143F: false,
    runtimePostBy143F: false,
    runtimeDbReadBy143F: false,
    runtimeDbWriteBy143F: false,
    databaseReadBy143F: false,
    databaseWriteBy143F: false,
    providerCallBy143F: false,
    providerSecretReadBy143F: false,
    realtimeSocketOpenBy143F: false,
    realtimeBroadcastBy143F: false,
    moderationBypassBy143F: false,
    walletMutationBy143F: false,
    paymentAuthorizationBy143F: false,
    monthlyPayoutBy143F: false,
    moneyMovementBy143F: false,
    fakeSuccessBy143F: false,
  },
  readiness: getStreamFoundationProviderRealtimeModerationGateContractsScaffoldReadiness(),
} as const;
