import { getStreamFoundationRuntimeMountTargetPatchDraftPreviewPackagePlanningReadiness } from "./runtime-mount-target-patch-draft-preview-package-planning";

export const STREAM_144B_RUNTIME_MOUNT_TARGET_PATCH_DRAFT_PREVIEW_PACKAGE_PLANNING_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-144B",
  stage: "controlled_runtime_mount_target_patch_draft_preview_package_planning_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/runtime-mount-target-patch-draft-preview-package-planning/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-144A",
  contractGroups: [
    "target_patch_draft_preview_package",
    "proposed_target_file_snapshot",
    "proposed_diff_preview_text",
    "insertion_marker_evidence",
    "duplicate_mount_evidence",
    "auth_boundary_evidence",
    "blocked_route_evidence",
    "rollback_preview",
    "compile_gate",
    "owner_approval_gate",
  ],
  blockedNow: {
    previewPackageCreatedNow: false,
    previewPackageRenderedNow: false,
    targetSnapshotReadNow: false,
    finalSelectedTargetNow: null,
    diffPreviewTextGeneratedNow: false,
    proposedDiffAppliedNow: false,
    targetPatchAllowed: false,
    targetRouteWriteAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    backendRestartAllowed: false,
    runtimePostAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    fakeSuccessAllowed: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-144C",
    exactApprovalRequiredBefore144C: true,
    opsOnlyCompileAndSafetyVerification: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimeHttpAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    targetRouteWriteAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy144B: false,
    appTsChangeBy144B: false,
    serverTsChangeBy144B: false,
    streamIndexChangeBy144B: false,
    prismaSchemaChangeBy144B: false,
    migrationCreatedBy144B: false,
    routeBehaviorChangeBy144B: false,
    backendRestartBy144B: false,
    runtimeHttpBy144B: false,
    runtimePostBy144B: false,
    runtimeDbReadBy144B: false,
    runtimeDbWriteBy144B: false,
    databaseReadBy144B: false,
    databaseWriteBy144B: false,
    providerCallBy144B: false,
    providerSecretReadBy144B: false,
    realtimeSocketOpenBy144B: false,
    realtimeBroadcastBy144B: false,
    moderationBypassBy144B: false,
    runtimeMountBy144B: false,
    targetRouteWriteBy144B: false,
    rollbackExecutionBy144B: false,
    postMountSmokeBy144B: false,
    walletMutationBy144B: false,
    paymentAuthorizationBy144B: false,
    monthlyPayoutBy144B: false,
    moneyMovementBy144B: false,
    fakeSuccessBy144B: false,
  },
  readiness: getStreamFoundationRuntimeMountTargetPatchDraftPreviewPackagePlanningReadiness(),
} as const;
