import { getStreamFoundation144HRunnerApprovalReadiness } from "./runner-approval-144h";

export const STREAM_144H_RUNNER_APPROVAL_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-144H",
  stage: "controlled_runtime_mount_target_patch_draft_preview_evidence_capture_runner_approval_package_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/runner-approval-144h/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-144G",
  contractGroups: [
    "ops_only_evidence_capture_runner_package",
    "future_target_hash_capture",
    "future_target_excerpt_capture",
    "future_route_anchor_inspection",
    "future_auth_boundary_inspection",
    "future_blocked_route_inspection",
    "future_duplicate_mount_inventory",
    "future_report_output_contract",
    "compile_gate",
    "owner_approval_gate",
  ],
  futureRunnerScope: {
    futureRunnerMayReadTargetFilesForEvidenceOnlyAfterSeparateApproval: true,
    futureRunnerMayReadHashesAfterSeparateApproval: true,
    futureRunnerMayReadExcerptsAfterSeparateApproval: true,
    futureRunnerMayInspectAnchorsAfterSeparateApproval: true,
    futureRunnerMayWriteSourceFiles: false,
    futureRunnerMayWritePrismaSchema: false,
    futureRunnerMayCreateMigration: false,
    futureRunnerMayRestartBackend: false,
    futureRunnerMayPerformRuntimePost: false,
    futureRunnerMayReadRuntimeDb: false,
    futureRunnerMayWriteRuntimeDb: false,
    futureRunnerMayCallProvider: false,
    futureRunnerMayReadProviderSecret: false,
    futureRunnerMayOpenRealtimeSocket: false,
    futureRunnerMayBroadcastRealtime: false,
    futureRunnerMayBypassModeration: false,
    futureRunnerMayMountRuntime: false,
    futureRunnerMayChangeRouteBehavior: false,
    futureRunnerMayWriteTargetRoute: false,
    futureRunnerMayReturnFakeSuccess: false,
  },
  blockedNow: {
    runnerPackageCreatedNow: false,
    runnerExecutionAllowedNow: false,
    targetFileReadNow: false,
    targetHashCapturedNow: false,
    targetExcerptCapturedNow: false,
    routeAnchorsInspectedNow: false,
    authBoundaryInspectedNow: false,
    blockedRoutesInspectedNow: false,
    reportWrittenNow: false,
    targetPatchAllowed: false,
    targetRouteWriteAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    backendRestartAllowed: false,
    runtimePostAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    fakeSuccessAllowed: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-144I",
    exactApprovalRequiredBefore144I: true,
    opsOnlyCompileAndSafetyVerification: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimeHttpAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    targetRouteWriteAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy144H: false,
    appTsChangeBy144H: false,
    serverTsChangeBy144H: false,
    streamIndexChangeBy144H: false,
    prismaSchemaChangeBy144H: false,
    migrationCreatedBy144H: false,
    routeBehaviorChangeBy144H: false,
    backendRestartBy144H: false,
    runtimeHttpBy144H: false,
    runtimePostBy144H: false,
    runtimeDbReadBy144H: false,
    runtimeDbWriteBy144H: false,
    databaseReadBy144H: false,
    databaseWriteBy144H: false,
    providerCallBy144H: false,
    providerSecretReadBy144H: false,
    realtimeSocketOpenBy144H: false,
    realtimeBroadcastBy144H: false,
    moderationBypassBy144H: false,
    runtimeMountBy144H: false,
    targetRouteWriteBy144H: false,
    targetFileReadBy144H: false,
    targetHashCapturedBy144H: false,
    targetExcerptCapturedBy144H: false,
    rollbackExecutionBy144H: false,
    postMountSmokeBy144H: false,
    walletMutationBy144H: false,
    paymentAuthorizationBy144H: false,
    monthlyPayoutBy144H: false,
    moneyMovementBy144H: false,
    fakeSuccessBy144H: false,
  },
  readiness: getStreamFoundation144HRunnerApprovalReadiness(),
} as const;
