import { getStreamFoundationTargetPatchReviewHandoffControlledWriteApprovalPackageReadiness } from "./target-patch-review-handoff-controlled-write-approval-package";

export const STREAM_142K_TARGET_PATCH_REVIEW_HANDOFF_CONTROLLED_WRITE_APPROVAL_PACKAGE_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-142K",
  stage: "target_patch_review_handoff_and_controlled_target_write_approval_package",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/target-patch-review-handoff-controlled-write-approval-package/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-142J",
  currentRouteFreeze: {
    routesStayBlocked: true,
    expectedCurrentStatusCode: 423,
    targetWriteAllowedNow: false,
    routeBindingAllowedNow: false,
    routeBehaviorChangeAllowedNow: false,
    runtimePostAllowedNow: false,
    runtimeSuccessAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
  forbidden: {
    appTsChangeBy142K: false,
    serverTsChangeBy142K: false,
    streamIndexChangeBy142K: false,
    liveWriteHandlerChangeBy142K: false,
    schemaMigrationBy142K: false,
    backendRestartBy142K: false,
    runtimeHttpBy142K: false,
    runtimePostBy142K: false,
    databaseReadBy142K: false,
    databaseWriteBy142K: false,
    providerCallBy142K: false,
    providerSecretReadBy142K: false,
    walletMutationBy142K: false,
    paymentAuthorizationBy142K: false,
    monthlyPayoutBy142K: false,
    moneyMovementBy142K: false,
    fakeSuccessBy142K: false,
  },
  readiness: getStreamFoundationTargetPatchReviewHandoffControlledWriteApprovalPackageReadiness(),
} as const;
