import { getStreamFoundation144LTargetPatchPlanningReadiness } from "./target-patch-planning-144l";

export const STREAM_144L_TARGET_PATCH_PLANNING_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-144L",
  stage: "controlled_target_patch_planning_batch_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/target-patch-planning-144l/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-144K",
  candidateTargetsCompared: [
    "src/app.ts",
    "src/server.ts",
    "src/modules/stream/index.ts",
    "src/modules/admin/admin.routes.ts",
    "src/modules/stream/infrastructure/routes/stream.routes.ts",
    "src/modules/stream/infrastructure/routes/stream-live.routes.ts",
    "src/modules/stream/foundation/**",
  ],
  missingRouteFiles: [
    "src/modules/stream/infrastructure/routes/stream.routes.ts",
    "src/modules/stream/infrastructure/routes/stream-live.routes.ts",
  ],
  preferredDirection: "prefer_dedicated_stream_route_boundary_later",
  targetPatchDecisionMadeNow: false,
  sourceOnlyPlanningItems: [
    "candidate_target_comparison",
    "missing_stream_route_files_strategy",
    "dedicated_stream_route_files_option",
    "existing_foundation_routes_mount_option",
    "admin_routes_overload_guard",
    "auth_boundary_preservation",
    "blocked_route_preservation",
    "rollback_plan",
    "compile_gate",
    "owner_approval_gate",
  ],
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-144M",
    exactApprovalRequiredBefore144M: true,
    compileAndSafetyVerificationOpsOnly: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    createMissingRouteFilesAllowed: false,
    targetRouteWriteAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimeHttpAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy144L: false,
    appTsChangeBy144L: false,
    serverTsChangeBy144L: false,
    streamIndexChangeBy144L: false,
    adminRoutesChangeBy144L: false,
    missingRouteFileCreateBy144L: false,
    prismaSchemaChangeBy144L: false,
    migrationCreatedBy144L: false,
    routeBehaviorChangeBy144L: false,
    backendRestartBy144L: false,
    runtimeHttpBy144L: false,
    runtimePostBy144L: false,
    runtimeDbReadBy144L: false,
    runtimeDbWriteBy144L: false,
    databaseReadBy144L: false,
    databaseWriteBy144L: false,
    providerCallBy144L: false,
    providerSecretReadBy144L: false,
    realtimeSocketOpenBy144L: false,
    realtimeBroadcastBy144L: false,
    moderationBypassBy144L: false,
    runtimeMountBy144L: false,
    targetRouteWriteBy144L: false,
    rollbackExecutionBy144L: false,
    postMountSmokeBy144L: false,
    walletMutationBy144L: false,
    paymentAuthorizationBy144L: false,
    monthlyPayoutBy144L: false,
    moneyMovementBy144L: false,
    fakeSuccessBy144L: false,
  },
  readiness: getStreamFoundation144LTargetPatchPlanningReadiness(),
} as const;
