import { getStreamFoundationPostPatchRuntimeSmokeApprovalPackageReadiness } from "./post-patch-handoff-runtime-smoke-approval-package";

export const STREAM_142P_POST_PATCH_HANDOFF_RUNTIME_SMOKE_APPROVAL_PACKAGE_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-142P",
  stage: "post_patch_handoff_and_controlled_blocked_route_runtime_smoke_approval_package",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/post-patch-handoff-runtime-smoke-approval-package/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-142O-FIX2",
  verification142OFix2: {
    ok: true,
    routeBindingPassed: 3,
    runtimeImportOk: true,
    routePatchContextSafetyOk: true,
    tscExitCode: 0,
    runtimePostPerformed: 0,
    databaseWritePerformed: 0,
    providerCallPerformed: 0,
    walletMutationPerformed: 0,
    moneyMovementPerformed: 0,
    fakeSuccessAllowed: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-142Q",
    exactApprovalRequiredBefore142Q: true,
    controlledRuntimePostSmokeAllowedOnlyAfterApproval: true,
    routes: [
      "/api/stream/live/start",
      "/api/stream/live/stop",
      "/api/stream/live/heartbeat",
    ],
    expectedStatusCode: 423,
    backendRestartAllowedFor142Q: false,
    sourceWriteAllowedFor142Q: false,
    databaseWriteAllowedFor142Q: false,
    providerCallAllowedFor142Q: false,
    walletMutationAllowedFor142Q: false,
    moneyMovementAllowedFor142Q: false,
    fakeSuccessAllowedFor142Q: false,
  },
  forbidden: {
    targetWriteBy142P: false,
    backendRestartBy142P: false,
    runtimeHttpBy142P: false,
    runtimePostBy142P: false,
    databaseReadBy142P: false,
    databaseWriteBy142P: false,
    providerCallBy142P: false,
    providerSecretReadBy142P: false,
    walletMutationBy142P: false,
    paymentAuthorizationBy142P: false,
    monthlyPayoutBy142P: false,
    moneyMovementBy142P: false,
    fakeSuccessBy142P: false,
  },
  readiness: getStreamFoundationPostPatchRuntimeSmokeApprovalPackageReadiness(),
} as const;
