import { getStreamFoundationRepositoryBoundaryContractsScaffoldReadiness } from "./live-runtime-repository-boundary-contracts";

export const STREAM_143B_REPOSITORY_BOUNDARY_CONTRACTS_SCAFFOLD_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-143B",
  stage: "controlled_live_runtime_repository_boundary_contracts_scaffold_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/live-runtime-repository-boundary-contracts/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-143A",
  contractGroups: [
    "repository_interface_contracts",
    "idempotency_key_contracts",
    "transaction_boundary_contracts",
    "persistence_safety_envelope",
    "record_drafts",
  ],
  schemaAndMigration: {
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    schemaPatchAllowedNow: false,
  },
  runtimeBoundary: {
    repositoryImplementationAllowedNow: false,
    repositoryMountAllowedNow: false,
    runtimeDbReadAllowedNow: false,
    runtimeDbWriteAllowedNow: false,
    routeBehaviorChangeAllowedNow: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-143C",
    exactApprovalRequiredBefore143C: true,
    opsOnlyCompileAndSafetyVerification: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy143B: false,
    appTsChangeBy143B: false,
    serverTsChangeBy143B: false,
    streamIndexChangeBy143B: false,
    prismaSchemaChangeBy143B: false,
    migrationCreatedBy143B: false,
    routeBehaviorChangeBy143B: false,
    backendRestartBy143B: false,
    runtimeHttpBy143B: false,
    runtimePostBy143B: false,
    databaseReadBy143B: false,
    databaseWriteBy143B: false,
    providerCallBy143B: false,
    providerSecretReadBy143B: false,
    walletMutationBy143B: false,
    paymentAuthorizationBy143B: false,
    monthlyPayoutBy143B: false,
    moneyMovementBy143B: false,
    fakeSuccessBy143B: false,
  },
  readiness: getStreamFoundationRepositoryBoundaryContractsScaffoldReadiness(),
} as const;
