import { getStreamFoundationRuntimeMountTargetPatchReviewPackagePlanningReadiness } from "./runtime-mount-target-patch-review-package-planning";

export const STREAM_143V_RUNTIME_MOUNT_TARGET_PATCH_REVIEW_PACKAGE_PLANNING_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-143V",
  stage: "controlled_runtime_mount_target_patch_review_package_planning_source_only",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/runtime-mount-target-patch-review-package-planning/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-143U",
  contractGroups: [
    "target_patch_package_review",
    "exact_target_candidate_selection",
    "exact_insertion_marker_review",
    "duplicate_mount_risk_gate",
    "auth_boundary_preservation_gate",
    "blocked_route_preservation_gate",
    "rollback_package_plan",
    "compile_gate",
    "owner_approval_gate",
  ],
  blockedNow: {
    targetPatchPackageCreatedNow: false,
    proposedDiffAppliedNow: false,
    targetWriteAllowed: false,
    targetRouteWriteAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    backendRestartAllowed: false,
    runtimePostAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    fakeSuccessAllowed: false,
  },
  nextStageScope: {
    nextStage: "BACKEND-STREAM-FOUNDATION-143W",
    exactApprovalRequiredBefore143W: true,
    opsOnlyCompileAndSafetyVerification: true,
    sourceModificationAllowed: false,
    writeTargetsAllowed: false,
    prismaSchemaWriteAllowed: false,
    migrationAllowed: false,
    backendRestartAllowed: false,
    runtimeHttpAllowed: false,
    runtimePostAllowed: false,
    runtimeDbReadAllowed: false,
    runtimeDbWriteAllowed: false,
    providerCallAllowed: false,
    providerSecretReadAllowed: false,
    realtimeSocketOpenAllowed: false,
    realtimeBroadcastAllowed: false,
    moderationBypassAllowed: false,
    runtimeMountAllowed: false,
    routeBehaviorChangeAllowed: false,
    targetRouteWriteAllowed: false,
    rollbackExecutionAllowed: false,
    postMountSmokeAllowed: false,
    walletMutationAllowed: false,
    moneyMovementAllowed: false,
    fakeSuccessAllowed: false,
  },
  forbidden: {
    targetWriteBy143V: false,
    appTsChangeBy143V: false,
    serverTsChangeBy143V: false,
    streamIndexChangeBy143V: false,
    prismaSchemaChangeBy143V: false,
    migrationCreatedBy143V: false,
    routeBehaviorChangeBy143V: false,
    backendRestartBy143V: false,
    runtimeHttpBy143V: false,
    runtimePostBy143V: false,
    runtimeDbReadBy143V: false,
    runtimeDbWriteBy143V: false,
    databaseReadBy143V: false,
    databaseWriteBy143V: false,
    providerCallBy143V: false,
    providerSecretReadBy143V: false,
    realtimeSocketOpenBy143V: false,
    realtimeBroadcastBy143V: false,
    moderationBypassBy143V: false,
    runtimeMountBy143V: false,
    targetRouteWriteBy143V: false,
    rollbackExecutionBy143V: false,
    postMountSmokeBy143V: false,
    walletMutationBy143V: false,
    paymentAuthorizationBy143V: false,
    monthlyPayoutBy143V: false,
    moneyMovementBy143V: false,
    fakeSuccessBy143V: false,
  },
  readiness: getStreamFoundationRuntimeMountTargetPatchReviewPackagePlanningReadiness(),
} as const;
