import { getStreamFoundationPostRuntimeSmokeVerificationHandoffReadiness } from "./post-runtime-smoke-verification-handoff";

export const STREAM_142R_POST_RUNTIME_SMOKE_VERIFICATION_HANDOFF_STAGING_MANIFEST = {
  version: "BACKEND-STREAM-FOUNDATION-142R",
  stage: "post_runtime_smoke_verification_and_foundation_handoff",
  sourceOnly: true,
  changedScope: "src/modules/stream/foundation/post-runtime-smoke-verification-handoff/**",
  previousStage: "BACKEND-STREAM-FOUNDATION-142Q",
  verifiedRuntimeSmoke: {
    ok: true,
    status: "controlled_blocked_route_runtime_post_smoke_passed",
    baseUrl: "http://127.0.0.1:4001",
    attemptedRoutes: 3,
    passedRoutes: 3,
    expectedStatusCode: 423,
    tscExitCode: 0,
    runtimePostPerformed: 3,
    databaseWritePerformed: 0,
    providerCallPerformed: 0,
    walletMutationPerformed: 0,
    moneyMovementPerformed: 0,
    fakeSuccessAllowed: false,
  },
  followUp: {
    responseBodiesWereEmptyIn142Q: true,
    emptyBodyDoesNotIndicateSuccess: true,
    nextStage: "BACKEND-STREAM-FOUNDATION-142S",
    exactApprovalRequiredBefore142S: true,
    sourceOnlyPlanning: true,
  },
  forbidden: {
    targetWriteBy142R: false,
    backendRestartBy142R: false,
    runtimeHttpBy142R: false,
    runtimePostBy142R: false,
    databaseReadBy142R: false,
    databaseWriteBy142R: false,
    providerCallBy142R: false,
    providerSecretReadBy142R: false,
    walletMutationBy142R: false,
    paymentAuthorizationBy142R: false,
    monthlyPayoutBy142R: false,
    moneyMovementBy142R: false,
    fakeSuccessBy142R: false,
  },
  readiness: getStreamFoundationPostRuntimeSmokeVerificationHandoffReadiness(),
} as const;
