import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAdminDashboardActionStateContract,
  TaxiAdminDashboardFilterContract,
  TaxiAdminDashboardPanelContract,
  TaxiAdminDashboardVersion,
} from './taxiAdminDashboard.types';

export const TAXI_ADMIN_DASHBOARD_VERSION: TaxiAdminDashboardVersion = 'TAXI-BACKEND-FOUNDATION-001H-FIX1';

export const TAXI_ADMIN_DASHBOARD_FILTERS: readonly TaxiAdminDashboardFilterContract[] = [
  {
    filterId: 'filter_country_iso2',
    title: 'Country filter',
    filterKey: 'country_iso2',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_calendar_day',
    title: 'Calendar day filter',
    filterKey: 'calendar_day',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_participant_role',
    title: 'Driver/rider role filter',
    filterKey: 'participant_role',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_complaint_tier',
    title: 'Daily complaint tier filter',
    filterKey: 'complaint_tier',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_ai_confidence',
    title: 'Sabi AI confidence filter',
    filterKey: 'ai_confidence',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: false,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_review_status',
    title: 'Review status filter',
    filterKey: 'review_status',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_appeal_status',
    title: 'Appeal status filter',
    filterKey: 'appeal_status',
    requiredForDailyReport: true,
    requiredForComplaintReview: true,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
  {
    filterId: 'filter_reward_freeze_status',
    title: 'Reward freeze status filter',
    filterKey: 'reward_freeze_status',
    requiredForDailyReport: true,
    requiredForComplaintReview: false,
    requiredForLeagueFairness: true,
    adminVisible: true,
    mobileVisible: false,
    runtimeQueryEnabledNow: false,
  },
] as const;

export const TAXI_ADMIN_DASHBOARD_ACTION_STATES: readonly TaxiAdminDashboardActionStateContract[] = [
  {
    stateId: 'no_action_clean_day',
    title: 'Clean country/day participant status',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: false,
    requiresAdminDecision: false,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'needs_sabi_ai_review',
    title: 'Needs Sabi AI review',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: false,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'needs_admin_review',
    title: 'Needs Admin review',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'needs_participant_explanation',
    title: 'Needs participant explanation before hard action',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: true,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'cooldown_candidate',
    title: 'Cooldown candidate after verified daily tier',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'hard_block_candidate',
    title: 'Hard block candidate after more than three verified daily complaints',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: true,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'reward_freeze_candidate',
    title: 'Reward freeze candidate while complaint or appeal is open',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
  {
    stateId: 'restore_candidate',
    title: 'Restore candidate after false complaint or clean Admin decision',
    appliesToDrivers: true,
    appliesToRiders: true,
    requiresCountryDayScope: true,
    requiresSabiAiEvidence: true,
    requiresAdminDecision: true,
    requiresAppealWindow: false,
    canExecuteNow: false,
    fakePenaltyBlocked: true,
    fakeRewardBlocked: true,
  },
] as const;

export const TAXI_ADMIN_DASHBOARD_PANELS: readonly TaxiAdminDashboardPanelContract[] = [
  {
    panelId: 'daily_ai_report_dashboard',
    title: 'Daily Sabi AI report dashboard',
    purpose: 'Show required daily AI report status by country, day and participant role.',
    usesFoundationContracts: true,
    compatibleWithClientBoundarySummary: true,
    containsRawEvidenceForMobile: false,
    adminOnlyRawEvidence: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'complaint_review_board',
    title: 'Complaint review board',
    purpose: 'Review complaint tiers, false complaint signals, cancellation abuse and trip-after-cancel signals before action.',
    usesFoundationContracts: true,
    compatibleWithClientBoundarySummary: true,
    containsRawEvidenceForMobile: false,
    adminOnlyRawEvidence: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'action_state_board',
    title: 'Action-state board',
    purpose: 'Separate pending AI review, Admin review, appeal window, cooldown candidate, hard block candidate, reward freeze and restore candidate.',
    usesFoundationContracts: true,
    compatibleWithClientBoundarySummary: true,
    containsRawEvidenceForMobile: false,
    adminOnlyRawEvidence: true,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
  {
    panelId: 'kernel_safe_mobile_summary_board',
    title: 'Kernel-safe mobile summary board',
    purpose: 'Define the safe status summaries that client app may display through the Taxi kernel only.',
    usesFoundationContracts: true,
    compatibleWithClientBoundarySummary: true,
    containsRawEvidenceForMobile: false,
    adminOnlyRawEvidence: false,
    runtimeMountedNow: false,
    fakeSuccessBlocked: true,
  },
] as const;

export const taxiAdminDashboardRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/taxi/admin/dashboard/contracts',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin dashboard contracts for daily Sabi AI reports, complaint filters and action-state boards.',
  },
  {
    method: 'GET',
    path: '/api/taxi/admin/dashboard/daily-country-day',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future country/day dashboard read route, blocked until exact runtime approval and DB read approval.',
  },
  {
    method: 'POST',
    path: '/api/taxi/admin/dashboard/action-state/preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future action-state preview route; no real sanctions, rewards or status changes from this foundation patch.',
  },
] as const;
