import type { StreamPremiumGiftAsset187A } from "./streamPremiumGiftPack187A";
import type { StreamPremiumGiftEffectProfile187B } from "./streamPremiumGiftEffects187B";
import type { StreamPremiumGiftPreviewExperience187C } from "./streamPremiumGiftPreviewExperience187C";
import type { StreamPremiumGiftFinalPolish187D } from "./streamPremiumGiftFinalPolish187D";
import type { StreamPremiumGiftAppearanceProfile188G } from "./streamPremiumGiftAppearanceEngine188G";
import type { StreamPremiumGiftVisualFxProfile188H } from "./streamPremiumGiftVisualFxPack188H";
import type { StreamPremiumGiftFinalScreenPolish188I } from "./streamPremiumGiftFinalScreenPolish188I";

export const streamPremiumGiftPack197ABasePath = "assets/stream/gifts/197a-pack-4-ultra-premium" as const;

export const streamPremiumGiftPack197A: StreamPremiumGiftAsset187A[] = [
  {
    id: "celestial-tiger-crown", displayName: "Celestial Tiger Crown", displayNameRu: "Небесный Тигр", iconName: "flash-outline", legacyTitleKey: "giftTierPremium", catalogSegment: "premium",
    previewRu: "небесный тигр прыгает через коронный свет", localCostLabel: "95 demo-points · fair Legendary preview", effectLabel: "tiger crown sky leap", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "celestial gold", safetyBadge: "fair price · preview only", rarityLabel: "Legendary Crown", motionSpec: "tiger leap, crown light, sky ribbon trail", posterFile: "celestial-tiger-crown.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "diamond-sakura-palace", displayName: "Diamond Sakura Palace", displayNameRu: "Алмазная Сакура", iconName: "flower-outline", legacyTitleKey: "giftTierPremium", catalogSegment: "anime",
    previewRu: "алмазный дворец раскрывает сакура-лепестки", localCostLabel: "120 demo-points · fair Legendary preview", effectLabel: "diamond sakura palace bloom", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "diamond sakura", safetyBadge: "fair price · preview only", rarityLabel: "Legendary Sakura", motionSpec: "palace gate, diamond petals, rose-gold shimmer", posterFile: "diamond-sakura-palace.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "aurora-phoenix-parade", displayName: "Aurora Phoenix Parade", displayNameRu: "Аврора Феникс", iconName: "flame-outline", legacyTitleKey: "giftTierUltra", catalogSegment: "premium",
    previewRu: "феникс проходит по аврора-параду", localCostLabel: "180 demo-points · fair Mythic preview", effectLabel: "aurora phoenix parade", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "aurora fire", safetyBadge: "fair price · preview only", rarityLabel: "Mythic Aurora", motionSpec: "phoenix wing, aurora curtain, feather comet", posterFile: "aurora-phoenix-parade.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "royal-galaxy-yacht", displayName: "Royal Galaxy Yacht", displayNameRu: "Галактика Яхта", iconName: "boat-outline", legacyTitleKey: "giftTierUltra", catalogSegment: "premium",
    previewRu: "галактическая яхта выходит через звёздный портал", localCostLabel: "210 demo-points · fair Mythic preview", effectLabel: "royal galaxy yacht reveal", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "galaxy royal", safetyBadge: "fair price · preview only", rarityLabel: "Mythic Royal", motionSpec: "yacht glide, star portal, velvet comet trail", posterFile: "royal-galaxy-yacht.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "crystal-lotus-dragon", displayName: "Crystal Lotus Dragon", displayNameRu: "Лотос Дракон", iconName: "sparkles-outline", legacyTitleKey: "giftTierUltra", catalogSegment: "anime",
    previewRu: "кристальный дракон раскрывает лотос над сценой", localCostLabel: "260 demo-points · fair Ultra Mythic preview", effectLabel: "crystal lotus dragon bloom", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "crystal lotus", safetyBadge: "fair price · preview only", rarityLabel: "Ultra Mythic Lotus", motionSpec: "lotus open, dragon orbit, crystal bloom finale", posterFile: "crystal-lotus-dragon.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "neon-opera-idol", displayName: "Neon Opera Idol", displayNameRu: "Неон Опера", iconName: "mic-outline", legacyTitleKey: "giftTierPremium", catalogSegment: "sound",
    previewRu: "idol-сцена открывает неоновую оперу", localCostLabel: "85 demo-points · fair Epic preview", effectLabel: "neon opera idol stage", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "opera neon", safetyBadge: "fair price · preview only", rarityLabel: "Epic Sound", motionSpec: "opera curtain, idol beam, neon note trail", posterFile: "neon-opera-idol.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "golden-falcon-crown", displayName: "Golden Falcon Crown", displayNameRu: "Золотой Сокол", iconName: "shield-checkmark-outline", legacyTitleKey: "giftTierPremium", catalogSegment: "premium",
    previewRu: "золотой сокол несёт crown flare через эфир", localCostLabel: "150 demo-points · fair Legendary preview", effectLabel: "golden falcon crown flight", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "falcon gold", safetyBadge: "fair price · preview only", rarityLabel: "Legendary Falcon", motionSpec: "falcon dive, crown flare, gold feather trail", posterFile: "golden-falcon-crown.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  },
  {
    id: "imperial-dragon-meteor", displayName: "Imperial Dragon Meteor", displayNameRu: "Имперский Дракон", iconName: "planet-outline", legacyTitleKey: "giftTierUltra", catalogSegment: "premium",
    previewRu: "имперский дракон закрывает сцену метеорным финалом", localCostLabel: "340 demo-points · fair Ultra Mythic preview", effectLabel: "imperial dragon meteor finale", qualityLabel: "ultra premium poster + FX spec", loopLabel: "3.6 сек ultra loop план", visualTone: "imperial cosmic", safetyBadge: "fair price · preview only", rarityLabel: "Ultra Mythic Dragon", motionSpec: "dragon gate, meteor rain, imperial finale burst", posterFile: "imperial-dragon-meteor.svg", posterFallbackReady: true, mp4LoopPlanned: true, providerRuntimeReadyNow: false, paymentReadyNow: false, payoutReadyNow: false, sendRuntimeReadyNow: false
  }
];

export const streamPremiumGiftPack197AIds = new Set(streamPremiumGiftPack197A.map((gift) => gift.id));

export const streamPremiumGiftPack197AEffectProfiles: StreamPremiumGiftEffectProfile187B[] = [
  { assetId: "celestial-tiger-crown", liveEffectLabel: "tiger crown sky leap", intensityLabel: "Legendary fair impact", soundCueLabel: "tiger crown hit", soundCueLabelRu: "tiger crown hit", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/celestial-tiger-crown-cue.wav`, soundCueDurationMs: 1200, hapticLabel: "strong premium impact", hapticImpactStyle: "strong", colorA: "#FFD76B", colorB: "#6EC6FF", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "diamond-sakura-palace", liveEffectLabel: "diamond sakura palace bloom", intensityLabel: "Legendary fair impact", soundCueLabel: "diamond sakura chime", soundCueLabelRu: "diamond sakura chime", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/diamond-sakura-palace-cue.wav`, soundCueDurationMs: 1320, hapticLabel: "medium premium impact", hapticImpactStyle: "medium", colorA: "#FF9BD5", colorB: "#BDEBFF", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "aurora-phoenix-parade", liveEffectLabel: "aurora phoenix parade", intensityLabel: "Mythic fair impact", soundCueLabel: "phoenix aurora rise", soundCueLabelRu: "phoenix aurora rise", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/aurora-phoenix-parade-cue.wav`, soundCueDurationMs: 1440, hapticLabel: "finale premium impact", hapticImpactStyle: "finale", colorA: "#FF7A3D", colorB: "#7CFFD9", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "royal-galaxy-yacht", liveEffectLabel: "royal galaxy yacht reveal", intensityLabel: "Mythic fair impact", soundCueLabel: "galaxy yacht shimmer", soundCueLabelRu: "galaxy yacht shimmer", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/royal-galaxy-yacht-cue.wav`, soundCueDurationMs: 1560, hapticLabel: "strong premium impact", hapticImpactStyle: "strong", colorA: "#7D6BFF", colorB: "#F2C75B", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "crystal-lotus-dragon", liveEffectLabel: "crystal lotus dragon bloom", intensityLabel: "Ultra Mythic fair impact", soundCueLabel: "crystal lotus dragon hit", soundCueLabelRu: "crystal lotus dragon hit", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/crystal-lotus-dragon-cue.wav`, soundCueDurationMs: 1680, hapticLabel: "finale premium impact", hapticImpactStyle: "finale", colorA: "#A6F7FF", colorB: "#C38CFF", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "neon-opera-idol", liveEffectLabel: "neon opera idol stage", intensityLabel: "Epic fair impact", soundCueLabel: "opera neon cue", soundCueLabelRu: "opera neon cue", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/neon-opera-idol-cue.wav`, soundCueDurationMs: 1800, hapticLabel: "medium premium impact", hapticImpactStyle: "medium", colorA: "#FF4FD8", colorB: "#00F5FF", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "golden-falcon-crown", liveEffectLabel: "golden falcon crown flight", intensityLabel: "Legendary fair impact", soundCueLabel: "falcon crown sweep", soundCueLabelRu: "falcon crown sweep", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/golden-falcon-crown-cue.wav`, soundCueDurationMs: 1920, hapticLabel: "strong premium impact", hapticImpactStyle: "strong", colorA: "#FFD24A", colorB: "#FF8F1F", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false },
  { assetId: "imperial-dragon-meteor", liveEffectLabel: "imperial dragon meteor finale", intensityLabel: "Ultra Mythic fair impact", soundCueLabel: "imperial dragon meteor", soundCueLabelRu: "imperial dragon meteor", soundCueFile: `${streamPremiumGiftPack197ABasePath}/sound-cues/imperial-dragon-meteor-cue.wav`, soundCueDurationMs: 2040, hapticLabel: "finale premium impact", hapticImpactStyle: "finale", colorA: "#FF5B4A", colorB: "#9B5CFF", phases: ["signature entrance", "ultra premium loop", "clean finale burst"], visualFx: ["cinematic glow", "premium particles", "safe-area trail"], reducedMotionFallback: "poster-first fallback + readable labels, no heavy playback", localSoundAssetReady: true, localHapticMetadataReady: true, livePreviewRuntimeReadyNow: true, soundPlaybackRuntimeEnabledNow: false, backendRuntimeReadyNow: false, paymentRuntimeReadyNow: false, payoutRuntimeReadyNow: false, realSendRuntimeReadyNow: false }
];

export const streamPremiumGiftPack197APreviewExperiences: StreamPremiumGiftPreviewExperience187C[] = [
  { assetId: "celestial-tiger-crown", stageLightingLabel: "celestial gold ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: tiger crown hit", hapticPreviewLabel: "haptic label: strong impact", liveSceneCopyRu: "Небесный Тигр выглядит дорого: небесный тигр прыгает через коронный свет с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 95 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Небесный Тигр, ultra premium gift preview, fair price 95 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "diamond-sakura-palace", stageLightingLabel: "diamond sakura ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: diamond sakura chime", hapticPreviewLabel: "haptic label: medium impact", liveSceneCopyRu: "Алмазная Сакура выглядит дорого: алмазный дворец раскрывает сакура-лепестки с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 120 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Алмазная Сакура, ultra premium gift preview, fair price 120 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "aurora-phoenix-parade", stageLightingLabel: "aurora fire ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: phoenix aurora rise", hapticPreviewLabel: "haptic label: finale impact", liveSceneCopyRu: "Аврора Феникс выглядит дорого: феникс проходит по аврора-параду с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 180 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Аврора Феникс, ultra premium gift preview, fair price 180 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "royal-galaxy-yacht", stageLightingLabel: "galaxy royal ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: galaxy yacht shimmer", hapticPreviewLabel: "haptic label: strong impact", liveSceneCopyRu: "Галактика Яхта выглядит дорого: галактическая яхта выходит через звёздный портал с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 210 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Галактика Яхта, ultra premium gift preview, fair price 210 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "crystal-lotus-dragon", stageLightingLabel: "crystal lotus ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: crystal lotus dragon hit", hapticPreviewLabel: "haptic label: finale impact", liveSceneCopyRu: "Лотос Дракон выглядит дорого: кристальный дракон раскрывает лотос над сценой с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 260 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Лотос Дракон, ultra premium gift preview, fair price 260 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "neon-opera-idol", stageLightingLabel: "opera neon ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: opera neon cue", hapticPreviewLabel: "haptic label: medium impact", liveSceneCopyRu: "Неон Опера выглядит дорого: idol-сцена открывает неоновую оперу с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 85 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Неон Опера, ultra premium gift preview, fair price 85 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "golden-falcon-crown", stageLightingLabel: "falcon gold ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: falcon crown sweep", hapticPreviewLabel: "haptic label: strong impact", liveSceneCopyRu: "Золотой Сокол выглядит дорого: золотой сокол несёт crown flare через эфир с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 150 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Золотой Сокол, ultra premium gift preview, fair price 150 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "imperial-dragon-meteor", stageLightingLabel: "imperial cosmic ultra stage", motionQualityLabel: "premium 60fps target spec · preview only", soundPreviewLabel: "sound label: imperial dragon meteor", hapticPreviewLabel: "haptic label: finale impact", liveSceneCopyRu: "Имперский Дракон выглядит дорого: имперский дракон закрывает сцену метеорным финалом с чистым glow, trail и finale burst.", safeModeCopyRu: "Цена соответствует quality tier: 340 demo-points preview; нет оплаты, списания, backend и реальной отправки.", screenReaderHintRu: "Имперский Дракон, ultra premium gift preview, fair price 340 demo-points, no charge no send.", phaseChips: ["ultra entrance", "cinematic loop", "clean finale"], qualityBadges: ["fair price", "poster-first", "no autoplay"], defaultQuality: "ultra", localPreviewUiReadyNow: true, actualSoundPlaybackRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false }
];

export const streamPremiumGiftPack197AFinalPolishProfiles: StreamPremiumGiftFinalPolish187D[] = [
  { assetId: "celestial-tiger-crown", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/celestial-tiger-crown.svg`, animeStyleLabel: "ultra premium anime · celestial gold", premiumBadge: "Legendary · fair 95", catalogHeroCopyRu: "Небесный Тигр — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "celestial gold aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "tiger leap, crown light, sky ribbon trail", soundSignature: "tiger crown hit, label/no autoplay", hapticSignature: "strong impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Legendary", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "diamond-sakura-palace", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/diamond-sakura-palace.svg`, animeStyleLabel: "ultra premium anime · diamond sakura", premiumBadge: "Legendary · fair 120", catalogHeroCopyRu: "Алмазная Сакура — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "diamond sakura aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "palace gate, diamond petals, rose-gold shimmer", soundSignature: "diamond sakura chime, label/no autoplay", hapticSignature: "medium impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Legendary", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "aurora-phoenix-parade", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/aurora-phoenix-parade.svg`, animeStyleLabel: "ultra premium anime · aurora fire", premiumBadge: "Mythic · fair 180", catalogHeroCopyRu: "Аврора Феникс — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "aurora fire aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "phoenix wing, aurora curtain, feather comet", soundSignature: "phoenix aurora rise, label/no autoplay", hapticSignature: "finale impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Mythic", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "royal-galaxy-yacht", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/royal-galaxy-yacht.svg`, animeStyleLabel: "ultra premium anime · galaxy royal", premiumBadge: "Mythic · fair 210", catalogHeroCopyRu: "Галактика Яхта — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "galaxy royal aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "yacht glide, star portal, velvet comet trail", soundSignature: "galaxy yacht shimmer, label/no autoplay", hapticSignature: "strong impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Mythic", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "crystal-lotus-dragon", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/crystal-lotus-dragon.svg`, animeStyleLabel: "ultra premium anime · crystal lotus", premiumBadge: "Ultra Mythic · fair 260", catalogHeroCopyRu: "Лотос Дракон — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "crystal lotus aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "lotus open, dragon orbit, crystal bloom finale", soundSignature: "crystal lotus dragon hit, label/no autoplay", hapticSignature: "finale impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Ultra Mythic", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "neon-opera-idol", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/neon-opera-idol.svg`, animeStyleLabel: "ultra premium anime · opera neon", premiumBadge: "Epic · fair 85", catalogHeroCopyRu: "Неон Опера — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "opera neon aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "opera curtain, idol beam, neon note trail", soundSignature: "opera neon cue, label/no autoplay", hapticSignature: "medium impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Epic", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "golden-falcon-crown", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/golden-falcon-crown.svg`, animeStyleLabel: "ultra premium anime · falcon gold", premiumBadge: "Legendary · fair 150", catalogHeroCopyRu: "Золотой Сокол — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "falcon gold aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "falcon dive, crown flare, gold feather trail", soundSignature: "falcon crown sweep, label/no autoplay", hapticSignature: "strong impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Legendary", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false },
  { assetId: "imperial-dragon-meteor", heroPosterFile: `${streamPremiumGiftPack197ABasePath}/posters/imperial-dragon-meteor.svg`, animeStyleLabel: "ultra premium anime · imperial cosmic", premiumBadge: "Ultra Mythic · fair 340", catalogHeroCopyRu: "Имперский Дракон — дорогой premium gift без мусорного эффекта: чистый entrance, layered glow, readable finale.", stageAuraCopyRu: "imperial cosmic aura, fair-price chip, poster-first fallback и no autoplay safety.", visualSignature: "dragon gate, meteor rain, imperial finale burst", soundSignature: "imperial dragon meteor, label/no autoplay", hapticSignature: "finale impact, local metadata", posterDetailChips: ["ultra poster", "fair price", "clean FX"], polishBadgeChips: ["Pack 4", "Ultra Mythic", "quality checked"], finalSafetyCopyRu: "Preview only: no real send, no payment, no Wallet mutation, no payout, no fake money movement.", finalPolishReadyNow: true, posterFallbackReadyNow: true, localPreviewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, realSendRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false }
];

export const streamPremiumGiftPack197AAppearanceProfiles: StreamPremiumGiftAppearanceProfile188G[] = [
  { assetId: "celestial-tiger-crown", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Небесный Тигр · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · celestial gold", entranceRu: "premium entrance: небесный тигр прыгает через коронный свет", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 940, loopDurationMs: 2650, finaleDurationMs: 980, stageLightingRu: "celestial gold luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "tiger leap, crown light, sky ribbon trail", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "tiger crown hit label only", hapticHitRu: "strong haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "diamond-sakura-palace", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Алмазная Сакура · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · diamond sakura", entranceRu: "premium entrance: алмазный дворец раскрывает сакура-лепестки", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 965, loopDurationMs: 2710, finaleDurationMs: 1015, stageLightingRu: "diamond sakura luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "palace gate, diamond petals, rose-gold shimmer", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "diamond sakura chime label only", hapticHitRu: "medium haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "aurora-phoenix-parade", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Аврора Феникс · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · aurora fire", entranceRu: "premium entrance: феникс проходит по аврора-параду", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 990, loopDurationMs: 2770, finaleDurationMs: 1050, stageLightingRu: "aurora fire luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "phoenix wing, aurora curtain, feather comet", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "phoenix aurora rise label only", hapticHitRu: "finale haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "royal-galaxy-yacht", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Галактика Яхта · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · galaxy royal", entranceRu: "premium entrance: галактическая яхта выходит через звёздный портал", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 1015, loopDurationMs: 2830, finaleDurationMs: 1085, stageLightingRu: "galaxy royal luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "yacht glide, star portal, velvet comet trail", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "galaxy yacht shimmer label only", hapticHitRu: "strong haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "crystal-lotus-dragon", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Лотос Дракон · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · crystal lotus", entranceRu: "premium entrance: кристальный дракон раскрывает лотос над сценой", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 1040, loopDurationMs: 2890, finaleDurationMs: 1120, stageLightingRu: "crystal lotus luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "lotus open, dragon orbit, crystal bloom finale", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "crystal lotus dragon hit label only", hapticHitRu: "finale haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "neon-opera-idol", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Неон Опера · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · opera neon", entranceRu: "premium entrance: idol-сцена открывает неоновую оперу", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 1065, loopDurationMs: 2950, finaleDurationMs: 1155, stageLightingRu: "opera neon luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "opera curtain, idol beam, neon note trail", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "opera neon cue label only", hapticHitRu: "medium haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "golden-falcon-crown", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Золотой Сокол · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · falcon gold", entranceRu: "premium entrance: золотой сокол несёт crown flare через эфир", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 1090, loopDurationMs: 3010, finaleDurationMs: 1190, stageLightingRu: "falcon gold luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "falcon dive, crown flare, gold feather trail", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "falcon crown sweep label only", hapticHitRu: "strong haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "imperial-dragon-meteor", packLabelRu: "Pack 4 · Ultra Premium", appearanceTitleRu: "Имперский Дракон · Ultra Premium Appearance", fullScreenLayerRu: "cinematic full-screen safe-area layer · imperial cosmic", entranceRu: "premium entrance: имперский дракон закрывает сцену метеорным финалом", loopRu: "layered loop: glow, aura, recipient focus, clean particles", finaleRu: "ultra finale: no clutter, high-value burst and soft fade", entranceDurationMs: 1115, loopDurationMs: 3070, finaleDurationMs: 1225, stageLightingRu: "imperial cosmic luxury lighting", backgroundDimRu: "premium dim 28% with readable chat", particleSystemRu: "quality particles, controlled density, no noisy spam", motionTrailRu: "dragon gate, meteor rain, imperial finale burst", recipientFocusRu: "creator/recipient halo remains readable", soundHitRu: "imperial dragon meteor label only", hapticHitRu: "finale haptic metadata only", luxuryMoodRu: "ultra premium, not fake, not cheap", appearanceChipsRu: ["Pack 4", "fair price", "ultra FX", "poster-first", "safe"], fallbackCopyRu: "Lite mode: premium poster + glow + copy, no heavy playback", safetyCopyRu: "197A appearance metadata only: no backend, no payment, no provider, no real send, no payout, no random win.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, randomWinRuntimeEnabledNow: false }
];

export const streamPremiumGiftPack197AVisualFxProfiles: StreamPremiumGiftVisualFxProfile188H[] = [
  { assetId: "celestial-tiger-crown", visualFxTitleRu: "Небесный Тигр · Ultra Premium FX", primaryGlowRu: "celestial gold cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "tiger leap, crown light, sky ribbon trail", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "celestial gold luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 1700, auraPulseMs: 820, premiumFxScore: 94, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "diamond-sakura-palace", visualFxTitleRu: "Алмазная Сакура · Ultra Premium FX", primaryGlowRu: "diamond sakura cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "palace gate, diamond petals, rose-gold shimmer", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "diamond sakura luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 1810, auraPulseMs: 855, premiumFxScore: 95, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "aurora-phoenix-parade", visualFxTitleRu: "Аврора Феникс · Ultra Premium FX", primaryGlowRu: "aurora fire cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "phoenix wing, aurora curtain, feather comet", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "aurora fire luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 1920, auraPulseMs: 890, premiumFxScore: 96, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "royal-galaxy-yacht", visualFxTitleRu: "Галактика Яхта · Ultra Premium FX", primaryGlowRu: "galaxy royal cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "yacht glide, star portal, velvet comet trail", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "galaxy royal luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 2030, auraPulseMs: 925, premiumFxScore: 97, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "crystal-lotus-dragon", visualFxTitleRu: "Лотос Дракон · Ultra Premium FX", primaryGlowRu: "crystal lotus cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "lotus open, dragon orbit, crystal bloom finale", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "crystal lotus luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 2140, auraPulseMs: 960, premiumFxScore: 98, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "neon-opera-idol", visualFxTitleRu: "Неон Опера · Ultra Premium FX", primaryGlowRu: "opera neon cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "opera curtain, idol beam, neon note trail", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "opera neon luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 2250, auraPulseMs: 995, premiumFxScore: 99, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "golden-falcon-crown", visualFxTitleRu: "Золотой Сокол · Ultra Premium FX", primaryGlowRu: "falcon gold cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "falcon dive, crown flare, gold feather trail", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "falcon gold luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 2360, auraPulseMs: 1030, premiumFxScore: 94, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false },
  { assetId: "imperial-dragon-meteor", visualFxTitleRu: "Имперский Дракон · Ultra Premium FX", primaryGlowRu: "imperial cosmic cinematic glow", particleBurstRu: "premium controlled particles · no clutter", motionTrailRu: "dragon gate, meteor rain, imperial finale burst", auraRu: "clean aura around recipient", screenImpactRu: "large but readable safe-area impact", finaleBurstRu: "high-value finale burst + soft fade", luxuryLightingRu: "imperial cosmic luxury stage", overlayDepthRu: "foreground detail + mid aura + background light", particleDensityLabel: "controlled ultra", glowIntensityLabel: "premium bright", burstScaleLabel: "large clean", trailDurationMs: 2470, auraPulseMs: 1065, premiumFxScore: 95, fxChipsRu: ["ultra", "fair", "clean", "quality"], fallbackCopyRu: "lite: poster + single glow ring, no heavy animation", safetyCopyRu: "Visual FX is metadata/local preview only: no actual playback, no send, no payment, no Wallet mutation.", userFacingOnly: true, previewOnlyNow: true, backendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, providerRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, sendRuntimeEnabledNow: false, actualAnimationRuntimeEnabledNow: false, actualSoundAutoplayEnabledNow: false, randomWinRuntimeEnabledNow: false }
];

export const streamPremiumGiftPack197AFinalScreenPolishProfiles: StreamPremiumGiftFinalScreenPolish188I[] = [
  { assetId: "celestial-tiger-crown", finalScreenTitleRu: "Небесный Тигр · ultra premium final screen", premiumImpactRu: "tiger crown sky leap with fair-price quality badge and clean recipient focus", soundSignatureRu: "tiger crown hit · label only · no autoplay", hapticSignatureRu: "strong metadata · local only", timingSignatureRu: "entrance 940ms · loop 2650ms · finale 980ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "diamond-sakura-palace", finalScreenTitleRu: "Алмазная Сакура · ultra premium final screen", premiumImpactRu: "diamond sakura palace bloom with fair-price quality badge and clean recipient focus", soundSignatureRu: "diamond sakura chime · label only · no autoplay", hapticSignatureRu: "medium metadata · local only", timingSignatureRu: "entrance 965ms · loop 2710ms · finale 1015ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "aurora-phoenix-parade", finalScreenTitleRu: "Аврора Феникс · ultra premium final screen", premiumImpactRu: "aurora phoenix parade with fair-price quality badge and clean recipient focus", soundSignatureRu: "phoenix aurora rise · label only · no autoplay", hapticSignatureRu: "finale metadata · local only", timingSignatureRu: "entrance 990ms · loop 2770ms · finale 1050ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "royal-galaxy-yacht", finalScreenTitleRu: "Галактика Яхта · ultra premium final screen", premiumImpactRu: "royal galaxy yacht reveal with fair-price quality badge and clean recipient focus", soundSignatureRu: "galaxy yacht shimmer · label only · no autoplay", hapticSignatureRu: "strong metadata · local only", timingSignatureRu: "entrance 1015ms · loop 2830ms · finale 1085ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "crystal-lotus-dragon", finalScreenTitleRu: "Лотос Дракон · ultra premium final screen", premiumImpactRu: "crystal lotus dragon bloom with fair-price quality badge and clean recipient focus", soundSignatureRu: "crystal lotus dragon hit · label only · no autoplay", hapticSignatureRu: "finale metadata · local only", timingSignatureRu: "entrance 1040ms · loop 2890ms · finale 1120ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "neon-opera-idol", finalScreenTitleRu: "Неон Опера · ultra premium final screen", premiumImpactRu: "neon opera idol stage with fair-price quality badge and clean recipient focus", soundSignatureRu: "opera neon cue · label only · no autoplay", hapticSignatureRu: "medium metadata · local only", timingSignatureRu: "entrance 1065ms · loop 2950ms · finale 1155ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "golden-falcon-crown", finalScreenTitleRu: "Золотой Сокол · ultra premium final screen", premiumImpactRu: "golden falcon crown flight with fair-price quality badge and clean recipient focus", soundSignatureRu: "falcon crown sweep · label only · no autoplay", hapticSignatureRu: "strong metadata · local only", timingSignatureRu: "entrance 1090ms · loop 3010ms · finale 1190ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false },
  { assetId: "imperial-dragon-meteor", finalScreenTitleRu: "Имперский Дракон · ultra premium final screen", premiumImpactRu: "imperial dragon meteor finale with fair-price quality badge and clean recipient focus", soundSignatureRu: "imperial dragon meteor · label only · no autoplay", hapticSignatureRu: "finale metadata · local only", timingSignatureRu: "entrance 1115ms · loop 3070ms · finale 1225ms", finaleCloseRu: "soft fade, no noisy spam, no fake win feeling", recipientFocusRu: "recipient halo visible without hiding stream", crowdMomentRu: "premium gift moment for stream chat, no gambling/result language", reduceMotionFallbackRu: "static poster + glow + readable chip", soundPreviewRuntimeEnabledNow: false, realGiftSendRuntimeEnabledNow: false, paymentRuntimeEnabledNow: false, payoutRuntimeEnabledNow: false, backendRuntimeEnabledNow: false }
];

export const streamPremiumGiftPack197ASummary = {
  version: "STREAM-GAME-GIFTS-197A",
  addedGiftCount: streamPremiumGiftPack197A.length,
  cumulativeGiftCountAfter197A: 32,
  pack4Count: streamPremiumGiftPack197A.length,
  fairPricingEnabled: true,
  minDemoPointPrice: 85,
  maxDemoPointPrice: 340,
  pricingPolicyRu: "Цена соответствует качеству эффекта: нет fake expensive, нет мусора, только fair demo-points preview labels.",
  userFacingOnly: true,
  backendRuntimeEnabledNow: false,
  paymentRuntimeEnabledNow: false,
  providerRuntimeEnabledNow: false,
  payoutRuntimeEnabledNow: false,
  walletMutationEnabledNow: false,
  realSendRuntimeEnabledNow: false,
  actualAnimationPlaybackRuntimeEnabledNow: false,
  actualSoundAutoplayRuntimeEnabledNow: false,
} as const;

export function getStreamPremiumGiftEffectProfile197A(assetId: string): StreamPremiumGiftEffectProfile187B {
  return streamPremiumGiftPack197AEffectProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197AEffectProfiles[0];
}
export function getStreamPremiumGiftPreviewExperience197A(assetId: string): StreamPremiumGiftPreviewExperience187C {
  return streamPremiumGiftPack197APreviewExperiences.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197APreviewExperiences[0];
}
export function getStreamPremiumGiftFinalPolish197A(assetId: string): StreamPremiumGiftFinalPolish187D {
  return streamPremiumGiftPack197AFinalPolishProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197AFinalPolishProfiles[0];
}
export function getStreamPremiumGiftAppearanceProfile197A(assetId: string): StreamPremiumGiftAppearanceProfile188G {
  return streamPremiumGiftPack197AAppearanceProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197AAppearanceProfiles[0];
}
export function getStreamPremiumGiftVisualFxProfile197A(assetId: string): StreamPremiumGiftVisualFxProfile188H {
  return streamPremiumGiftPack197AVisualFxProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197AVisualFxProfiles[0];
}
export function getStreamPremiumGiftFinalScreenPolish197A(assetId: string): StreamPremiumGiftFinalScreenPolish188I {
  return streamPremiumGiftPack197AFinalScreenPolishProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack197AFinalScreenPolishProfiles[0];
}
