import { streamPremiumGiftAnimationAssetSpecs189A } from "./streamPremiumGiftAnimationAssetProduction189A";

export type StreamPremiumGiftLottieSvgRenderPlan189B = {
  id: string;
  displayNameRu: string;
  displayName: string;
  cinematicLabelRu: string;
  primaryColor: string;
  lightColor: string;
  lottiePlanFile: string;
  svgSequenceFiles: string[];
  phaseCount: number;
  layerCount: number;
  fps: number;
  durationMs: number;
  renderStatusRu: string;
  fallbackRu: string;
  previewOnlyNow: true;
  actualLottieRuntimeIncludedNow: false;
  actualSvgAnimationRuntimeIncludedNow: false;
  realSendRuntimeIncludedNow: false;
  paymentRuntimeIncludedNow: false;
};

export const streamPremiumGiftLottieSvgRenderPlans189B: StreamPremiumGiftLottieSvgRenderPlan189B[] = [
  {
    id: "sakura-heart-burst",
    displayNameRu: "Сакура Сердце",
    displayName: "Sakura Heart Burst",
    cinematicLabelRu: "sakura heart cinematic bloom",
    primaryColor: "#F6A8D8",
    lightColor: "#FFD7EF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/sakura-heart-burst-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/sakura-heart-burst-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/sakura-heart-burst-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/sakura-heart-burst-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "koi-luck-splash",
    displayNameRu: "Карп Удачи",
    displayName: "Koi Luck Splash",
    cinematicLabelRu: "aqua koi luck wave",
    primaryColor: "#74D6FF",
    lightColor: "#D7FAFF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/koi-luck-splash-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/koi-luck-splash-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/koi-luck-splash-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/koi-luck-splash-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "neon-fox-tail",
    displayNameRu: "Неоновый Лис",
    displayName: "Neon Fox Tail",
    cinematicLabelRu: "neon fox tail sweep",
    primaryColor: "#9B5CFF",
    lightColor: "#F0D9FF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/neon-fox-tail-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/neon-fox-tail-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/neon-fox-tail-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/neon-fox-tail-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "moon-cat-guard",
    displayNameRu: "Лунный Кот",
    displayName: "Moon Cat Guard",
    cinematicLabelRu: "moon cat halo guard",
    primaryColor: "#BFD7FF",
    lightColor: "#F2F7FF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/moon-cat-guard-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/moon-cat-guard-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/moon-cat-guard-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/moon-cat-guard-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "dj-star-drop",
    displayNameRu: "DJ Звезда",
    displayName: "DJ Star Drop",
    cinematicLabelRu: "beat star stage pulse",
    primaryColor: "#F2C75B",
    lightColor: "#FFF0B3",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/dj-star-drop-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/dj-star-drop-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/dj-star-drop-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/dj-star-drop-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "golden-lion-roar",
    displayNameRu: "Золотой Лев",
    displayName: "Golden Lion Roar",
    cinematicLabelRu: "gold lion royal flare",
    primaryColor: "#F5B542",
    lightColor: "#FFE6A3",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/golden-lion-roar-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/golden-lion-roar-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/golden-lion-roar-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/golden-lion-roar-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "royal-rose-stage",
    displayNameRu: "Королевская Роза",
    displayName: "Royal Rose Stage",
    cinematicLabelRu: "royal rose velvet bloom",
    primaryColor: "#E84C7A",
    lightColor: "#FFD0DF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/royal-rose-stage-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/royal-rose-stage-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/royal-rose-stage-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/royal-rose-stage-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "cosmic-dragon-gate",
    displayNameRu: "Космический Дракон",
    displayName: "Cosmic Dragon Gate",
    cinematicLabelRu: "cosmic dragon portal gate",
    primaryColor: "#7C66FF",
    lightColor: "#DCD5FF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/cosmic-dragon-gate-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/cosmic-dragon-gate-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/cosmic-dragon-gate-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/cosmic-dragon-gate-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "phoenix-crown-burst",
    displayNameRu: "Феникс Корона",
    displayName: "Phoenix Crown Burst",
    cinematicLabelRu: "phoenix crown flame rise",
    primaryColor: "#FF7A45",
    lightColor: "#FFE0C7",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/phoenix-crown-burst-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/phoenix-crown-burst-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/phoenix-crown-burst-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/phoenix-crown-burst-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "crystal-whale-wave",
    displayNameRu: "Кристальный Кит",
    displayName: "Crystal Whale Wave",
    cinematicLabelRu: "crystal whale prism wave",
    primaryColor: "#7AE7FF",
    lightColor: "#D9FBFF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/crystal-whale-wave-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/crystal-whale-wave-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/crystal-whale-wave-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/crystal-whale-wave-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "cyber-panda-beat",
    displayNameRu: "Кибер Панда",
    displayName: "Cyber Panda Beat",
    cinematicLabelRu: "cyber panda bass flash",
    primaryColor: "#56F0C2",
    lightColor: "#D8FFF4",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/cyber-panda-beat-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/cyber-panda-beat-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/cyber-panda-beat-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/cyber-panda-beat-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "velvet-butterfly-storm",
    displayNameRu: "Бархатные Бабочки",
    displayName: "Velvet Butterfly Storm",
    cinematicLabelRu: "velvet butterfly storm bloom",
    primaryColor: "#C48BFF",
    lightColor: "#F3DFFF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/velvet-butterfly-storm-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/velvet-butterfly-storm-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/velvet-butterfly-storm-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/velvet-butterfly-storm-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "thunder-tiger-flash",
    displayNameRu: "Громовой Тигр",
    displayName: "Thunder Tiger Flash",
    cinematicLabelRu: "thunder tiger shock ring",
    primaryColor: "#FFD24A",
    lightColor: "#FFF2B8",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/thunder-tiger-flash-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/thunder-tiger-flash-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/thunder-tiger-flash-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/thunder-tiger-flash-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "aurora-unicorn-ride",
    displayNameRu: "Аврора Единорог",
    displayName: "Aurora Unicorn Ride",
    cinematicLabelRu: "aurora unicorn light ride",
    primaryColor: "#94F7D1",
    lightColor: "#E5FFF6",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/aurora-unicorn-ride-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/aurora-unicorn-ride-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/aurora-unicorn-ride-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/aurora-unicorn-ride-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "diamond-genie-lamp",
    displayNameRu: "Алмазный Джинн",
    displayName: "Diamond Genie Lamp",
    cinematicLabelRu: "diamond genie smoke reveal",
    primaryColor: "#8EC5FF",
    lightColor: "#E4F1FF",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/diamond-genie-lamp-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/diamond-genie-lamp-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/diamond-genie-lamp-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/diamond-genie-lamp-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "galaxy-idol-stage",
    displayNameRu: "Галакси Айдол",
    displayName: "Galaxy Idol Stage",
    cinematicLabelRu: "galaxy idol spotlight finale",
    primaryColor: "#FF8BE8",
    lightColor: "#FFE0FA",
    lottiePlanFile: "assets/stream/gifts/189b-render-plan/lottie-scaffold/galaxy-idol-stage-lottie-render-plan-189b.json",
    svgSequenceFiles: ["assets/stream/gifts/189b-render-plan/svg-sequence/galaxy-idol-stage-entrance-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/galaxy-idol-stage-loop-frame-189b.svg", "assets/stream/gifts/189b-render-plan/svg-sequence/galaxy-idol-stage-finale-frame-189b.svg"],
    phaseCount: 3,
    layerCount: 7,
    fps: 30,
    durationMs: 2920,
    renderStatusRu: "render plan ready · production export later",
    fallbackRu: "SVG poster sequence + static fallback for lite/reduce-motion",
    previewOnlyNow: true,
    actualLottieRuntimeIncludedNow: false,
    actualSvgAnimationRuntimeIncludedNow: false,
    realSendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  }
];

export const streamPremiumGiftLottieSvgRenderPlanSummary189B = {
  version: "STREAM-GAME-GIFTS-189B",
  totalGifts: streamPremiumGiftLottieSvgRenderPlans189B.length,
  animationSpecCountFrom189A: streamPremiumGiftAnimationAssetSpecs189A.length,
  lottiePlanFiles: streamPremiumGiftLottieSvgRenderPlans189B.length,
  svgSequenceFiles: streamPremiumGiftLottieSvgRenderPlans189B.reduce((total, plan) => total + plan.svgSequenceFiles.length, 0),
  phasesPerGift: 3,
  layerCountPerGift: 7,
  runtimeIncludedNow: false,
  actualLottieRuntimeIncludedNow: false,
  actualSvgAnimationRuntimeIncludedNow: false,
  backendRuntimeIncludedNow: false,
  paymentRuntimeIncludedNow: false,
  providerRuntimeIncludedNow: false,
  payoutRuntimeIncludedNow: false,
  sendRuntimeIncludedNow: false,
} as const;

export function getStreamPremiumGiftLottieSvgRenderPlan189B(giftId: string): StreamPremiumGiftLottieSvgRenderPlan189B {
  return streamPremiumGiftLottieSvgRenderPlans189B.find((plan) => plan.id === giftId) ?? streamPremiumGiftLottieSvgRenderPlans189B[0];
}
