import { streamPremiumGiftPack187A } from "./streamPremiumGiftPack187A";
import { streamPremiumGiftPack188A } from "./streamPremiumGiftPack188A";

export type StreamPremiumGiftAnimationAssetSpec189A = {
  id: string;
  displayNameRu: string;
  displayName: string;
  productionTier: "standard-plus" | "premium" | "hero";
  animationSpecFile: string;
  entranceRu: string;
  loopRu: string;
  finaleRu: string;
  particlesRu: string;
  durationMs: number;
  fps: number;
  lottieTarget: string;
  mp4LoopTarget: string;
  spriteTarget: string;
  layerStackRu: string[];
  exportStatusRu: string;
  fallbackRu: string;
  previewOnlyNow: true;
  animationRuntimeIncludedNow: false;
  sendRuntimeIncludedNow: false;
  paymentRuntimeIncludedNow: false;
};

export const streamPremiumGiftAnimationAssetSpecs189A: StreamPremiumGiftAnimationAssetSpec189A[] = [
  {
    id: "sakura-heart-burst",
    displayNameRu: "Сакура Сердце",
    displayName: "Sakura Heart Burst",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/sakura-heart-burst-animation-spec-189a.json",
    entranceRu: "petal heart entrance",
    loopRu: "heart pulse loop",
    finaleRu: "petal crown finale",
    particlesRu: "rose-gold sakura particles",
    durationMs: 2980,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/sakura-heart-burst.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/sakura-heart-burst.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/sakura-heart-burst.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "koi-luck-splash",
    displayNameRu: "Карп Удачи",
    displayName: "Koi Luck Splash",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/koi-luck-splash-animation-spec-189a.json",
    entranceRu: "water-ring entrance",
    loopRu: "wave orbit loop",
    finaleRu: "luck splash finale",
    particlesRu: "aqua koi particles",
    durationMs: 3160,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/koi-luck-splash.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/koi-luck-splash.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/koi-luck-splash.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "neon-fox-tail",
    displayNameRu: "Неоновый Лис",
    displayName: "Neon Fox Tail",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/neon-fox-tail-animation-spec-189a.json",
    entranceRu: "neon swipe entrance",
    loopRu: "tail trail loop",
    finaleRu: "electric fox finale",
    particlesRu: "violet fox sparks",
    durationMs: 3340,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/neon-fox-tail.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/neon-fox-tail.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/neon-fox-tail.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "moon-cat-guard",
    displayNameRu: "Лунный Кот",
    displayName: "Moon Cat Guard",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/moon-cat-guard-animation-spec-189a.json",
    entranceRu: "moon-rise entrance",
    loopRu: "guardian halo loop",
    finaleRu: "lunar shield finale",
    particlesRu: "silver star dust",
    durationMs: 3520,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/moon-cat-guard.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/moon-cat-guard.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/moon-cat-guard.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "dj-star-drop",
    displayNameRu: "DJ Звезда",
    displayName: "DJ Star Drop",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/dj-star-drop-animation-spec-189a.json",
    entranceRu: "beat-drop entrance",
    loopRu: "star pulse loop",
    finaleRu: "stage beat finale",
    particlesRu: "equalizer sparkles",
    durationMs: 2800,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/dj-star-drop.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/dj-star-drop.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/dj-star-drop.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "golden-lion-roar",
    displayNameRu: "Золотой Лев",
    displayName: "Golden Lion Roar",
    productionTier: "premium",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/golden-lion-roar-animation-spec-189a.json",
    entranceRu: "royal crest entrance",
    loopRu: "lion aura loop",
    finaleRu: "crown roar finale",
    particlesRu: "gold dust rays",
    durationMs: 2980,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/golden-lion-roar.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/golden-lion-roar.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/golden-lion-roar.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "royal-rose-stage",
    displayNameRu: "Королевская Роза",
    displayName: "Royal Rose Stage",
    productionTier: "premium",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/royal-rose-stage-animation-spec-189a.json",
    entranceRu: "curtain bloom entrance",
    loopRu: "rose aura loop",
    finaleRu: "royal bloom finale",
    particlesRu: "velvet petal rain",
    durationMs: 3160,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/royal-rose-stage.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/royal-rose-stage.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/royal-rose-stage.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "cosmic-dragon-gate",
    displayNameRu: "Космический Дракон",
    displayName: "Cosmic Dragon Gate",
    productionTier: "hero",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/cosmic-dragon-gate-animation-spec-189a.json",
    entranceRu: "portal gate entrance",
    loopRu: "dragon orbit loop",
    finaleRu: "galaxy gate finale",
    particlesRu: "cosmic comet sparks",
    durationMs: 3340,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/cosmic-dragon-gate.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/cosmic-dragon-gate.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/cosmic-dragon-gate.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "phoenix-crown-burst",
    displayNameRu: "Феникс Корона",
    displayName: "Phoenix Crown Burst",
    productionTier: "hero",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/phoenix-crown-burst-animation-spec-189a.json",
    entranceRu: "flame-wing entrance",
    loopRu: "phoenix ascent loop",
    finaleRu: "crown flare finale",
    particlesRu: "ember crown particles",
    durationMs: 3520,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/phoenix-crown-burst.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/phoenix-crown-burst.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/phoenix-crown-burst.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "crystal-whale-wave",
    displayNameRu: "Кристальный Кит",
    displayName: "Crystal Whale Wave",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/crystal-whale-wave-animation-spec-189a.json",
    entranceRu: "crystal wave entrance",
    loopRu: "whale arc loop",
    finaleRu: "wave halo finale",
    particlesRu: "aqua prism particles",
    durationMs: 2800,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/crystal-whale-wave.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/crystal-whale-wave.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/crystal-whale-wave.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "cyber-panda-beat",
    displayNameRu: "Кибер Панда",
    displayName: "Cyber Panda Beat",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/cyber-panda-beat-animation-spec-189a.json",
    entranceRu: "neon beat entrance",
    loopRu: "panda beat loop",
    finaleRu: "bass flash finale",
    particlesRu: "cyber equalizer sparks",
    durationMs: 2980,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/cyber-panda-beat.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/cyber-panda-beat.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/cyber-panda-beat.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "velvet-butterfly-storm",
    displayNameRu: "Бархатные Бабочки",
    displayName: "Velvet Butterfly Storm",
    productionTier: "standard-plus",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/velvet-butterfly-storm-animation-spec-189a.json",
    entranceRu: "velvet swarm entrance",
    loopRu: "soft orbit loop",
    finaleRu: "butterfly bloom finale",
    particlesRu: "violet butterfly particles",
    durationMs: 3160,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/velvet-butterfly-storm.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/velvet-butterfly-storm.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/velvet-butterfly-storm.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "thunder-tiger-flash",
    displayNameRu: "Громовой Тигр",
    displayName: "Thunder Tiger Flash",
    productionTier: "premium",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/thunder-tiger-flash-animation-spec-189a.json",
    entranceRu: "lightning slash entrance",
    loopRu: "tiger charge loop",
    finaleRu: "shock ring finale",
    particlesRu: "gold thunder particles",
    durationMs: 3340,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/thunder-tiger-flash.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/thunder-tiger-flash.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/thunder-tiger-flash.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "aurora-unicorn-ride",
    displayNameRu: "Аврора Единорог",
    displayName: "Aurora Unicorn Ride",
    productionTier: "premium",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/aurora-unicorn-ride-animation-spec-189a.json",
    entranceRu: "aurora gate entrance",
    loopRu: "unicorn glide loop",
    finaleRu: "aurora crown finale",
    particlesRu: "pastel star particles",
    durationMs: 3520,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/aurora-unicorn-ride.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/aurora-unicorn-ride.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/aurora-unicorn-ride.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "diamond-genie-lamp",
    displayNameRu: "Алмазный Джинн",
    displayName: "Diamond Genie Lamp",
    productionTier: "premium",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/diamond-genie-lamp-animation-spec-189a.json",
    entranceRu: "diamond smoke entrance",
    loopRu: "genie swirl loop",
    finaleRu: "lamp burst finale",
    particlesRu: "blue gem particles",
    durationMs: 2800,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/diamond-genie-lamp.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/diamond-genie-lamp.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/diamond-genie-lamp.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  },
  {
    id: "galaxy-idol-stage",
    displayNameRu: "Галакси Айдол",
    displayName: "Galaxy Idol Stage",
    productionTier: "hero",
    animationSpecFile: "assets/stream/gifts/189a-animation-specs/galaxy-idol-stage-animation-spec-189a.json",
    entranceRu: "idol spotlight entrance",
    loopRu: "stage orbit loop",
    finaleRu: "idol star finale",
    particlesRu: "galaxy confetti particles",
    durationMs: 2980,
    fps: 30,
    lottieTarget: "assets/stream/gifts/production/lottie/galaxy-idol-stage.json",
    mp4LoopTarget: "assets/stream/gifts/production/mp4/galaxy-idol-stage.mp4",
    spriteTarget: "assets/stream/gifts/production/sprites/galaxy-idol-stage.webp",
    layerStackRu: ["background dim", "stage light", "hero gift", "particles", "trail", "finale burst"],
    exportStatusRu: "production spec ready · render later",
    fallbackRu: "poster + glow pulse fallback for lite/reduce-motion",
    previewOnlyNow: true,
    animationRuntimeIncludedNow: false,
    sendRuntimeIncludedNow: false,
    paymentRuntimeIncludedNow: false,
  }
];

export const streamPremiumGiftAnimationAssetProductionSummary189A = {
  version: "STREAM-GAME-GIFTS-189A",
  totalGifts: streamPremiumGiftAnimationAssetSpecs189A.length,
  pack1GiftCount: streamPremiumGiftPack187A.length,
  pack2GiftCount: streamPremiumGiftPack188A.length,
  animationSpecFiles: streamPremiumGiftAnimationAssetSpecs189A.length,
  phasesPerGift: 3,
  layerStackPerGift: 6,
  runtimeIncludedNow: false,
  actualAnimationPlaybackRuntimeIncludedNow: false,
  backendRuntimeIncludedNow: false,
  paymentRuntimeIncludedNow: false,
  providerRuntimeIncludedNow: false,
  payoutRuntimeIncludedNow: false,
  sendRuntimeIncludedNow: false,
} as const;

export function getStreamPremiumGiftAnimationAssetSpec189A(giftId: string): StreamPremiumGiftAnimationAssetSpec189A {
  return streamPremiumGiftAnimationAssetSpecs189A.find((spec) => spec.id === giftId) ?? streamPremiumGiftAnimationAssetSpecs189A[0];
}
