export type StreamPremiumGiftFinalPolish187D = {
  assetId: string;
  heroPosterFile: string;
  animeStyleLabel: string;
  premiumBadge: string;
  catalogHeroCopyRu: string;
  stageAuraCopyRu: string;
  visualSignature: string;
  soundSignature: string;
  hapticSignature: string;
  posterDetailChips: readonly string[];
  polishBadgeChips: readonly string[];
  finalSafetyCopyRu: string;
  finalPolishReadyNow: true;
  posterFallbackReadyNow: true;
  localPreviewOnlyNow: true;
  backendRuntimeEnabledNow: false;
  paymentRuntimeEnabledNow: false;
  realSendRuntimeEnabledNow: false;
  payoutRuntimeEnabledNow: false;
};

export const streamPremiumGiftFinalPolishProfiles187D: StreamPremiumGiftFinalPolish187D[] = [
  {
    assetId: "sakura-heart-burst",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/sakura-heart-burst-final-polish.svg",
    animeStyleLabel: "anime sakura romance",
    premiumBadge: "Ultra Bloom",
    catalogHeroCopyRu: "Сакура раскрывается как живой heart-bloom: лепестки, glow и мягкий финальный sparkle.",
    stageAuraCopyRu: "Розовая сцена, petal storm, soft chime и gentle haptic в preview.",
    visualSignature: "petal heart burst + soft pink aura",
    soundSignature: "soft chime, 620ms, no autoplay",
    hapticSignature: "soft pulse, local only",
    posterDetailChips: ["petal layers", "heart glow", "soft aura"],
    polishBadgeChips: ["anime", "romantic", "ultra"],
    finalSafetyCopyRu: "Preview локальный: не отправляет подарок, не списывает алмазы и не проигрывает звук автоматически.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "koi-luck-splash",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/koi-luck-splash-final-polish.svg",
    animeStyleLabel: "anime water luck",
    premiumBadge: "Aqua Fortune",
    catalogHeroCopyRu: "Карп удачи проходит дугой через aqua ring, оставляя водные искры и calm luck trail.",
    stageAuraCopyRu: "Сцена с водой, ripple rings, water bell label и pulse haptic preview.",
    visualSignature: "koi arc + ripple sparkle",
    soundSignature: "water bell, 700ms, no autoplay",
    hapticSignature: "wave pulse, local only",
    posterDetailChips: ["water rings", "koi trail", "luck sparkle"],
    polishBadgeChips: ["anime", "aqua", "fortune"],
    finalSafetyCopyRu: "Это подарок, а не игра: нет расчёта выигрыша, оплаты, cash-out или provider вызова.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-fox-tail",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/neon-fox-tail-final-polish.svg",
    animeStyleLabel: "cyber anime fox",
    premiumBadge: "Neon Tail",
    catalogHeroCopyRu: "Неоновый лис оставляет electric tail sweep, sharp glow и быстрый synth snap эффект.",
    stageAuraCopyRu: "Cyber сцена, neon trail, synth label и snap haptic как локальный preview.",
    visualSignature: "neon fox trail + electric burst",
    soundSignature: "synth snap, 480ms, no autoplay",
    hapticSignature: "snap impact, local only",
    posterDetailChips: ["electric tail", "neon edge", "cyber glow"],
    polishBadgeChips: ["anime", "neon", "sharp"],
    finalSafetyCopyRu: "Neon preview не запускает send runtime: это только локальный visual/haptic layer.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "moon-cat-guard",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/moon-cat-guard-final-polish.svg",
    animeStyleLabel: "moon guardian anime",
    premiumBadge: "Calm Halo",
    catalogHeroCopyRu: "Лунный кот появляется в спокойном moon halo, вокруг мягко движется star dust.",
    stageAuraCopyRu: "Ночная сцена, moon glow, night bell label и gentle haptic для спокойного preview.",
    visualSignature: "moon halo + star orbit",
    soundSignature: "night bell, 540ms, no autoplay",
    hapticSignature: "gentle tap, local only",
    posterDetailChips: ["moon halo", "cat guard", "star dust"],
    polishBadgeChips: ["anime", "calm", "reader safe"],
    finalSafetyCopyRu: "Поддерживает lite/reduce-motion preview: poster + shimmer без тяжёлого движения.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "dj-star-drop",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/dj-star-drop-final-polish.svg",
    animeStyleLabel: "anime beat stage",
    premiumBadge: "Beat Drop",
    catalogHeroCopyRu: "DJ звезда падает на сцену с beat rings, equalizer glow и festival flash.",
    stageAuraCopyRu: "Club сцена, beat pulse, EDM label и rhythm haptic как локальный preview.",
    visualSignature: "star drop + equalizer burst",
    soundSignature: "EDM hit, 520ms, no autoplay",
    hapticSignature: "beat pulse, local only",
    posterDetailChips: ["beat rings", "eq glow", "star flash"],
    polishBadgeChips: ["anime", "sound", "festival"],
    finalSafetyCopyRu: "Sound metadata есть, но actual audio playback runtime не включён автоматически.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "golden-lion-roar",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/golden-lion-roar-final-polish.svg",
    animeStyleLabel: "royal anime lion",
    premiumBadge: "Royal Impact",
    catalogHeroCopyRu: "Золотой лев создаёт crown flare, royal aura и мощный finale impact.",
    stageAuraCopyRu: "Золотая сцена, crown rays, roar label и strong haptic только локально.",
    visualSignature: "gold crown burst + lion aura",
    soundSignature: "soft roar, 760ms, no autoplay",
    hapticSignature: "strong impact, local only",
    posterDetailChips: ["crown rays", "gold aura", "lion flare"],
    polishBadgeChips: ["anime", "royal", "impact"],
    finalSafetyCopyRu: "Сильный эффект остаётся preview-only: нет backend send, provider, оплаты или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-rose-stage",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/royal-rose-stage-final-polish.svg",
    animeStyleLabel: "royal rose anime",
    premiumBadge: "Velvet Bloom",
    catalogHeroCopyRu: "Королевская роза открывается как velvet curtain, petals формируют сценическую ауру.",
    stageAuraCopyRu: "Красная сцена, petal curtain, romantic label и elegant haptic preview.",
    visualSignature: "rose curtain + velvet aura",
    soundSignature: "romantic sting, 590ms, no autoplay",
    hapticSignature: "elegant tap, local only",
    posterDetailChips: ["velvet curtain", "petal bloom", "rose aura"],
    polishBadgeChips: ["anime", "royal", "elegant"],
    finalSafetyCopyRu: "Local preview сохраняет no-charge/no-send режим до настоящего backend этапа.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "cosmic-dragon-gate",
    heroPosterFile: "assets/stream/gifts/187d-final-polish/cosmic-dragon-gate-final-polish.svg",
    animeStyleLabel: "mythic cosmic anime",
    premiumBadge: "Mythic Portal",
    catalogHeroCopyRu: "Космический дракон открывает portal gate, comet trail и mythic finale glow.",
    stageAuraCopyRu: "Космическая сцена, dragon trail, deep hit label и finale haptic локально.",
    visualSignature: "portal gate + dragon comet trail",
    soundSignature: "deep cosmic hit, 880ms, no autoplay",
    hapticSignature: "finale impact, local only",
    posterDetailChips: ["portal gate", "dragon trail", "cosmic finale"],
    polishBadgeChips: ["anime", "mythic", "ultra"],
    finalSafetyCopyRu: "Mythic preview не связан с games result, payment, cash-out, Wallet или provider.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
];

export const getStreamPremiumGiftFinalPolish187D = (assetId: string): StreamPremiumGiftFinalPolish187D => {
  return streamPremiumGiftFinalPolishProfiles187D.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftFinalPolishProfiles187D[0];
};

export const streamPremiumGiftFinalPolish187DSafety = {
  userFacingOnly: true,
  giftCount: 8,
  finalPolishReadyNow: true,
  posterFallbackReadyNow: true,
  localPreviewOnlyNow: true,
  actualMp4RuntimeEnabledNow: false,
  actualSoundPlaybackRuntimeEnabledNow: false,
  backendRuntimeEnabledNow: false,
  paymentRuntimeEnabledNow: false,
  realSendRuntimeEnabledNow: false,
  payoutRuntimeEnabledNow: false,
  providerRuntimeEnabledNow: false,
} as const;
