import type { StreamPremiumGiftAsset187A } from "./streamPremiumGiftPack187A";
import type { StreamPremiumGiftEffectProfile187B } from "./streamPremiumGiftEffects187B";
import type { StreamPremiumGiftPreviewExperience187C } from "./streamPremiumGiftPreviewExperience187C";
import type { StreamPremiumGiftFinalPolish187D } from "./streamPremiumGiftFinalPolish187D";
import type { StreamPremiumGiftAppearanceProfile188G } from "./streamPremiumGiftAppearanceEngine188G";
import type { StreamPremiumGiftVisualFxProfile188H } from "./streamPremiumGiftVisualFxPack188H";
import type { StreamPremiumGiftFinalScreenPolish188I } from "./streamPremiumGiftFinalScreenPolish188I";

export const streamPremiumGiftPack190ABasePath = "assets/stream/gifts/190a-premium-pack" as const;

export const streamPremiumGiftPack190A: StreamPremiumGiftAsset187A[] = [
  {
    id: "solar-samurai-dash",
    displayName: "Solar Samurai Dash",
    displayNameRu: "Солнечный Самурай",
    iconName: "flash-outline",
    legacyTitleKey: "giftTierPremium",
    catalogSegment: "anime",
    previewRu: "самурай входит через солнечный клинок",
    localCostLabel: "320 алмазов позже",
    effectLabel: "solar blade entrance",
    qualityLabel: "anime ultra SVG ready",
    loopLabel: "3.4 сек loop план",
    visualTone: "solar samurai",
    safetyBadge: "safe-area",
    rarityLabel: "Mythic Solar",
    motionSpec: "solar blade dash, gold rays, samurai cape trail",
    posterFile: "solar-samurai-dash.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "mermaid-pearl-bloom",
    displayName: "Mermaid Pearl Bloom",
    displayNameRu: "Русалка Жемчуг",
    iconName: "water-outline",
    legacyTitleKey: "giftTierUltra",
    catalogSegment: "premium",
    previewRu: "русалка раскрывает жемчужную волну",
    localCostLabel: "240 алмазов позже",
    effectLabel: "pearl bloom wave",
    qualityLabel: "anime pearl SVG ready",
    loopLabel: "3.0 сек loop план",
    visualTone: "pearl ocean",
    safetyBadge: "poster first",
    rarityLabel: "Legendary Pearl",
    motionSpec: "pearl bloom, sea mist, mermaid wave",
    posterFile: "mermaid-pearl-bloom.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "midnight-wolf-moon",
    displayName: "Midnight Wolf Moon",
    displayNameRu: "Полночный Волк",
    iconName: "moon-outline",
    legacyTitleKey: "giftTierEffect",
    catalogSegment: "anime",
    previewRu: "волк появляется на фоне лунного портала",
    localCostLabel: "180 алмазов позже",
    effectLabel: "moon wolf howl aura",
    qualityLabel: "dark anime SVG ready",
    loopLabel: "2.7 сек loop план",
    visualTone: "midnight wolf",
    safetyBadge: "moderated",
    rarityLabel: "Legendary Moon",
    motionSpec: "moon portal, wolf silhouette, silver trail",
    posterFile: "midnight-wolf-moon.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "candy-planet-pop",
    displayName: "Candy Planet Pop",
    displayNameRu: "Конфетная Планета",
    iconName: "planet-outline",
    legacyTitleKey: "giftTierAudio",
    catalogSegment: "sound",
    previewRu: "конфетная планета взрывается pop-искрами",
    localCostLabel: "95 алмазов позже",
    effectLabel: "candy planet pop",
    qualityLabel: "pop anime SVG ready",
    loopLabel: "2.2 сек loop план",
    visualTone: "candy planet",
    safetyBadge: "muted safe",
    rarityLabel: "Epic Pop",
    motionSpec: "candy orbit, bubble burst, pink pop trail",
    posterFile: "candy-planet-pop.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "royal-peacock-fan",
    displayName: "Royal Peacock Fan",
    displayNameRu: "Королевский Павлин",
    iconName: "color-palette-outline",
    legacyTitleKey: "giftTierPremium",
    catalogSegment: "premium",
    previewRu: "павлин раскрывает королевский веер",
    localCostLabel: "360 алмазов позже",
    effectLabel: "royal fan reveal",
    qualityLabel: "luxury anime SVG ready",
    loopLabel: "3.8 сек loop план",
    visualTone: "royal peacock",
    safetyBadge: "safe-area",
    rarityLabel: "Mythic Royal",
    motionSpec: "peacock fan, jewel feather, royal shimmer",
    posterFile: "royal-peacock-fan.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "neon-shark-surge",
    displayName: "Neon Shark Surge",
    displayNameRu: "Неоновая Акула",
    iconName: "fish-outline",
    legacyTitleKey: "giftTierEffect",
    catalogSegment: "anime",
    previewRu: "неоновая акула прорезает экран волной",
    localCostLabel: "210 алмазов позже",
    effectLabel: "neon shark surge",
    qualityLabel: "neon ocean SVG ready",
    loopLabel: "2.9 сек loop план",
    visualTone: "neon shark",
    safetyBadge: "moderated",
    rarityLabel: "Legendary Surge",
    motionSpec: "shark surge, aqua laser, wave tunnel",
    posterFile: "neon-shark-surge.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "angel-harp-glow",
    displayName: "Angel Harp Glow",
    displayNameRu: "Ангельская Арфа",
    iconName: "musical-note-outline",
    legacyTitleKey: "giftTierAudio",
    catalogSegment: "sound",
    previewRu: "арфа даёт золотой световой аккорд",
    localCostLabel: "150 алмазов позже",
    effectLabel: "angel harp glow",
    qualityLabel: "soft light SVG ready",
    loopLabel: "2.5 сек loop план",
    visualTone: "angel harp",
    safetyBadge: "muted safe",
    rarityLabel: "Rare Harmony",
    motionSpec: "harp string glow, light notes, angel ring",
    posterFile: "angel-harp-glow.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  },
  {
    id: "volcano-dragon-flare",
    displayName: "Volcano Dragon Flare",
    displayNameRu: "Вулкан Дракон",
    iconName: "flame-outline",
    legacyTitleKey: "giftTierUltra",
    catalogSegment: "premium",
    previewRu: "дракон выходит из вулканического портала",
    localCostLabel: "420 алмазов позже",
    effectLabel: "volcano dragon flare",
    qualityLabel: "ultra fire SVG ready",
    loopLabel: "4.0 сек loop план",
    visualTone: "volcano dragon",
    safetyBadge: "poster first",
    rarityLabel: "Mythic Flare",
    motionSpec: "lava gate, dragon flare, ember storm",
    posterFile: "volcano-dragon-flare.svg",
    posterFallbackReady: true,
    mp4LoopPlanned: true,
    providerRuntimeReadyNow: false,
    paymentReadyNow: false,
    payoutReadyNow: false,
    sendRuntimeReadyNow: false,
  }
];

export const streamPremiumGiftPack190AIds = new Set(streamPremiumGiftPack190A.map((gift) => gift.id));

export const streamPremiumGiftPack190AEffectProfiles: StreamPremiumGiftEffectProfile187B[] = [
  {
    assetId: "solar-samurai-dash",
    liveEffectLabel: "solar blade entrance",
    intensityLabel: "Mythic Solar",
    soundCueLabel: "solar blade hit",
    soundCueLabelRu: "удар солнечного клинка",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/solar-samurai-dash-cue.wav",
    soundCueDurationMs: 1200,
    hapticLabel: "sharp gold impact",
    hapticImpactStyle: "strong",
    colorA: "#FFD76B",
    colorB: "#FF7A3D",
    phases: ["solar blade entrance entrance", "solar samurai живой loop", "Mythic Solar finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    liveEffectLabel: "pearl bloom wave",
    intensityLabel: "Legendary Pearl",
    soundCueLabel: "pearl water shimmer",
    soundCueLabelRu: "жемчужный водный shimmer",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/mermaid-pearl-bloom-cue.wav",
    soundCueDurationMs: 1290,
    hapticLabel: "water pearl pulse",
    hapticImpactStyle: "medium",
    colorA: "#8BE8FF",
    colorB: "#F7E9FF",
    phases: ["pearl bloom wave entrance", "pearl ocean живой loop", "Legendary Pearl finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    liveEffectLabel: "moon wolf howl aura",
    intensityLabel: "Legendary Moon",
    soundCueLabel: "moon howl cue",
    soundCueLabelRu: "лунный howl cue",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/midnight-wolf-moon-cue.wav",
    soundCueDurationMs: 1380,
    hapticLabel: "deep moon pulse",
    hapticImpactStyle: "medium",
    colorA: "#7286FF",
    colorB: "#D7E0FF",
    phases: ["moon wolf howl aura entrance", "midnight wolf живой loop", "Legendary Moon finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "candy-planet-pop",
    liveEffectLabel: "candy planet pop",
    intensityLabel: "Epic Pop",
    soundCueLabel: "sweet pop sparkle",
    soundCueLabelRu: "сладкий pop sparkle",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/candy-planet-pop-cue.wav",
    soundCueDurationMs: 1470,
    hapticLabel: "tiny pop tap",
    hapticImpactStyle: "light",
    colorA: "#FF8BD6",
    colorB: "#A9F7FF",
    phases: ["candy planet pop entrance", "candy planet живой loop", "Epic Pop finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    liveEffectLabel: "royal fan reveal",
    intensityLabel: "Mythic Royal",
    soundCueLabel: "royal feather shine",
    soundCueLabelRu: "королевский feather shine",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/royal-peacock-fan-cue.wav",
    soundCueDurationMs: 1560,
    hapticLabel: "elegant royal pulse",
    hapticImpactStyle: "strong",
    colorA: "#2EE8B6",
    colorB: "#C59BFF",
    phases: ["royal fan reveal entrance", "royal peacock живой loop", "Mythic Royal finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "neon-shark-surge",
    liveEffectLabel: "neon shark surge",
    intensityLabel: "Legendary Surge",
    soundCueLabel: "neon water slash",
    soundCueLabelRu: "неоновый water slash",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/neon-shark-surge-cue.wav",
    soundCueDurationMs: 1650,
    hapticLabel: "surge impact",
    hapticImpactStyle: "medium",
    colorA: "#00F5FF",
    colorB: "#5A7CFF",
    phases: ["neon shark surge entrance", "neon shark живой loop", "Legendary Surge finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "angel-harp-glow",
    liveEffectLabel: "angel harp glow",
    intensityLabel: "Rare Harmony",
    soundCueLabel: "harp angel chord",
    soundCueLabelRu: "ангельский harp chord",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/angel-harp-glow-cue.wav",
    soundCueDurationMs: 1740,
    hapticLabel: "soft chord pulse",
    hapticImpactStyle: "soft",
    colorA: "#FFE9A8",
    colorB: "#FFFFFF",
    phases: ["angel harp glow entrance", "angel harp живой loop", "Rare Harmony finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    liveEffectLabel: "volcano dragon flare",
    intensityLabel: "Mythic Flare",
    soundCueLabel: "dragon lava hit",
    soundCueLabelRu: "драконий lava hit",
    soundCueFile: "assets/stream/gifts/190a-premium-pack/sound-cues/volcano-dragon-flare-cue.wav",
    soundCueDurationMs: 1830,
    hapticLabel: "finale heavy impact",
    hapticImpactStyle: "finale",
    colorA: "#FF4D2E",
    colorB: "#FFD76B",
    phases: ["volcano dragon flare entrance", "volcano dragon живой loop", "Mythic Flare finale burst"],
    visualFx: ["premium glow", "particle crown", "motion trail", "aura depth"],
    reducedMotionFallback: "lite: premium poster + one glow pulse + muted sound label only",
    localSoundAssetReady: true,
    localHapticMetadataReady: true,
    livePreviewRuntimeReadyNow: true,
    soundPlaybackRuntimeEnabledNow: false,
    backendRuntimeReadyNow: false,
    paymentRuntimeReadyNow: false,
    payoutRuntimeReadyNow: false,
    realSendRuntimeReadyNow: false,
  }
];

export const streamPremiumGiftPack190APreviewExperiences: StreamPremiumGiftPreviewExperience187C[] = [
  {
    assetId: "solar-samurai-dash",
    stageLightingLabel: "solar samurai stage lighting",
    motionQualityLabel: "solar blade entrance ultra preview",
    soundPreviewLabel: "sound label: solar blade hit",
    hapticPreviewLabel: "haptic label: sharp gold impact",
    liveSceneCopyRu: "Солнечный Самурай появляется на экране как дорогой premium overlay: solar blade dash, gold rays, samurai cape trail.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Солнечный Самурай, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    stageLightingLabel: "pearl ocean stage lighting",
    motionQualityLabel: "pearl bloom wave ultra preview",
    soundPreviewLabel: "sound label: pearl water shimmer",
    hapticPreviewLabel: "haptic label: water pearl pulse",
    liveSceneCopyRu: "Русалка Жемчуг появляется на экране как дорогой premium overlay: pearl bloom, sea mist, mermaid wave.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Русалка Жемчуг, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    stageLightingLabel: "midnight wolf stage lighting",
    motionQualityLabel: "moon wolf howl aura ultra preview",
    soundPreviewLabel: "sound label: moon howl cue",
    hapticPreviewLabel: "haptic label: deep moon pulse",
    liveSceneCopyRu: "Полночный Волк появляется на экране как дорогой premium overlay: moon portal, wolf silhouette, silver trail.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Полночный Волк, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "candy-planet-pop",
    stageLightingLabel: "candy planet stage lighting",
    motionQualityLabel: "candy planet pop ultra preview",
    soundPreviewLabel: "sound label: sweet pop sparkle",
    hapticPreviewLabel: "haptic label: tiny pop tap",
    liveSceneCopyRu: "Конфетная Планета появляется на экране как дорогой premium overlay: candy orbit, bubble burst, pink pop trail.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Конфетная Планета, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    stageLightingLabel: "royal peacock stage lighting",
    motionQualityLabel: "royal fan reveal ultra preview",
    soundPreviewLabel: "sound label: royal feather shine",
    hapticPreviewLabel: "haptic label: elegant royal pulse",
    liveSceneCopyRu: "Королевский Павлин появляется на экране как дорогой premium overlay: peacock fan, jewel feather, royal shimmer.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Королевский Павлин, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-shark-surge",
    stageLightingLabel: "neon shark stage lighting",
    motionQualityLabel: "neon shark surge ultra preview",
    soundPreviewLabel: "sound label: neon water slash",
    hapticPreviewLabel: "haptic label: surge impact",
    liveSceneCopyRu: "Неоновая Акула появляется на экране как дорогой premium overlay: shark surge, aqua laser, wave tunnel.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Неоновая Акула, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "angel-harp-glow",
    stageLightingLabel: "angel harp stage lighting",
    motionQualityLabel: "angel harp glow ultra preview",
    soundPreviewLabel: "sound label: harp angel chord",
    hapticPreviewLabel: "haptic label: soft chord pulse",
    liveSceneCopyRu: "Ангельская Арфа появляется на экране как дорогой premium overlay: harp string glow, light notes, angel ring.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Ангельская Арфа, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    stageLightingLabel: "volcano dragon stage lighting",
    motionQualityLabel: "volcano dragon flare ultra preview",
    soundPreviewLabel: "sound label: dragon lava hit",
    hapticPreviewLabel: "haptic label: finale heavy impact",
    liveSceneCopyRu: "Вулкан Дракон появляется на экране как дорогой premium overlay: lava gate, dragon flare, ember storm.",
    safeModeCopyRu: "Preview локальный: звук не проигрывается автоматически, haptic только по кнопке, real send/payment/backend отключены.",
    screenReaderHintRu: "Вулкан Дракон, premium preview с poster fallback, без оплаты и без отправки.",
    phaseChips: ["entrance", "live loop", "finale"],
    qualityBadges: ["premium anime", "sound label", "haptic metadata"],
    defaultQuality: "ultra",
    localPreviewUiReadyNow: true,
    actualSoundPlaybackRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  }
];

export const streamPremiumGiftPack190AFinalPolishProfiles: StreamPremiumGiftFinalPolish187D[] = [
  {
    assetId: "solar-samurai-dash",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/solar-samurai-dash-final-polish.svg",
    animeStyleLabel: "premium anime · solar samurai",
    premiumBadge: "Mythic Solar",
    catalogHeroCopyRu: "Солнечный Самурай выглядит как дорогой live gift: самурай входит через солнечный клинок, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: solar samurai, solar blade entrance, sound label и haptic signature.",
    visualSignature: "solar blade dash, gold rays, samurai cape trail",
    soundSignature: "solar blade hit, label only, no autoplay",
    hapticSignature: "sharp gold impact, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/mermaid-pearl-bloom-final-polish.svg",
    animeStyleLabel: "premium anime · pearl ocean",
    premiumBadge: "Legendary Pearl",
    catalogHeroCopyRu: "Русалка Жемчуг выглядит как дорогой live gift: русалка раскрывает жемчужную волну, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: pearl ocean, pearl bloom wave, sound label и haptic signature.",
    visualSignature: "pearl bloom, sea mist, mermaid wave",
    soundSignature: "pearl water shimmer, label only, no autoplay",
    hapticSignature: "water pearl pulse, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/midnight-wolf-moon-final-polish.svg",
    animeStyleLabel: "premium anime · midnight wolf",
    premiumBadge: "Legendary Moon",
    catalogHeroCopyRu: "Полночный Волк выглядит как дорогой live gift: волк появляется на фоне лунного портала, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: midnight wolf, moon wolf howl aura, sound label и haptic signature.",
    visualSignature: "moon portal, wolf silhouette, silver trail",
    soundSignature: "moon howl cue, label only, no autoplay",
    hapticSignature: "deep moon pulse, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "candy-planet-pop",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/candy-planet-pop-final-polish.svg",
    animeStyleLabel: "premium anime · candy planet",
    premiumBadge: "Epic Pop",
    catalogHeroCopyRu: "Конфетная Планета выглядит как дорогой live gift: конфетная планета взрывается pop-искрами, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: candy planet, candy planet pop, sound label и haptic signature.",
    visualSignature: "candy orbit, bubble burst, pink pop trail",
    soundSignature: "sweet pop sparkle, label only, no autoplay",
    hapticSignature: "tiny pop tap, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/royal-peacock-fan-final-polish.svg",
    animeStyleLabel: "premium anime · royal peacock",
    premiumBadge: "Mythic Royal",
    catalogHeroCopyRu: "Королевский Павлин выглядит как дорогой live gift: павлин раскрывает королевский веер, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: royal peacock, royal fan reveal, sound label и haptic signature.",
    visualSignature: "peacock fan, jewel feather, royal shimmer",
    soundSignature: "royal feather shine, label only, no autoplay",
    hapticSignature: "elegant royal pulse, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-shark-surge",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/neon-shark-surge-final-polish.svg",
    animeStyleLabel: "premium anime · neon shark",
    premiumBadge: "Legendary Surge",
    catalogHeroCopyRu: "Неоновая Акула выглядит как дорогой live gift: неоновая акула прорезает экран волной, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: neon shark, neon shark surge, sound label и haptic signature.",
    visualSignature: "shark surge, aqua laser, wave tunnel",
    soundSignature: "neon water slash, label only, no autoplay",
    hapticSignature: "surge impact, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "angel-harp-glow",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/angel-harp-glow-final-polish.svg",
    animeStyleLabel: "premium anime · angel harp",
    premiumBadge: "Rare Harmony",
    catalogHeroCopyRu: "Ангельская Арфа выглядит как дорогой live gift: арфа даёт золотой световой аккорд, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: angel harp, angel harp glow, sound label и haptic signature.",
    visualSignature: "harp string glow, light notes, angel ring",
    soundSignature: "harp angel chord, label only, no autoplay",
    hapticSignature: "soft chord pulse, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    heroPosterFile: "assets/stream/gifts/190a-premium-pack/final-polish/volcano-dragon-flare-final-polish.svg",
    animeStyleLabel: "premium anime · volcano dragon",
    premiumBadge: "Mythic Flare",
    catalogHeroCopyRu: "Вулкан Дракон выглядит как дорогой live gift: дракон выходит из вулканического портала, супер glow и финальный burst.",
    stageAuraCopyRu: "Сцена: volcano dragon, volcano dragon flare, sound label и haptic signature.",
    visualSignature: "lava gate, dragon flare, ember storm",
    soundSignature: "dragon lava hit, label only, no autoplay",
    hapticSignature: "finale heavy impact, local only",
    posterDetailChips: ["poster fallback", "aura layer", "final burst"],
    polishBadgeChips: ["anime", "premium", "pack 3"],
    finalSafetyCopyRu: "Локальный premium preview: нет real send, оплаты, backend/provider или payout.",
    finalPolishReadyNow: true,
    posterFallbackReadyNow: true,
    localPreviewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    realSendRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
  }
];

export const streamPremiumGiftPack190AAppearanceProfiles: StreamPremiumGiftAppearanceProfile188G[] = [
  {
    assetId: "solar-samurai-dash",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Солнечный Самурай · full-screen premium entrance",
    fullScreenLayerRu: "solar samurai overlay layer на весь экран",
    entranceRu: "solar blade entrance входит через cinematic glow",
    loopRu: "solar blade dash, gold rays, samurai cape trail живёт в live loop",
    finaleRu: "Mythic Solar finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "solar samurai spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "solar blade entrance particles",
    motionTrailRu: "solar samurai motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "удар солнечного клинка",
    hapticHitRu: "sharp gold impact",
    luxuryMoodRu: "дорогой anime/live event: Mythic Solar",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Русалка Жемчуг · full-screen premium entrance",
    fullScreenLayerRu: "pearl ocean overlay layer на весь экран",
    entranceRu: "pearl bloom wave входит через cinematic glow",
    loopRu: "pearl bloom, sea mist, mermaid wave живёт в live loop",
    finaleRu: "Legendary Pearl finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "pearl ocean spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "pearl bloom wave particles",
    motionTrailRu: "pearl ocean motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "жемчужный водный shimmer",
    hapticHitRu: "water pearl pulse",
    luxuryMoodRu: "дорогой anime/live event: Legendary Pearl",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Полночный Волк · full-screen premium entrance",
    fullScreenLayerRu: "midnight wolf overlay layer на весь экран",
    entranceRu: "moon wolf howl aura входит через cinematic glow",
    loopRu: "moon portal, wolf silhouette, silver trail живёт в live loop",
    finaleRu: "Legendary Moon finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "midnight wolf spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "moon wolf howl aura particles",
    motionTrailRu: "midnight wolf motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "лунный howl cue",
    hapticHitRu: "deep moon pulse",
    luxuryMoodRu: "дорогой anime/live event: Legendary Moon",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "candy-planet-pop",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Конфетная Планета · full-screen premium entrance",
    fullScreenLayerRu: "candy planet overlay layer на весь экран",
    entranceRu: "candy planet pop входит через cinematic glow",
    loopRu: "candy orbit, bubble burst, pink pop trail живёт в live loop",
    finaleRu: "Epic Pop finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "candy planet spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "candy planet pop particles",
    motionTrailRu: "candy planet motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "сладкий pop sparkle",
    hapticHitRu: "tiny pop tap",
    luxuryMoodRu: "дорогой anime/live event: Epic Pop",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Королевский Павлин · full-screen premium entrance",
    fullScreenLayerRu: "royal peacock overlay layer на весь экран",
    entranceRu: "royal fan reveal входит через cinematic glow",
    loopRu: "peacock fan, jewel feather, royal shimmer живёт в live loop",
    finaleRu: "Mythic Royal finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "royal peacock spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "royal fan reveal particles",
    motionTrailRu: "royal peacock motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "королевский feather shine",
    hapticHitRu: "elegant royal pulse",
    luxuryMoodRu: "дорогой anime/live event: Mythic Royal",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-shark-surge",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Неоновая Акула · full-screen premium entrance",
    fullScreenLayerRu: "neon shark overlay layer на весь экран",
    entranceRu: "neon shark surge входит через cinematic glow",
    loopRu: "shark surge, aqua laser, wave tunnel живёт в live loop",
    finaleRu: "Legendary Surge finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "neon shark spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "neon shark surge particles",
    motionTrailRu: "neon shark motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "неоновый water slash",
    hapticHitRu: "surge impact",
    luxuryMoodRu: "дорогой anime/live event: Legendary Surge",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "angel-harp-glow",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Ангельская Арфа · full-screen premium entrance",
    fullScreenLayerRu: "angel harp overlay layer на весь экран",
    entranceRu: "angel harp glow входит через cinematic glow",
    loopRu: "harp string glow, light notes, angel ring живёт в live loop",
    finaleRu: "Rare Harmony finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "angel harp spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "angel harp glow particles",
    motionTrailRu: "angel harp motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "ангельский harp chord",
    hapticHitRu: "soft chord pulse",
    luxuryMoodRu: "дорогой anime/live event: Rare Harmony",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    packLabelRu: "Pack 3 · Premium Live",
    appearanceTitleRu: "Вулкан Дракон · full-screen premium entrance",
    fullScreenLayerRu: "volcano dragon overlay layer на весь экран",
    entranceRu: "volcano dragon flare входит через cinematic glow",
    loopRu: "lava gate, dragon flare, ember storm живёт в live loop",
    finaleRu: "Mythic Flare finale burst закрывает экран",
    entranceDurationMs: 920,
    loopDurationMs: 2600,
    finaleDurationMs: 840,
    stageLightingRu: "volcano dragon spotlight + depth glow",
    backgroundDimRu: "мягкое затемнение live-фона, фокус на подарке",
    particleSystemRu: "volcano dragon flare particles",
    motionTrailRu: "volcano dragon motion trail",
    recipientFocusRu: "получатель подсвечен premium focus ring",
    soundHitRu: "драконий lava hit",
    hapticHitRu: "finale heavy impact",
    luxuryMoodRu: "дорогой anime/live event: Mythic Flare",
    appearanceChipsRu: ["entrance", "loop", "finale", "pack 3"],
    fallbackCopyRu: "reduce-motion: poster + glow + static aura, без heavy particles",
    safetyCopyRu: "Appearance preview only: без отправки, оплаты, backend, provider и payout.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  }
];

export const streamPremiumGiftPack190AVisualFxProfiles: StreamPremiumGiftVisualFxProfile188H[] = [
  {
    assetId: "solar-samurai-dash",
    visualFxTitleRu: "Солнечный Самурай · Pack 3 luxury FX",
    primaryGlowRu: "solar samurai ultra glow",
    particleBurstRu: "solar blade entrance particle burst",
    motionTrailRu: "solar blade dash, gold rays, samurai cape trail",
    auraRu: "Mythic Solar aura ring",
    screenImpactRu: "Солнечный Самурай даёт premium screen impact",
    finaleBurstRu: "solar blade entrance finale burst",
    luxuryLightingRu: "solar samurai cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 93,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    visualFxTitleRu: "Русалка Жемчуг · Pack 3 luxury FX",
    primaryGlowRu: "pearl ocean ultra glow",
    particleBurstRu: "pearl bloom wave particle burst",
    motionTrailRu: "pearl bloom, sea mist, mermaid wave",
    auraRu: "Legendary Pearl aura ring",
    screenImpactRu: "Русалка Жемчуг даёт premium screen impact",
    finaleBurstRu: "pearl bloom wave finale burst",
    luxuryLightingRu: "pearl ocean cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 94,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    visualFxTitleRu: "Полночный Волк · Pack 3 luxury FX",
    primaryGlowRu: "midnight wolf ultra glow",
    particleBurstRu: "moon wolf howl aura particle burst",
    motionTrailRu: "moon portal, wolf silhouette, silver trail",
    auraRu: "Legendary Moon aura ring",
    screenImpactRu: "Полночный Волк даёт premium screen impact",
    finaleBurstRu: "moon wolf howl aura finale burst",
    luxuryLightingRu: "midnight wolf cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 95,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "candy-planet-pop",
    visualFxTitleRu: "Конфетная Планета · Pack 3 luxury FX",
    primaryGlowRu: "candy planet ultra glow",
    particleBurstRu: "candy planet pop particle burst",
    motionTrailRu: "candy orbit, bubble burst, pink pop trail",
    auraRu: "Epic Pop aura ring",
    screenImpactRu: "Конфетная Планета даёт premium screen impact",
    finaleBurstRu: "candy planet pop finale burst",
    luxuryLightingRu: "candy planet cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 96,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    visualFxTitleRu: "Королевский Павлин · Pack 3 luxury FX",
    primaryGlowRu: "royal peacock ultra glow",
    particleBurstRu: "royal fan reveal particle burst",
    motionTrailRu: "peacock fan, jewel feather, royal shimmer",
    auraRu: "Mythic Royal aura ring",
    screenImpactRu: "Королевский Павлин даёт premium screen impact",
    finaleBurstRu: "royal fan reveal finale burst",
    luxuryLightingRu: "royal peacock cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 97,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-shark-surge",
    visualFxTitleRu: "Неоновая Акула · Pack 3 luxury FX",
    primaryGlowRu: "neon shark ultra glow",
    particleBurstRu: "neon shark surge particle burst",
    motionTrailRu: "shark surge, aqua laser, wave tunnel",
    auraRu: "Legendary Surge aura ring",
    screenImpactRu: "Неоновая Акула даёт premium screen impact",
    finaleBurstRu: "neon shark surge finale burst",
    luxuryLightingRu: "neon shark cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 98,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "angel-harp-glow",
    visualFxTitleRu: "Ангельская Арфа · Pack 3 luxury FX",
    primaryGlowRu: "angel harp ultra glow",
    particleBurstRu: "angel harp glow particle burst",
    motionTrailRu: "harp string glow, light notes, angel ring",
    auraRu: "Rare Harmony aura ring",
    screenImpactRu: "Ангельская Арфа даёт premium screen impact",
    finaleBurstRu: "angel harp glow finale burst",
    luxuryLightingRu: "angel harp cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 99,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    visualFxTitleRu: "Вулкан Дракон · Pack 3 luxury FX",
    primaryGlowRu: "volcano dragon ultra glow",
    particleBurstRu: "volcano dragon flare particle burst",
    motionTrailRu: "lava gate, dragon flare, ember storm",
    auraRu: "Mythic Flare aura ring",
    screenImpactRu: "Вулкан Дракон даёт premium screen impact",
    finaleBurstRu: "volcano dragon flare finale burst",
    luxuryLightingRu: "volcano dragon cinematic stage lighting",
    overlayDepthRu: "front particles + hero poster + rear aura",
    particleDensityLabel: "premium dense",
    glowIntensityLabel: "ultra glow",
    burstScaleLabel: "wide finale",
    trailDurationMs: 1700,
    auraPulseMs: 880,
    premiumFxScore: 93,
    fxChipsRu: ["glow", "particles", "trail", "burst"],
    fallbackCopyRu: "lite: poster fallback + one aura pulse + no heavy particles",
    safetyCopyRu: "Visual FX metadata only: no animation runtime, no payment, no real send.",
    userFacingOnly: true,
    previewOnlyNow: true,
    backendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    providerRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    sendRuntimeEnabledNow: false,
    actualAnimationRuntimeEnabledNow: false,
    actualSoundAutoplayEnabledNow: false,
    randomWinRuntimeEnabledNow: false,
  }
];

export const streamPremiumGiftPack190AFinalScreenPolishProfiles: StreamPremiumGiftFinalScreenPolish188I[] = [
  {
    assetId: "solar-samurai-dash",
    finalScreenTitleRu: "Солнечный Самурай · Pack 3 premium finale",
    premiumImpactRu: "самурай входит через солнечный клинок и закрывает экран дорогим final burst",
    soundSignatureRu: "удар солнечного клинка, label only, no autoplay",
    hapticSignatureRu: "sharp gold impact, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "solar blade entrance растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "mermaid-pearl-bloom",
    finalScreenTitleRu: "Русалка Жемчуг · Pack 3 premium finale",
    premiumImpactRu: "русалка раскрывает жемчужную волну и закрывает экран дорогим final burst",
    soundSignatureRu: "жемчужный водный shimmer, label only, no autoplay",
    hapticSignatureRu: "water pearl pulse, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "pearl bloom wave растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "midnight-wolf-moon",
    finalScreenTitleRu: "Полночный Волк · Pack 3 premium finale",
    premiumImpactRu: "волк появляется на фоне лунного портала и закрывает экран дорогим final burst",
    soundSignatureRu: "лунный howl cue, label only, no autoplay",
    hapticSignatureRu: "deep moon pulse, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "moon wolf howl aura растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "candy-planet-pop",
    finalScreenTitleRu: "Конфетная Планета · Pack 3 premium finale",
    premiumImpactRu: "конфетная планета взрывается pop-искрами и закрывает экран дорогим final burst",
    soundSignatureRu: "сладкий pop sparkle, label only, no autoplay",
    hapticSignatureRu: "tiny pop tap, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "candy planet pop растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "royal-peacock-fan",
    finalScreenTitleRu: "Королевский Павлин · Pack 3 premium finale",
    premiumImpactRu: "павлин раскрывает королевский веер и закрывает экран дорогим final burst",
    soundSignatureRu: "королевский feather shine, label only, no autoplay",
    hapticSignatureRu: "elegant royal pulse, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "royal fan reveal растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "neon-shark-surge",
    finalScreenTitleRu: "Неоновая Акула · Pack 3 premium finale",
    premiumImpactRu: "неоновая акула прорезает экран волной и закрывает экран дорогим final burst",
    soundSignatureRu: "неоновый water slash, label only, no autoplay",
    hapticSignatureRu: "surge impact, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "neon shark surge растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "angel-harp-glow",
    finalScreenTitleRu: "Ангельская Арфа · Pack 3 premium finale",
    premiumImpactRu: "арфа даёт золотой световой аккорд и закрывает экран дорогим final burst",
    soundSignatureRu: "ангельский harp chord, label only, no autoplay",
    hapticSignatureRu: "soft chord pulse, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "angel harp glow растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  },
  {
    assetId: "volcano-dragon-flare",
    finalScreenTitleRu: "Вулкан Дракон · Pack 3 premium finale",
    premiumImpactRu: "дракон выходит из вулканического портала и закрывает экран дорогим final burst",
    soundSignatureRu: "драконий lava hit, label only, no autoplay",
    hapticSignatureRu: "finale heavy impact, local haptic metadata",
    timingSignatureRu: "0.3s entrance · 2.6s loop · 0.8s finale",
    finaleCloseRu: "volcano dragon flare растворяется через luxury fade",
    recipientFocusRu: "получатель получает cinematic focus ring",
    crowdMomentRu: "чат видит premium gift moment без real send runtime",
    reduceMotionFallbackRu: "poster fallback + static glow + muted-safe sound label",
    soundPreviewRuntimeEnabledNow: false,
    realGiftSendRuntimeEnabledNow: false,
    paymentRuntimeEnabledNow: false,
    payoutRuntimeEnabledNow: false,
    backendRuntimeEnabledNow: false,
  }
];

export const streamPremiumGiftPack190ASummary = {
  version: "STREAM-GAME-GIFTS-190A",
  packLabel: "Pack 3 · Premium Live",
  addedGiftCount: streamPremiumGiftPack190A.length,
  cumulativeGiftCountAfter190A: 24,
  posterFallbackCount: streamPremiumGiftPack190A.length,
  finalPolishPosterCount: streamPremiumGiftPack190A.length,
  soundCueCount: streamPremiumGiftPack190AEffectProfiles.length,
  appearanceProfileCount: streamPremiumGiftPack190AAppearanceProfiles.length,
  visualFxProfileCount: streamPremiumGiftPack190AVisualFxProfiles.length,
  userFacingAssetsOnly: true,
  actualSoundAutoplayEnabledNow: false,
  actualAnimationRuntimeEnabledNow: false,
  backendRuntimeEnabledNow: false,
  paymentRuntimeEnabledNow: false,
  providerRuntimeEnabledNow: false,
  payoutRuntimeEnabledNow: false,
  sendRuntimeEnabledNow: false,
} as const;

export function getStreamPremiumGiftEffectProfile190A(assetId: string): StreamPremiumGiftEffectProfile187B {
  return streamPremiumGiftPack190AEffectProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190AEffectProfiles[0];
}

export function getStreamPremiumGiftPreviewExperience190A(assetId: string): StreamPremiumGiftPreviewExperience187C {
  return streamPremiumGiftPack190APreviewExperiences.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190APreviewExperiences[0];
}

export function getStreamPremiumGiftFinalPolish190A(assetId: string): StreamPremiumGiftFinalPolish187D {
  return streamPremiumGiftPack190AFinalPolishProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190AFinalPolishProfiles[0];
}

export function getStreamPremiumGiftAppearanceProfile190A(assetId: string): StreamPremiumGiftAppearanceProfile188G {
  return streamPremiumGiftPack190AAppearanceProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190AAppearanceProfiles[0];
}

export function getStreamPremiumGiftVisualFxProfile190A(assetId: string): StreamPremiumGiftVisualFxProfile188H {
  return streamPremiumGiftPack190AVisualFxProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190AVisualFxProfiles[0];
}

export function getStreamPremiumGiftFinalScreenPolish190A(assetId: string): StreamPremiumGiftFinalScreenPolish188I {
  return streamPremiumGiftPack190AFinalScreenPolishProfiles.find((profile) => profile.assetId === assetId) ?? streamPremiumGiftPack190AFinalScreenPolishProfiles[0];
}
