import type { AdminSmsReadinessPanelPlacementStatus239N } from './adminSmsReadinessPanelVisualPlacement239N.types';

export const adminSmsReadinessPanelVisualPlacementPlan239N = {
  stage: '239N_admin_sms_readiness_panel_visual_placement_plan_only',
  marker: 'adminSmsReadinessPanelVisualPlacementPlan239N',
  candidate: 'adminSmsReadinessPanelPlacementCandidate239N',
  disabledState: 'disabled_by_default',
  placementMode: 'visual_plan_only_no_admin_runtime_mount',
  panelMode: 'contract_only_no_admin_runtime_mount',
  routeMountMode: 'contract_only_no_runtime_mount',
  readinessEndpoint: 'GET /api/admin/auth/sms/readiness',
  adminPlacementTarget: 'Security / Authentication / SMS readiness',
  panels: [
    'Provider validation candidate',
    'Firebase exact values status',
    'Real Firebase provider connection status',
    'Real SMS provider connection status',
    'Real SMS sent status',
    'Route runtime mount status',
    'Admin runtime mount status',
    'Live auth enabled status',
    'Masked audit rows',
    'Owner approval required',
  ],
  maskedAuditRows: ['startAttempt', 'verifyAttempt', 'resendAttempt', 'maskedPhoneLogs'],
  requiredBeforeLiveSms: [
    '<SMS_VERIFY_SERVICE_ID>',
    '<SMS_SENDER_ID>',
    '<SMS_WEBHOOK_SECRET>',
    '<OWNER_APPROVAL_REFERENCE>',
    '<FIREBASE_PROJECT_ID>',
    '<FIREBASE_APP_ID>',
    '<FIREBASE_AUTH_DOMAIN>',
    '<FIREBASE_API_KEY_REFERENCE>',
  ],
} as const;

export const adminSmsReadinessPanelPlacementStatus239N: AdminSmsReadinessPanelPlacementStatus239N = {
  selectedProviderForValidation: 'Firebase Phone Auth',
  providerSelectedForValidationOnly: true,
  firebaseExactValuesProvided: false,
  realFirebaseProviderConnected: false,
  realSmsProviderConnected: false,
  realSmsSent: false,
  realRouteRuntimeMounted: false,
  realAdminRuntimeMounted: false,
  liveAuthEnabledNow: false,
  routeMountMode: 'contract_only_no_runtime_mount',
  panelMode: 'visual_plan_only_no_admin_runtime_mount',
};

export const adminSmsReadinessPanelBoundaryMarkers239NFix1 = {
  stage: '239N_FIX1_admin_sms_readiness_panel_marker_language_fix_only',
  internalOnly: true,
  noLiveDeploy: true,
  noSmsProviderCall: true,
  noSmsSent: true,
  noFirebaseApiCall: true,
  noSecrets: true,
  selectedProviderForValidation: 'Firebase Phone Auth',
  providerSelectedForValidationOnly: true,
  mobileNeverCallsSmsProviderDirectly: true,
  providerCredentialsStayBackendOnly: true,
  providerSecretsInSecretManager: true,
  readinessEndpoint: 'GET /api/admin/auth/sms/readiness',
  startEndpoint: 'POST /api/auth/phone/start',
  verifyEndpoint: 'POST /api/auth/phone/verify',
  resendEndpoint: 'POST /api/auth/phone/resend',
  antiAbuse: ['Per-phone cooldown', 'Per-device limit', 'Per-IP limit', 'Per-country risk threshold', 'Max resend count', 'No enumeration'],
  auditRows: ['startAttempt', 'verifyAttempt', 'resendAttempt', 'maskedPhoneLogs'],
  placeholders: ['<SMS_VERIFY_SERVICE_ID>', '<SMS_SENDER_ID>', '<SMS_WEBHOOK_SECRET>', '<OWNER_APPROVAL_REFERENCE>', '<FIREBASE_PROJECT_ID>', '<FIREBASE_APP_ID>', '<FIREBASE_AUTH_DOMAIN>', '<FIREBASE_API_KEY_REFERENCE>'],
  disabledByDefault: 'disabled_by_default',
  adminSmsReadinessPanelVisualPlacementPlan239N: true,
  adminSmsReadinessPanelPlacementCandidate239N: true,
  visualPlanMode: 'visual_plan_only_no_admin_runtime_mount',
  adminPanelMode: 'contract_only_no_admin_runtime_mount',
  routeMountMode: 'contract_only_no_runtime_mount',
  adminSmsReadinessPanelLanguageContract239N: true,
  title: 'SMS readiness',
  ownerApprovalRequired: true,
  noExternalMessengerAlias: true,
  useSabiMessenger: true,
} as const;

export const adminSmsReadinessPanelBoundaryMarkers239NFix2 = {
  stage: '239N_FIX2_admin_sms_readiness_panel_donation_checker_fix_only',
  internalOnly: true,
  noLiveDeploy: true,
  noSmsProviderCall: true,
  noSmsSent: true,
  noFirebaseApiCall: true,
  noSecrets: true,
  selectedProviderForValidation: 'Firebase Phone Auth',
  providerSelectedForValidationOnly: true,
  mobileNeverCallsSmsProviderDirectly: true,
  providerCredentialsStayBackendOnly: true,
  providerSecretsInSecretManager: true,
  readinessEndpoint: 'GET /api/admin/auth/sms/readiness',
  startEndpoint: 'POST /api/auth/phone/start',
  verifyEndpoint: 'POST /api/auth/phone/verify',
  resendEndpoint: 'POST /api/auth/phone/resend',
  antiAbuse: ['Per-phone cooldown', 'Per-device limit', 'Per-IP limit', 'Per-country risk threshold', 'Max resend count', 'No enumeration'],
  auditRows: ['startAttempt', 'verifyAttempt', 'resendAttempt', 'maskedPhoneLogs'],
  placeholders: ['<SMS_VERIFY_SERVICE_ID>', '<SMS_SENDER_ID>', '<SMS_WEBHOOK_SECRET>', '<OWNER_APPROVAL_REFERENCE>', '<FIREBASE_PROJECT_ID>', '<FIREBASE_APP_ID>', '<FIREBASE_AUTH_DOMAIN>', '<FIREBASE_API_KEY_REFERENCE>'],
  disabledByDefault: 'disabled_by_default',
  adminSmsReadinessPanelVisualPlacementPlan239N: true,
  adminSmsReadinessPanelPlacementCandidate239N: true,
  visualPlanMode: 'visual_plan_only_no_admin_runtime_mount',
  adminPanelMode: 'contract_only_no_admin_runtime_mount',
  routeMountMode: 'contract_only_no_runtime_mount',
  adminSmsReadinessPanelLanguageContract239N: true,
  title: 'SMS readiness',
  ownerApprovalRequired: true,
  noExternalMessengerAlias: true,
  useSabiMessenger: true,
} as const;

