import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAntiAccidentalRuntimeGuard,
  TaxiFinalHandoffMatrixItem,
  TaxiFinalReadinessScoreItem,
  TaxiClientBoundaryCompatibilityAssertion,
} from './taxiFinalControl.types';

export const TAXI_FINAL_CONTROL_VERSION = 'TAXI-BACKEND-FOUNDATION-001L' as const;

export const TAXI_FINAL_READINESS_SCORE_ITEMS: readonly TaxiFinalReadinessScoreItem[] = [
  {
    dimensionId: 'client_boundary_compatibility',
    title: 'Client app uses Taxi kernel facade/events/state only.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'admin_foundation_contracts',
    title: 'Admin sections, permissions, dashboard filters, action inbox and approval gates are foundation-backed.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'sabi_ai_daily_report_completeness',
    title: 'Full Sabi AI daily report is required for every country/day before close.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'all_complaints_daily_review',
    title: 'All driver/rider complaints must be checked every day with false complaint and abuse detection.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'evidence_redaction_privacy',
    title: 'Raw evidence remains Admin/foundation only; mobile receives redacted kernel-safe status.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'admin_approval_gates',
    title: 'Heavy actions require participant explanation, supervisor approval and locked Admin decision.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'execution_readiness_gates',
    title: 'Future API, scheduler, DB, Wallet, provider, payment and payout execution gates are contract-only now.',
    scorePercent: 100,
    level: 'blocked_until_exact_approval',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'anti_accidental_runtime_guard',
    title: 'Accidental runtime activation is blocked by explicit safe-disabled control markers.',
    scorePercent: 100,
    level: 'blocked_until_exact_approval',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'wallet_payment_payout_locks',
    title: 'Driver top-up, Admin-configured commission debit, charge, tips, prize release and payout remain locked.',
    scorePercent: 100,
    level: 'blocked_until_exact_approval',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'provider_dispatch_locks',
    title: 'Dispatch, route, traffic, radar, map, quote and matching providers remain disabled.',
    scorePercent: 100,
    level: 'blocked_until_exact_approval',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
  {
    dimensionId: 'fake_success_blockers',
    title: 'No fake driver assignment, payment, trip completion, sanction, restore, prize or payout success.',
    scorePercent: 100,
    level: 'ready_contract_only',
    adminVisible: true,
    clientKernelBoundaryCompatible: true,
    blocksRuntimeUntilExactApproval: true,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_FINAL_HANDOFF_MATRIX: readonly TaxiFinalHandoffMatrixItem[] = [
  {
    owner: 'foundation',
    stage: 'contract_ready_safe_disabled',
    title: 'Taxi contracts, safety rules and kernel boundaries are source-ready.',
    requiredBeforeRuntime: ['exact owner approval', 'route mount plan', 'rollback plan'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'admin_ui',
    stage: 'admin_visible_contract_ready',
    title: 'Admin can show readiness, daily report, action inbox and approval gates from the same foundation contracts.',
    requiredBeforeRuntime: ['admin permission map', 'review-only dashboard smoke', 'no write buttons until approval'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'client_boundary',
    stage: 'admin_visible_contract_ready',
    title: 'Client app uses kernel-safe summaries only and never imports provider/payment/payout runtime directly.',
    requiredBeforeRuntime: ['kernel facade binding', 'redacted status schema', 'clean close behavior'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'sabi_ai',
    stage: 'exact_approval_required_before_execution',
    title: 'Daily AI report executor is not running now; contracts require every complaint checked every day.',
    requiredBeforeRuntime: ['AI provider approval', 'evidence retention policy', 'daily scheduler approval'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'db_schema',
    stage: 'future_runtime_blocked_now',
    title: 'DB schema, Prisma generate, migrations, reads and writes remain blocked until exact approval.',
    requiredBeforeRuntime: ['schema review', 'migration plan', 'backup and rollback plan'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'runtime_api',
    stage: 'future_runtime_blocked_now',
    title: 'Taxi HTTP routes, dashboard runtime and scheduler runtime remain unmounted.',
    requiredBeforeRuntime: ['route protection review', 'rate limit plan', 'auth smoke'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'provider_dispatch',
    stage: 'future_runtime_blocked_now',
    title: 'Dispatch/map/route/traffic/provider calls require reference labels and exact runtime approval.',
    requiredBeforeRuntime: ['provider references', 'safe-disabled smoke', 'fail-closed provider_not_configured behavior'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
  {
    owner: 'wallet_payment_payout',
    stage: 'future_runtime_blocked_now',
    title: 'Driver top-up, Admin-configured commission debit, ride charge, tips, prizes and payouts remain locked.',
    requiredBeforeRuntime: ['Wallet ledger approval', 'payment provider approval', 'payout legal finance review'],
    canExecuteNow: false,
    exactApprovalRequired: true,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_ANTI_ACCIDENTAL_RUNTIME_GUARDS: readonly TaxiAntiAccidentalRuntimeGuard[] = [
  {
    guardId: 'no_app_ts_mount_without_exact_approval',
    title: 'Do not mount Taxi runtime routes in app.ts without exact approval.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_scheduler_start_without_exact_approval',
    title: 'Do not start daily Sabi AI report scheduler without exact approval.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_db_read_write_without_schema_gate',
    title: 'No DB read/write before schema, migration and approval gates are complete.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_wallet_mutation_without_ledger_gate',
    title: 'No driver balance mutation or Admin-configured commission debit before Wallet ledger gate.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_payment_charge_without_provider_gate',
    title: 'No ride charge, hold, tips or refund before payment provider gate.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_payout_release_without_legal_finance_gate',
    title: 'No prize release or payout before legal/finance/Admin approval.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_dispatch_provider_call_without_reference_label_gate',
    title: 'No dispatch/map/route/provider call before provider reference labels and exact approval.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_mobile_direct_backend_provider_imports',
    title: 'Client app cannot import backend/provider/payment/payout directly; Taxi kernel only.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_raw_evidence_publish_to_mobile',
    title: 'Raw chat, call, route, complaint and identity evidence is Admin/foundation only.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
  {
    guardId: 'no_fake_success_fallback',
    title: 'No fake assignment, payment, completion, sanction, reward, restore or payout fallback.',
    enforcedFromFoundation: true,
    canBeBypassedByUi: false,
    exactApprovalRequiredToUnlock: true,
    runtimeEnabledNow: false,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_CLIENT_BOUNDARY_COMPATIBILITY_ASSERTIONS: readonly TaxiClientBoundaryCompatibilityAssertion[] = [
  {
    assertionId: 'mobile_ui_uses_kernel_facade_only',
    description: 'Taxi client app communicates through kernel facade/events/state only.',
    requiredForMobileUi: true,
    adminFoundationBacked: true,
    directProviderImportAllowed: false,
    directPaymentOrPayoutAllowed: false,
    rawEvidenceAllowedOnMobile: false,
  },
  {
    assertionId: 'mobile_receives_redacted_status_only',
    description: 'Mobile receives redacted status and user-facing explanation, never raw evidence.',
    requiredForMobileUi: true,
    adminFoundationBacked: true,
    directProviderImportAllowed: false,
    directPaymentOrPayoutAllowed: false,
    rawEvidenceAllowedOnMobile: false,
  },
  {
    assertionId: 'mobile_publish_after_admin_lock_only',
    description: 'Mobile status is published after Admin locked decision, not from UI speculation.',
    requiredForMobileUi: true,
    adminFoundationBacked: true,
    directProviderImportAllowed: false,
    directPaymentOrPayoutAllowed: false,
    rawEvidenceAllowedOnMobile: false,
  },
  {
    assertionId: 'mobile_close_stops_taxi_session_runtime',
    description: 'Closing Taxi must stop future active session runtime; no always-on hidden Taxi background process.',
    requiredForMobileUi: true,
    adminFoundationBacked: true,
    directProviderImportAllowed: false,
    directPaymentOrPayoutAllowed: false,
    rawEvidenceAllowedOnMobile: false,
  },
  {
    assertionId: 'mobile_resume_never_fakes_active_trip',
    description: 'Resume cannot fake active trip, driver, payment or completion without verified backend state.',
    requiredForMobileUi: true,
    adminFoundationBacked: true,
    directProviderImportAllowed: false,
    directPaymentOrPayoutAllowed: false,
    rawEvidenceAllowedOnMobile: false,
  },
];

export const taxiFinalControlRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/admin/taxi/final-control/contracts',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin final foundation control contracts for readiness score, handoff matrix and anti-runtime guards.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/final-control/readiness-score',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future read-only readiness score route; unmounted until exact runtime approval.',
  },
  {
    method: 'GET',
    path: '/api/admin/taxi/final-control/handoff-matrix',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future Admin handoff matrix route; unmounted and DB-free now.',
  },
  {
    method: 'POST',
    path: '/api/admin/taxi/final-control/anti-runtime-guard/check',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future anti-accidental-runtime guard check; no mutation and no runtime now.',
  },
];
