export type SabiAiLocalDryRunExecutionCandidate254P = typeof import('./sabiAiLocalDryRunExecutionCandidate254P').sabiAiLocalDryRunExecutionCandidate254P;
export type SabiAiLocalDryRunExecutionSafety254P = typeof import('./sabiAiLocalDryRunExecutionCandidate254P').sabiAiLocalDryRunExecutionSafety254P;
