import {
  STREAM_FOUNDATION_142S_BLOCKED_RESPONSE_ENVELOPE_PLANNING_VERSION,
  type StreamFoundation142SBlockedResponseEnvelopeInspectionPlanningSnapshot,
  type StreamFoundation142SEmptyBodyHypothesis,
  type StreamFoundation142SNormalizationPlanStep,
} from "./streamFoundationBlockedResponseEnvelopeInspectionPlanningContracts";

export const STREAM_FOUNDATION_142S_OWNER_APPROVAL_TEXT =
  "I approve BACKEND-STREAM-FOUNDATION-142S controlled blocked-response envelope inspection and normalization planning only, inspect why 142Q runtime POST smoke received HTTP 423 with empty response bodies, prepare source-only plan to preserve 423 blocked status and restore/verify JSON blocked envelopes if needed, do not write src/app.ts, do not write src/server.ts, do not write src/modules/stream/index.ts, do not restart backend, no runtime POST, no DB write, no provider call, no Wallet mutation, no payment authorization, no monthly payout, no money movement, no fake success.";

export const STREAM_FOUNDATION_142S_REQUIRED_EXACT_APPROVAL_TEXT_FOR_142T =
  "I approve BACKEND-STREAM-FOUNDATION-142T controlled blocked-response envelope source inspection ops-only, inspect src/app.ts and the 142C runtime handler draft source to determine why runtime POST returns HTTP 423 with empty response bodies, prepare a report only, do not write src/app.ts, do not write src/server.ts, do not write src/modules/stream/index.ts, do not restart backend, no runtime POST, no DB write, no provider call, no Wallet mutation, no payment authorization, no monthly payout, no money movement, no fake success.";

const EMPTY_BODY_HYPOTHESES: readonly StreamFoundation142SEmptyBodyHypothesis[] = [
  {
    id: "powershell_non_2xx_body_capture_gap",
    status: "needs_ops_runner_verification",
    description: "PowerShell web-request capture can treat non-2xx responses as errors, so response stream handling must be checked.",
    inspectionTargets: ["ops/stream/142q-controlled-blocked-route-runtime-post-smoke/run-stream-foundation-142q-controlled-blocked-route-runtime-post-smoke.ps1"],
    preserveStatusCode423: true,
    allowRuntimePostIn142S: false,
    allowTargetWriteIn142S: false,
    allowDatabaseWrite: false,
    allowProviderCall: false,
    allowWalletMutation: false,
    allowMoneyMovement: false,
    allowFakeSuccess: false,
  },
  {
    id: "express_423_json_body_not_serialized",
    status: "needs_source_inspection",
    description: "src/app.ts route code should be inspected to verify status-plus-json response shape is still used after 142N.",
    inspectionTargets: ["src/app.ts"],
    preserveStatusCode423: true,
    allowRuntimePostIn142S: false,
    allowTargetWriteIn142S: false,
    allowDatabaseWrite: false,
    allowProviderCall: false,
    allowWalletMutation: false,
    allowMoneyMovement: false,
    allowFakeSuccess: false,
  },
  {
    id: "runtime_handler_envelope_undefined_or_non_json",
    status: "needs_source_inspection",
    description: "The 142C runtime handler draft should be inspected to verify it returns a serializable blocked envelope with statusCode 423.",
    inspectionTargets: ["src/modules/stream/foundation/live-write-runtime-handler/streamFoundationLiveWriteRuntimeHandlerDraft.ts"],
    preserveStatusCode423: true,
    allowRuntimePostIn142S: false,
    allowTargetWriteIn142S: false,
    allowDatabaseWrite: false,
    allowProviderCall: false,
    allowWalletMutation: false,
    allowMoneyMovement: false,
    allowFakeSuccess: false,
  },
  {
    id: "response_interceptor_or_error_middleware_swallowing_body",
    status: "needs_source_inspection",
    description: "Express middleware or error handling should be checked only if app route and handler envelope are correct.",
    inspectionTargets: ["src/app.ts", "src/server.ts"],
    preserveStatusCode423: true,
    allowRuntimePostIn142S: false,
    allowTargetWriteIn142S: false,
    allowDatabaseWrite: false,
    allowProviderCall: false,
    allowWalletMutation: false,
    allowMoneyMovement: false,
    allowFakeSuccess: false,
  },
  {
    id: "client_capture_needs_response_stream_fallback",
    status: "not_success_signal",
    description: "Because HTTP status is 423 and success markers are absent, empty body is a quality/diagnostic issue, not a launch-success signal.",
    inspectionTargets: ["142Q runtime report", "future 142T source inspection report"],
    preserveStatusCode423: true,
    allowRuntimePostIn142S: false,
    allowTargetWriteIn142S: false,
    allowDatabaseWrite: false,
    allowProviderCall: false,
    allowWalletMutation: false,
    allowMoneyMovement: false,
    allowFakeSuccess: false,
  },
];

const NORMALIZATION_PLAN_STEPS: readonly StreamFoundation142SNormalizationPlanStep[] = [
  {
    id: "inspect_app_route_response_shape",
    description: "Verify start/stop/heartbeat routes still respond with HTTP 423 and a JSON envelope object.",
    currentStageAction: "plan_only",
    futureStageRequired: "142T_ops_inspection",
    preserveStatusCode423: true,
    sourceWriteAllowedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
  {
    id: "inspect_142c_runtime_handler_envelope",
    description: "Verify runtime handler draft returns a JSON-serializable blocked envelope and not undefined or empty value.",
    currentStageAction: "plan_only",
    futureStageRequired: "142T_ops_inspection",
    preserveStatusCode423: true,
    sourceWriteAllowedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
  {
    id: "inspect_142q_response_capture",
    description: "Verify the 142Q runner captures non-2xx response streams correctly before deciding a backend source fix is needed.",
    currentStageAction: "plan_only",
    futureStageRequired: "142T_ops_inspection",
    preserveStatusCode423: true,
    sourceWriteAllowedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
  {
    id: "draft_json_blocked_envelope_requirement",
    description: "Define required blocked JSON envelope fields while keeping HTTP 423 as the safety baseline.",
    currentStageAction: "plan_only",
    futureStageRequired: "142T_ops_inspection",
    preserveStatusCode423: true,
    sourceWriteAllowedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
  {
    id: "prepare_future_patch_only_if_needed",
    description: "Only after inspection, prepare a separate exact-approval target patch if JSON blocked envelopes truly need normalization.",
    currentStageAction: "plan_only",
    futureStageRequired: "future_exact_target_patch_if_needed",
    preserveStatusCode423: true,
    sourceWriteAllowedNow: false,
    runtimePostAllowedNow: false,
    databaseWriteAllowedNow: false,
    providerCallAllowedNow: false,
    walletMutationAllowedNow: false,
    moneyMovementAllowedNow: false,
    fakeSuccessAllowedNow: false,
  },
];

export function getStreamFoundationBlockedResponseEnvelopeInspectionPlanningSnapshot(): StreamFoundation142SBlockedResponseEnvelopeInspectionPlanningSnapshot {
  return {
    version: STREAM_FOUNDATION_142S_BLOCKED_RESPONSE_ENVELOPE_PLANNING_VERSION,
    stage: "blocked_response_envelope_inspection_and_normalization_planning_only",
    status: "blocked_response_envelope_planning_ready",
    previousStage: "BACKEND-STREAM-FOUNDATION-142R",
    ownerApprovalAccepted: true,
    ownerApprovalText: STREAM_FOUNDATION_142S_OWNER_APPROVAL_TEXT,
    evidenceFrom142QAnd142R: {
      runtimeSmokePassed: true,
      routesAttempted: 3,
      routesReturned423: 3,
      responseBodiesEmpty: true,
      responseJsonParseOk: false,
      noForbiddenSuccessFragments: true,
      tscExitCode: 0,
      sourceMutationPerformed: 0,
      backendRestartPerformed: 0,
      databaseWritePerformed: 0,
      providerCallPerformed: 0,
      walletMutationPerformed: 0,
      moneyMovementPerformed: 0,
      fakeSuccessAllowed: false,
    },
    planningDecision: {
      emptyBodyIsNotSuccess: true,
      preserve423BlockedAsPrimarySafetyRequirement: true,
      jsonBlockedEnvelopeRestorationMayBeNeeded: true,
      currentStageIsPlanningOnly: true,
      targetWriteAllowedNow: false,
      runtimePostAllowedNow: false,
      backendRestartAllowedNow: false,
    },
    emptyBodyHypotheses: EMPTY_BODY_HYPOTHESES,
    normalizationPlanSteps: NORMALIZATION_PLAN_STEPS,
    requiredExactApprovalTextFor142T: STREAM_FOUNDATION_142S_REQUIRED_EXACT_APPROVAL_TEXT_FOR_142T,
    nextApprovalPolicy: {
      exactApprovalRequiredBefore142T: true,
      nextStageIsOpsOnlySourceInspection: true,
      nextStageMayInspectAppTs: true,
      nextStageMayInspectRuntimeHandlerDraft: true,
      nextStageMustNotWriteTargets: true,
      nextStageMustNotRestartBackend: true,
      nextStageMustNotRuntimePost: true,
      nextStageMustNotDatabaseWrite: true,
      nextStageMustNotProviderCall: true,
      nextStageMustNotWalletMutation: true,
      nextStageMustNotMoneyMovement: true,
      nextStageMustNotFakeSuccess: true,
    },
    safety: {
      sourceOnly142S: true,
      targetWriteBy142S: false,
      appTsChangeBy142S: false,
      serverTsChangeBy142S: false,
      streamIndexChangeBy142S: false,
      backendRestartBy142S: false,
      runtimeHttpBy142S: false,
      runtimePostBy142S: false,
      databaseReadBy142S: false,
      databaseWriteBy142S: false,
      providerCallBy142S: false,
      providerSecretReadBy142S: false,
      walletMutationBy142S: false,
      paymentAuthorizationBy142S: false,
      monthlyPayoutBy142S: false,
      moneyMovementBy142S: false,
      fakeSuccessBy142S: false,
    },
  };
}
