import type {
  SabiAiStreamClipDraftQueue252B,
  SabiAiStreamClipMetadata252B,
  SabiAiStreamClipSafetyReview252B,
  SabiAiStreamSafetyLocks252B,
} from './sabiAiStreamClipReview252B.types';

export const sabiAiStreamClipMetadataTemplate252B: SabiAiStreamClipMetadata252B = {
  clipId: 'local-draft-id',
  accountMode: 'sabi_ai_own_stream_account',
  publicStatus: 'draft_until_review_passed',
  title: '',
  description: '',
  languageCode: 'ru',
  targetCultureOrMentality: '',
  theme: [
    'love',
    'homeland',
    'nature',
    'human_values',
    'respect',
    'learning',
    'kindness',
    'safe_youth_development',
    'real_human_communication',
  ],
  creativeStyle: 'original_style_description',
  mood: 'calm_positive_educational_or_emotional',
  lyricsMode: 'original_or_no_lyrics',
  musicMode: 'original_composition_or_no_music',
  videoMode: 'original_visual_plan',
  ageAudience: 'general_or_youth_safe',
  createdBy: 'Sabi AI',
  ownerApprovalStatus: 'pending',
  safetyReviewStatus: 'pending',
  publicPostAllowed: false,
  liveBroadcastAllowed: false,
} as const;

export const sabiAiStreamClipSafetyReview252B: SabiAiStreamClipSafetyReview252B = {
  reviewBeforePublicPost: true,
  originalityReview: true,
  copyrightSafeReview: true,
  noExistingSongCopy: true,
  noExistingClipCopy: true,
  noCelebrityVoiceOrIdentityCopy: true,
  cultureRespectReview: true,
  noHumiliationReview: true,
  youthSafetyReview: true,
  childSafetyReview: true,
  redPriorityCrimeRiskReview: true,
  noHarmfulIllegalPromotionReview: true,
  noPersonalDataLeakReview: true,
  noNonConsensualContentReview: true,
  ownerOrAuthorizedApprovalRequired: true,
  doNotRevealInvestigationReasonToBadActor: true,
  neutralMessageOnlyWhenRestricted: true,
} as const;

export const sabiAiStreamClipDraftQueue252B: SabiAiStreamClipDraftQueue252B = {
  queueMode: 'draft_clip_queue_before_public_account_post',
  states: [
    'draft_created',
    'metadata_ready',
    'safety_review_pending',
    'needs_edit',
    'owner_review_pending',
    'approved_for_account_post_queue',
    'posted_to_account_after_future_runtime_approval',
    'rejected',
    'red_priority_hold',
  ],
} as const;

export const sabiAiStreamSafetyLocks252B: SabiAiStreamSafetyLocks252B = {
  localCodeArtifactOnly: true,
  noLiveBroadcastNow: true,
  noRuntimeMountNow: true,
  noAdminRouteConnectionNow: true,
  noRuntimePostNow: true,
  noProviderCallNow: true,
  noProtectedConfigReadWriteNow: true,
  noDbMutationNow: true,
  noPaymentNow: true,
  noRestrictedLiveActionNow: true,
  finalActionsExecutedNow: false,
  ownerApprovalRequiredForPublicPost: true,
  ownerApprovalRequiredForLiveBroadcast: true,
} as const;
