export type StreamCountryCode = "all" | "af" | "al" | "dz" | "ad" | "ao" | "ag" | "ar" | "am" | "au" | "at" | "az" | "bs" | "bh" | "bd" | "bb" | "by" | "be" | "bz" | "bj" | "bt" | "bo" | "ba" | "bw" | "br" | "bn" | "bg" | "bf" | "bi" | "cv" | "kh" | "cm" | "ca" | "cf" | "td" | "cl" | "cn" | "co" | "km" | "cg" | "cd" | "cr" | "ci" | "hr" | "cu" | "cy" | "cz" | "dk" | "dj" | "dm" | "do" | "ec" | "eg" | "sv" | "gq" | "er" | "ee" | "sz" | "et" | "fj" | "fi" | "fr" | "ga" | "gm" | "ge" | "de" | "gh" | "gr" | "gd" | "gt" | "gn" | "gw" | "gy" | "ht" | "hn" | "hu" | "is" | "in" | "id" | "ir" | "iq" | "ie" | "il" | "it" | "jm" | "jp" | "jo" | "kz" | "ke" | "ki" | "kw" | "kg" | "la" | "lv" | "lb" | "ls" | "lr" | "ly" | "li" | "lt" | "lu" | "mg" | "mw" | "my" | "mv" | "ml" | "mt" | "mh" | "mr" | "mu" | "mx" | "fm" | "md" | "mc" | "mn" | "me" | "ma" | "mz" | "mm" | "na" | "nr" | "np" | "nl" | "nz" | "ni" | "ne" | "ng" | "kp" | "mk" | "no" | "om" | "pk" | "pw" | "pa" | "pg" | "py" | "pe" | "ph" | "pl" | "pt" | "qa" | "ro" | "ru" | "rw" | "kn" | "lc" | "vc" | "ws" | "sm" | "st" | "sa" | "sn" | "rs" | "sc" | "sl" | "sg" | "sk" | "si" | "sb" | "so" | "za" | "kr" | "ss" | "es" | "lk" | "sd" | "sr" | "se" | "ch" | "sy" | "tj" | "tz" | "th" | "tl" | "tg" | "to" | "tt" | "tn" | "tr" | "tm" | "tv" | "ug" | "ua" | "ae" | "gb" | "us" | "uy" | "uz" | "vu" | "va" | "ve" | "vn" | "ye" | "zm" | "zw";

export type StreamCountry = {
  code: StreamCountryCode;
  ru: string;
  en: string;
};

export const STREAM_ALL_COUNTRIES: StreamCountry[] = [
  { code: "all", ru: "Все страны", en: "All countries" },
  { code: "af", ru: "Афганистан", en: "Afghanistan" },
  { code: "al", ru: "Албания", en: "Albania" },
  { code: "dz", ru: "Алжир", en: "Algeria" },
  { code: "ad", ru: "Андорра", en: "Andorra" },
  { code: "ao", ru: "Ангола", en: "Angola" },
  { code: "ag", ru: "Антигуа и Барбуда", en: "Antigua and Barbuda" },
  { code: "ar", ru: "Аргентина", en: "Argentina" },
  { code: "am", ru: "Армения", en: "Armenia" },
  { code: "au", ru: "Австралия", en: "Australia" },
  { code: "at", ru: "Австрия", en: "Austria" },
  { code: "az", ru: "Азербайджан", en: "Azerbaijan" },
  { code: "bs", ru: "Багамы", en: "Bahamas" },
  { code: "bh", ru: "Бахрейн", en: "Bahrain" },
  { code: "bd", ru: "Бангладеш", en: "Bangladesh" },
  { code: "bb", ru: "Барбадос", en: "Barbados" },
  { code: "by", ru: "Беларусь", en: "Belarus" },
  { code: "be", ru: "Бельгия", en: "Belgium" },
  { code: "bz", ru: "Белиз", en: "Belize" },
  { code: "bj", ru: "Бенин", en: "Benin" },
  { code: "bt", ru: "Бутан", en: "Bhutan" },
  { code: "bo", ru: "Боливия", en: "Bolivia" },
  { code: "ba", ru: "Босния и Герцеговина", en: "Bosnia and Herzegovina" },
  { code: "bw", ru: "Ботсвана", en: "Botswana" },
  { code: "br", ru: "Бразилия", en: "Brazil" },
  { code: "bn", ru: "Бруней", en: "Brunei" },
  { code: "bg", ru: "Болгария", en: "Bulgaria" },
  { code: "bf", ru: "Буркина-Фасо", en: "Burkina Faso" },
  { code: "bi", ru: "Бурунди", en: "Burundi" },
  { code: "cv", ru: "Кабо-Верде", en: "Cabo Verde" },
  { code: "kh", ru: "Камбоджа", en: "Cambodia" },
  { code: "cm", ru: "Камерун", en: "Cameroon" },
  { code: "ca", ru: "Канада", en: "Canada" },
  { code: "cf", ru: "ЦАР", en: "Central African Republic" },
  { code: "td", ru: "Чад", en: "Chad" },
  { code: "cl", ru: "Чили", en: "Chile" },
  { code: "cn", ru: "Китай", en: "China" },
  { code: "co", ru: "Колумбия", en: "Colombia" },
  { code: "km", ru: "Коморы", en: "Comoros" },
  { code: "cg", ru: "Конго", en: "Congo" },
  { code: "cd", ru: "ДР Конго", en: "DR Congo" },
  { code: "cr", ru: "Коста-Рика", en: "Costa Rica" },
  { code: "ci", ru: "Кот-д’Ивуар", en: "Côte d’Ivoire" },
  { code: "hr", ru: "Хорватия", en: "Croatia" },
  { code: "cu", ru: "Куба", en: "Cuba" },
  { code: "cy", ru: "Кипр", en: "Cyprus" },
  { code: "cz", ru: "Чехия", en: "Czechia" },
  { code: "dk", ru: "Дания", en: "Denmark" },
  { code: "dj", ru: "Джибути", en: "Djibouti" },
  { code: "dm", ru: "Доминика", en: "Dominica" },
  { code: "do", ru: "Доминиканская Республика", en: "Dominican Republic" },
  { code: "ec", ru: "Эквадор", en: "Ecuador" },
  { code: "eg", ru: "Египет", en: "Egypt" },
  { code: "sv", ru: "Сальвадор", en: "El Salvador" },
  { code: "gq", ru: "Экваториальная Гвинея", en: "Equatorial Guinea" },
  { code: "er", ru: "Эритрея", en: "Eritrea" },
  { code: "ee", ru: "Эстония", en: "Estonia" },
  { code: "sz", ru: "Эсватини", en: "Eswatini" },
  { code: "et", ru: "Эфиопия", en: "Ethiopia" },
  { code: "fj", ru: "Фиджи", en: "Fiji" },
  { code: "fi", ru: "Финляндия", en: "Finland" },
  { code: "fr", ru: "Франция", en: "France" },
  { code: "ga", ru: "Габон", en: "Gabon" },
  { code: "gm", ru: "Гамбия", en: "Gambia" },
  { code: "ge", ru: "Грузия", en: "Georgia" },
  { code: "de", ru: "Германия", en: "Germany" },
  { code: "gh", ru: "Гана", en: "Ghana" },
  { code: "gr", ru: "Греция", en: "Greece" },
  { code: "gd", ru: "Гренада", en: "Grenada" },
  { code: "gt", ru: "Гватемала", en: "Guatemala" },
  { code: "gn", ru: "Гвинея", en: "Guinea" },
  { code: "gw", ru: "Гвинея-Бисау", en: "Guinea-Bissau" },
  { code: "gy", ru: "Гайана", en: "Guyana" },
  { code: "ht", ru: "Гаити", en: "Haiti" },
  { code: "hn", ru: "Гондурас", en: "Honduras" },
  { code: "hu", ru: "Венгрия", en: "Hungary" },
  { code: "is", ru: "Исландия", en: "Iceland" },
  { code: "in", ru: "Индия", en: "India" },
  { code: "id", ru: "Индонезия", en: "Indonesia" },
  { code: "ir", ru: "Иран", en: "Iran" },
  { code: "iq", ru: "Ирак", en: "Iraq" },
  { code: "ie", ru: "Ирландия", en: "Ireland" },
  { code: "il", ru: "Израиль", en: "Israel" },
  { code: "it", ru: "Италия", en: "Italy" },
  { code: "jm", ru: "Ямайка", en: "Jamaica" },
  { code: "jp", ru: "Япония", en: "Japan" },
  { code: "jo", ru: "Иордания", en: "Jordan" },
  { code: "kz", ru: "Казахстан", en: "Kazakhstan" },
  { code: "ke", ru: "Кения", en: "Kenya" },
  { code: "ki", ru: "Кирибати", en: "Kiribati" },
  { code: "kw", ru: "Кувейт", en: "Kuwait" },
  { code: "kg", ru: "Кыргызстан", en: "Kyrgyzstan" },
  { code: "la", ru: "Лаос", en: "Laos" },
  { code: "lv", ru: "Латвия", en: "Latvia" },
  { code: "lb", ru: "Ливан", en: "Lebanon" },
  { code: "ls", ru: "Лесото", en: "Lesotho" },
  { code: "lr", ru: "Либерия", en: "Liberia" },
  { code: "ly", ru: "Ливия", en: "Libya" },
  { code: "li", ru: "Лихтенштейн", en: "Liechtenstein" },
  { code: "lt", ru: "Литва", en: "Lithuania" },
  { code: "lu", ru: "Люксембург", en: "Luxembourg" },
  { code: "mg", ru: "Мадагаскар", en: "Madagascar" },
  { code: "mw", ru: "Малави", en: "Malawi" },
  { code: "my", ru: "Малайзия", en: "Malaysia" },
  { code: "mv", ru: "Мальдивы", en: "Maldives" },
  { code: "ml", ru: "Мали", en: "Mali" },
  { code: "mt", ru: "Мальта", en: "Malta" },
  { code: "mh", ru: "Маршалловы Острова", en: "Marshall Islands" },
  { code: "mr", ru: "Мавритания", en: "Mauritania" },
  { code: "mu", ru: "Маврикий", en: "Mauritius" },
  { code: "mx", ru: "Мексика", en: "Mexico" },
  { code: "fm", ru: "Микронезия", en: "Micronesia" },
  { code: "md", ru: "Молдова", en: "Moldova" },
  { code: "mc", ru: "Монако", en: "Monaco" },
  { code: "mn", ru: "Монголия", en: "Mongolia" },
  { code: "me", ru: "Черногория", en: "Montenegro" },
  { code: "ma", ru: "Марокко", en: "Morocco" },
  { code: "mz", ru: "Мозамбик", en: "Mozambique" },
  { code: "mm", ru: "Мьянма", en: "Myanmar" },
  { code: "na", ru: "Намибия", en: "Namibia" },
  { code: "nr", ru: "Науру", en: "Nauru" },
  { code: "np", ru: "Непал", en: "Nepal" },
  { code: "nl", ru: "Нидерланды", en: "Netherlands" },
  { code: "nz", ru: "Новая Зеландия", en: "New Zealand" },
  { code: "ni", ru: "Никарагуа", en: "Nicaragua" },
  { code: "ne", ru: "Нигер", en: "Niger" },
  { code: "ng", ru: "Нигерия", en: "Nigeria" },
  { code: "kp", ru: "КНДР", en: "North Korea" },
  { code: "mk", ru: "Северная Македония", en: "North Macedonia" },
  { code: "no", ru: "Норвегия", en: "Norway" },
  { code: "om", ru: "Оман", en: "Oman" },
  { code: "pk", ru: "Пакистан", en: "Pakistan" },
  { code: "pw", ru: "Палау", en: "Palau" },
  { code: "pa", ru: "Панама", en: "Panama" },
  { code: "pg", ru: "Папуа — Новая Гвинея", en: "Papua New Guinea" },
  { code: "py", ru: "Парагвай", en: "Paraguay" },
  { code: "pe", ru: "Перу", en: "Peru" },
  { code: "ph", ru: "Филиппины", en: "Philippines" },
  { code: "pl", ru: "Польша", en: "Poland" },
  { code: "pt", ru: "Португалия", en: "Portugal" },
  { code: "qa", ru: "Катар", en: "Qatar" },
  { code: "ro", ru: "Румыния", en: "Romania" },
  { code: "ru", ru: "Россия", en: "Russia" },
  { code: "rw", ru: "Руанда", en: "Rwanda" },
  { code: "kn", ru: "Сент-Китс и Невис", en: "Saint Kitts and Nevis" },
  { code: "lc", ru: "Сент-Люсия", en: "Saint Lucia" },
  { code: "vc", ru: "Сент-Винсент и Гренадины", en: "Saint Vincent and the Grenadines" },
  { code: "ws", ru: "Самоа", en: "Samoa" },
  { code: "sm", ru: "Сан-Марино", en: "San Marino" },
  { code: "st", ru: "Сан-Томе и Принсипи", en: "Sao Tome and Principe" },
  { code: "sa", ru: "Саудовская Аравия", en: "Saudi Arabia" },
  { code: "sn", ru: "Сенегал", en: "Senegal" },
  { code: "rs", ru: "Сербия", en: "Serbia" },
  { code: "sc", ru: "Сейшелы", en: "Seychelles" },
  { code: "sl", ru: "Сьерра-Леоне", en: "Sierra Leone" },
  { code: "sg", ru: "Сингапур", en: "Singapore" },
  { code: "sk", ru: "Словакия", en: "Slovakia" },
  { code: "si", ru: "Словения", en: "Slovenia" },
  { code: "sb", ru: "Соломоновы Острова", en: "Solomon Islands" },
  { code: "so", ru: "Сомали", en: "Somalia" },
  { code: "za", ru: "ЮАР", en: "South Africa" },
  { code: "kr", ru: "Южная Корея", en: "South Korea" },
  { code: "ss", ru: "Южный Судан", en: "South Sudan" },
  { code: "es", ru: "Испания", en: "Spain" },
  { code: "lk", ru: "Шри-Ланка", en: "Sri Lanka" },
  { code: "sd", ru: "Судан", en: "Sudan" },
  { code: "sr", ru: "Суринам", en: "Suriname" },
  { code: "se", ru: "Швеция", en: "Sweden" },
  { code: "ch", ru: "Швейцария", en: "Switzerland" },
  { code: "sy", ru: "Сирия", en: "Syria" },
  { code: "tj", ru: "Таджикистан", en: "Tajikistan" },
  { code: "tz", ru: "Танзания", en: "Tanzania" },
  { code: "th", ru: "Таиланд", en: "Thailand" },
  { code: "tl", ru: "Тимор-Лешти", en: "Timor-Leste" },
  { code: "tg", ru: "Того", en: "Togo" },
  { code: "to", ru: "Тонга", en: "Tonga" },
  { code: "tt", ru: "Тринидад и Тобаго", en: "Trinidad and Tobago" },
  { code: "tn", ru: "Тунис", en: "Tunisia" },
  { code: "tr", ru: "Турция", en: "Türkiye" },
  { code: "tm", ru: "Туркменистан", en: "Turkmenistan" },
  { code: "tv", ru: "Тувалу", en: "Tuvalu" },
  { code: "ug", ru: "Уганда", en: "Uganda" },
  { code: "ua", ru: "Украина", en: "Ukraine" },
  { code: "ae", ru: "ОАЭ", en: "United Arab Emirates" },
  { code: "gb", ru: "Великобритания", en: "United Kingdom" },
  { code: "us", ru: "США", en: "United States" },
  { code: "uy", ru: "Уругвай", en: "Uruguay" },
  { code: "uz", ru: "Узбекистан", en: "Uzbekistan" },
  { code: "vu", ru: "Вануату", en: "Vanuatu" },
  { code: "va", ru: "Ватикан", en: "Vatican City" },
  { code: "ve", ru: "Венесуэла", en: "Venezuela" },
  { code: "vn", ru: "Вьетнам", en: "Vietnam" },
  { code: "ye", ru: "Йемен", en: "Yemen" },
  { code: "zm", ru: "Замбия", en: "Zambia" },
  { code: "zw", ru: "Зимбабве", en: "Zimbabwe" },
];


export function getStreamCountryName(code: StreamCountryCode, language?: string | null): string {
  const normalized = String(language || "en").toLowerCase();
  const country = STREAM_ALL_COUNTRIES.find((item) => item.code === code) ?? STREAM_ALL_COUNTRIES[0];

  if (code === "all") {
    const allLabels: Record<string, string> = {
      ru: "Все страны",
      en: "All countries",
      uz: "Barcha davlatlar",
      zh: "全部国家",
      kk: "Барлық елдер",
      ky: "Бардык өлкөлөр",
      tg: "Ҳама кишварҳо",
      tk: "Ähli ýurtlar",
      az: "Bütün ölkələr",
      tr: "Tüm ülkeler",
      ar: "كل الدول",
      fa: "همه کشورها",
      hi: "सभी देश",
      ur: "تمام ممالک",
      ko: "모든 국가",
      ja: "すべての国",
      de: "Alle Länder",
      fr: "Tous les pays",
      es: "Todos los países",
      it: "Tutti i paesi",
      pt: "Todos os países",
      id: "Semua negara",
      ms: "Semua negara",
      th: "ทุกประเทศ",
      vi: "Tất cả quốc gia",
    };
    const short = normalized.split("-")[0];
    return allLabels[short] ?? allLabels.en;
  }

  return normalized.startsWith("ru") ? country.ru : country.en;
}

export function searchStreamCountries(query: string, language?: string | null): StreamCountry[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return STREAM_ALL_COUNTRIES;
  return STREAM_ALL_COUNTRIES.filter((country) => {
    return country.ru.toLowerCase().includes(normalized) || country.en.toLowerCase().includes(normalized) || country.code.includes(normalized);
  });
}
