import type { SabiRelease244B } from './sabiRelease244b.types';

export const sabiRelease244B: SabiRelease244B = {
  version: 'SABI-RELEASE-244B-OFFICIAL-SITE-EMAIL-SMS-SERVER-AI-GOOGLE-CLOUD-DEPLOY-FINAL-OWNER-COMMAND-EXACT-PHRASE-FINAL-ACCEPTANCE-GATE-STATIC-CHECK',
  marker: 'SABI_RELEASE_244B_OFFICIAL_SITE_EMAIL_SMS_SERVER_AI_GOOGLE_CLOUD_DEPLOY_FINAL_OWNER_COMMAND_EXACT_PHRASE_FINAL_ACCEPTANCE_GATE_STATIC_CHECK_STILL_NO_LIVE_DEPLOY_NO_LIVE_SMS',
  strictPlanMode: true,
  noPivotWithoutOwnerApproval: true,
  maximumAcceleration: true,
  googleCloudDeployFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckOnly: true,
  ownerFinalCommandExactPhraseFinalAcceptanceGateStaticCheckReady: true,
  officialWebsiteMustWorkOnServer: true,
  officialDomainEmailMustWork: true,
  smsIsMandatoryForProgram: true,
  smsWithoutItProgramDoesNotWork: true,
  allCriticalLogicMustBeServerSide: true,
  cloudRunCustomDomainMappingFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckRequired: true,
  officialSiteHttpsFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckRequired: true,
  officialSiteHealthCheckFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckRequired: true,
  emailDnsAuthenticationFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckRequired: true,
  emailDnsAuthentication: {
    mx: true,
    spf: true,
    dkim: true,
    dmarc: true,
  },
  firebasePhoneAuthOrApprovedSmsProviderRequired: true,
  phoneNumberSignInMustBeEnabledBeforeLiveUse: true,
  liveSmsStillLockedUntilExactOwnerApproval: true,
  smsServerBoundaryRequired: true,
  serverSabiAiPersonalityTrainingMustFollowPlan: true,
  ownerSabiAiReportOnly: true,
  ownerFinalDecisionRequired: true,
  noSecretRevealToOwnerSabiAi: true,
  bankAccountOpeningUrgent: true,
  walletIntegrationBlockedUntilOfficialSiteEmailAndSmsReady: true,
  walletProviderIntegrationRequiresOwnerExactApproval: true,
  publicCommunicationChannel: 'Sabi Messenger',
  noTelegramMention: true,
  noDonationOrInvestmentRequest: true,
  sabiAllocatedCompanyFundsOnly: true,
  targetSubmissionDate: '2026-07-01',
  targetPublicLaunchDate: '2026-07-15',
  ownerFinalCommandExactPhraseFinalAcceptanceGateStaticCheckReferenceOnly: true,
  ownerExactPhraseFinalAcceptanceGateStaticCheckValue: 'I approve RELEASE-244B official site email SMS server AI Google Cloud deploy final Owner command exact phrase final acceptance gate static check planning only',
  liveDeployCommandExactPhraseFinalAcceptanceGateStaticCheckReferenceOnly: true,
  liveDeployCommandExactPhraseFinalAcceptanceGateStaticCheckReferenceOnlyValue: 'gcloud run deploy sabi-official-site --region <REGION> --source <SERVER_BUILD_CONTEXT>',
  acceptedNow: false,
  executableNow: false,
  noExecutionNow: true,
  exactPhraseCandidateRequiresSeparateExactPhraseBeforeAcceptance: true,
  exactPhraseFinalAcceptanceGateRequiresSeparateExactPhraseBeforeLiveDeploy: true,
  finalAcceptanceGateRequiresSeparateOwnerExactApprovalBeforeLiveDeploy: true,
  finalAcceptanceGateStaticCheckRequiresSeparateReportBeforeLiveDeploy: true,
  finalAcceptanceGateStillPlanningOnly: true,
  finalOwnerCommandWillRequireSeparateAcceptanceGateBeforeLiveDeploy: true,
  noFinalOwnerCommandAcceptedNow: true,
  noFinalOwnerCommandExecutionNow: true,
  noExactPhraseAcceptedNow: true,
  noExactPhraseExecutionNow: true,
  noFinalAcceptanceGateAcceptedNow: true,
  noFinalAcceptanceGateExecutionNow: true,
  noFinalAcceptanceGateStaticCheckAcceptedNow: true,
  noFinalAcceptanceGateStaticCheckExecutionNow: true,
  nextStep: '244C_official_site_email_sms_server_ai_google_cloud_deploy_final_owner_command_exact_phrase_final_acceptance_gate_static_check_report_still_no_live_deploy_no_live_sms',
  readiness: {
    officialSiteGoogleCloudDeployFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckReadiness: 100,
    officialDomainEmailGoogleCloudFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckReadiness: 100,
    smsGoogleCloudServerBoundaryFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckReadiness: 100,
    serverSabiAiGoogleCloudPersonalityFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckReadiness: 100,
    bankWalletGoogleCloudDependencyFinalOwnerCommandExactPhraseFinalAcceptanceGateStaticCheckReadiness: 100,
    previous244AReadiness: 100,
    googleCloudDeployExecutedNow: 0,
    ownerFinalCommandAcceptedNow: 0,
    finalOwnerCommandExecutableNow: 0,
    exactPhraseAcceptedNow: 0,
    exactPhraseExecutableNow: 0,
    finalAcceptanceGateAcceptedNow: 0,
    finalAcceptanceGateExecutableNow: 0,
    finalAcceptanceGateStaticCheckAcceptedNow: 0,
    finalAcceptanceGateStaticCheckExecutableNow: 0,
    cloudRunServiceCreatedNow: 0,
    liveDomainDnsChangedNow: 0,
    liveEmailDnsChangedNow: 0,
    liveSmsSentNow: 0,
    walletPaymentPayoutNow: 0,
    realProductionLaunchNow: 0,
  },
  safety: {
    noLiveGoogleCloudDeployNow: true,
    noCloudRunServiceCreateNow: true,
    noDomainDnsMutationNow: true,
    noLiveEmailDnsMutationNow: true,
    noLiveSmsSendNow: true,
    noFirebaseApiCallNow: true,
    noSmsProviderCallNow: true,
    noWalletPaymentPayoutNow: true,
    noSecretInSourceChatAdminMobile: true,
    noPlainSecretInReport: true,
    noEnvReadWriteNow: true,
    noSecretManagerReadWriteNow: true,
    noDbMutationNow: true,
    noRuntimeMountNow: true,
    noPublicLaunchClaimNow: true,
    ownerExactApprovalRequiredBeforeLiveAction: true,
    noOwnerFinalCommandAcceptedNow: true,
    noFinalOwnerCommandExecutionNow: true,
    noExactPhraseAcceptedNow: true,
    noExactPhraseExecutionNow: true,
    noFinalAcceptanceGateAcceptedNow: true,
    noFinalAcceptanceGateExecutionNow: true,
    noFinalAcceptanceGateStaticCheckAcceptedNow: true,
    noFinalAcceptanceGateStaticCheckExecutionNow: true,
  },
};

export default sabiRelease244B;
