import type {
  TaxiAdminMakerCheckerRule001X,
  TaxiAdminOperationalQueue001X,
  TaxiAdminRuntimePanel001X,
  TaxiAdminWorkflowStep001X,
} from './types';

export const TAXI_ADMIN_RUNTIME_READINESS_VERSION_001X = 'TAXI-BACKEND-FOUNDATION-001X-MEGA' as const;

export const TAXI_ADMIN_RUNTIME_PANELS_001X: readonly TaxiAdminRuntimePanel001X[] = [
  {
    id: 'taxi-admin-schema-migration-control-001x',
    domain: 'schema_migration_control',
    title: 'Taxi schema migration control',
    purpose: 'Reviews 001W schema candidates before any Prisma schema write, generate, migration, or DB access.',
    permissions: ['taxi:admin:read', 'taxi:admin:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'schema_approval_required', 'fake_success_blocked'],
    actions: [
      action('schema-preview', 'preview_only', 'Preview schema candidate pack', 'taxi:admin:read', 'schema_approval_required'),
      action('schema-approve-request', 'approve', 'Request exact owner schema approval', 'taxi:admin:write', 'maker_checker_required'),
      action('schema-lock', 'lock', 'Keep migration locked until exact approval', 'taxi:admin:write', 'schema_approval_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-driver-onboarding-review-001x',
    domain: 'driver_onboarding_review',
    title: 'Driver onboarding review',
    purpose: 'Controls driver profile, KYC/KYB, license, region, park membership, and compliance readiness before dispatch eligibility.',
    permissions: ['taxi:admin:read', 'taxi:driver-review:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'driver_kyc_required', 'country_city_scope_required', 'fake_success_blocked'],
    actions: [
      action('driver-review-open', 'review', 'Open driver application review', 'taxi:admin:read', 'driver_kyc_required'),
      action('driver-request-changes', 'request_changes', 'Request driver document changes', 'taxi:driver-review:write', 'audit_reason_required'),
      action('driver-approve-dry-run', 'approve', 'Approve driver eligibility dry-run', 'taxi:driver-review:write', 'maker_checker_required'),
      action('driver-reject-dry-run', 'reject', 'Reject driver eligibility dry-run', 'taxi:driver-review:write', 'audit_reason_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-vehicle-park-review-001x',
    domain: 'vehicle_park_review',
    title: 'Vehicle and driver park review',
    purpose: 'Reviews vehicle documents, class, insurance, inspection, park assignment, and city permissions.',
    permissions: ['taxi:admin:read', 'taxi:vehicle-review:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'vehicle_documents_required', 'country_city_scope_required', 'fake_success_blocked'],
    actions: [
      action('vehicle-review-open', 'review', 'Open vehicle review', 'taxi:admin:read', 'vehicle_documents_required'),
      action('vehicle-approve-dry-run', 'approve', 'Approve vehicle dry-run', 'taxi:vehicle-review:write', 'maker_checker_required'),
      action('park-assignment-lock', 'lock', 'Lock park assignment until documents pass', 'taxi:vehicle-review:write', 'vehicle_documents_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-tariff-region-matrix-001x',
    domain: 'tariff_region_matrix',
    title: 'Tariff, region, and commission matrix',
    purpose: 'Controls city zones, tariffs, surge limits, cancellation fees, admin-configured commission, and quote limits.',
    permissions: ['taxi:admin:read', 'taxi:tariff-region:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'country_city_scope_required', 'tariff_region_config_required', 'fake_success_blocked'],
    actions: [
      action('tariff-matrix-preview', 'preview_only', 'Preview tariff matrix', 'taxi:admin:read', 'tariff_region_config_required'),
      action('tariff-update-dry-run', 'approve', 'Approve tariff update dry-run', 'taxi:tariff-region:write', 'maker_checker_required'),
      action('commission-bps-preview', 'preview_only', 'Preview admin commission basis points', 'taxi:tariff-region:write', 'audit_reason_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-quote-dispatch-monitor-001x',
    domain: 'quote_dispatch_monitor',
    title: 'Quote and dispatch monitor',
    purpose: 'Prepares Admin visibility for rider request, ETA, quote, matching, dispatch offer, and no-driver fallback without live dispatch.',
    permissions: ['taxi:admin:read', 'taxi:dispatch:read'],
    gates: ['admin_auth_required', 'country_city_scope_required', 'provider_reference_labels_required', 'tariff_region_config_required', 'fake_success_blocked'],
    actions: [
      action('quote-monitor-preview', 'preview_only', 'Preview quote readiness', 'taxi:dispatch:read', 'provider_reference_labels_required'),
      action('dispatch-fallback-preview', 'preview_only', 'Preview no-driver fallback', 'taxi:dispatch:read', 'fake_success_blocked'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-trip-lifecycle-monitor-001x',
    domain: 'trip_lifecycle_monitor',
    title: 'Trip lifecycle monitor',
    purpose: 'Prepares Admin read model for request accepted, arrival, pickup, active trip, completion, cancellation, and safety interrupt.',
    permissions: ['taxi:admin:read', 'taxi:trip-monitor:read'],
    gates: ['admin_auth_required', 'country_city_scope_required', 'audit_reason_required', 'fake_success_blocked'],
    actions: [
      action('trip-timeline-preview', 'preview_only', 'Preview trip timeline state machine', 'taxi:trip-monitor:read', 'audit_reason_required'),
      action('trip-lock-preview', 'lock', 'Preview trip lock behavior', 'taxi:admin:read', 'fake_success_blocked'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-payment-settlement-review-001x',
    domain: 'payment_hold_settlement_review',
    title: 'Payment hold, refund, and driver settlement review',
    purpose: 'Controls payment hold readiness, refund review, driver settlement preview, maker-checker approvals, and payout lock.',
    permissions: ['taxi:admin:read', 'taxi:settlement-review:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'wallet_boundary_approval_required', 'refund_settlement_review_required', 'fake_success_blocked'],
    actions: [
      action('payment-hold-preview', 'preview_only', 'Preview payment hold readiness', 'taxi:settlement-review:write', 'wallet_boundary_approval_required'),
      action('refund-review-dry-run', 'review', 'Review refund dry-run', 'taxi:settlement-review:write', 'refund_settlement_review_required'),
      action('driver-settlement-approve-dry-run', 'approve', 'Approve driver settlement dry-run', 'taxi:settlement-review:write', 'maker_checker_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-support-dispute-safety-review-001x',
    domain: 'support_dispute_safety_review',
    title: 'Support, dispute, SOS, and safety review',
    purpose: 'Controls support case routing, dispute evidence, SOS escalation, rider/driver safety lock, and abuse prevention readiness.',
    permissions: ['taxi:admin:read', 'taxi:support-safety:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'support_evidence_required', 'support_safety_policy_approved', 'fake_success_blocked'],
    actions: [
      action('support-case-review', 'review', 'Review support case', 'taxi:support-safety:write', 'support_evidence_required'),
      action('safety-lock-dry-run', 'lock', 'Safety lock dry-run', 'taxi:support-safety:write', 'maker_checker_required'),
      action('safety-unlock-review', 'unlock_after_review', 'Unlock after safety review dry-run', 'taxi:support-safety:write', 'support_evidence_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-provider-readiness-control-001x',
    domain: 'provider_readiness_control',
    title: 'Provider readiness control',
    purpose: 'Controls maps, route, ETA, dispatch, notification, fraud, wallet and payment provider labels without reading env or calling providers.',
    permissions: ['taxi:admin:read', 'taxi:provider-readiness:write'],
    gates: ['admin_auth_required', 'maker_checker_required', 'audit_reason_required', 'provider_reference_labels_required', 'wallet_boundary_approval_required', 'fake_success_blocked'],
    actions: [
      action('provider-label-preview', 'preview_only', 'Preview provider reference labels only', 'taxi:provider-readiness:write', 'provider_reference_labels_required'),
      action('provider-activation-lock', 'lock', 'Keep provider runtime locked', 'taxi:provider-readiness:write', 'fake_success_blocked'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
  {
    id: 'taxi-admin-audit-compliance-export-001x',
    domain: 'audit_compliance_export',
    title: 'Audit and compliance export',
    purpose: 'Prepares Admin audit visibility, compliance export contract, regulator evidence bundle, and change-history review.',
    permissions: ['taxi:admin:read', 'taxi:audit:read'],
    gates: ['admin_auth_required', 'audit_reason_required', 'country_city_scope_required', 'fake_success_blocked'],
    actions: [
      action('audit-export-preview', 'export_readiness_report', 'Export readiness report preview', 'taxi:audit:read', 'audit_reason_required'),
      action('compliance-bundle-preview', 'preview_only', 'Preview compliance bundle', 'taxi:audit:read', 'country_city_scope_required'),
    ],
    readsRuntimeNow: false,
    writesRuntimeNow: false,
    routeMountedNow: false,
    adminUiRuntimeMountedNow: false,
    dbReadNow: false,
    dbWriteNow: false,
    walletMutationNow: false,
    paymentNow: false,
    payoutNow: false,
    providerDispatchNow: false,
    fakeSuccessBlocked: true,
  },
];

export const TAXI_ADMIN_WORKFLOW_STEPS_001X: readonly TaxiAdminWorkflowStep001X[] = [
  workflow('schema-001', 'taxi-admin-schema-migration-control-001x', 1, 'Review 001W schema candidate report', 'schema_approval_required'),
  workflow('schema-002', 'taxi-admin-schema-migration-control-001x', 2, 'Collect exact owner approval for migration', 'maker_checker_required'),
  workflow('driver-001', 'taxi-admin-driver-onboarding-review-001x', 1, 'Check driver identity and documents', 'driver_kyc_required'),
  workflow('driver-002', 'taxi-admin-driver-onboarding-review-001x', 2, 'Apply maker-checker approval lock', 'maker_checker_required'),
  workflow('vehicle-001', 'taxi-admin-vehicle-park-review-001x', 1, 'Review vehicle documents and park assignment', 'vehicle_documents_required'),
  workflow('tariff-001', 'taxi-admin-tariff-region-matrix-001x', 1, 'Review city tariff matrix and commission basis points', 'tariff_region_config_required'),
  workflow('provider-001', 'taxi-admin-provider-readiness-control-001x', 1, 'Verify provider reference labels only', 'provider_reference_labels_required'),
  workflow('dispatch-001', 'taxi-admin-quote-dispatch-monitor-001x', 1, 'Preview quote/dispatch readiness without dispatch', 'provider_reference_labels_required'),
  workflow('trip-001', 'taxi-admin-trip-lifecycle-monitor-001x', 1, 'Preview trip state machine locks', 'audit_reason_required'),
  workflow('settlement-001', 'taxi-admin-payment-settlement-review-001x', 1, 'Review hold/refund/driver settlement dry-run', 'refund_settlement_review_required'),
  workflow('support-001', 'taxi-admin-support-dispute-safety-review-001x', 1, 'Review support evidence and SOS policy', 'support_evidence_required'),
  workflow('audit-001', 'taxi-admin-audit-compliance-export-001x', 1, 'Preview audit export scope', 'audit_reason_required'),
];

export const TAXI_ADMIN_OPERATIONAL_QUEUES_001X: readonly TaxiAdminOperationalQueue001X[] = [
  queue('schema-approval-queue', 'schema_migration_control', 'TaxiProviderReadinessSnapshot', ['missing_schema_approval', 'rollback_plan_missing'], 720),
  queue('driver-review-queue', 'driver_onboarding_review', 'TaxiDriverApplication', ['kyc_pending', 'license_expiring', 'region_missing'], 240),
  queue('vehicle-review-queue', 'vehicle_park_review', 'TaxiVehicle', ['insurance_missing', 'inspection_expired', 'park_assignment_missing'], 240),
  queue('tariff-region-queue', 'tariff_region_matrix', 'TaxiTariffRegion', ['inactive_region', 'commission_bps_missing', 'surge_limit_missing'], 360),
  queue('quote-dispatch-queue', 'quote_dispatch_monitor', 'TaxiRiderRequest', ['provider_not_configured', 'no_driver_fallback', 'eta_unavailable'], 60),
  queue('trip-monitor-queue', 'trip_lifecycle_monitor', 'TaxiTrip', ['stuck_status', 'pickup_overdue', 'completion_review_required'], 30),
  queue('settlement-review-queue', 'payment_hold_settlement_review', 'TaxiDriverSettlement', ['refund_requested', 'driver_adjustment', 'payment_hold_review'], 180),
  queue('support-safety-queue', 'support_dispute_safety_review', 'TaxiSupportCase', ['sos_event', 'evidence_required', 'abuse_signal'], 15),
  queue('provider-readiness-queue', 'provider_readiness_control', 'TaxiProviderReadinessSnapshot', ['maps_missing', 'dispatch_missing', 'wallet_missing'], 360),
  queue('audit-export-queue', 'audit_compliance_export', 'TaxiAuditLog', ['export_requested', 'regulator_bundle', 'change_history_review'], 1440),
];

export const TAXI_ADMIN_MAKER_CHECKER_RULES_001X: readonly TaxiAdminMakerCheckerRule001X[] = [
  makerChecker('driver-approval-maker-checker', 'driver-', 'taxi:driver-review:write', 'taxi:admin:write'),
  makerChecker('vehicle-approval-maker-checker', 'vehicle-', 'taxi:vehicle-review:write', 'taxi:admin:write'),
  makerChecker('tariff-update-maker-checker', 'tariff-', 'taxi:tariff-region:write', 'taxi:admin:write'),
  makerChecker('provider-readiness-maker-checker', 'provider-', 'taxi:provider-readiness:write', 'taxi:admin:write'),
  makerChecker('settlement-maker-checker', 'driver-settlement-', 'taxi:settlement-review:write', 'taxi:admin:write'),
  makerChecker('support-safety-maker-checker', 'safety-', 'taxi:support-safety:write', 'taxi:admin:write'),
];

function action(
  id: string,
  kind: TaxiAdminRuntimePanel001X['actions'][number]['kind'],
  label: string,
  permission: TaxiAdminRuntimePanel001X['actions'][number]['permission'],
  gate: TaxiAdminRuntimePanel001X['actions'][number]['gate'],
): TaxiAdminRuntimePanel001X['actions'][number] {
  return {
    id,
    kind,
    label,
    permission,
    gate,
    requiresAuditReason: true,
    requiresMakerChecker: true,
    exactOwnerApprovalRequiredForRuntime: true,
    dryRunOnlyNow: true,
    writesDbNow: false,
    callsProviderNow: false,
    mutatesWalletNow: false,
    paymentNow: false,
    payoutNow: false,
    fakeSuccessBlocked: true,
  };
}

function workflow(id: string, panelId: string, order: number, title: string, requiredGate: TaxiAdminWorkflowStep001X['requiredGate']): TaxiAdminWorkflowStep001X {
  return {
    id,
    panelId,
    order,
    title,
    requiredGate,
    blockingUntilPassed: true,
    ownerApprovalRequiredBeforeRuntime: true,
    backendRuntimeEnabledNow: false,
    dbMutationEnabledNow: false,
  };
}

function queue(
  id: string,
  domain: TaxiAdminOperationalQueue001X['domain'],
  sourceModelCandidate: string,
  prioritySignals: readonly string[],
  requiredSlaMinutes: number,
): TaxiAdminOperationalQueue001X {
  return {
    id,
    domain,
    sourceModelCandidate,
    prioritySignals,
    requiredSlaMinutes,
    readsDbNow: false,
    writesDbNow: false,
    mountedNow: false,
    fakeQueueSuccessBlocked: true,
  };
}

function makerChecker(
  id: string,
  actionIdPrefix: string,
  firstActorPermission: TaxiAdminMakerCheckerRule001X['firstActorPermission'],
  secondActorPermission: TaxiAdminMakerCheckerRule001X['secondActorPermission'],
): TaxiAdminMakerCheckerRule001X {
  return {
    id,
    actionIdPrefix,
    firstActorPermission,
    secondActorPermission,
    sameActorAllowed: false,
    moneyMovementBlockedUntilSecondApproval: true,
    runtimeApprovalEnabledNow: false,
    fakeApprovalBlocked: true,
  };
}
