// Auto-generated by TAXI-PROVIDER-BINDING-025G.
// Safe-disabled provider binding labels registry only.
// No raw secrets, no env reads, no provider calls, no Wallet mutation, no DB writes, no live binding, no money movement.
import { taxiProviderBindingSafeDisabledRoutes025G } from './registry';
import type { TaxiProviderBindingSafeDisabledRegistryReadiness025G } from './types';

export const taxiProviderBindingSafeDisabledRegistryReadiness025G: TaxiProviderBindingSafeDisabledRegistryReadiness025G = Object.freeze({
  version: 'TAXI-PROVIDER-BINDING-SAFE-DISABLED-REGISTRY-025G',
  registryMaterialized: true,
  registrySafeDisabled: true,
  liveProviderBindingEnabled: false,
  providerCallEnabled: false,
  walletMutationEnabled: false,
  dbWriteEnabled: false,
  moneyMovementEnabled: false,
  envReadRequired: false,
  rawSecretValuesStored: false,
  rawSecretValuesPrinted: false,
  candidateValuesPrinted: false,
  providerReferenceLabelsOnly: true,
  countryRouteCount: taxiProviderBindingSafeDisabledRoutes025G.length,
  branchlessNoPhysicalBranchModel: true,
  perCountryCurrencyRequired: true,
  driverSelfTopupOnly: false,
  driverBalanceTopupOnlyViaApprovedAgentNow: true,
  taxiAgentApplicationRequiredBeforeTopup: true,
  currentFxRateRequiredWhenConversionNeeded: true,
  fxRateSnapshotRequired: true,
  sabiAiProviderCoverageMonitoringRequired: true,
  sabiAiFxRateFreshnessMonitoringRequired: true,
  sabiAiReportOnlyNoMoneyMutation: true,
  separateLiveEnablementApprovalRequired: true,
  routes: taxiProviderBindingSafeDisabledRoutes025G,
});

export function getTaxiProviderBindingSafeDisabledRegistryReadiness025G(): TaxiProviderBindingSafeDisabledRegistryReadiness025G {
  return taxiProviderBindingSafeDisabledRegistryReadiness025G;
}
