// Auto-generated by TAXI-PROVIDER-BINDING-025G.
// Safe-disabled provider binding labels registry only.
// No raw secrets, no env reads, no provider calls, no Wallet mutation, no DB writes, no live binding, no money movement.
export type TaxiProviderBindingRegistryCountryCode025G = 'UZ' | 'KZ' | 'KG' | 'TJ' | 'RU' | 'AZ' | 'TR' | 'AE';

export type TaxiProviderBindingRegistryCurrency025G = 'UZS' | 'KZT' | 'KGS' | 'TJS' | 'RUB' | 'AZN' | 'TRY' | 'AED';

export type TaxiProviderBindingSafeDisabledRegistryRoute025G = Readonly<{
  countryCode: TaxiProviderBindingRegistryCountryCode025G;
  settlementCurrency: TaxiProviderBindingRegistryCurrency025G;
  acceptPaymentProviderLabel: string;
  driverTopupCardProviderLabel: string;
  driverTopupWalletProviderLabel: string;
  fxRateProviderLabel: string;
  physicalBranchRequired: false;
  branchlessProviderCoverageModel: true;
  registrySafeDisabled: true;
  liveProviderBindingEnabled: false;
  providerCallEnabled: false;
  walletMutationEnabled: false;
  moneyMovementEnabled: false;
  separateLiveEnablementApprovalRequired: true;
}>;

export type TaxiProviderBindingSafeDisabledRegistryReadiness025G = Readonly<{
  version: 'TAXI-PROVIDER-BINDING-SAFE-DISABLED-REGISTRY-025G';
  registryMaterialized: true;
  registrySafeDisabled: true;
  liveProviderBindingEnabled: false;
  providerCallEnabled: false;
  walletMutationEnabled: false;
  dbWriteEnabled: false;
  moneyMovementEnabled: false;
  envReadRequired: false;
  rawSecretValuesStored: false;
  rawSecretValuesPrinted: false;
  candidateValuesPrinted: false;
  providerReferenceLabelsOnly: true;
  countryRouteCount: number;
  branchlessNoPhysicalBranchModel: true;
  perCountryCurrencyRequired: true;
  driverSelfTopupOnly: false;
  driverBalanceTopupOnlyViaApprovedAgentNow: true;
  taxiAgentApplicationRequiredBeforeTopup: true;
  currentFxRateRequiredWhenConversionNeeded: true;
  fxRateSnapshotRequired: true;
  sabiAiProviderCoverageMonitoringRequired: true;
  sabiAiFxRateFreshnessMonitoringRequired: true;
  sabiAiReportOnlyNoMoneyMutation: true;
  separateLiveEnablementApprovalRequired: true;
  routes: readonly TaxiProviderBindingSafeDisabledRegistryRoute025G[];
}>;
