import type { SabiRelease243FContract } from './sabiRelease243f.types';

export const sabiRelease243FContract: SabiRelease243FContract = {
  version: 'SABI-RELEASE-243F-OFFICIAL-SITE-EMAIL-SMS-SERVER-AI-GOOGLE-CLOUD-DEPLOY-EXACT-OWNER-APPROVAL-GATE-STATIC-CHECK',
  marker: 'SABI_RELEASE_243F_OFFICIAL_SITE_EMAIL_SMS_SERVER_AI_GOOGLE_CLOUD_DEPLOY_EXACT_OWNER_APPROVAL_GATE_STATIC_CHECK_STILL_NO_LIVE_DEPLOY_NO_LIVE_SMS',
  approvalFlagRequired: '--i-approve-release-243f-official-site-email-sms-server-ai-google-cloud-deploy-exact-owner-approval-gate-static-check',
  strictPlanMode: true,
  noPivotWithoutOwnerApproval: true,
  maximumAcceleration: true,
  googleCloudDeployExactOwnerApprovalGateStaticCheckOnly: true,
  ownerExactApprovalGateStaticCheckReady: true,
  officialWebsiteMustWorkOnServer: true,
  officialDomainEmailMustWork: true,
  smsIsMandatoryForProgram: true,
  smsWithoutItProgramDoesNotWork: true,
  allCriticalLogicMustBeServerSide: true,
  cloudRunCustomDomainMappingOwnerApprovalStaticCheckRequired: true,
  officialSiteHttpsOwnerApprovalStaticCheckRequired: true,
  officialSiteHealthCheckOwnerApprovalStaticCheckRequired: true,
  emailDnsAuthenticationOwnerApprovalStaticCheckRequired: {
    mx: true,
    spf: true,
    dkim: true,
    dmarc: true,
  },
  firebasePhoneAuthOrApprovedSmsProviderRequired: true,
  phoneNumberSignInMustBeEnabledBeforeLiveUse: true,
  liveSmsStillLockedUntilExactOwnerApproval: true,
  smsServerBoundaryRequired: true,
  serverSabiAiPersonalityTrainingMustFollowPlan: true,
  ownerSabiAiReportOnly: true,
  ownerFinalDecisionRequired: true,
  noSecretRevealToOwnerSabiAi: true,
  bankAccountOpeningUrgent: true,
  walletIntegrationBlockedUntilOfficialSiteEmailAndSmsReady: true,
  walletProviderIntegrationRequiresOwnerExactApproval: true,
  publicCommunicationChannel: 'Sabi Messenger',
  noTelegramMention: true,
  noDonationOrInvestmentRequest: true,
  sabiAllocatedCompanyFundsOnly: true,
  targetSubmissionDate: '2026-07-01',
  targetPublicLaunchDate: '2026-07-15',
  ownerApprovalPhraseReferenceOnly:
    'I approve RELEASE-243F official site email SMS server AI Google Cloud deploy exact Owner approval gate static check planning only',
  liveDeployCommandReferenceOnly:
    'gcloud run deploy sabi-official-site --region <REGION> --source <SERVER_BUILD_CONTEXT>',
  acceptedNow: false,
  executableNow: false,
  noExecutionNow: true,
  readiness: {
    officialSiteGoogleCloudDeployApprovalGateStaticCheckReadiness: 100,
    officialDomainEmailGoogleCloudApprovalGateStaticCheckReadiness: 100,
    smsGoogleCloudServerBoundaryApprovalGateStaticCheckReadiness: 100,
    serverSabiAiGoogleCloudPersonalityApprovalGateStaticCheckReadiness: 100,
    bankWalletGoogleCloudDependencyApprovalGateStaticCheckReadiness: 100,
    previous243EReadiness: 100,
    googleCloudDeployExecutedNow: 0,
    cloudRunServiceCreatedNow: 0,
    liveDomainDnsChangedNow: 0,
    liveEmailDnsChangedNow: 0,
    liveSmsSentNow: 0,
    walletPaymentPayoutNow: 0,
    realProductionLaunchNow: 0,
  },
  safety: {
    noLiveGoogleCloudDeployNow: true,
    noCloudRunServiceCreateNow: true,
    noDomainDnsMutationNow: true,
    noLiveEmailDnsMutationNow: true,
    noLiveSmsSendNow: true,
    noFirebaseApiCallNow: true,
    noSmsProviderCallNow: true,
    noWalletPaymentPayoutNow: true,
    noSecretInSourceChatAdminMobile: true,
    noPlainSecretInReport: true,
    noEnvReadWriteNow: true,
    noSecretManagerReadWriteNow: true,
    noDbMutationNow: true,
    noRuntimeMountNow: true,
    noPublicLaunchClaimNow: true,
    ownerExactApprovalRequiredBeforeLiveAction: true,
  },
  nextStep:
    '243G_official_site_email_sms_server_ai_google_cloud_deploy_exact_owner_approval_gate_report_still_no_live_deploy_no_live_sms',
};

export const sabiRelease243FReadiness = sabiRelease243FContract.readiness;
export const sabiRelease243FSafety = sabiRelease243FContract.safety;
