import {
  getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationReadiness,
  getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationSnapshot,
} from "../kernel-diagnostics-backend-route-connection-source-only-post-write-verification";
import {
  STREAM_FOUNDATION_140C_KERNEL_DIAGNOSTICS_CONTROLLED_BACKEND_ENTRY_PATCH_PLANNING_VERSION,
  type StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningCheck,
  type StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningDecision,
  type StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningItem,
  type StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningSafety,
  type StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningSnapshot,
} from "./streamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningContracts";

const SAFETY: StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningSafety = {
  patchScope: "src/modules/stream/foundation/** only",
  planningSourceBuiltNow: true,
  streamIndexPatchIncludedNow: false,
  streamModuleIndexTouchedNow: false,
  backendEntryPatchIncludedNow: false,
  appServerPatchIncludedNow: false,
  appServerTouchedNow: false,
  routeMountAllowedNow: false,
  routeMountPerformedNow: false,
  protectedRouteRegisteredNow: false,
  expressRouterCreatedNow: false,
  expressRouterImportedNow: false,
  expressRouterBoundNow: false,
  runtimeHttpRequestPerformedNow: false,
  databaseReadAllowedNow: false,
  databaseWriteAllowedNow: false,
  providerCallAllowedNow: false,
  walletMutationAllowedNow: false,
  paymentAuthorizationAllowedNow: false,
  monthlyPayoutAllowedNow: false,
  moneyMovementAllowedNow: false,
  rawSecretsReturned: false,
  mobileProviderKeysAllowed: false,
  fakeSuccessAllowed: false,
};

function buildPlannedPatchItems(): readonly StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningItem[] {
  return [
    {
      target: "stream_module_index",
      plannedPath: "src/modules/stream/index.ts",
      operation: "plan_only_no_write",
      requiredBeforeRuntimeSmoke: true,
      plannedForFuturePatch: true,
      writtenNow: false,
      mountedNow: false,
      includesRuntimeExecutionNow: false,
      includesDatabaseExecutionNow: false,
      includesProviderCallNow: false,
      includesWalletMutationNow: false,
      safeCode: "140c_plan_stream_module_index_export_only",
      safeMessageKey: "stream.foundation.140c.plan.streamModuleIndex",
    },
    {
      target: "backend_app_route_registration",
      plannedPath: "src/app.ts",
      operation: "plan_only_no_write",
      requiredBeforeRuntimeSmoke: true,
      plannedForFuturePatch: true,
      writtenNow: false,
      mountedNow: false,
      includesRuntimeExecutionNow: false,
      includesDatabaseExecutionNow: false,
      includesProviderCallNow: false,
      includesWalletMutationNow: false,
      safeCode: "140c_plan_backend_app_route_registration",
      safeMessageKey: "stream.foundation.140c.plan.backendAppRouteRegistration",
    },
    {
      target: "backend_server_route_audit",
      plannedPath: "src/server.ts",
      operation: "plan_only_no_write",
      requiredBeforeRuntimeSmoke: false,
      plannedForFuturePatch: true,
      writtenNow: false,
      mountedNow: false,
      includesRuntimeExecutionNow: false,
      includesDatabaseExecutionNow: false,
      includesProviderCallNow: false,
      includesWalletMutationNow: false,
      safeCode: "140c_plan_backend_server_route_audit",
      safeMessageKey: "stream.foundation.140c.plan.backendServerRouteAudit",
    },
    {
      target: "protected_router_mount_validation",
      plannedPath: "backend protected admin route middleware chain",
      operation: "plan_only_no_write",
      requiredBeforeRuntimeSmoke: true,
      plannedForFuturePatch: true,
      writtenNow: false,
      mountedNow: false,
      includesRuntimeExecutionNow: false,
      includesDatabaseExecutionNow: false,
      includesProviderCallNow: false,
      includesWalletMutationNow: false,
      safeCode: "140c_plan_protected_router_mount_validation",
      safeMessageKey: "stream.foundation.140c.plan.protectedRouterMountValidation",
    },
    {
      target: "post_mount_runtime_http_smoke",
      plannedPath: "future production smoke after explicit mount approval",
      operation: "plan_only_no_write",
      requiredBeforeRuntimeSmoke: false,
      plannedForFuturePatch: true,
      writtenNow: false,
      mountedNow: false,
      includesRuntimeExecutionNow: false,
      includesDatabaseExecutionNow: false,
      includesProviderCallNow: false,
      includesWalletMutationNow: false,
      safeCode: "140c_plan_post_mount_runtime_http_smoke",
      safeMessageKey: "stream.foundation.140c.plan.postMountRuntimeHttpSmoke",
    },
  ] as const;
}

function buildChecks(plannedPatchItems: readonly StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningItem[]): readonly StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningCheck[] {
  const previous = getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationSnapshot();
  const previousReadiness = getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationReadiness();
  const previousReady = previous.status === "controlled_backend_route_connection_source_only_post_write_verification_ready" && previousReadiness.ready === true && previous.readyForControlledBackendEntryPatchPlanning === true;
  const plannedStreamIndex = plannedPatchItems.some((item) => item.target === "stream_module_index" && item.plannedPath === "src/modules/stream/index.ts" && item.writtenNow === false);
  const plannedBackendEntry = plannedPatchItems.some((item) => item.target === "backend_app_route_registration" && item.plannedPath === "src/app.ts" && item.writtenNow === false);
  const plannedMountValidation = plannedPatchItems.some((item) => item.target === "protected_router_mount_validation" && item.writtenNow === false && item.mountedNow === false);
  const plannedRuntimeSmoke = plannedPatchItems.some((item) => item.target === "post_mount_runtime_http_smoke" && item.includesRuntimeExecutionNow === false);
  const allPlanOnlySafe = plannedPatchItems.length === 5 && plannedPatchItems.every((item) => item.operation === "plan_only_no_write" && item.writtenNow === false && item.mountedNow === false && item.includesRuntimeExecutionNow === false && item.includesDatabaseExecutionNow === false && item.includesProviderCallNow === false && item.includesWalletMutationNow === false);

  return [
    {
      area: "previous_140b_verification",
      checkId: "140c_previous_140b_ready",
      passed: previousReady,
      blocking: !previousReady,
      expected: "140B post-write verification is ready for backend entry patch planning.",
      observed: `${previous.status}:${String(previousReadiness.ready)}:${String(previous.readyForControlledBackendEntryPatchPlanning)}`,
      remediation: "Complete 140B post-write verification before planning backend entry patch.",
      safeCode: "previous_140b_ready",
      safeMessageKey: "stream.foundation.140c.previous140bReady",
    },
    {
      area: "planned_stream_module_index_patch",
      checkId: "140c_stream_index_patch_planned_only",
      passed: plannedStreamIndex && SAFETY.streamIndexPatchIncludedNow === false && SAFETY.streamModuleIndexTouchedNow === false,
      blocking: !plannedStreamIndex || SAFETY.streamIndexPatchIncludedNow || SAFETY.streamModuleIndexTouchedNow,
      expected: "src/modules/stream/index.ts is identified for a future patch, not written now.",
      observed: `${String(plannedStreamIndex)}:${String(SAFETY.streamIndexPatchIncludedNow)}:${String(SAFETY.streamModuleIndexTouchedNow)}`,
      remediation: "Keep stream index as plan-only until explicit owner review.",
      safeCode: "stream_index_patch_planned_only",
      safeMessageKey: "stream.foundation.140c.streamIndexPatchPlannedOnly",
    },
    {
      area: "planned_backend_entry_patch",
      checkId: "140c_backend_entry_patch_planned_only",
      passed: plannedBackendEntry && SAFETY.backendEntryPatchIncludedNow === false && SAFETY.appServerPatchIncludedNow === false && SAFETY.appServerTouchedNow === false,
      blocking: !plannedBackendEntry || SAFETY.backendEntryPatchIncludedNow || SAFETY.appServerPatchIncludedNow || SAFETY.appServerTouchedNow,
      expected: "src/app.ts backend route registration is identified for future patch, not written now.",
      observed: `${String(plannedBackendEntry)}:${String(SAFETY.backendEntryPatchIncludedNow)}:${String(SAFETY.appServerPatchIncludedNow)}:${String(SAFETY.appServerTouchedNow)}`,
      remediation: "Do not patch app/server until explicit owner-approved backend entry stage.",
      safeCode: "backend_entry_patch_planned_only",
      safeMessageKey: "stream.foundation.140c.backendEntryPatchPlannedOnly",
    },
    {
      area: "planned_protected_router_mount",
      checkId: "140c_protected_router_mount_planned_only",
      passed: plannedMountValidation && SAFETY.protectedRouteRegisteredNow === false && SAFETY.expressRouterBoundNow === false,
      blocking: !plannedMountValidation || SAFETY.protectedRouteRegisteredNow || SAFETY.expressRouterBoundNow,
      expected: "Protected router mount validation is plan-only; no router is registered/bound now.",
      observed: `${String(plannedMountValidation)}:${String(SAFETY.protectedRouteRegisteredNow)}:${String(SAFETY.expressRouterBoundNow)}`,
      remediation: "Register protected router only in a controlled mount patch after owner approval.",
      safeCode: "protected_router_mount_planned_only",
      safeMessageKey: "stream.foundation.140c.protectedRouterMountPlannedOnly",
    },
    {
      area: "planned_runtime_smoke",
      checkId: "140c_runtime_smoke_planned_only",
      passed: plannedRuntimeSmoke && SAFETY.runtimeHttpRequestPerformedNow === false,
      blocking: !plannedRuntimeSmoke || SAFETY.runtimeHttpRequestPerformedNow,
      expected: "Runtime HTTP smoke is planned for after mount approval, not executed now.",
      observed: `${String(plannedRuntimeSmoke)}:${String(SAFETY.runtimeHttpRequestPerformedNow)}`,
      remediation: "Do not run HTTP smoke until the route is explicitly mounted.",
      safeCode: "runtime_smoke_planned_only",
      safeMessageKey: "stream.foundation.140c.runtimeSmokePlannedOnly",
    },
    {
      area: "source_only_scope",
      checkId: "140c_foundation_scope_only",
      passed: SAFETY.patchScope === "src/modules/stream/foundation/** only" && allPlanOnlySafe,
      blocking: SAFETY.patchScope !== "src/modules/stream/foundation/** only" || !allPlanOnlySafe,
      expected: "140C writes planning source only inside foundation.",
      observed: `${SAFETY.patchScope}:${String(allPlanOnlySafe)}`,
      remediation: "Remove any real index/app/server/runtime changes from 140C.",
      safeCode: "foundation_scope_only",
      safeMessageKey: "stream.foundation.140c.foundationScopeOnly",
    },
    {
      area: "route_mount_deferred",
      checkId: "140c_route_mount_deferred",
      passed: SAFETY.routeMountAllowedNow === false && SAFETY.routeMountPerformedNow === false,
      blocking: SAFETY.routeMountAllowedNow || SAFETY.routeMountPerformedNow,
      expected: "No route mount allowed/performed in planning stage.",
      observed: `${String(SAFETY.routeMountAllowedNow)}:${String(SAFETY.routeMountPerformedNow)}`,
      remediation: "Mount only in a separately approved controlled backend entry patch.",
      safeCode: "route_mount_deferred",
      safeMessageKey: "stream.foundation.140c.routeMountDeferred",
    },
    {
      area: "runtime_execution_deferred",
      checkId: "140c_runtime_execution_deferred",
      passed: SAFETY.runtimeHttpRequestPerformedNow === false,
      blocking: SAFETY.runtimeHttpRequestPerformedNow,
      expected: "No runtime HTTP request in 140C.",
      observed: String(SAFETY.runtimeHttpRequestPerformedNow),
      remediation: "Run runtime HTTP smoke only after mount approval.",
      safeCode: "runtime_execution_deferred",
      safeMessageKey: "stream.foundation.140c.runtimeExecutionDeferred",
    },
    {
      area: "persistence_provider_wallet_deferred",
      checkId: "140c_db_provider_wallet_deferred",
      passed: SAFETY.databaseWriteAllowedNow === false && SAFETY.providerCallAllowedNow === false && SAFETY.walletMutationAllowedNow === false,
      blocking: SAFETY.databaseWriteAllowedNow || SAFETY.providerCallAllowedNow || SAFETY.walletMutationAllowedNow,
      expected: "No DB/provider/Wallet runtime in 140C.",
      observed: `${String(SAFETY.databaseWriteAllowedNow)}:${String(SAFETY.providerCallAllowedNow)}:${String(SAFETY.walletMutationAllowedNow)}`,
      remediation: "Keep DB/provider/Wallet work for later approved stages.",
      safeCode: "db_provider_wallet_deferred",
      safeMessageKey: "stream.foundation.140c.dbProviderWalletDeferred",
    },
    {
      area: "money_movement_block",
      checkId: "140c_money_movement_blocked",
      passed: SAFETY.paymentAuthorizationAllowedNow === false && SAFETY.monthlyPayoutAllowedNow === false && SAFETY.moneyMovementAllowedNow === false,
      blocking: SAFETY.paymentAuthorizationAllowedNow || SAFETY.monthlyPayoutAllowedNow || SAFETY.moneyMovementAllowedNow,
      expected: "No payment authorization/payout/money movement.",
      observed: `${String(SAFETY.paymentAuthorizationAllowedNow)}:${String(SAFETY.monthlyPayoutAllowedNow)}:${String(SAFETY.moneyMovementAllowedNow)}`,
      remediation: "Keep money movement blocked until real provider and Wallet ledger gates are approved.",
      safeCode: "money_movement_blocked",
      safeMessageKey: "stream.foundation.140c.moneyMovementBlocked",
    },
    {
      area: "secret_redaction",
      checkId: "140c_no_secrets",
      passed: SAFETY.rawSecretsReturned === false && SAFETY.mobileProviderKeysAllowed === false,
      blocking: SAFETY.rawSecretsReturned || SAFETY.mobileProviderKeysAllowed,
      expected: "No raw secrets and no mobile provider keys.",
      observed: `${String(SAFETY.rawSecretsReturned)}:${String(SAFETY.mobileProviderKeysAllowed)}`,
      remediation: "Keep provider keys server-side only.",
      safeCode: "no_secrets",
      safeMessageKey: "stream.foundation.140c.noSecrets",
    },
    {
      area: "fake_success_block",
      checkId: "140c_fake_success_blocked",
      passed: SAFETY.fakeSuccessAllowed === false,
      blocking: SAFETY.fakeSuccessAllowed,
      expected: "Fake success is blocked.",
      observed: String(SAFETY.fakeSuccessAllowed),
      remediation: "Return provider_not_configured/safe-disabled until real providers are configured.",
      safeCode: "fake_success_blocked",
      safeMessageKey: "stream.foundation.140c.fakeSuccessBlocked",
    },
  ];
}

function buildDecision(checks: readonly StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningCheck[]): StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningDecision {
  const blocking = checks.filter((check) => check.blocking);
  if (blocking.some((check) => check.area === "previous_140b_verification")) {
    return {
      decisionCode: "controlled_backend_entry_patch_planning_blocked_by_140b",
      planningReadyNow: false,
      readyForControlledBackendEntryPatchOwnerReview: false,
      readyForProductionBackend: false,
      routeMountAllowedNow: false,
      runtimeActivationAllowedNow: false,
      safeCode: "140c_blocked_by_140b",
      safeMessageKey: "stream.foundation.140c.blockedBy140b",
    };
  }
  if (blocking.length > 0) {
    return {
      decisionCode: "controlled_backend_entry_patch_planning_blocked_by_safety_gate",
      planningReadyNow: false,
      readyForControlledBackendEntryPatchOwnerReview: false,
      readyForProductionBackend: false,
      routeMountAllowedNow: false,
      runtimeActivationAllowedNow: false,
      safeCode: "140c_blocked_by_safety_gate",
      safeMessageKey: "stream.foundation.140c.blockedBySafetyGate",
    };
  }
  return {
    decisionCode: "controlled_backend_entry_patch_planning_ready_for_owner_review",
    planningReadyNow: true,
    readyForControlledBackendEntryPatchOwnerReview: true,
    readyForProductionBackend: false,
    routeMountAllowedNow: false,
    runtimeActivationAllowedNow: false,
    safeCode: "140c_backend_entry_patch_planning_ready",
    safeMessageKey: "stream.foundation.140c.backendEntryPatchPlanningReady",
  };
}

export function getStreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningSnapshot(): StreamFoundationKernelDiagnosticsControlledBackendEntryPatchPlanningSnapshot {
  const previous = getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationSnapshot();
  const previousReadiness = getStreamFoundationKernelDiagnosticsBackendRouteConnectionSourceOnlyPostWriteVerificationReadiness();
  const plannedPatchItems = buildPlannedPatchItems();
  const checks = buildChecks(plannedPatchItems);
  const decision = buildDecision(checks);
  return {
    version: STREAM_FOUNDATION_140C_KERNEL_DIAGNOSTICS_CONTROLLED_BACKEND_ENTRY_PATCH_PLANNING_VERSION,
    status: decision.planningReadyNow ? "controlled_backend_entry_patch_planning_ready_unmounted" : "controlled_backend_entry_patch_planning_blocked",
    patchScope: "src/modules/stream/foundation/** only",
    previous140bStatus: previous.status,
    previous140bReady: previousReadiness.ready,
    plannedPatchItems,
    plannedPatchItemCount: plannedPatchItems.length,
    totalChecks: checks.length,
    passedChecks: checks.filter((check) => check.passed).length,
    blockingChecks: checks.filter((check) => check.blocking).length,
    planningReadyNow: decision.planningReadyNow,
    readyForControlledBackendEntryPatchOwnerReview: decision.readyForControlledBackendEntryPatchOwnerReview,
    readyForProductionBackend: false,
    streamIndexPatchIncludedNow: false,
    streamModuleIndexTouchedNow: false,
    backendEntryPatchIncludedNow: false,
    appServerPatchIncludedNow: false,
    appServerTouchedNow: false,
    routeMountAllowedNow: false,
    routeMountPerformedNow: false,
    protectedRouteRegisteredNow: false,
    expressRouterCreatedNow: false,
    expressRouterImportedNow: false,
    expressRouterBoundNow: false,
    runtimeHttpRequestsPerformed: 0,
    databaseExecutionPerformed: 0,
    providerCallsPerformed: 0,
    walletMutationPerformed: 0,
    paymentAuthorizationPerformed: 0,
    monthlyPayoutPerformed: 0,
    moneyMovementPerformed: 0,
    rawSecretsReturned: 0,
    mobileProviderKeysAllowed: false,
    fakeSuccessAllowed: false,
    checks,
    decision,
    safety: SAFETY,
  };
}
