import type {
  SabiAiStreamCreativeThemeMatrix252D,
  SabiAiStreamLearningStyleMatrix252D,
  SabiAiStreamSafetyLocks252D,
} from './sabiAiStreamLearningStyleMatrix252D.types';

export const sabiAiStreamLearningStyleMatrix252D: SabiAiStreamLearningStyleMatrix252D = {
  learningBeforeLive: true,
  firstLearningScopeLanguages: 25,
  first25Languages: [
    'ru',
    'en',
    'uz',
    'zh',
    'es',
    'fr',
    'de',
    'ar',
    'hi',
    'tr',
    'pt',
    'it',
    'ja',
    'ko',
    'id',
    'ms',
    'fa',
    'ur',
    'kk',
    'ky',
    'tg',
    'az',
    'pl',
    'nl',
    'uk',
  ],
  futureGoal: 'all_world_languages_after_foundation',
} as const;

export const sabiAiStreamCreativeThemeMatrix252D: SabiAiStreamCreativeThemeMatrix252D = {
  allowedPositiveThemes: [
    'love',
    'homeland',
    'nature',
    'human_values',
    'respect',
    'learning',
    'kindness',
    'family_values',
    'friendship',
    'honesty',
    'peace',
    'youth_growth',
    'real_human_communication',
    'environment_care',
    'culture_respect',
  ],
  contentFormsFuture: [
    'short_original_clip',
    'music_video_concept',
    'poetic_monologue',
    'educational_short',
    'nature_values_clip',
    'homeland_respect_clip',
    'language_learning_clip',
    'safe_youth_dialogue_clip',
  ],
} as const;

export const sabiAiStreamSafetyLocks252D: SabiAiStreamSafetyLocks252D = {
  localCodeArtifactOnly: true,
  noLiveBroadcastNow: true,
  noRuntimeMountNow: true,
  noAdminRouteConnectionNow: true,
  noRuntimePostNow: true,
  noRuntimeGenerationNow: true,
  noProviderCallNow: true,
  noProtectedConfigReadWriteNow: true,
  noDbMutationNow: true,
  noPaymentNow: true,
  noRestrictedLiveActionNow: true,
  finalActionsExecutedNow: false,
  ownerApprovalRequiredForPublicPost: true,
  ownerApprovalRequiredForLiveBroadcast: true,
} as const;
