import type { TaxiRouteDescriptor } from '../foundation';
import type {
  TaxiAdminApprovalDecisionContract,
  TaxiAdminApprovalGateContract,
  TaxiAdminApprovalGatesVersion,
  TaxiAdminDailyReportFinalizeRule,
} from './taxiAdminApprovalGates.types';

export const TAXI_ADMIN_APPROVAL_GATES_VERSION: TaxiAdminApprovalGatesVersion = 'TAXI-BACKEND-FOUNDATION-001J';

export const TAXI_ADMIN_APPROVAL_GATE_CONTRACTS: readonly TaxiAdminApprovalGateContract[] = [
  {
    gateId: 'daily_report_close_gate',
    title: 'Daily report close gate: every complaint must be checked before close',
    requiredActors: ['sabi_ai', 'admin_reviewer'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'sabi_ai_completion_gate',
    title: 'Sabi AI completion gate for all driver and rider complaints',
    requiredActors: ['sabi_ai', 'foundation_kernel'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'complaint_penalty_gate',
    title: 'Complaint penalty gate before points removal or cooldown candidate',
    requiredActors: ['sabi_ai', 'admin_reviewer'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'hard_block_gate',
    title: 'Hard block gate requires explanation and supervisor approval',
    requiredActors: ['sabi_ai', 'admin_reviewer', 'admin_supervisor'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: true,
    requiresSupervisorApproval: true,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'reward_freeze_gate',
    title: 'Reward freeze gate for disputed top-3 driver or rider prize candidates',
    requiredActors: ['sabi_ai', 'admin_reviewer'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: true,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'reward_release_gate',
    title: 'Reward release gate requires clean report plus legal or finance review',
    requiredActors: ['sabi_ai', 'admin_reviewer', 'legal_review', 'finance_review'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: true,
    requiresLegalOrFinanceReview: true,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'restore_points_gate',
    title: 'Restore points gate for false complaint or clean Admin decision',
    requiredActors: ['sabi_ai', 'admin_reviewer'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: true,
    requiresSabiAiEvidenceBundle: true,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
  {
    gateId: 'client_boundary_publish_gate',
    title: 'Client kernel boundary summary publish gate after Admin locked decision only',
    requiredActors: ['admin_reviewer', 'foundation_kernel'],
    requiresCountryDayScope: true,
    requiresFullDailyReport: true,
    requiresAllComplaintsChecked: false,
    requiresSabiAiEvidenceBundle: false,
    requiresParticipantExplanation: false,
    requiresSupervisorApproval: false,
    requiresLegalOrFinanceReview: false,
    canExecuteRuntimeNow: false,
    fakeDecisionBlocked: true,
  },
] as const;

export const TAXI_ADMIN_APPROVAL_DECISION_STATES: readonly TaxiAdminApprovalDecisionContract[] = [
  {
    state: 'not_started',
    title: 'Approval review has not started',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: false,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'ai_review_required',
    title: 'Sabi AI must complete complaint review before Admin can finalize',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: false,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'admin_review_required',
    title: 'Admin review is required before any sanction, restore or reward release',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: false,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'participant_explanation_required',
    title: 'Participant explanation is required before hard block or prize disqualification',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: true,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'approval_required',
    title: 'Final Admin approval is required and runtime is still safe-disabled',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: true,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'approved_for_future_runtime',
    title: 'Approved as contract state only; future execution still requires separate exact approval',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: true,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'rejected',
    title: 'Approval rejected; no penalty, restore or reward release can execute from this state',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: true,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
  {
    state: 'safe_disabled_locked',
    title: 'Safe-disabled lock: foundation can describe decisions but cannot execute runtime actions',
    visibleInAdmin: true,
    visibleInClientBoundarySummary: true,
    rawEvidenceVisibleToMobile: false,
    blocksRealPenaltyUntilApproved: true,
    blocksRewardReleaseUntilApproved: true,
    canMutateDbNow: false,
    canMutateWalletNow: false,
    canCallProviderNow: false,
    fakeSuccessBlocked: true,
  },
] as const;

export const TAXI_ADMIN_DAILY_REPORT_FINALIZE_RULES: readonly TaxiAdminDailyReportFinalizeRule[] = [
  {
    ruleId: 'all_complaints_checked_before_close',
    title: 'Every driver and rider complaint must be checked before closing a country/day report',
    requiredForEveryCountryDay: true,
    adminMayCloseOnlyAfterSatisfied: true,
    mobileMayReceiveOnlySafeSummary: true,
    runtimeEnabledNow: false,
    fakeCloseBlocked: true,
  },
  {
    ruleId: 'open_appeals_block_close',
    title: 'Open hard-block or prize-disqualification appeals block final close',
    requiredForEveryCountryDay: true,
    adminMayCloseOnlyAfterSatisfied: true,
    mobileMayReceiveOnlySafeSummary: true,
    runtimeEnabledNow: false,
    fakeCloseBlocked: true,
  },
  {
    ruleId: 'reward_freeze_review_required',
    title: 'Reward freeze/release candidates require Admin plus legal or finance review',
    requiredForEveryCountryDay: true,
    adminMayCloseOnlyAfterSatisfied: true,
    mobileMayReceiveOnlySafeSummary: true,
    runtimeEnabledNow: false,
    fakeCloseBlocked: true,
  },
  {
    ruleId: 'raw_evidence_admin_only',
    title: 'Raw evidence remains Admin/foundation only and never goes to client app',
    requiredForEveryCountryDay: true,
    adminMayCloseOnlyAfterSatisfied: true,
    mobileMayReceiveOnlySafeSummary: true,
    runtimeEnabledNow: false,
    fakeCloseBlocked: true,
  },
  {
    ruleId: 'kernel_summary_after_admin_lock',
    title: 'Client kernel boundary summary can be published only after Admin locked decision state',
    requiredForEveryCountryDay: true,
    adminMayCloseOnlyAfterSatisfied: true,
    mobileMayReceiveOnlySafeSummary: true,
    runtimeEnabledNow: false,
    fakeCloseBlocked: true,
  },
] as const;

export const taxiAdminApprovalGateRouteDescriptors: readonly TaxiRouteDescriptor[] = [
  {
    method: 'GET',
    path: '/api/taxi/admin/approval-gates/contracts',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Admin approval gate contracts for daily AI report close, penalties, restore and reward review.',
  },
  {
    method: 'POST',
    path: '/api/taxi/admin/approval-gates/finalize-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future finalization preview route only; no real close, sanction, restore or reward release now.',
  },
  {
    method: 'GET',
    path: '/api/taxi/admin/approval-gates/mobile-summary-preview',
    authRequired: true,
    mountedNow: false,
    runtimeEnabled: false,
    exactApprovalRequiredForRuntime: true,
    description: 'Future kernel-safe mobile summary preview; raw evidence stays Admin/foundation only.',
  },
] as const;
