export const SABI_QR_ADMIN_PROVIDER_REGISTRY = [
  {
    providerId: "alipay_plus",
    title: "Alipay+ partner/acquiring API",
    module: "payments",
    status: "not_configured",
    keyVisibility: "admin_secret_only",
    mobileCanReadSecret: false,
    requiredAdminFields: ["partnerId", "clientId", "merchantId", "publicKey", "privateKeyVaultRef", "environment"],
    requiredWebhooks: ["notifyPayment", "inquiryPayment", "refundNotification"],
    tokenOnlyStorage: true,
  },
  {
    providerId: "card_issuing_provider",
    title: "Virtual card issuing provider",
    module: "cards",
    status: "not_configured",
    keyVisibility: "admin_secret_only",
    mobileCanReadSecret: false,
    requiredAdminFields: ["issuerProgramId", "apiKeyVaultRef", "webhookSecretVaultRef", "supportedCountries", "kycPolicy"],
    requiredWebhooks: ["cardIssued", "cardAuthorized", "cardDeclined", "cardFrozen", "cardClosed"],
    tokenOnlyStorage: true,
  },
  {
    providerId: "local_bank_gateway",
    title: "Local bank/payment gateway",
    module: "wallet",
    status: "not_configured",
    keyVisibility: "admin_secret_only",
    mobileCanReadSecret: false,
    requiredAdminFields: ["gatewayId", "merchantId", "apiKeyVaultRef", "tokenizationEnabled"],
    requiredWebhooks: ["paymentStatus", "payoutStatus", "cardTokenized"],
    tokenOnlyStorage: true,
  },
  {
    providerId: "crypto_provider",
    title: "Crypto wallet provider",
    module: "crypto_wallet",
    status: "not_configured",
    keyVisibility: "admin_secret_only",
    mobileCanReadSecret: false,
    requiredAdminFields: ["providerName", "apiKeyVaultRef", "chainPolicy", "amlPolicy"],
    requiredWebhooks: ["depositDetected", "withdrawalStatus", "riskAlert"],
    tokenOnlyStorage: true,
  },
  {
    providerId: "school_work_attendance",
    title: "School/Work attendance authority",
    module: "verification",
    status: "not_configured",
    keyVisibility: "server_env_only",
    mobileCanReadSecret: false,
    requiredAdminFields: ["organizationId", "allowedLocations", "attendanceAdminRole", "exportPolicy"],
    requiredWebhooks: [],
    tokenOnlyStorage: true,
  },
] as const;
