export type Sms241JReadiness = Readonly<{
  sms241JAdminUiMaskedReadinessBuildSmokeExactOwnerRunCommandFinalPreBuildExecutionSummaryReady: 100;
  sms241IAdminUiMaskedReadinessBuildSmokeExactOwnerRunCommandAcceptanceGateStaticCheckReady: 100;
  sms241HAdminUiMaskedReadinessBuildSmokeExactOwnerRunCommandAcceptanceGateReady: 100;
  sms241GAdminUiMaskedReadinessBuildSmokeExactOwnerRunCommandStaticCheckReady: 100;
  sms241FAdminUiMaskedReadinessBuildSmokeExactOwnerRunCommandReady: 100;
  exactOwnerBuildSmokeCommandProvidedNow: 0;
  exactOwnerBuildSmokeCommandAcceptedNow: 0;
  ownerBuildSmokeApprovalProvidedNow: 0;
  ownerBuildSmokeApprovalAcceptedNow: 0;
  adminBuildExecutedNow: 0;
  adminBuildExecutionEnabledNow: 0;
  realAdminUiChangedNow: 0;
  realSmsSent: 0;
  productionPublicLaunch: 0;
}>;

export type Sms241JGate = Readonly<{
  acceptedNow: false;
  executableNow: false;
  noExecutionNow: true;
  exactOwnerCommandProvidedNow: false;
  exactOwnerCommandAcceptedNow: false;
  ownerBuildSmokeApprovalProvidedNow: false;
  ownerBuildSmokeApprovalAcceptedNow: false;
  canAcceptOwnerCommandNow: false;
  canRunAdminBuildNow: false;
  canApproveAdminBuildExecutionNow: false;
  canDisplayPlainSecretNow: false;
  canDisplayProviderResponseNow: false;
  canDisplayLiveTokenNow: false;
  canCopyPlainSecretNow: false;
  canExportSecretNow: false;
  canMutateRuntimeNow: false;
  canSendLiveSmsNow: false;
}>;

export type Sms241JSafety = Readonly<{
  noLiveSms: true;
  noFirebaseApiCall: true;
  noSmsProviderCall: true;
  noSmsSent: true;
  noEnvOrSecrets: true;
  noEnvRead: true;
  noEnvWrite: true;
  noSecretManagerRead: true;
  noSecretManagerWrite: true;
  noSecretManagerAccessGrant: true;
  noSecretValueInSource: true;
  noPlainSecretInChat: true;
  noPlainSecretInAdminUi: true;
  noSecretRevealToAdmin: true;
  noSecretRevealToDeveloper: true;
  noSecretRevealToOwnerSabiAi: true;
  noBreakGlassAccess: true;
  noDbSessionTokenWrites: true;
  noAdminUiRuntimeMount: true;
  noBackendRouteRuntimeMount: true;
  noRealAdminUiChange: true;
  noAdminStatusMutation: true;
  noAdminBuildExecution: true;
  noOwnerBuildSmokeApprovalAccepted: true;
  noExactOwnerCommandAccepted: true;
  noGoogleCloudDeploy: true;
  noWalletPaymentPayoutCrypto: true;
  ownerFinalApprovalRequiredBeforeLiveAction: true;
}>;

export type Sms241JReport = Readonly<{
  version: string;
  marker: string;
  windowsExpandArchiveSafePath: true;
  shortPathReady: true;
  finalPreBuildExecutionSummaryOnly: true;
  finalPreBuildExecutionSummaryReady: true;
  ownerExactRunCommandFinalPreBuildExecutionSummaryReady: true;
  preBuildExecutionSummaryReady: true;
  buildSmokeStillNotExecuted: true;
  ownerFinalApprovalRequired: true;
  ownerSabiAiReportOnly: true;
  maskedAdminStatusOnly: true;
  commandReference: string;
  ownerApprovalPhraseReferenceOnly: string;
  readiness: Sms241JReadiness;
  gate: Sms241JGate;
  safety: Sms241JSafety;
  publicWording: readonly string[];
  nextStep: string;
}>;
