import type { PremiumFeatureKey, PremiumPlan } from "./premium.types";

export const PREMIUM_FEATURE_CATALOG: Readonly<Record<PremiumPlan, readonly PremiumFeatureKey[]>> = {
  FREE: [],
  PREMIUM: [
    "ai_text_translation",
    "ai_audio_translation",
    "ai_video_translation",
    "ai_call_translation",
    "ai_workspace_access",
    "ai_deep_search",
    "ai_media_search",
    "ai_student_assistant",
    "bots_access",
    "business_account_access",
    "advanced_qr_routes",
    "priority_support",
  ],
  BUSINESS_PREMIUM: [
    "ai_text_translation",
    "ai_audio_translation",
    "ai_video_translation",
    "ai_call_translation",
    "ai_workspace_access",
    "ai_business_assistant",
    "ai_deep_search",
    "ai_media_search",
    "ai_student_assistant",
    "bots_access",
    "business_account_access",
    "advanced_qr_routes",
    "priority_support",
  ],
  ADMIN: [
    "ai_text_translation",
    "ai_audio_translation",
    "ai_video_translation",
    "ai_call_translation",
    "ai_workspace_access",
    "ai_business_assistant",
    "ai_deep_search",
    "ai_media_search",
    "ai_student_assistant",
    "bots_access",
    "business_account_access",
    "advanced_qr_routes",
    "priority_support",
  ],
};
